puppetlabs/puppetdb

documentation/connect_puppet_master.markdown

(PDB-137) Document firewall and selinux requirements for PuppetDB.

Firewall doc

---

project.clj

(EZ-15) Update ezbake plugin to 0.1.0

---

src/puppetlabs/puppetdb/catalogs.clj
src/puppetlabs/puppetdb/cli/benchmark.clj
src/puppetlabs/puppetdb/jdbc/internal.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/anonymizer_test.clj
test/puppetlabs/puppetdb/fixtures.clj
test/puppetlabs/puppetdb/http_test.clj
test/puppetlabs/puppetdb/query/reports_test.clj
test/puppetlabs/puppetdb/scf/storage_utils_test.clj
test/puppetlabs/puppetdb/testutils/catalogs.clj
test/puppetlabs/puppetdb/testutils/events.clj

I ran lein eastwood on the repo and these are the things that jumped out at me.
A few docstrings after function arguments, a few places where tests weren't
running as expected.

(maint) eastwood linting

---

src/puppetlabs/puppetdb/http/cruft.clj
src/puppetlabs/puppetdb/http/v4.clj

```
*[master][~/Projects/ajroetker-puppet_server]$ curl -XGET http://localhost:8080/v4/pe/state_overview/a          rbenv:1.9.3-p547
{
"failed" : 0,
"changed" : 0,
"unchanged" : 0,
"noop" : 0,
"unreported" : 1,
"unresponsive" : 253
}%
```

Create state-overview endpoing prototype

---

test/puppetlabs/puppetdb/testutils/jetty.clj

Somehow ActiveMQ was up, the ActiveMQ MBeans were up, PuppetDB was
up (along with the discarded message MBean) but the MBean we use to ge
metadata about the queue was not yet up. This patch now checks for all
three things to be up before until-consumed proceeds.

(PDB-908) Fix race condition with until-consumed startup

---

test/puppetlabs/puppetdb/testutils/jetty.clj

Previously tests would set Jetty's port to 0, which automatically picks
an open port on startup. The downside of that was the PuppetDB config
wouldn't be updated with the actual port chosen, so that info would have
to be pulled from the Jetty server. This patch switches to determine an
open port before starting TK, then use that port in the TK config. This
makes our test more like what users would run (specifying a port rather
than letting Jetty choose).

(PDB-1255) Switch tests to pick open port before bootstrapping TK

---

documentation/configure.markdown
documentation/release_notes.markdown

(PDB-1139) Add preliminary 2.3.0 release notes

---

documentation/api/query/v4/upgrading-from-v3.markdown

This documents the changes we've made from the v3->v4 API.

(PDB-1136) communicate v3->v4 API changes

---

documentation/anonymization.markdown
src/puppetlabs/puppetdb/anonymizer.clj
src/puppetlabs/puppetdb/cli/anonymize.clj
test/puppetlabs/puppetdb/anonymizer_test.clj

This implements anonymization for logs and metrics.

(PDB-1197) anonymize logs and metrics

---

src/com/puppetlabs/puppetdb/scf/migrate.clj

Check to see if there is a schema_migrations table before querying it.
This eliminates these error messages from the postgresql log:
STATEMENT:  SELECT version FROM schema_migrations ORDER BY version
ERROR:  relation "schema_migrations" does not exist at character 21
A very large number of these messages are produced during the unit
tests.
src/com/puppetlabs/puppetdb/scf/migrate.clj | 14 ++++++++------
1 file changed, 8 insertions(+), 6 deletions(-)

(maint) applied-migrations: don't ignore exceptions

---

documentation/release_notes.markdown

This PR adds the 2.3.1 release notes.

Ticket/stable/pdb 1328 2.3.1 release notes

---

src/com/puppetlabs/puppetdb/scf/migrate.clj

```
We can't assume that we'll have access to the public schema.
This reverts commit 53210f67eb8b2223cfb719ae484313b8cec55042.
src/com/puppetlabs/puppetdb/scf/migrate.clj | 14 ++++++--------
1 file changed, 6 insertions(+), 8 deletions(-)
```

(PDB-1363) Revert "(maint) applied-migrations: don't ignore exceptions"

---

documentation/release_notes.markdown

Add preliminary 2.3.2 release notes
```
documentation/release_notes.markdown | 43 +++++++++++++++++++++++++++++++++++++++++++
1 file changed, 43 insertions(+)
```

Add preliminary 2.3.2 release notes

---

documentation/release_notes.markdown

This commit adds the preliminary 2.3.3 release notes.

(PDB-1385) Add 2.3.3 release notes

---

Gemfile
puppet/spec/spec_helper.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
puppet/spec/unit/reports/puppetdb_spec.rb
puppet/spec/unit/util/puppetdb/config_spec.rb

Reverts puppetlabs/puppetdb#1342

Revert "(PDB-1412) Update rspec dependency from 2.x to 3.x"

---

documentation/_puppetdb_nav.html
documentation/api/query/v4/preparing-for-3.0.markdown

This adds the upgrading from v3 document to our stable branch,
for better visibility to users.

(maint) add upgrading from v3 document to stable branch

---

documentation/api/query/v4/events.markdown
documentation/api/query/v4/operators.markdown
documentation/api/query/v4/reports.markdown
documentation/api/query/v4/upgrading-from-v3.markdown
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query/facts.clj
src/puppetlabs/puppetdb/query/resources.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/catalogs_test.clj
test/puppetlabs/puppetdb/http/events_test.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/http/resources_test.clj

This implements a group_by operator and the "count" aggregate function. It
should be functional on all endpoints except facts and fact-contents, which
will be addressed by PDB-1447.

(PDB-1181) Add group_by and aggregate functions (count only)

---

documentation/release_notes.markdown

This updates our release notes for the 2.3.4 release.

(PDB-1494) Update release notes for 2.3.4.

---

acceptance/tests/db_garbage_collection/node_ttl.rb
documentation/api/query/v4/catalogs.markdown
documentation/api/query/v4/factsets.markdown
documentation/api/query/v4/nodes.markdown
documentation/api/query/v4/query.markdown
documentation/api/query/v4/upgrading-from-v3.markdown
documentation/configure.markdown
documentation/maintain_and_tune.markdown
puppet/lib/puppet/face/node/status.rb
puppet/spec/unit/indirector/facts/puppetdb_spec.rb
src/puppetlabs/puppetdb/cli/export.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/http/catalogs.clj
src/puppetlabs/puppetdb/http/edges.clj
src/puppetlabs/puppetdb/http/facts.clj
src/puppetlabs/puppetdb/http/factsets.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/http/resources.clj
src/puppetlabs/puppetdb/query.clj
src/puppetlabs/puppetdb/query/facts.clj
src/puppetlabs/puppetdb/query/nodes.clj
src/puppetlabs/puppetdb/query/population.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

This includes several commits related to improving our handling of deactivated nodes. It's based on PDB-1310, so until that gets merged, a per-commit review may be in order.

(PDB-1450) Improved node expiration

---

src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/query/facts.clj
src/puppetlabs/puppetdb/query/paging.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/facts_test.clj

This reverts commit e09574ab7109607c9aca450f447ba0cb883c3194.

Revert "(PDB-1482) allow ordering on non-extracted fields"

---

src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/query/facts.clj
src/puppetlabs/puppetdb/query/paging.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/facts_test.clj

Reverts puppetlabs/puppetdb#1403
There was no issue with this after all!

Revert "Revert "(PDB-1482) allow ordering on non-extracted fields""

---

documentation/api/commands.markdown
documentation/api/query/curl.markdown
documentation/api/query/tutorial.markdown
documentation/api/query/v4/aggregate-event-counts.markdown
documentation/api/query/v4/catalogs.markdown
documentation/api/query/v4/edges.markdown
documentation/api/query/v4/environments.markdown
documentation/api/query/v4/event-counts.markdown
documentation/api/query/v4/events.markdown
documentation/api/query/v4/fact-contents.markdown
documentation/api/query/v4/fact-names.markdown
documentation/api/query/v4/fact-paths.markdown
documentation/api/query/v4/facts.markdown
documentation/api/query/v4/factsets.markdown
documentation/api/query/v4/nodes.markdown
documentation/api/query/v4/paging.markdown
documentation/api/query/v4/query.markdown
documentation/api/query/v4/reports.markdown
documentation/api/query/v4/resources.markdown
documentation/api/query/v4/server-time.markdown
documentation/api/query/v4/upgrading-from-v3.markdown
documentation/api/query/v4/version.markdown
documentation/connect_puppet_master.markdown
documentation/maintain_and_tune.markdown
documentation/release_notes.markdown

Update documentation/ to reflect the changes in (PDB-1485).
The documentation/ changes here are currently on top of the (PDB-1485) changes, and so should not be merged until that PR is merged (and this tip commit has been rebased).

(PDB-1350) documentation: update / -> /pdb/query

---

documentation/release_notes.markdown

This PR pairs with stable PR: https://github.com/puppetlabs/puppetdb/pull/1416

(PDB-1454) Document need to wipe MQ during downgrades

---

acceptance/tests/inventory/basic_fact_retrieval.rb
documentation/_puppetdb_nav.html
documentation/api/command/v1/commands.markdown
documentation/api/index.markdown
documentation/api/metrics/v1/index.markdown
documentation/api/query/v4/upgrading-from-v3.markdown
documentation/connect_puppet_master.markdown
documentation/release_notes.markdown
documentation/versioning_policy.markdown
puppet/lib/puppet/face/node/status.rb
puppet/lib/puppet/indirector/facts/puppetdb.rb
puppet/lib/puppet/indirector/resource/puppetdb.rb
puppet/lib/puppet/util/puppetdb/command.rb
puppet/lib/puppet/util/puppetdb/config.rb
puppet/spec/unit/indirector/facts/puppetdb_spec.rb
puppet/spec/unit/util/puppetdb/config_spec.rb
resources/public/dashboard/index.html
resources/puppetlabs/puppetdb/bootstrap.cfg
src/puppetlabs/puppetdb/cli/benchmark.clj
src/puppetlabs/puppetdb/cli/export.clj
src/puppetlabs/puppetdb/cli/import.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/http/command.clj
src/puppetlabs/puppetdb/http/v4.clj
test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/fixtures.clj
test/puppetlabs/puppetdb/http/command_test.clj
test/puppetlabs/puppetdb/testutils/services.clj

Split out Command API into it's own TK service.

(PDB-1561) split command api

---

documentation/release_notes.markdown

this updates our release notes for 2.3.5

(PDB-1571) update release notes for 2.3.5 release

---

.travis.yml
acceptance/helper.rb
acceptance/tests/reports/event_query_with_read_db.rb
documentation/api/query/v4/operators.markdown
documentation/configure.markdown
documentation/release_notes.markdown
src/puppetlabs/puppetdb/honeysql.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

Retires support for postgres 9.3.

(PDB-1592) retire support for postgres 9.3

---

acceptance/helper.rb
acceptance/setup/post_suite/10_collect_artifacts.rb
acceptance/tests/commands/args-handling.rb
acceptance/tests/commands/list-sub-commands.rb
acceptance/tests/reports/report_storage.rb
documentation/configure.markdown
documentation/connect_puppet_master.markdown
documentation/install_from_packages.markdown
documentation/maintain_and_tune.markdown
documentation/postgres_ssl.markdown
project.clj
puppet/lib/puppet/util/puppetdb/command.rb
resources/ext/cli/ssl-setup.erb
resources/ext/config/conf.d/config.ini
resources/ext/config/conf.d/database.ini
resources/ext/config/conf.d/jetty.ini
resources/ext/config/logback.xml
resources/ext/config/request-logging.xml
resources/ext/ezbake.conf

This patch migrates us to ezbake 0.3 which introduces AIO pathing into the mix.

(PDB-1455 RE-5675) Migrate PDB to ezbake 0.3 & AIO pathing

---

acceptance/helper.rb
project.clj

(PDB-1455) Fix incorrect path for puppet_confdir, and switch to dev branch of ezbake

---

acceptance/setup/pre_suite/40_install_deps.rb

This moves the code to install a real ruby on Debian for AIO so it iterates
on all all database nodes, before it was only installing it on the first one.

(PDB-1455) Iterate to install ruby on Debian for AIO

---

src/puppetlabs/puppetdb/mq.clj

Specifically an MQ related error message from d853fd9765ca0dcad180371dc47137bb68d20bd3

Merge conflict from stable to master missed a change

---

project.clj

(PDB-1639) Bump to Clojure 1.7.0-RC2

---

acceptance/helper.rb
project.clj

This removes the ezbake pinning from our acceptance tests.

(PDB-1619) Unpin against dev branch for ezbake

---

project.clj

(PDB-1609) Mirror pe-extensions versioning

---

acceptance/config/ec2-west-el6-64mda-el5-64a-ubuntu1204-64a.cfg
acceptance/setup/pre_suite/40_install_deps.rb
acceptance/setup/pre_suite/80_add_dev_repo.rb
acceptance/tests/import_export/legacy_storeconfigs_import_export.rb

(maint) Update tests to use new Facter 3 variables

---

src/puppetlabs/puppetdb/cli/anonymize.clj
src/puppetlabs/puppetdb/cli/benchmark.clj
src/puppetlabs/puppetdb/cli/export.clj
src/puppetlabs/puppetdb/cli/import.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj
test/puppetlabs/puppetdb/config_test.clj

This PR unifies the CLI handling in PuppetDB.

(maint) Unify cli interfaces

---

project.clj

Bump ezbake to 0.3.11 for improved service account handling

---

test/puppetlabs/puppetdb/command_test.clj

this fixes a race with the commands test. Under some circumstances the same
timestamp would be used on both sides of a comparison.

(maint) fix command test race

---

src/puppetlabs/puppetdb/cli/benchmark.clj

Prior to this commit we implicitly assumed that transaction_uuid's are
unique for every report and catalog, but cannot add the constraint to
the schema for a variety of reasons relating to upgrades. This commit
updates the benchmarking tool to change the transaction_uuid for a
catalog and its associated report like we do for timestamps.

(maint) Update `transaction_uuid` while benchmarking

---

documentation/index.markdown
documentation/release_notes.markdown

Folding in the feedback from Ken's PR here: https://github.com/puppetlabs/puppetdb/pull/1513. I have put all my changes in a separate commit so that it can be reviewed separately. I'll collapse the two commits once review is done.

(PDB-1157) Cleanup release notes for 3.0.0

---

project.clj

(maint) update pdb-version in preparation for release

---

acceptance/helper.rb

This removes some old code that seems unneccessary with the recent module
changes. Previously we were doing some special stuff for el5 to install postgres 8.4,
but with the 5.0 module this results in two declarations of the Postgresql class.

(maint) remove add_el5_postgres?

---

acceptance/tests/reports/event_query_with_read_db.rb

Missed this one in the previous patch.

(PDB-1787) remove remaining call to add_el5_postgres

---

documentation/release_notes.markdown

This updates our release notes for 2.3.6

(PDB-1682) update release notes for 2.3.6

---

resources/public/dashboard/index.html

Some of the urls in the dashboard needed updating.

(maint) Fix broken dashboard urls

---

documentation/api/query/v4/fact-contents.markdown
documentation/api/query/v4/operators.markdown
documentation/api/query/v4/resources.markdown

When this is merged, please resolve [DOC-2165](https://tickets.puppetlabs.com/browse/DOC-2165).

(docs) Fix some missing commas and colons in JSON

---

documentation/api/query/v4/facts.markdown
documentation/api/query/v4/operators.markdown
src/puppetlabs/puppetdb/query.clj
src/puppetlabs/puppetdb/query/events.clj
src/puppetlabs/puppetdb/query/facts.clj
src/puppetlabs/puppetdb/query/resources.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/query/nodes_test.clj

(PDB-1440) implement sum, avg, min, max

---

documentation/release_notes.markdown
project.clj

This commit adds release notes and updates the project.clj version for a
3.0.2 release.

(PDB-1831) Update project.clj version and release notes for 3.0.2

---

ext/build_defaults.yaml

(PDB-1806) remove F20 from build targets

---

documentation/api/command/v1/commands.markdown
project.clj
src/puppetlabs/puppetdb/client.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/http/command.clj
test/puppetlabs/puppetdb/fixtures.clj
test/puppetlabs/puppetdb/testutils/services.clj

~~Also includes factoring out a config service and MQService.~~ took this part out

(maint) Add secondsToWaitForCompletion cmd param

---

resources/public/dashboard/charts.js
resources/public/dashboard/index.html

This commit refactors the dashboard to pass around arguments rather than
relying on global mutable state and simplifies some of logic for
rendering.
This commit should make it easier to make the metrics configurable via Clojure code (good for PE) or moving to clojurescript if wanted to dabble in that sort of thing.

(maint) Make the PuppetDB dashboard javascript more functional

---

documentation/api/query/v4/nodes.markdown
src/puppetlabs/puppetdb/query/nodes.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/nodes_test.clj

This adds a latest_report_status and latest_report_hash to the nodes response.

(PDB-1820) add status and hash field to nodes response

---

src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

This changes our jsonb migration to leave the existing json column in place,
and changes our query code to use a coalesce of the two instead of the one-shot
migration to jsonb.

(PDB-1998) use a coalesce instead of jsonb migration

---

src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/catalogs_test.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

This commit adds support for extracts with no subexpression.

(PDB-1459) Support extract with no subexpression

---

src/puppetlabs/puppetdb/client.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/facts.clj
test/puppetlabs/puppetdb/command_test.clj

This PR cleans up the code in `command.clj`.

(maint) Simplify code in command.clj

---

acceptance/config/ec2-west-debian8-64mda-64a.cfg
config/image_templates/ec2.yaml

This sets up the config for acceptance testing on debian eight.

(PDB-1797) testing support for jessie

---

ext/jenkins/packaging.sh

We left out jessie in our s3 sync command.

(PDB-1978) Include jessie in s3 sync command

---

project.clj

(PDB-2083) Bump project.clj version for 3.2.0 release

---

documentation/puppetdb_connection.markdown
puppet/lib/puppet/face/node/status.rb
puppet/lib/puppet/indirector/facts/puppetdb.rb
puppet/lib/puppet/indirector/resource/puppetdb.rb
puppet/lib/puppet/util/puppetdb/atom.rb
puppet/lib/puppet/util/puppetdb/command.rb
puppet/lib/puppet/util/puppetdb/config.rb
puppet/lib/puppet/util/puppetdb/http.rb
puppet/spec/unit/util/puppetdb/config_spec.rb
puppet/spec/unit/util/puppetdb/http_spec.rb

This includes a sizable refactor of the http module, may be best to review the commits.

(PDB-2070) Add cmd broadcast, min_successful_writes to terminus

---

project.clj

(PE-12468) Bump ezbake version for service startup timeout

---

src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

This fixes a bug created by the collapsed 1.x and 2.x migrations. The
bug would occur in upgrade scenarios. If a pre-3.0 migration version was
found in the database, it would fail, even if the database was a 3.0.0
database (and upgrades are supported). This commit fixes that and
separates out the supported upgrade versions and the known previous
version that are no longer referenced in PuppetDB.

(MAINT) Don't fail when old migration versions are present

---

documentation/_puppetdb_nav.html
documentation/api/status/v1/status.markdown
project.clj
resources/puppetlabs/puppetdb/bootstrap.cfg
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/scf/storage_utils.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/dashboard_test.clj
test/puppetlabs/puppetdb/pdb_routing_test.clj
test/puppetlabs/puppetdb/status_test.clj
test/puppetlabs/puppetdb/testutils/services.clj

This gets us consistent with the first cut functionality described in the
ticket description.
To demonstrate,
curl -X GET http://localhost:8080/status/v1/services

(PDB-2098) tk-status integration

---

ext/jenkins/lein-test.sh

Reverts puppetlabs/puppetdb#1755

Revert "(maint) Use new pg test users on jenkins"

---

Rakefile
ext/jenkins/beaker-tests.sh

(QENG-3111) Make use of the PUPPETDB_DBTYPE CI variable.

---

ext/jenkins/lein-test.sh

(maint) Use new pg test users on jenkins

---

documentation/install_from_source.markdown
ext/bin/setup-pdb-pg
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage_utils.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/testutils/db.clj
test/puppetlabs/puppetdb/testutils/services.clj

This adds a database index and support functions needed to implement
enhanced sync functionality in PE.

(PDB-2072) Migration to support enhanced sync

---

project.clj

(maint) Bump to Clojure 1.8.0-RC3

---

project.clj

(maint) Upgrade to ActiveMQ 5.13.0

---

documentation/_puppetdb_nav.html
documentation/api/query/v4/reports.markdown
documentation/puppetdb_connection.markdown
documentation/resource_statuses.markdown

This commit documents unchanged resources information for PE Ankeny in
the FOSS documentation.

(PDB-2251) Document unchanged resources for PE 2015.3.0 (Ankeny)

---

src/puppetlabs/puppetdb/command.clj

... so we can do better cache invalidation by observing response-mult.

(PDB-2159) Augment the command processed message

---

documentation/api/ext/v1/resource-graphs.markdown
documentation/api/query/v4/catalogs.markdown

This commit adds documentation for the PE only historical-catalogs
views.

(PDB-2309) Document historical-catalogs views in PE

---

project.clj

(maint) Bump clojure version to 1.8.0 final

---

documentation/api/query/v4/operators.markdown
documentation/api/query/v4/paging.markdown
src/puppetlabs/puppetdb/query/paging.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/index_test.clj

This patch implements support for paging operators within a "from" clause.

(PDB-2182) support paging operators in query body

---

documentation/configure.markdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/http/server.clj
src/puppetlabs/puppetdb/middleware.clj

This adds a [developer] section in configuration, along with an option to
pretty print API responses by default.

(PDB-2133) Add [developer] configuration section with option to pretty print

---

acceptance/helper.rb
acceptance/setup/pre_suite/70_install_released_puppetdb.rb
src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

This reverts some of the combined migration to allow upgrades from 2.3.2 and
later.

(PDB-2353) support upgrades from 2.3.2

---

project.clj

(maint) Update library dependencies

---

documentation/api/query/v4/pql.markdown
resources/puppetlabs/puppetdb/pql/pql-grammar-experimental.ebnf
src/puppetlabs/puppetdb/pql/transform.clj
test/puppetlabs/puppetdb/pql/parser_test.clj
test/puppetlabs/puppetdb/pql/transform_test.clj
test/puppetlabs/puppetdb/pql_test.clj

This enables support for limit, offset, and order by clauses in PQL.

(PDB-2319) paging support in PQL

---

documentation/_puppetdb_nav.html
documentation/api/query/tutorial-pql.markdown
documentation/api/query/tutorial.markdown

This commit defines a new PQL specific tutorial.

(PDB-2366) PQL tutorial documentation

---

documentation/_puppetdb_nav.html
documentation/api/admin/v1/summary-stats.markdown
src/puppetlabs/puppetdb/admin.clj
src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/query/summary_stats.clj
test/puppetlabs/puppetdb/admin_test.clj
test/puppetlabs/puppetdb/examples.clj
test/puppetlabs/puppetdb/testutils/cli.clj
test/puppetlabs/puppetdb/testutils/services.clj

Add a /admin/v1/summary-statistics endpoint to return information about
database usage.

(PDB-2497) add endpoint for PDB summary statistics

---

src/puppetlabs/puppetdb/query/summary_stats.clj
test/puppetlabs/puppetdb/admin_test.clj

Change a couple of our summary stats from character lengths to column sizes.
This will make the queries run faster.

(PDB-2381) data collection script

---

test/puppetlabs/puppetdb/testutils/cli.clj
test/puppetlabs/puppetdb/testutils/reports.clj

This commit removes some more potential ordering issues from tests.

(maint) Remove some more potential ordering issues from tests

---

test/puppetlabs/puppetdb/scf/migrate_test.clj

This tests a fix that was rolled up from stable. The tests weren't rolled up
because we handle test databases differently between branches.

(PDB-2537) test indexes! idempotency on alternative schemas

---

project.clj

(PDB-2502) Bump version to 4.1.0-SNAPSHOT

---

documentation/api/query/v4/fact-contents.markdown
documentation/api/query/v4/nodes.markdown

This adds some real structured facts to the fact-contents docs, adds a little
more information about fact paths, and adds a fact-contents subquery to the
nodes document.

(PDB-2570) tweak documentation on fact path querying

---

src/puppetlabs/puppetdb/scf/storage.clj

This commit fixes an issue with historical catalogs where we were not
checking the for hash duplication and our catalog duplication rate
metric was always showing 0.

(PDB-2579) Check hash duplication with historical catalogs

---

NOTICE.txt
acceptance/README.md
documentation/acceptance_tests.markdown
documentation/connect_puppet_apply.markdown
documentation/connect_puppet_master.markdown
documentation/index.markdown
documentation/install_from_packages.markdown
documentation/install_via_module.markdown
documentation/maintain_and_tune.markdown
documentation/release_notes.markdown

Remove `Labs` from documentation

(PDB-2592) Rebrand in doc mentions of Puppet Labs.

---

documentation/api/query/tutorial-pql.markdown
documentation/api/query/v4/index.markdown
documentation/api/query/v4/nodes.markdown
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/nodes_test.clj

Add the most recent cached catalog status to the nodes response.

(PDB-2586) add cached catalog status to nodes

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

Don't consider a node stale just because any report/catalog is too old;
require that the newest report/catalog be too old.

(PDB-2617) stale-nodes: use newest report/catalog

---

locales/es.po
project.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/http.clj
src/puppetlabs/puppetdb/middleware.clj
src/puppetlabs/puppetdb/pdb_routing.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/meta_test.clj
test/puppetlabs/puppetdb/middleware_test.clj
test/puppetlabs/puppetdb/testutils.clj
test/puppetlabs/puppetdb/testutils/http.clj

Reverts puppetlabs/puppetdb#1940 - needs a fix on extensions then can go back in

Revert "(PDB-2482) Add ability to configure PE with token auth"

---

acceptance/helper.rb
acceptance/setup/pre_suite/15_setup_repos.rb

Upgrade tests will fail if the only installed repos are the nightly repos.

(maint) install released repos even when testing nightlies

---

project.clj
src/puppetlabs/puppetdb/cli/benchmark.clj
src/puppetlabs/puppetdb/cli/import.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage_utils.clj
test/puppetlabs/puppetdb/middleware_test.clj
test/puppetlabs/puppetdb/mq_test.clj
test/puppetlabs/puppetdb/testutils.clj
test/puppetlabs/puppetdb/testutils/log.clj
test/puppetlabs/puppetdb/testutils/repl.clj

(PDB-2546) add HUP support to PDB

---

project.clj

Bump kitchensink to 1.3.1 and tk-jetty to 1.5.8.

(maint) bump kitchensink and tk-jetty

---

src/puppetlabs/puppetdb/cli/services.clj

The way at-at's uses Java Executors causes any exceptions thrown by a
task to be silently swallowed, so wrap the task with a try/catch that
logs exceptions as errors.
You can demonstrate the problem by adding a throw to the
db-maintenance-tasks function and running this:
lein test :only puppetlabs.puppetdb.acceptance.node-ttl/test-node-ttl
It should hang.  After this patch, the test should still hang, but
should also log the exception.

(PDB-2704) Log at-at exceptions

---

src/puppetlabs/puppetdb/mq_listener.clj
test/puppetlabs/puppetdb/command_test.clj

This commit adds the certname to handle-command-retry and handle-command-failure log messages in order to track problematic commands to individual nodes.

(PDB-2580) Add certname to command failure messages

---

puppet/lib/puppet/reports/puppetdb.rb
puppet/spec/unit/reports/puppetdb_spec.rb

The flag is set to true if the corresponding puppet run was stared in noop mode.

(PDB-2495) Leverage noop flag from puppet report when the flag is available

---

documentation/api/query/tutorial-pql.markdown
documentation/api/query/tutorial.markdown

Add a blurb to docs describing usage of puppetdb_query.

(PDB-2661) Document the puppetdb_query function

---

src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/mq_listener.clj
test/puppetlabs/puppetdb/command_test.clj

Current versions of PuppetDB incur a high cost when a command is
retried. The command gets written to a scheduler queue, then re-enqueued
in the regular queue, then reprocessed. A very common case is a database
transaction issue, where two commands are attempting to update the same
data. One thread wins, one loses and has to be retried. We should
implement a quicker "inner loop" retry, where we don't incur the I/O
overhead in this common case. When the quick retries fail, we can then
go through the normal retry logic.
This commit implements this quick retry in command processing (separate
from the queue logic) and removes the exponential backoff for the
traditional retry logic in favor of a set 10 minute retry time.

(PDB-2865) Add quick-retries to PDB command processing

---

acceptance/helper.rb
ext/jenkins/packaging-cleanup.sh
ext/jenkins/packaging.sh

This should fix our PR testing issues.

update package_repo_host to builds.delivery.puppetlabs.net

---

documentation/api/query/v4/pql.markdown

I made some correctness and copy edits as I was following along with these docs to understand PQL.
- added missing anchor for the config_jetty link
- removed spurious commas throughout
- tightened up language by removing 'basically'-style extemporization

(MAINT) Copy-edits to PQL docs

---

src/puppetlabs/puppetdb/anonymizer.clj

Update the anonymization tool to anonymize producer like any other node name.

(PDB-2837) update anonymization to consider producer

---

documentation/api/query/v4/catalogs.markdown
documentation/configure.markdown
src/puppetlabs/puppetdb/catalogs.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/export.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/testutils/resources.clj

This removes historical catalog storage and the associated jsonb columns in the
catalogs table.

(PDB-2894) remove support for historical catalogs

---

acceptance/setup/pre_suite/40_install_deps.rb
ext/jenkins/lein-test.sh
ext/travisci/test.sh
project.clj
src/puppetlabs/puppetdb/query/edges.clj
src/puppetlabs/puppetdb/query/fact_contents.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/testutils/db.clj
test/puppetlabs/puppetdb/testutils/log.clj

Don't merge - just running the tests.

Merge stable into master

---

documentation/_puppetdb_nav.html
documentation/api/ext/v1/state-overview.markdown

Add documentation for the state overview endpoint.

(PDB-2767) document state overview

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/facts_test.clj

Add a bit of handling to allow queries of the form
facts{value in ["foo"]}

(PDB-2330) in clause against array broken on fact value

---

test/puppetlabs/puppetdb/admin_clean_test.clj

Travis seems to be particularly good at exposing this test race
condition. The symptom is a noisy but passing
`puppetlabs.puppetdb.admin-clean-test/admin-clean-competition`. The test
finishes, but the database connection pool is shutdown before
the cleanup finishes. This then causes the next test
`puppetlabs.puppetdb.admin-clean-test/admin-clean-status` to fail.

(PDB-3043) Fix admin-cleanup-test race condition

---

src/puppetlabs/puppetdb/command/dlo.clj
src/puppetlabs/puppetdb/queue.clj
test/puppetlabs/puppetdb/admin_clean_test.clj
test/puppetlabs/puppetdb/command/dlo_test.clj
test/puppetlabs/puppetdb/queue_test.clj

(PDB-3029) Test dlo/initialize with existing items

---

src/puppetlabs/puppetdb/mq_listener.clj

Because PuppetDB's command-processing threadpools are unbounded, the
only reason that they would throw a RejectedExecutionException is
because they're shutting down or have shut down, which means that
PuppetDB is shutting down. Commands that are rejected are retried when
PuppetDB next starts up, so there's no action the user needs to take in
order to prevent loss of data. Therefore, there's no reason to show the
user the exceptions that arise when the threadpool throws
a RejectedExecutionException. To that end, swallow slingshot exceptions
with kind `:puppetlabs.puppetdb.threadpool/rejected` in the thread
started by `puppetdb.mq-listener/message-listener-service`'s TK start
method.

(PDB-2983) Hide rejected execution exceptions.

---

documentation/configure.markdown
documentation/puppetdb-faq.markdown

Added an FAQ entry that gives some recommendations for the threads and
concurrent-writes settings. These recommendations came out of
performance testing that was done comparing ActiveMQ and Stockpile.

(PDB-3062) Add command proc tuning FAQ

---

test/puppetlabs/puppetdb/command_test.clj

The intention of the tests is to verify that if we receive two factsets
for the same certname and process them at the same time, that we get
correct results (i.e. one wins, the other is retried). These tests were
failing in Jenkins due to a timing issue. Switching from the
SynchronousQueue to a CountDownLatch should fix this issue and avoid
having timeouts like the code did previously.

(MAINT) Fix concurrent command proc test issue

---

test/puppetlabs/puppetdb/command_test.clj

Before pg 9.4, the serialization message was in the first exception.
Now it's in a second chained exception.  We'd adjusted the tests to look
for the newer location.  Instead, look for both.

(maint) Pursue serialization failure in two places

---

documentation/configure.markdown

New OSS documentation from the Product Analytics team clarifying how update checking also sends analytics data to Puppet. 
Please let me know if you have any questions. Thanks!

(PE-17713) Document analytics data collected during update checking.

---

src/puppetlabs/puppetdb/query_eng/engine.clj

We had the other half of this covered already.

(PDB-3099) implicit facts->inventory relationship

---

Gemfile

(maint) Update beaker to ~3.4, unpin from 2.30.1

---

documentation/puppetdb_connection.markdown

This is being set to true by PE.

(PE-18318) Update docs for command_broadcast flag

---

src/puppetlabs/puppetdb/scf/migrate.clj

Reverts puppetlabs/puppetdb#2066

Revert "(PDB-3053) Create unique index on certnames.latest_report_id"

---

Gemfile

This is just a branch for me to use while we fix the beaker issue on beaker master branch.

(PDB-3193) Fix beaker AWS duplicate keys

---

test/puppetlabs/puppetdb/threadpool_test.clj

Try to work around CI slowness

(PDB-3282) Increase timeouts in threadpool_test

---

documentation/api/query/tutorial.markdown

Re-opening PR 2184 under Stable branch.

Missing comma from example

---

src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/queue.clj
test/puppetlabs/puppetdb/command_test.clj

Make sure that when files are randomly deleted from the queue, the queue
depth statistics are updated properly.

(PDB-3307) Ensure queue depth reflects removals

---

documentation/api/query/v4/packages.markdown
src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/server.clj
test/puppetlabs/puppetdb/http/packages_test.clj

Add a dedicated REST endpoint for the packages entity.

(PDB-3372) REST endpoint for packages

---

test/puppetlabs/puppetdb/integration/fixtures.clj

We can work around this by:
- Pointing the MRI agent at our terminus using --vardir
- Copying the puppetdb_query function into the master codedir when starting
puppetserver

(maint) Remove 'install-terminus-into' from integration tests

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

The packages table needs to be kept up-to-date with deletions from the
certnames_packages table, as it's used for coarse-grained counting in places
where accuracy matters.

(PDB-3396) Pinpoint GC for packages

---

ext/jenkins/lein-test.sh

This gets us the new clojure integration tests

(maint) Run lein test all in jenkins

---

src/puppetlabs/puppetdb/command.clj

Change command processing logging to include elapsed ms. This will be
useful to support for correlating slow processing to specific nodes.
Cherry pick of 494c3e6bd26e1f2e0743e9c61b162b769d676799
cf. PDB-3096

(PDB-3432) log elapsed time with command processing

---

test/puppetlabs/puppetdb/integration/sensitive_params.clj

Postgres command line tools like pg_dump require that credentials be
provided via the console or a PGPASSFILE, so create a temporary file
containing the pdb_test credentials and point PGPASSFILE to it in
pg_dump's environment.

(PDB-3457) Fix sensitive-params test's pg_dump authorization

---

.travis.yml

(maint) Run integration tests against puppetserver master branch

---

test/puppetlabs/puppetdb/integration/fixtures.clj

Using port 8140 everywhere makes things start failing when multiple tests are
run on the same machine.

(maint) Dynamically allocate puppetserver port in integration test

---

project.clj

This fixes streaming response memory issues.

(PDB-3467) Update cheshire to 5.7.1

---

test/puppetlabs/puppetdb/admin_clean_test.clj

Use a cyclic barrier to block the next test iteration until we know that
the current iteration has released the clean lock.
A (Thread/sleep 1000) at the end of the clear-clean-status! wrapper
function will demonstrate the problem, and the original failure looked
like this:
FAIL in (admin-clean-status) (admin_clean_test.clj:43)
expected: (= http/status-ok (:status result))
actual: (not (= 200 409))
{:status 409,
:headers
{"Date" "Wed, 07 Sep 2016 19:48:43 GMT",
"Content-Type" "application/json; charset=utf-8",
"Connection" "close",
"Server" "Jetty(9.2.10.v20150310)"},
:body
"{\n  \"kind\" : \"conflict\",\n  \"msg\" : \"Another cleanup is already in progress\",\n  \"details\" : null\n}",
:request-time 5,
:trace-redirects ["http://localhost:41655/pdb/admin/v1/cmd"],
:orig-content-encoding …

(PDB-3029) admin-clean-test: block until unlock

---

documentation/ha.markdown

see [DOC-3234](https://tickets.puppetlabs.com/browse/DOC-3234)

(docs) update mismatched version number in heading.

---

src/puppetlabs/puppetdb/jdbc.clj

Before this change, our internal transaction wrapper macro was explicitly
passing a :read-committed isolation level to clojure.jdbc when not otherwise
specified. This causes a call to .setTransactionIsolation on the jdbc driver,
which executes SQL on the server. So it ends up making an extra network round
trip for each query.
This commit sets read-committed transaction isolation in the connection pool
config, so each connection already has that by default. It also allows nil
isolation levels to be passed to clojure.jdbc, which will then use whatever the
connection already has.

(PDB-3195) Default transaction isolation in connection pool config

---

src/puppetlabs/puppetdb/scf/storage.clj

This was previously done with the text version of the value_hash column; it's
stored as bytea, so it required a conversion. Change the query to compare in the
bytea domain.

(PDB-3639) Optimize existing-fact-values query

---

documentation/release_notes.markdown

Update release notes for 5.1.1 release.

---

project.clj

* updates the clj-parent version

(maint) update clj-parent version

---

documentation/configure.markdown
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/schema.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/generative/submit_command.clj
test/puppetlabs/puppetdb/schema_test.clj
test/puppetlabs/puppetdb/testutils/catalogs.clj

* adds facts blacklist option to PDB user config

(PDB-3630) add support for facts blacklist in PDB config 4.4.x

---

documentation/configure.markdown
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/schema.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/schema_test.clj
test/puppetlabs/puppetdb/testutils/catalogs.clj

* adds facts blacklist to LTS branch

(PDB-3630) add support for facts blacklist in PDB config LTS

---

documentation/configure.markdown

* update and move facts blacklist docs to the correct section

(maint) update facts-blacklist docs

---

src/puppetlabs/puppetdb/scf/migrate.clj

We've encountered some problematic queries when doing historical scans over
reports. This adds an index targeted at those queries.

 (PDB-3738) Add compound report id index

---

test/puppetlabs/puppetdb/integration/reports.clj

Something in the agent changed to make it log more at info level; adjust the
tests to match.

(maint) Fix reports integration test

---

src/puppetlabs/puppetdb/scf/migrate.clj

Time migrations and log them to make testing/support awareness easier.

(PDB-3600) time migration execution

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/query_eng_test.clj

This should avoid the slow fallback queries in more cases.

(PDB-3821) Rewrite simple fact queries to use inventory endpoint

---

documentation/release_notes.markdown

Release notes PR wound up on master. This cherry-picks them onto 5.2.x.

(docs) 5.2.x release notes

---

acceptance/setup/pre_suite/15_setup_repos.rb
puppet/spec/unit/reports/puppetdb_spec.rb

Accommodate the addition of provider_used to reports in puppet
https://github.com/puppetlabs/puppet/commit/8927d52650f303764bb4bb4944c4a7d1d17404a1

(PDB-3861) Accommodate puppet's addition of provider_used to reports

---

project.clj

Passing build builds.delivery.puppetlabs.net/puppetdb/5.1.5.SNAPSHOT.2018.03.08T1350

(RE-10172) Update to ezbake 1.8.1

---

src/puppetlabs/puppetdb/command.clj
test/puppetlabs/puppetdb/command_test.clj

This commit changes the replace-facts command to call `distinct` on the
`package_inventory` list which prevents an issue where duplicate entries
in the `package_inventory` would prevent nodes from submitting facts
because of a hash collision when they had multiples of a package in
their inventory.

(PDB-3862) Ensure that the package inventory on facts is distinct

---

documentation/release_notes.markdown

(docs)(DOC-3528) Add 5.1.5 release notes.

---

documentation/release_notes.markdown

(docs)(DOC-3532) Add 5.2.2 release notes.

---

.travis.yml

cf. https://confluence.puppetlabs.com/display/PM/Platform+Versions+and+Dependencies

(PDB-3919) 5.1.x: test server 5.1.x and puppet 5.3.x in CI, not master

---

docker/ci/build

This updates the build script to build containers in the correct
namespace for publishing to dockerhub.

(CPR-600) Auto-publish to dockerhub

---

project.clj

This reverts commit 9a5580c0eea922f913080add9fc3913cc460cf06.

Revert ezbake version bump

---

project.clj

This reverts commit e40393c4c6a0ad69f7f0dc7bd7dd592caacef9a8.

Revert "(maint) Bump to ezbake 1.8.7"

---

docker/Gemfile
docker/ci/build
docker/puppetdb-postgres/spec/dockerfile_spec.rb
docker/puppetdb/spec/dockerfile_spec.rb

Depends on https://github.com/puppetlabs/puppet_docker_tools/pull/26

(maint) Stop using the docker-api gem for spec tests

---

test/puppetlabs/puppetdb/cli/services_test.clj

Don't wait when we're testing the case where we intentionally block
the gc.  Otherwise the test takes much longer than it should.

(PDB-3952) Fix wait in test-stop-with-periodic-gc-running

---

docker/ci/build

(maint) actually fix the typo

---

docker/ci/build

Test merge 6.0.x

---

docker/puppetdb-postgres/docker-entrypoint-initdb.d/extensions.sh
documentation/configure.markdown
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/schema.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/config_test.clj

Test merge 5.2.x

---

docker/puppetdb-postgres/docker-entrypoint-initdb.d/extensions.sh
documentation/configure.markdown
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/schema.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/config_test.clj

Test merge master

---

project.clj

Merge 5.2.x -> 6.0.x

---

documentation/configure.markdown

https://tickets.puppetlabs.com/browse/DOCUMENT-947

Fixing broken link [DOCUMENT-947]

---

project.clj

Minor changes in clj-parent that do not directly impact pdb

(PDB-4197) update clj-parent to 2.4.0

---

src/puppetlabs/puppetdb/command.clj

This commit adds logging for commands when they're bashed in the
queue while being processed.

(PDB-4177) Add logging for bashed commands

---

project.clj

To keep in line with puppetserver

(MAINT) Bump clj-parent to 2.4.1

---

src/puppetlabs/puppetdb/scf/storage.clj

Don't use set returning functions in statement projections.  We were
doing that in the fact path gc operations, and postgres no longer
allows them there (as of version 10).
The approach taken here should also stop pdb from generating a flood
of tiny temp files when running the gc query.
cf. (PDB-3924)
For now I've arranged for pdb to respond to PDB_TEST_PATH_GC_VIA_TEMP_TABLE=1 to enable the temp file fix.  Without that it runs the same query without the temp table, and so you should be able to verify the fix by setting `log_temp_files = 0` in your postgresql.conf, restart pg, and then run
lein test :only puppetlabs.puppetdb.scf.storage-test/fact-path-gc
without and then with the environment variable set.
I'll remove the "don't merge" after we've finished testing, and I've removed the …

(PDB-3857) Make fact path gc compatible with pg 10+

---

.travis.yml

Removes HipChat notifications, adds Slack

(maint) switch to Slack for notifications

---

documentation/release_notes.markdown
project.clj

Merge 6.2.0-release into master

---

azure-pipelines.yml
docker/ci/build.ps1

- Cleanup containers by name that are > 14 days old by default
New cleanup message
```
Pruning Containers
Total reclaimed space: 0B
Found puppet/puppetdb images:
6.0.2 16833fdab765 2019-02-10 23:27:42 +0000 GMT
5.2.7 1eea7ca0e945 2019-02-08 20:03:16 +0000 GMT
6.2.0 5b84704c1d01 2019-02-01 20:23:46 +0000 GMT
Filtering removal candidates...
Pruning Dangling Images
Deleted Images:
deleted: sha256:992a0d77f7c0ca5b5beb4bee42b8d76e7470b04551c0ab4eab96a390b8b5468a
deleted: sha256:7ec8b7266a9eafb289eab1a04a62cdd44df6d00bbc653b997a54d025322c28cc
deleted: sha256:add31a1cde5167fd89f39a212bcf7e74278ea3bbaee0941171bc0af8d5a49969
deleted: sha256:53bd8ed7553999749ae63ca63d71263e69eb082409183feca02fe5cbe1e2b06d
deleted: sha256:5e5109d67ead48fecc05dbef47735e4d13118b0d1841e4cfd8ec7021273b8c23
deleted: …
```

(maint) Cleanup Azure container leftovers smarter

---

acceptance/setup/pre_suite/50_install_modules.rb
documentation/api/query/curl.markdown
documentation/api/query/v4/ast.markdown
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

- Keeps Docker assets intact that were deleted from the prior 5.x series
branches.

(maint) Mergeup 5.2.x to 6.0.x

---

src/puppetlabs/puppetdb/http/query.clj
test/puppetlabs/puppetdb/http/index_test.clj

When given the `ast_only: true` parameter, a database connection is
required to verify the validity of the arrays used in conjuction with
the 'in' operator. Before the db connection was not properly made
causing a NullPointerException.

(PDB-4232) Open db conn to verify AST response

---

docker/Makefile

Allow the Docker image namespace "puppet" (i.e. puppet/puppetdb) to be
configurable, which makes it easier for local development of the image.
We don't want to push these images to DockerHub ever, so we don't honor
the namespace override in the `make publish` target.

(MAINT) Configurable image name

---

docker/ci/build.ps1

For consistency with our other near-copies of this file.

(MAINT) Update container test for PE versions

---

project.clj
src/puppetlabs/puppetdb/http/query.clj
test/puppetlabs/puppetdb/http/index_test.clj

Conflicts were resolved by maintaining the state of the current branch, except
for the ezbake bump.

Merge 6.0.x -> master

---

Gemfile

(maint) bump beaker-hostgenerator to 1.1.26

---

docker/Makefile
docker/README.md

Contents copied from existing documentation on DockerHub and new
"Configuration" section added.
Update the documentation when we update the image on DockerHub.

(MAINT) Add container README

---

src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

The resource_events table can contain duplicate rows because the existing
unique constraint does not work as intended. In PostgreSQL, null values
are not considered equal in an index.
Migration now uses a set to dedupe the resource_events table as its being
written to, and the unique constraint is dropped in favor of the new
primary key on the resource_events table.

(PDB-4312) handle duplicates in resource_events table

---

azure-pipelines.yml
documentation/release_notes.markdown

Test merge 6.3.x

---

docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

#2883 contained a bug which this PR addresses

(maint) Fix unquoted Docker PDB health wait

---

documentation/api/query/v4/nodes.markdown
src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/time.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

#2871 was merged to master when it is needed on 6.3.x, this cherry picks the commits back to 6.3.x

Cherry pick query support to 6.3.x

---

documentation/api/query/v4/facts.markdown
src/puppetlabs/puppetdb/query_eng.clj
test/puppetlabs/puppetdb/http/facts_test.clj

Support order by on fact values, now that we're using jsonb.

(PDB-3687) Support ordering on fact values

---

documentation/api/query/curl.markdown

(docs) Adding example to curl docs

---

documentation/CONTRIBUTING.md
documentation/api/index.markdown
documentation/api/query/tutorial-pql.markdown
documentation/api/query/tutorial.markdown
documentation/api/query/v4/aggregate-event-counts.markdown
documentation/api/query/v4/event-counts.markdown
documentation/api/query/v4/events.markdown
documentation/api/query/v4/fact-names.markdown
documentation/api/query/v4/facts.markdown
documentation/api/query/v4/pql.markdown
documentation/api/query/v4/reports.markdown
documentation/configure.markdown
documentation/connect_puppet_apply.markdown
documentation/connect_puppet_master.markdown
documentation/ha.markdown
documentation/load_testing_tool.markdown
documentation/maintain_and_tune.markdown
documentation/pdb_support_guide.markdown
documentation/postgres_ssl.markdown
documentation/puppetdb-faq.markdown
documentation/release_notes.markdown
documentation/repl.markdown
documentation/upgrade.markdown

Fixes problems with "since" and "only" ambiguity in docs.

fix since/only problems

---

project.clj

Update lein-ezbake to 2.0.3 to support FIPS

(PDB-4385) update lein-ezbake version for FIPS

---

documentation/release_notes.markdown

(DOCS) add PDB-4422 release note

---

documentation/api/command/v1/commands.markdown
documentation/api/wire_format/replace_catalog_inputs_format_v1.markdown
ext/test/upgrade-and-exit
puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/lib/puppet/util/puppetdb/command_names.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/command/constants.clj
src/puppetlabs/puppetdb/http/command.clj
src/puppetlabs/puppetdb/queue.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/examples.clj
test/puppetlabs/puppetdb/http/command_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/testutils/queue.clj

(PDB-4372) Add "replace catalog inputs" command

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb

We're storing this in the Context

(SERVER-2581) Send hiera key lookups

---

documentation/api/query/examples-pql.markdown
documentation/api/query/v4/ast.markdown
src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/query/resources.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/inventory_test.clj
test/puppetlabs/puppetdb/http/resources_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

See commit message.
It's ready!

(PDB-2634) Hash projection for (some) json fields

---

documentation/api/query/v4/pql.markdown
resources/puppetlabs/puppetdb/pql/pql-grammar.ebnf
test/puppetlabs/puppetdb/pql/parser_test.clj
test/puppetlabs/puppetdb/pql_test.clj

(PDB-3284) Remove whitespace requirement

---

.travis.yml
docker/Makefile
docker/docker-compose.yml
docker/spec/puppetdb_spec.rb

* bundle update in Makefile
* use ENV vars in `docker-compose.yml` properly and pull images correctly
* bump compose to 1.25.0-rc2
* remove unnecessary waiter calls

(maint) Docker spec suite consistency

---

.travis.yml
dev-resources/jdk11-fips-security
dev-resources/jdk8-fips-security
project.clj

Update FIPS profile to latest known working config. Adds security
policies for JDK8 and JDK11.
Adds a FIPS test also

(PE-26658) fips profile for pdb testing

---

project.clj

Update i18n plugin to remove deprecation warning about hook

(PDB-4255) fix deprecation warning from i18n

---

ext/test/upgrade-and-exit
src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

This partial index on file will speed up queries using regular
expressions to match against partial file paths.

(PDB-4640) Add GIN index on catalog_resources file

---

documentation/release_notes/release_notes_5.2.markdown

This commit adds one new feature release note.

(DOCS) PDB 5.2.13 release notes

---

documentation/release_notes/release_notes_latest.markdown

This commit adds one new feature release note.

(DOCS) PDB 6.9.1 release notes

---

project.clj

This fixes an error with systemd on Debian 8

(maint) Bump ezbake version

---

Gemfile

(maint) acceptance test: fix pry error

---

src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

The recent changes to coordinate migrations mistakenly omitted
migrations that were older than the roll-up migration from the set of
valid migrations.
This causes an error at startup for all those who have been running
PuppetDB against databases that were in service before the rollup was
added, and so of course, include those older migrations in their
schema_migrations table.
cf. PDB-4636 PDB-4637

(PDB-4709) Don't treat rolled-up migrations as invalid

---

project.clj

This reverts commit c09f2181e3a42711299da0214ce481249aacab76.

Revert "(PDB-4748) Update pinned deps for 6.11"

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/query_eng_test.clj

Cherry pick back to 6.10.2-hotfix, no conflicts

(PDB-4769) Revert definition of active_nodes

---

documentation/release_notes/release_notes_5.2.markdown

Also adds contributors for older releases.

(doc) Add release notes for 5.2.17

---

src/puppetlabs/puppetdb/scf/storage_utils.clj
src/puppetlabs/puppetdb/utils.clj

This will help debug if the postgres is acting up or if there's an
actual timeout occuring.

(maint) Make explicit why the status check failed

---

documentation/configure.markdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query_eng.clj
test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/http/query_logging_test.clj
test/puppetlabs/puppetdb/testutils/http.clj

Probably want to hide whitespace changes during review.

(PDB-4834) Add a debug AST/SQL logging option

---

documentation/configure.markdown
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/middleware.clj
src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/schema.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/middleware_test.clj
test/puppetlabs/puppetdb/schema_test.clj

This still needs doc updates but should be ready for another set of eyes. I can squash the first couple commits into one if we prefer.

(PDB-4872) Update harmful language

---

ext/test/upgrade-and-exit
resources/ext/cli/delete-reports.erb
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/testutils/catalog_inputs.clj

This PR is just #3336 with a few changes.

(PDB-4895) Hash and index catalog inputs

---

src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

Only the final commit is new here -- the rest is #3338

(PDB-4908) Track table locking related to gc partition drops

---

src/puppetlabs/puppetdb/cli/services.clj

Add a promise to shared-globals that is delivered after the initial
garbage collection finishes. On the PE side, we will wait on that
promise to start the initial sync.

(PDB-4938) Deliver promise after initial gc

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/query_eng_test.clj

When a count function is provided, LEFT JOIN's cannot affect the total
number of results returned (unless used in a WHERE clause), so we can
allow drop-joins to remove unused LEFT JOIN's even if a count is
requested by the query.

(PDB-4984) Allow drop-joins to opimize count queries

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/command_broadcast_test.clj
test/puppetlabs/puppetdb/integration/puppetserver_metrics.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

(PDB-3418) Add new-fact-time metric

---

src/puppetlabs/puppetdb/command.clj
test/puppetlabs/puppetdb/command_test.clj

A new metric **(:concurrent-depth),** which counts the number of `/cmd` API requests that are waiting to write to the disk, was added.

(PDB-4268) Add new metric for concurrent enqueue

---

src/puppetlabs/puppetdb/command.clj

Extract this to a helper, like `shared-globals` because initial sync
will need to select the same options map that command processing uses in
order for initial sync to provide the correct settings to
`process-command!`.

(PDB-5059) Add a helper for command processing options

---

test/puppetlabs/puppetdb/http/inventory_test.clj
test/puppetlabs/puppetdb/http/nodes_test.clj

Add unit test for the changes introduced with https://github.com/puppetlabs/puppetdb/pull/3444 .

(PDB-5063) Add unit tests

---

src/puppetlabs/puppetdb/query_eng.clj
test/puppetlabs/puppetdb/http/nodes_test.clj

(PDB-5092) Update error handling in query response streaming

---

project.clj

(PE-31799) Update clj-parent to 4.6.19

---

project.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/http/reports_test.clj

Changed Pupperware branch from master to main
Skipped unit tests for issues:
- order_by fails in some subqueries
- to_string fails for integer numbers 
- to_string adds multiple spaces when extracting month from date

(PDB-5025) Added skipped unit tests for some issues

---

src/puppetlabs/puppetdb/scf/storage.clj

fact path gc is an operation we _know_ can be slow, so this will help us
in identifying if gc is stuck on this operation.

(maint) Demarcate fact-path gc with log messages

---

project.clj
src/puppetlabs/puppetdb/cli/benchmark.clj
src/puppetlabs/puppetdb/cli/time_shift_export.clj
test/puppetlabs/puppetdb/cli/time_shift_export_test.clj

This is just the beginning of this utility.
Now it only validates the input parameters and returns a "Not implemented" message.

(PDB-5097) PuppetDB export time shift utility

---

test/puppetlabs/puppetdb/integration/sensitive_params.clj

Ticket PDB-3461 is done.
As a result we can uncomment integration test sensitive-parameter-redaction.

(maint) enabled integration test 

---

project.clj
puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/lib/puppet/util/puppetdb.rb

And update clj-parent before the next release

(PDB-5134) Re-instate profiling for catalog submission

---

dev-resources/time-shift-export/input-archive/catalogs/catalog.json
dev-resources/time-shift-export/input-archive/export-metadata.json
dev-resources/time-shift-export/input-archive/facts/facts.json
dev-resources/time-shift-export/input-archive/reports/report.json
project.clj
src/puppetlabs/puppetdb/cli/time_shift_export.clj
src/puppetlabs/puppetdb/time.clj
test/puppetlabs/puppetdb/cli/time_shift_export_test.clj
test/puppetlabs/puppetdb/integration/time_shift_export.clj

The rest of the implementation for the time shift of PuppetDB export archive, utility.

(PDB-5095) Time shift PuppetDB export

---

.gitignore
documentation/testing_storage_changes.markdown
locust/load-test/config.yaml
locust/load-test/load-test.py
locust/run-load-test

Added a tool that allows us to load test the endpoints. 
Requirements: Python3
Usage: locust/run-load-test
This will generate four csv files and one html with the result.

(PDB-5094) Added load testing tool

---

acceptance/helper.rb

Since the introduction of read-only user (puppetdb-read) in puppetlabs-puppetdb module, the pre suite fails to complete with the following error: 
```
Jun 29 12:38:40 lifelong-friday puppetdb[17550]: Execution error (PSQLException) at org.postgresql.core.v3.ConnectionFactoryImpl/doAuthentication (ConnectionFactoryImpl.java:525).
Jun 29 12:38:40 lifelong-friday puppetdb[17550]: FATAL: password authentication failed for user "puppetdb-read"
```
The proposing fix consists in updating the manifest that is used for installing puppetdb.

(maint) Fix failing pre_suite for acceptance

---

src/puppetlabs/puppetdb/query_eng/engine.clj

When the query engine throws an AssertionError, a stack trace is
returned by the API, which is not what we want. And additionally, both
assertions were thrown by drop-joins, which will cause the query to fail
entirely. In one case we only want to skip attempting to drop joins.
The assertion that all projections have a set of `:join-deps` is
protected by the whole query also needing to specify that it
`:can-drop-unused-joins?`, but for `reports` we also assoc additional
projections into the query map from pe-puppetdb. That assoc was missing
a :join-deps key resulting in a query map that said it could drop joins,
but not all projections having a set of join dependencies. Replace that
assertion with an ex-info error that will short-circuit the attempt to
drop unused joins and continue to …

(PDB-5186) Replace drop-joins assertions with errors

---

documentation/release_notes.markdown

I'm not entirely sure if the intended quote and code segments will work the way I intended.  Will need to double-check.

(PDB-5178) Add release notes for 6.18.0

---

locust/load-test/cd4pe.yaml
locust/load-test/console.yaml
locust/load-test/estate-reporting.yaml
locust/load-test/load-test.py

Added estate reporting queries.
Renamed all queries so they are easier to identify by console, cd4pe and estate queries.
Added order_by parameter in the .yaml files which is used for the GET requests.

(PDB-5184) Add estate reporting queries.

---

src/puppetlabs/puppetdb/http/query.clj

If the PQL query parsing it's taking too long, a warning message it's logged that includes the query and the time the parsing took for that query.

(PDB-5168) Log PQL long parsing time

---

project.clj

This includes an update of jdbc to 0.7.11

(maint) Update clj-parent to 4.8.0

---

project.clj

Public version of the private 4.8.2 release

(maint) Update clj-parent to 4.8.3

---

test/puppetlabs/puppetdb/scf/migrate_test.clj

Add schema diff test to the existing migration 75 test.

(PDB-5336) Create migration 75 schema diff test

---

.travis.yml
ci/bin/prep-and-run-in
project.clj
test/puppetlabs/puppetdb/http/nodes_test.clj

Updates chesire to fix security issue in jackson dataformat

(maint) Update clj-parent to 4.8.4

---

src/puppetlabs/puppetdb/http/command.clj
test/puppetlabs/puppetdb/http/command_test.clj

A command with an empty string for a certname would cause the command
endpoint to throw unmanaged exceptions and potentially lock up syncing
PuppetDB applications thereafter. This was due to the way metadata was
being stored and read back in the queue. A metadata filename would be
happily created with no certname but upon processing would not recognize
the metadata without the certname. In particular, the regex did not
match empty certnames, so the result of the regex search and metadata
parsing would return nil.
In order to prevent this from happening, this change updates the command
http endpoint by correcting issues with request validation. Previously
some validation was done with Schema definitions, but the error results
returned were very unfriendly to our users. Some exceptions were …

(PDB-5282) Fix handling of empty certname at command endpoint

---

Gemfile
project.clj

Updates logback and jackson for security issues.

(maint) Update clj-parent to 4.9.1

---

project.clj

Allow CI to build PuppetDB on Debian 11

(PDB-5390) Update ezbake to 2.3.0

---

documentation/puppetdb.ditamap

Replace with missing command api link

(docs) Remove duplicate API section

---

src/puppetlabs/puppetdb/mq.clj
src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/status.clj
test/puppetlabs/puppetdb/status_test.clj

(PDB-5333) Allow retrieving PDB version without a db query

---

src/puppetlabs/puppetdb/cli/services.clj
test/puppetlabs/puppetdb/cli/services_test.clj

Run the fact path gc less frequently in order to lessen its impact on
postgres.
The fact path gc that is run during the "other" gc is quite expensive.
This can result in it taking a long time and/or putting Postgres under
load. The recent optimization to fact_contents did not provide any
improvements to the fact path gc operation, so this is ideally a
temporary fix while we further investigate why the operation is so
expensive and long running.

(PDB-5423) Only run "other" gc again after 24 hours

---

project.clj

(PDB-5449) Pin pgjdbc to 42.2.25

---

src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/status.clj
test/puppetlabs/puppetdb/status_test.clj

Revert "(PDB-5333) Allow retrieving PDB version without a db query"

---

src/puppetlabs/puppetdb/jdbc.clj

Problems with the jit have been reported with the jit, which was enabled by
deafult in pg 12.  In particular, it can cause some queries to
run *much* more slowly, even in situations where there don't appear to
be many rows involved.
So until the problem is resolved, disable the jit for all pdb
connections, by adding a "set session jit = off;" to the hikaricp
connection init string.

(PDB-5452) Disable postgres jit for all connections

---

documentation/api/command/v1/commands.markdown

(PDB-4285) Improve command endpoint docs

---

project.clj

update jackson-databind to address CVE-2020-36518
update pgjdbc to address CVE-2022-26520

(maint) update clj-parent to 4.9.7

---

puppet/lib/puppet/util/puppetdb/http.rb
puppet/spec/unit/util/puppetdb/http_spec.rb

This commit adds logic to PDB's Ruby http utils to track timeouts for
the `submit_only` server URLs, which are used by HDP. If a given URL
times out twice in a row, it is removed from the loaded config, to avoid
tying up JRubies indefinitely in the case where HDP has gone down. By
removing the URL, PDB will no longer try to submit things to it,
allowing requests to the other configured URLs to proceed quickly.
The URL will be re-added to the config whenever the JRuby instance is
refreshed: with a restart of Puppet Server, when the JRuby instance is
recreated when the "max requests per instance" threshold is hit, or if
the pool is flushed manually. Otherwise, the misbehaving URL will be
kept out of the list permanently.

(HDP-161) Remove `submit_only` server URL when it times out repeatedly (6.x)

---

documentation/api/status/v1/status.markdown
src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/status.clj
test/puppetlabs/puppetdb/status_test.clj

This reverts commit 27b68589aa3489e8d1bc301721a5297cd02b188c.
Please see commit message for more info.

Revert "(PDB-5333) Allow retrieving PDB version without a db query (v2)"

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/facts_test.clj

Please see commit message for more info.

(PE-33977) Fix AST validation regression when ~> inside extract

---

documentation/connect_puppet_apply.markdown
documentation/connect_puppet_server.markdown
documentation/install_from_packages.markdown
documentation/install_via_module.markdown
documentation/pdb_client_tools.markdown

Fixed two links and fixed a typo in step numbering. PE-34100, PE-34084, PE-34083.

(doc) Link and typo fixes

---

README.md
ci/bin/prep-and-run-in
ci/bin/run
documentation/release_notes_7.markdown
ext/bin/dep-diff
pdb
project.clj

* 7.x:
(maint) update pyenv to 3.7.13
(PE-34636) update clj-parent to 5.2.5, bc references
(maint) update travis integration test refs
(maint) Update readme build status link
(docs) update release notes date
@jonathannewman

(maint) merge up 7.x

---

documentation/release_notes_7.markdown

This adds the release notes for features and bug fixes for the 7.13.0 release.

(PDB-5616) add release notes for 7.13.0 version

---

documentation/release_notes_7.markdown
project.clj

* 7.x:
([PDB-5636](https://tickets.puppetlabs.com/browse/PDB-5636)) update ezbake to 2.4.2
(maint) Update version to 7.13.2-SNAPSHOT
(maint) Update version to 7.13.1 for release
([PDB-5657](https://tickets.puppetlabs.com/browse/PDB-5657)) Add 7.13.1 release notes

Merge 7.x into main

---

src/puppetlabs/puppetdb/cli/benchmark.clj

The math for the max queue size was wrong because it used hosts-per-sec to determine the queue size and always based its value off of run-interval. When benchmark is run in num-msgs mode it submits commands as fast as possible and the hosts-per-sec rate is unrelated to run-interval.

(maint) benchmark: fix num-msgs command rate

---

test/puppetlabs/puppetdb/integration/reports.clj

PuppetDB 8 only needs to maintain compatibility with Puppet 7 and 8, so it will not test Puppet 6

(maint) Remove unnecessary Puppet version checks

---

documentation/release_notes_7.markdown
src/puppetlabs/puppetdb/scf/storage_utils.clj
test/puppetlabs/puppetdb/http/resources_test.clj
test/puppetlabs/puppetdb/testutils/resources.clj

(PDB-5713) Fix bug with !~ operator
