acceptance/setup/pre_suite/40_install_deps.rb
This will hopefully fix the acceptance test failures that cropped up today in relation to OPS-5175
=> (maint) use latest lein

src/puppetlabs/puppetdb/cli/services.clj, test/puppetlabs/puppetdb/cli/services_test.clj
In order to support pagination in the service query method, have it
accept a map instead of the raw query structure.  The map should contain
a :query referring to the original query, alongside (optional)
:order-by, :offset, and :limit members.
=> (PDB-1071) Add pagination to service query method

src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/testutils/jetty.clj
Previously the jetty testutils service instances' configs were only
adjusted by process-config!, but the actual server's config was also
adjusted by hook-tk-parse-config-data.  Change it so that
adjust-tk-config is applied in both cases.
Doing so exposes a bug -- a [global] url-prefix setting with a relative
path like "foo" will prevent the server from responding on /foo.  That's
because add-web-routing-config (via the tk hook) wasn't normalizing the
url-prefix before stashing it in in the web-router-service config.  To
fix that, normalize the url-prefix in add-web-routing-config.
=> Apply the TK hook config to the test instances too

puppet/spec/spec_helper.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb, puppet/spec/unit/indirector/facts/puppetdb_spec.rb
In Puppet 4 directory environments are enabled by default, which means that
environments referenced in a config file must have a corresponding directory
in the environment path or an error will be thrown. This patch creates a
my_environment directory for facts and catalogs to bring us into accordance.
=> (PDB-1052) fix spec tests on puppet master

ext/jenkins/beaker-tests-source.sh
This commit sets the BEAKER_department variable to 'eso-dept',
to improve AWS usage reporting.
After review and merge, please merge or cherry-pick up to 'master'.
=> (maint) Set Beaker AWS department to 'eso-dept'

project.clj
@kbarber 
Hey thanks for setting up those jobs. I've modified the uberbuild job to use `lein-ezbake` and kicked off a run of that pipeline using my fork of puppetdb. I'll probably go to sleep before the acceptance matrix finishes but here it is: 
https://jenkins.puppetlabs.com/view/PuppetDB/view/lein-ezbake/job/platform_puppetdb_intn-sys_lein-ezbake/2/
=> (EZ-15) Update project.clj with lein-ezbake snippets.

tasks/tar.rake
Source based tests were failing since the uberjar name has been changed. This
patch ammends the rake install process to use the puppetdb-release.jar
filename instead as per the new project.clj change.
=> (maint) Fix rake install process to use new ezbake uberjar file

documentation/configure.markdown, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/testutils/jetty.clj
This commit deprecates the use of the `url-prefix` config setting under
the `[global]` header, favoring the use of the webrouting service to
configure the url-prefix. This commit uses the WebroutingService
get-route function to retrieve the url-prefix from the config data,
using the hook in config.clj to add a default or copy the config from
global url-prefix to the web-routing config.
=> (PDB-1070) Deprecate url-prefix in global

puppet/lib/puppet/indirector/catalog/puppetdb.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
This commit adds support for hyphenated classnames, supported by Puppet
2.7.x - 3.7.x.
=> (PDB-1024) Add support for hyphenated classnames

src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/facts_test.clj
This corrects an oversight in adding the hash field to factsets that left
ordering results on hash impossible. I'm not a fan of the solution here, but it
follows our approach for environments and I can't think of a better way ATM.
The constraints are:
a) The factsets query must be "doubled up" in jdbc.clj so that paging options are applied
on an object basis instead of a by-row basis (a factset comprises multiple rows.)
b) Both environment and hash are nullable fields in factsets, so a COALESCE is
necessary to prevent a "WHERE null IN null" scenario.
=> (maint) Allow factset ordering on hash

src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query/factsets.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/utils.clj
Reports, factsets and catalogs all have similar code, lazily collapsing n DB rows into a single JSON object. This commit refactors that logic to a single place.
I originally did this because I was repeating the logic again. Turned out I didn't need to collapse rows anymore, but the refactor still seemed good, so I'm pushing it up as a maint PR.
=> Refactor lazy collapsing of DB results to use common code

Gemfile, acceptance/config/ec2-west-debian6-64mda-64a.cfg, acceptance/config/ec2-west-debian7-64mda-64a.cfg, acceptance/config/ec2-west-el5-64mda-el5-64a.cfg, acceptance/config/ec2-west-el6-64mda-el5-64a-ubuntu1204-64a.cfg, acceptance/config/ec2-west-el6-64mda-el6-64a.cfg, acceptance/config/ec2-west-el6-64mda.cfg, acceptance/config/ec2-west-el7-64mda-el7-64a.cfg, acceptance/config/ec2-west-f20-64mda-f20-64a.cfg, acceptance/config/ec2-west-ubuntu1004-64mda-64a.cfg, acceptance/config/ec2-west-ubuntu1204-64mda-64a.cfg
This changes all the templates to provide the correct vpc/subnet ids
and pins our beaker gem to use my test branch (at least until this is
merged).
=> Add VPC support for acceptance test hosts for PuppetDB

acceptance/config/ec2-west-debian7-64mda-fallback.cfg
This corrects a typo in the ec2 instance configuration designed to test the
terminus fallback scenario.
=> (PDB-885) Correct hostname for beaker fallback test instances

resources/ext/ezbake.conf
Puppet 5.0.0 will likely include breaking changes as it is a major
version boundry. Putting this metadata in the package will prevent users
from accidentally having that broken setup.
=> (PDB-916) Only support puppet 3.7.3+ and 4.y.z releases

test/com/puppetlabs/puppetdb/test/zip.clj
The couldn't satisfy such-that unit test failure can happen if the
test.check generator generates 10 possible "trees" that are not
collection, such as all leaves. This can cause false negative test
results. This commit increases the probability a tree with leaves will
be created and increases the number of attempts (from 10 to 100) that
such-that will make before giving up.
=> (PDB-1109) Couldn't satisfy such that unit test failure

src/puppetlabs/puppetdb/cli/benchmark.clj, src/puppetlabs/puppetdb/cli/export.clj, src/puppetlabs/puppetdb/cli/import.clj, src/puppetlabs/puppetdb/client.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/testutils/jetty.clj, test/puppetlabs/puppetdb/utils_test.clj
Note that there are 4 commits, which might or might not be easier to review individually, and I wondered about defaulting the base-url :protocol to "http".  Right now it has to be specified every time.
(This series is based on the PDB-1070 PR and so may need to be rebased once that goes in.)
=> (PDB-1068) Recognize prefix urls in import export

documentation/api/index.markdown, documentation/api/query/v4/aggregate-event-counts.markdown, documentation/api/query/v4/catalogs.markdown, documentation/api/query/v4/environments.markdown, documentation/api/query/v4/event-counts.markdown, documentation/api/query/v4/events.markdown, documentation/api/query/v4/fact-contents.markdown, documentation/api/query/v4/fact-names.markdown, documentation/api/query/v4/fact-paths.markdown, documentation/api/query/v4/facts.markdown, documentation/api/query/v4/factsets.markdown, documentation/api/query/v4/nodes.markdown, documentation/api/query/v4/operators.markdown, documentation/api/query/v4/paging.markdown, documentation/api/query/v4/query.markdown, documentation/api/query/v4/reports.markdown, documentation/api/query/v4/resources.markdown, documentation/api/query/v4/server-time.markdown, documentation/api/query/v4/version.markdown, src/puppetlabs/puppetdb/http/server.clj
This commit removes the warning message when using the v4 endpoint of
the query api as well as the corresponding documentation changes needed
to express that v4 is the new 'stable' endpoint.
Merge with https://github.com/puppetlabs/puppet-docs/pull/426.
=> (PDB-1105) Remove experimental status of v4 api

documentation/configure.markdown, documentation/connect_puppet_master.markdown, documentation/puppetdb_connection.markdown
While writing the documentation on new configuration for terminus
failover, I noticed some out of date documentation on puppetdb.conf in
puppet-docs. I copied the shell of those docs here and updated them to
current and added som failover specific information.
=> (PDB-486) Add documentation on terminus failover support

acceptance/helper.rb
Without this, we'll use the puppetdb module default, currently v3, when
testing with the packaged module.
=> (PDB-695) Configure module to test against v4 API

acceptance/helper.rb
This commit addresses an issue where v3 of the http api was removed from
pdb but a bug in the pdb-module prevents us from validating a connection
from the master using the v4 of the api without a release of the module.
This *should* be turned back to the default (true) when this issue is
addressed.
=> (patch) Turn off strict_validation for master::config

resources/ext/config/conf.d/jetty.ini.erb, resources/ext/config/logback.xml.erb, resources/ext/config/request-logging.xml.erb
This commit add the necessary logback config and commented out param in
the jetty.ini to easily enable access-logging for PuppetDB.
=> (PDB-477) Setup access-logging by default

resources/ext/config/logback.xml, resources/ext/config/request-logging.xml
This commit makes the logback xml configs for the pdb package static as
ezbake does not support templating anything not in the conf.d resource
directory yet.
=> (PDB-477) Untemplate the logback xml configs

project.clj
This updates our dependencies to include trapperkeeper 1.0.1, and trapperkeeper-jetty9
1.1.1.
Other dependencies have been adjusted as well, to resolve dependency issues.
=> (PDB-1095) Upgrade to latest tk/tk-jetty

src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/http/factsets.clj, src/puppetlabs/puppetdb/schema.clj, test/puppetlabs/puppetdb/config_test.clj, test/puppetlabs/puppetdb/schema_test.clj
This commit changes the behavior of the config validation by warning
users in the log when there is an unused config item in the config file
instead of failing hard. This commit also refactors the items in
config.clj so that changes like this are a little easier in the future
by adding a `configure-section` function which removed the duplication
with `configure-puppetdb`, `configure-write-db`, etc.
=> (PDB-1067) Warn user with unknown config items

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj
Removed documentation for this setting, and code to check/warn about it's deprecation.
=> (PDB-693) Remove previously deprecated 'event-query-limit' setting

ext/templates/puppetdb-env.erb
There is a bug affecting some OSes where this template will miss a necessary newline in the bash it generates.  An example is here:
https://gist.github.com/wkalt/fe8949ea40eb95c3aa9b
note that JAVA_BIN and INSTALL_DIR are on the same line
=> (maint) fix puppetdb-env.erb so it generates valid bash

Gemfile
This pins our version of retriable so we keep Ruby 1.9.x compatibility.
=> Pin against Ruby 1.9.x compatible version of retriable

acceptance/helper.rb
Puppet 3.7.4 introduced a bug with Fedora (more info here
https://tickets.puppetlabs.com/browse/PUP-3927). This patch pins to
Puppet 3.7.3 only on Fedora, until a fix has been released.
=> (PDB-1200) Added pinning to Puppet 3.7.3 on Fedora

ext/travisci/test.sh
Travis is frequently failing with the following message:
java.lang.OutOfMemoryError: unable to create new native thread, this
patch fixes that by bumping the ulimit before running the tests.
=> (PDB-1202) Fix Travis OOM native thread error

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
Submitting the same factset more than once causes the factset hash to
change even though it's payload is still the same. This patch removes
those fields from the hash calculation.
=> (PDB-1199) Remove timestamps from factset hash calculation

src/puppetlabs/puppetdb/cli/services.clj, test/puppetlabs/puppetdb/cli/services_test.clj
Added another function to the PuppetDBServer TK service to allow
submission of commands in-process, similar to the way we allow querying
in-process. This allows other modules running in the same JVM instance
to submit commands directly to PuppetDB without having to use an HTTP call.
=> (PDB-1198) Added support for submitting commands in-process

test/puppetlabs/puppetdb/testutils/jetty.clj
This patch dynamically creates a temp logback and temp log file that an
in-process launched PuppetDB instances uses. Previously when an error
occurred in that Jetty instance, it was difficult to determine the
problem. Sometimes errors were lost, others were difficult to sort
through since it wrote to the same System.err that the test thread was
running in. This patch writes all in-process PuppetDB log information to
an actually file, which is scraped and dumped into the test thread's
console, make it much easier to diagnose errors
=> (PDB-908) Improve debugging info of in-process launched PDB

ext/jenkins/beaker-tests-source.sh
To avoid transient errors with bundler, we can use the --retry argument to
retry attempts at downloading gemfiles & git repos during bundle install.
=> (maint) Use bundler retries for PR testing

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/mq.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/mq_test.clj, test/puppetlabs/puppetdb/testutils/jetty.clj
These shims are just for testing and specifically to allow in-process testing of more than one PuppetDB instance.
=> (PDB-908) Add the ability to disable AMQ JMX and set a different queue destination name

project.clj
Previously lein-ezbake 0.2.0 wasn't working when we overrode local-repo
during beaker source based installation. The 0.2.1 revision passes the local-repo
through to the correct places so this works.
=> (PDB-1034) Upgrade lein-ezbake to support :local-repo

Gemfile
Without this, the upgrade to google-api-client 0.8 will have conflicts, since
this gem now pulls in activesupport >=3.2.
=> Switch to using 3.2 version of activerecord

Gemfile
Our ezbake patch has been merged, this pins our builds against that sha1 until
its released properly.
=> Pin beaker branch against a sha1 in master now ezbake patch is merged

documentation/connect_puppet_master.markdown, puppet/lib/puppet/face/storeconfigs.rb, puppet/lib/puppet/indirector/catalog/puppetdb.rb, puppet/lib/puppet/util/puppetdb/command.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb, puppet/spec/unit/indirector/facts/puppetdb_spec.rb
This commit removes all the to_pson calls in the terminus as well as
removing the associated char_encoding code that is dead code with the
switch to to_json.
=> (PDB-1026) Remove to_pson calls in terminus

documentation/release_notes.markdown, src/puppetlabs/puppetdb/scf/hash.clj, test-resources/puppetlabs/puppetdb/cli/export/big-catalog.json, test/puppetlabs/puppetdb/scf/hash_test.clj
If the user submits a new catalog with no changes other than tags, 
the catalog should still be stored. It previously was not, since the
tags were not part of the catalog hash computation. 
This does not update existing hashes stored in the db, so the next 
catalog update for each node will cause a db write.
=> (PDB-332) Add tags to catalog hash

Gemfile
We can now release our pinning against the sha1 in beaker master, now that the
ezbake code has been released as a gem.
=> Remove pinning against a git sha1 for beaker now ezbake helpers have been released

documentation/api/query/v4/events.markdown, src/puppetlabs/puppetdb/http/events.clj, test/puppetlabs/puppetdb/http/events_test.clj
This makes the query parameter for /events optional, for consistency with our
other endpoints.
=> (PDB-1132) events should not require a query

acceptance/helper.rb, acceptance/tests/reports/report_storage.rb, documentation/api/commands.markdown, documentation/api/query/v4/reports.markdown, documentation/api/wire_format/report_format_v5.markdown, puppet/lib/puppet/reports/puppetdb.rb, puppet/spec/unit/reports/puppetdb_spec.rb, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/reports.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/validation.clj, test-resources/puppetlabs/puppetdb/cli/export/reports-query-rows.json, test-resources/puppetlabs/puppetdb/cli/export/sample-report.json, test/puppetlabs/puppetdb/examples/reports.clj, test/puppetlabs/puppetdb/query/reports_test.clj
This adds a "noop" field to the reports object, which is a boolean flag
indicating whether the run producing the report was a --noop.
=> (PDB-1177) add noop flag to reports

project.clj
This bumps us to use ezbake 0.2.2, which at the very least solves logrotate
pathing mistakes in 0.2.1.
=> Bump to latest ezbake plugin

src/puppetlabs/puppetdb/query.clj, test/puppetlabs/puppetdb/query/reports_test.clj
This removes some of the legacy query code since we've dropped v3.
This doesn't put much of a dent in the file query.clj, but it at least
removes the obvious unused functions. We still use this query engine in
some of our weird endpoints, so greater work will be required to remove
the lot.
For now this removes some of the dead code at least.
=> Remove some unused legacy query code

acceptance/tests/security/cert_whitelist.rb, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/metrics.clj, src/puppetlabs/puppetdb/metrics/server.clj, src/puppetlabs/puppetdb/middleware.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/middleware_test.clj
Perhaps this is too ambitious? But simply changing the error message would mean middleware/wrap-with-authorization only really works for the whitelist, when an abstraction is already implemented via the `authorizer` parameter.
=> (PDB-1003) Better message on whitelist failure

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/testutils/reports.clj
There are many ways to represent an ISO 8601 timestamp in string
form. The end result is the posibility of having to two timestamps that
are the same, but represented different which causes the report to hash
differently. Although Puppet should be sending PuppetDB UTC dates, our
tests were using non-UTC dates, which would cause the dates to be stored
in another timezone, then converted to UTC on the way out of the
database which is really confusing.
=> (PDB-1241) Resource Event timestamps should be normalized before stored

src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/testutils/jetty.clj
These changes are to the tests only. This function will invoke a
function and wait for the messages put on the queue to be consumed. Will
throw an exception if the message takes too long, ends up in the
DLO. There is also code to ensure that the JMX beans have been
initialized after startup before the checking for consumed messages.
=> (PDB-908) Adding a new test until-consumed function

src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query/events.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/query/events_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj
This commit adds a migration which changes our database schema to use an
integer primary key for reports. This commit merges this migration with
the noop column migration since they are going out in the same release.
=> (PDB-1218) Add id to reports table

test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj
For some reason the facts data is committed (from an AMQ standpoint) but
the test doesn't show it as available for querying. Added a block for
facts like I did for reports to wait for when that data is visible.
=> (PDB-908) Add blocking on visibility of facts data in import/export test

acceptance/config/ec2-west-debian6-64mda-64a.cfg, acceptance/config/ec2-west-debian7-64mda-64a.cfg, acceptance/config/ec2-west-el5-64mda-el5-64a.cfg, acceptance/config/ec2-west-el6-64mda-el5-64a-ubuntu1204-64a.cfg, acceptance/config/ec2-west-el6-64mda-el6-64a.cfg, acceptance/config/ec2-west-el6-64mda.cfg, acceptance/config/ec2-west-el7-64mda-el7-64a.cfg, acceptance/config/ec2-west-f20-64mda-f20-64a.cfg, acceptance/config/ec2-west-ubuntu1004-64mda-64a.cfg, acceptance/config/ec2-west-ubuntu1204-64mda-64a.cfg
This switches us to availability zone us-west-2a to work on c3.large
capacity issues in us-west-2b.
=> (maint) Switch to different subnet-id for different availability zone

documentation/api/query/v4/reports.markdown, documentation/release_notes.markdown, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/reports_test.clj
This implements the latest_report? query on the reports endpoint. As with
events, this field is not returned in the response.
=> (PDB-1244) support latest_report? on reports

test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/testutils.clj
This commit adds an =-after? macro for use in puppetdb tests which takes
some transform function as its first arg and applies that function to
all subsequent args.
=> (maint) Add =-after? macro for import/export testing

Rakefile, ext/redhat/puppetdb.spec.erb
Update the terminus installation path for puppet 4 to match the paths specified
at https://github.com/puppetlabs/puppet-specifications/blob/master/file_paths.md,
changing agent/ to puppet/
=> (re-4060)(packaging) Update terminus install paths for puppet 4

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/query/factsets.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/testutils/jetty.clj
Making mq-endpoint ended up not being useful in running multiple
PuppetDB command queues, this commit removes it. This also moves a
couple of now shared functions to a more reusable place.
=> (PDB-908) Remove dyanmic from mq-endpoint, test function refactors

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/http/events.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/time.clj
Previously we were using clj-time.format/to-timestamps's default
ordering of date formatters to attempt to parse the incoming
string. This just used the values in the formatters map in whatever
order they are stored. These formats are used in the order they come out
of the hash-map until one successfully parses the time. This means we
could potentially have 10+ failures to parse a date before a successful
parse, and we do this each time in each report/catalog/factset etc.
This commit switches to use an ordered list of formatters, using the
most likely parsers to work (i.e. ISO8601), then falls through to the
existing behavior.
=> (PDB-1259) Faster conversion of strings to timestamps

README.md
The "Overview" link is broken. I guess it should point to index.markdown in the "documentation/api" instead of "documentation/api/query"
=> Fix "Overview" link

acceptance/tests/security/cert_whitelist_legacy.rb, documentation/configure.markdown, project.clj, src/com/puppetlabs/puppetdb/cli/services.clj, src/com/puppetlabs/puppetdb/config.clj, src/com/puppetlabs/puppetdb/http/metrics.clj, test/com/puppetlabs/puppetdb/test/config.clj, test/com/puppetlabs/puppetdb/testutils/jetty.clj
This includes cherry-picks of ea8f696:
This patch upgrades trapperkeeper, and the jetty component to the latest
revision. All lines of this patch are attributable to getting this to
work.
The major change was the change to certificate-whitelist, which is
not supported in trapperkeeper-webserver-jetty9 so we had to intercept
the configuration item, deprecate it and move it to a new [puppetdb] section
so we could do this work ourselves.
We avoid using [global] in this instance, since we have identified
a potential to clash if we want to bundle PDB with other clojure applications,
this is a general problem anyway - but our first move to try and reduce
this potential.
and 1476b28:
Correct the ssl-protocols rewrite for the master branch
Right now tk-webserver-jetty9 0.7.5 requires a list to be …
=> (PDB-1247) Upgrade TK to get max-threads support

project.clj
This commit adds a test classifier and a corresponding profile so that
when we build and deploy the puppetdb jar we get a `-test`
jar so that downstream consumers of puppetdb can use the pdb-testutils code.
=> (PDB-1179) Add test classifier for pdb testutils

src/puppetlabs/puppetdb/cli/benchmark.clj
This fixes an argument ordering error that caused the -F, -C, and -R flags to have the same
effect as the default case.
=> (maint) fix -F/-C/-R options for benchmark tool

Rakefile, ext/templates/deb/postinst.erb, ext/templates/dev/redhat/redhat_dev_postinst.erb, ext/templates/puppetdb-ssl-setup.erb, tasks/template.rake
Convert puppetdb-ssl-setup to puppetdb-ssl-setup.erb, and prepend the
AIO path to PATH.
Remove extraneous PATH settings from the Debian and Red Hat postinsts
since puppetlabs-ssl-setup sets the PATH internally, and nothing else in
the postinsts is relevant.
=> (PDB-1277) Fix puppetdb-ssl-setup/postinsts for AIO

ext/redhat/puppetdb.spec.erb
Nothing in puppetdb's runtime requires facter itself. Facter is a
transitive dependency of puppet, but does not need to be called out by
itself in the specfile. Puppet is required for the ssl setup.
=> (maint) Remove facter requirement from rpm specfile

src/puppetlabs/puppetdb/cli/benchmark.clj
This adds validation that nummsgs or runinterval is used, and adds numhosts to
the list or required parameters.
=> (PDB-1268) Add validation for benchmark parameters

documentation/_puppetdb_nav.html
New process:
- When you create or remove docs pages, please edit this TOC file to match.
- When you branch to make a new PuppetDB version, please edit the version number
in the TOC.
- We'll still need to wire up new PuppetDB versions in the puppet-docs repo,
but we won't need to host the TOC file in our repo; we can use it in place.
=> (docs) Add docs sidebar nav (TOC) file to PuppetDB repo, as _puppetdb_nav.html

documentation/connect_puppet_master.markdown, documentation/install_from_source.markdown
This commit updates the install from source documentation to reflect
steps needed when using the Puppet all-in-one agent.
It also updates the system calls to by init style agnostic.
Specific changes:
* If AIO is used the rake command should be the puppet supplied rake.
* The puppetdb user and group need to be created, since the service runs as
this user by default.
* System files need to be owned by the puppetdb user.
*  If AIO is used, the terminus code should be copied to the puppet vendored
ruby location.
* Change sysvinit system calls to be init system agnostic. Indicate where the
init files go for both sysvinit and systemd
=> (PDB-1305) Update install from source docs for AIO

src/puppetlabs/puppetdb/scf/migrate.clj
This fixes an issue with migrations from stable->master if facts exist in the
database without reports. Migration 29 was using an inner join
where a left outer join was required, which was causing the new certnames
table to leave behind everything without an associated report.
To reproduce the original problem,
git checkout stable
* start puppet, puppetdb
git checkout 1aafe0637f59bebf39ae61a1125907f5655b1e59
lein run benchmark -c postgres.ini -F acceptance/benchmark/facts -n 5 -N 20 -r 10
* stop puppetdb, puppet
git checkout master
* restart puppet, puppetdb
<migration fails>
=> (PDB-1290) fix inner join in migration 29

resources/ext/config/conf.d/config.ini, resources/ext/config/conf.d/database.ini, resources/ext/config/conf.d/jetty.ini, resources/ext/ezbake.conf
This commit removes the PE references from the pdb ezbake packaging
configs as we are going to build the pe package of puppetdb out of the
pe-puppet-extensions/puppet-sync repo.
=> (PDB-1179) Remove PE references from PDB packaging

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/metrics.clj, src/puppetlabs/puppetdb/metrics/server.clj, src/puppetlabs/puppetdb/middleware.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/metrics/core_test.clj
This commit cleans up the syntax of the starting of puppetdb and the
building of puppetdb webapplications with an authorizer. As new
webservers are added into the puppetdb project it is desirable to have
clean, standardized examples of build-app functions and configuration
manipulation. This commit also adds the authorizer, built from the
certificate-whitelist config, to the shared-globals of the
PuppetDBServer so that other apps need not build the authorizer from
scratch again.
=> (PDB-1179) Simplify start-puppetdb and webapp building

test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/mq_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
This renames testutils/jetty to testutils/services, which captures the scope of
its use and content a bit better. Some minimal cleanup as well.
=> (PDB-1255) Refactor jetty testutils

src/com/puppetlabs/puppetdb/scf/hash.clj, src/com/puppetlabs/puppetdb/scf/storage.clj, src/com/puppetlabs/puppetdb/utils.clj, test/com/puppetlabs/puppetdb/test/http/events.clj, test/com/puppetlabs/puppetdb/test/scf/hash.clj, test/com/puppetlabs/puppetdb/test/scf/storage.clj, test/com/puppetlabs/puppetdb/testutils/reports.clj
In master, we've changed our report hashing so that timestamps are converted to
a consistent representation before being hashed.
This backports that change to stable so that users will receive the update in 2.3.1,
and by the time they make it to 3.0 their reports should already be right.
Additional handling will be required in master for various edge cases.
=> (PDB-1286) backport resource timestamp normalization to stable

test/puppetlabs/puppetdb/scf/storage_test.clj
this removes a storage test that was mistakenly duplicated rolling up stable to
master rollup.
=> (maint) remove duplicated storage test

src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/metrics/server.clj, src/puppetlabs/puppetdb/middleware.clj
This commit factors out the wrapping of the default puppetdb middleware
to a `wrap-with-puppetdb-middleware` that is to be used to for all the
puppetdb webservers.
=> (PDB-1182) Factor out default puppetdb middleware

puppet/lib/puppet/indirector/facts/puppetdb.rb, puppet/spec/unit/indirector/facts/puppetdb_spec.rb
When adding trusted facts, a fallback mechanism is used to pull them
from the node object if there aren’t any there already. This code is
broken in puppet 4; it’s unclear whether it happened to work in puppet 3
because there was a global request object available or because this 
code was never called. In any case, the change works in both.
=> (PDB-1342) Fix trusted facts fallback

src/com/puppetlabs/puppetdb/scf/migrate.clj, test/com/puppetlabs/puppetdb/test/scf/migrate.clj
(PDB-1362) Drop values constraint earlier in fact paths migration
```
src/com/puppetlabs/puppetdb/scf/migrate.clj       |  2 +-
test/com/puppetlabs/puppetdb/test/scf/migrate.clj | 22 +++++++++++++++++++++-
2 files changed, 22 insertions(+), 2 deletions(-)
```
=> (PDB-1362) Drop values constraint earlier in fact paths migration

acceptance/tests/inventory/basic_fact_retrieval.rb, documentation/api/wire_format/catalog_format_v6.markdown, puppet/lib/puppet/face/storeconfigs.rb, puppet/spec/unit/face/storeconfigs_spec.rb, resources/puppetlabs/puppetdb/benchmark/samples/facts/pg2.vm.json, resources/puppetlabs/puppetdb/benchmark/samples/facts/puppetdb1.vm.json, src/puppetlabs/puppetdb/catalogs.clj, src/puppetlabs/puppetdb/facts.clj, src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query/factsets.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/examples.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/http/explore_test.clj, test/puppetlabs/puppetdb/http/fact_names_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/query/fact_names_test.clj, test/puppetlabs/puppetdb/query/nodes_test.clj, test/puppetlabs/puppetdb/query/population_test.clj, test/puppetlabs/puppetdb/query/resources_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/testutils/nodes.clj, test/puppetlabs/puppetdb/testutils/resources.clj
Other features would like to rely on the value of producer_timestamp. 
Newer versions of puppet populate this field, but it may be null
in upgrade scenarios. In that case, we can use the receive time 
('timestamp') with no ill effects.
=> (PDB-1264) Ensure producer_timestamp has a value

ext/templates/deb/control.erb
Previously installing the puppet-agent and puppetdb together would not
work on debian/ubuntu because puppetdb requires a specific version of
puppet or puppet-common, which puppet-agent cannot provide. This commit
addresses that by allowing puppet-agent to be a fallback if
puppet/puppet-common is not available (puppet for puppetdb,
puppet-common for the terminus).
=> (PDB-1389) Add puppet-agent option for debian dependencies

project.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/http/command.clj, src/puppetlabs/puppetdb/mq.clj, src/puppetlabs/puppetdb/mq_listener.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/http/command_test.clj, test/puppetlabs/puppetdb/mq_test.clj, test/puppetlabs/puppetdb/testutils.clj
(PDB-1252) Remove clamq; use ActiveMQ directly
Remove clamq entirely, and instead, just call ActiveMQ and javax.jms
directly.
=> (PDB-1252) Remove clamq; use ActiveMQ directly

.gitignore, Gemfile, Rakefile, acceptance/config/ec2-west-dev.cfg, acceptance/helper.rb, acceptance/setup/early/00_remove_previous_config.rb, acceptance/setup/pre_suite/05_clear_firewalls.rb, acceptance/setup/pre_suite/12_upgrade_distros.rb, acceptance/setup/pre_suite/15_setup_repos.rb, acceptance/setup/pre_suite/20_install_puppet.rb, acceptance/setup/pre_suite/30_generate_ssl_certs.rb, acceptance/setup/pre_suite/40_install_deps.rb, acceptance/setup/pre_suite/50_install_modules.rb, acceptance/setup/pre_suite/60_munge_etc_hosts_for_dujour.rb, acceptance/setup/pre_suite/70_install_released_puppetdb.rb, acceptance/setup/pre_suite/80_add_dev_repo.rb, acceptance/setup/pre_suite/90_install_devel_puppetdb.rb, documentation/acceptance_tests.markdown
Add support for iterating on acceptance tests more quickly by allowing a
developer to re-run them against an already created VM.
- Add PUPPETDB_SKIP_INSTALL and BEAKER_NO_PROVISION environment variables
to the Rakefile
- Add a beaker configuration designated for running these tests 
(ec2-west-dev)
- Add the beaker:first_run and beaker:rerun rake tasks
- Use a patched version of beaker that works on OS X hosts
- Document how this all works
=> (maint) Support iterative acceptance test development

Gemfile, puppet/spec/spec_helper.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb, puppet/spec/unit/reports/puppetdb_spec.rb, puppet/spec/unit/util/puppetdb/config_spec.rb
This commit updates the rspec dependency and updates the terminus spec
code to remove the associated updates new failures, deprecations and
warnings. This commit enables the `:should` syntax explicitly in the
`spec_helper.rb` to remove a deprecation warning that was introduced in
rspec 3.x.
Relates to https://tickets.puppetlabs.com/browse/BKR-100.
=> (PDB-1412) Update rspec dependency from 2.x to 3.x

src/puppetlabs/puppetdb/cli/services.clj, test/puppetlabs/puppetdb/http/facts_test.clj
Close the BoneCPDataSource when finished, freeing its threads (among
possibly other things).  Doing so substantially decreases the active
thread count at for the end of "lein test", which can be demonstrated by
adding this to the top of a test file before a run:
(defmethod report :begin-test-var [m]
(binding [*out* *err*]
(prn (:var m) :active-threads (Thread/activeCount))))
These changes should also affect normal invocations of "services -c ...".
src/puppetlabs/puppetdb/cli/services.clj     | 28 ++++++++++++++--------------
test/puppetlabs/puppetdb/http/facts_test.clj |  3 ++-
2 files changed, 16 insertions(+), 15 deletions(-)
=> (maint) Clean up BoneCP resources when finished

src/puppetlabs/puppetdb/query.clj, test/puppetlabs/puppetdb/http/aggregate_event_counts_test.clj
This specifically breaks when distinct_resources is true when using
report_receive_time, run_start_time or run_end_time. This code path
doesn't go through the query engine and we just missed these extra query
fields.
=> (PDB-1390) Fix dash to underscore issue with aggregate event counts

ext/build_defaults.yaml
Fedora 19 went EOL on 2015-01-06. We should not longer be providing
packages for this platform.
=> Remove Fedora 19 from build targets

acceptance/helper.rb
SNAPSHOT builds now get renamed when packages to be in rc form, this patch
renamed the existing format to be compatible.
=> (maint) Fix versioning rewrite for SNAPSHOT

src/com/puppetlabs/puppetdb/version.clj, test/com/puppetlabs/puppetdb/test/http/version.clj
The version-check function uses clj-http, which uses Apache HttpClient
for all the heavy lifting. Recent versions of HttpClient log connection
problems to INFO when using the library's built-in retry facilities.
This is suboptimal, as what's supposed to be a silent background process
(one where it's okay if it fails) to something that may freak out users
with scary looking error messages that are actually harmless.
If you disable automatic retries on the request, HttpClient throws an
exception; this matches the behavior of older versions. Since retries
aren't really required for version-checking, this patch disables them
and thus returns control of logging back to us.
=> (PDB-1428) Suppress version-check INFO logging

project.clj
This bumps us to the latest revision of TK/jetty9 for the purposes of bumping
the schema dependency. I've also upgraded to the latest kitchensink just for
maint purposes mainly.
=> (maint) Bump to latest trapperkeeper/jetty9/kitchensink

config/image_templates/ec2.yaml
Switch to a hand-modified el-7 image -- the only change was to purge the
pe-* packages that had been left behind by a bug in the puppetdb-packer
scripts.
=> (PDB-1431) Remove PE packages from el-7 AMI

project.clj, test/puppetlabs/puppetdb/query/events_test.clj, test/puppetlabs/puppetdb/testutils.clj, test/puppetlabs/puppetdb/testutils/reports.clj
Found some failures in the events_test that was relying on the order of
entries in a map that has changed in 1.7.0. Created a version of
clojure.core/select-values that will preserve the order of selected keys
and switched to an ordered-map to fix the issue.
=> (maint) Bump to clojure 1.7.0-beta2

project.clj
This adds the lein-ezbake plugin to the pe profile and changes
the PE artifact versioning to match FOSS, at least until the
pe-pdb component has a version >= the version of pe-puppetdb
already included in PE.
=> (re-4451) Updates for pe-puppetdb

src/puppetlabs/puppetdb/facts.clj, src/puppetlabs/puppetdb/query/fact_contents.clj, src/puppetlabs/puppetdb/query/facts.clj, src/puppetlabs/puppetdb/query_eng/engine.clj
This commit moves the late-project? field from the query-recs to
specific columns in the query-recs so that the specific fields that
queries can't do without are called out specifcally. The field is also
renamed to must-have? to align the name with the purpose.
=> (maint) Move late-project? from queries to columns

src/puppetlabs/puppetdb/http/aggregate_event_counts.clj, src/puppetlabs/puppetdb/http/events.clj, test/puppetlabs/puppetdb/http/events_test.clj
This commit cleans up some of the syntax of the distinct_resources param
handling as well as adding another error message to make the param
handling a little more consistent.
=> (PDB-1391) Add another error message when handling distinct_resources

acceptance/tests/reports/report_storage.rb, documentation/api/query/v4/reports.markdown, documentation/api/query/v4/upgrading-from-v3.markdown, src/puppetlabs/puppetdb/cli/export.clj, src/puppetlabs/puppetdb/http/reports.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/query/report_data.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/query/reports_test.clj
This commit provides two new endpoints for each report, namely
`/v4/reports/<hash>/logs` and `/v4/reports/<hash>/metrics`.
=> (PDB-1187) Provide endpoints for a specific report's logs and metrics

src/puppetlabs/puppetdb/cli/benchmark.clj
This commit changes the benchmark tool to use the trapperkeeper
load-config function instead of the kitchensink ini parser so that we
can use any valid pdb config file for the benchmarking tool.
=> (maint) Allow any valid tk config to be used by benchmark tool

project.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/schema.clj, src/puppetlabs/puppetdb/time.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/command/dlo_test.clj, test/puppetlabs/puppetdb/config_test.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/http/server_time_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/schema_test.clj, test/puppetlabs/puppetdb/testutils/nodes.clj, test/puppetlabs/puppetdb/time_test.clj
This commit upgrades the clj-time, ring-core, and compojure deps. In
clj-time "0.6.0" instances of secs were deprecated in favor of seconds.
This patch also updates references of secs in puppetdb to be seconds.
=> (maint) Upgrade clj-time ring-core and compojure deps

src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/scf/storage.clj
This commit addresses an issue where the above query for both
`resources` and `facts` was very slow on Postgres because we were
trimming the bytea hash to a string which was causing Postgres to do a
table scan. This commit fixes this issue by changing the parameters in
the `(?,?...)` to be munged bytea hashes so we don't do a table scan.
=> (maint) Speed up storage.clj `<hash> in (?,?,?...)` queries

src/puppetlabs/puppetdb/http/catalogs.clj
Previously we were passing the url-prefix *and* the version to catalog-status as
the url-prefix, which was causing the version to be doubled in the href urls
(i.e foo/v4/v4/catalogs/node/edges).
=> (maint) fix /v4/catalogs/<node> so version isn't repeated in the href

src/com/puppetlabs/puppetdb/scf/storage.clj, test/com/puppetlabs/puppetdb/test/scf/storage.clj
This is broken up into two commits so that it should be easier to test.  i.e. check out the first commit, which should fail "lein test" with a constraint violation, and then check out the tip, which should work.
=> (PDB-1448) GC values that swap paths correctly

src/com/puppetlabs/puppetdb/query/facts.clj
Previously we were mistakenly realizing the value of our facts response by
validating it as a collection. This changes the validation so that it is applied
on a per-element basis and doesn't disrupt the laziness of the response.
=> (maint) make facts response streaming

project.clj
The ezbake pe profile is currently overriding the main-namespace
for the project.
This removes that variable definition, taking the default for the
project.
=> (re-4451) Do not override main-namespace for pe builds

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj
Report start_time comes from the agent, so it doesn't make sense to
compare it to the producer_timestamp on the deactivate command. The
real fix to this is to add a producer_timestamp to the store report
command, but as a stopgap we'll just revert to the old behavior for
these records.
=> (PDB-1310) Don't check reports in deactivate

Gemfile, acceptance/config/ec2-west-debian7-64mda-64a.cfg, acceptance/config/ec2-west-debian7-64mda-fallback.cfg, acceptance/config/ec2-west-dev.cfg, acceptance/config/ec2-west-el5-64mda-el5-64a.cfg, acceptance/config/ec2-west-el6-64mda-el5-64a-ubuntu1204-64a.cfg, acceptance/config/ec2-west-el6-64mda-el6-64a.cfg, acceptance/config/ec2-west-el6-64mda-perf.cfg, acceptance/config/ec2-west-el6-64mda.cfg, acceptance/config/ec2-west-el7-64mda-el7-64a.cfg, acceptance/config/ec2-west-f20-64mda-f20-64a.cfg, acceptance/config/ec2-west-ubuntu1204-64mda-64a.cfg
Use the beaker version at the current tip of
rbrw:tmp/rotate-ec2-subnets, and change all of the acceptance/config
files to use CONFIG level vpc_id and subnet_ids settings.
(Don't merge this.)
=> (PDB-1263) Use beaker EC2 subnet rotation

documentation/configure.markdown, src/com/puppetlabs/puppetdb/config.clj
This commit deprecates the url-prefix setting under the `[global]`
header. This configuration is not necessary and done differently
for other trapperkeeper services.
=> (PDB-1485) Deprecate url-prefix setting

documentation/api/query/v3/aggregate-event-counts.markdown, documentation/api/query/v3/event-counts.markdown, documentation/api/query/v4/aggregate-event-counts.markdown, documentation/api/query/v4/event-counts.markdown, src/com/puppetlabs/puppetdb/http/aggregate_event_counts.clj, src/com/puppetlabs/puppetdb/http/event_counts.clj
This adds a deprecation message in the docs for event-counts and
aggregate-event-counts, and also introduces a warning when the endpoints are used.
=> (PDB-1479) deprecate event counts and aggregate event counts

src/puppetlabs/puppetdb/facts.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query/edges.clj, src/puppetlabs/puppetdb/query/events.clj, src/puppetlabs/puppetdb/query/fact_contents.clj, src/puppetlabs/puppetdb/query/facts.clj, src/puppetlabs/puppetdb/query/factsets.clj, src/puppetlabs/puppetdb/query/nodes.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query/resources.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/migration_legacy.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/http/environments_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/testutils/events.clj, test/puppetlabs/puppetdb/testutils/nodes.clj
This commit adds a migration to change the value_json column of facts to a TEXT
"value" column, which stores a json-serialized copy of the properly typed fact.
This field is returned by facts queries and deserialized in code to avoid
dragging type information out of the database. Doing this allows us to remove
the concept of late-project.
=> (PDB-1447) remove late project

src/puppetlabs/puppetdb/cli/benchmark.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/http/version.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/jdbc/internal.clj, src/puppetlabs/puppetdb/mq_listener.clj, src/puppetlabs/puppetdb/scf/hash_debug.clj, src/puppetlabs/puppetdb/scf/migrate.clj
(log/error (format ...)) can be better written as (log/errorf ...).
The same goes for other levels as well.
=> (PDB-1513) Clean up log-format calls

project.clj
This just bumps Clojure to 1.7.0-beta3 so we keep on the trail of this pending
release.
=> (maint) Bump clojure to 1.7.0-beta3

src/puppetlabs/puppetdb/http.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query/aggregate_event_counts.clj, src/puppetlabs/puppetdb/query/event_counts.clj, src/puppetlabs/puppetdb/query/report_data.clj, src/puppetlabs/puppetdb/query_eng.clj, test/puppetlabs/puppetdb/cli/services_test.clj
This commit addresses the "callback hell" of the query_eng.clj. Prior to
this commit the query-eng stream-query-result function had an output-fn
arguement whose interface was as follows, "output-fn takes a function
(f) as an argument and applies that funtion to another function (g),
(g) must realize the values of a lazy sequence of database rows."
This was primarily do to the fact the we need to stream results from the
database as well as stream results of http, which had to be done in a
separate thread. Another layer of complexity was that the http streaming
that we did also needed access to the count-query vector only available
int the stream-query result vector. All this complexity makes it very
confusing developing callbacks for querying puppetdb in process
directly, such as from PE …
=> (maint) Detangle query-eng database and http streaming

acceptance/tests/reports/report_storage.rb, src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query/factsets.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/http/catalogs_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj
Without this commit, our expanded fields required both the (possibly empty)
data field and either the hash or certname as an identier to form the href.
With this commit, we return essentially the desired data/href structure in the
postgres case, and in the hsqldb case, we overload the field name with the
identifier to retain the ability to create the href.
=> (PDB-1269) extractable-only fields

src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/http/resources_test.clj
Previously we were converting strings to numeric on the equality operator when
used on a field other than fact values, and exposing an error when the inequality
operators were used with a non-timestamp string.
=> (PDB-1453) don't allow numeric comparisons with strings

src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/query/facts.clj, src/puppetlabs/puppetdb/query/paging.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/facts_test.clj
Previously you couldn't order on a field that you weren't extracting.
This changes our paged sql function to do
select paged_results.* from (select blah from facts order by baz)
instead of select paged_results.* from (select blah from facts) order by baz,
and also ensures that we never order on column aliases -- always on the column
name or function application itself.
=> (PDB-1482) allow ordering on non-extracted fields

src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query/factsets.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, src/puppetlabs/puppetdb/utils.clj
This commit changes the json-aggregates in the query-eng to use
subselects instead of the `row` function, this means that we can "name"
columns directly from the (honey)SQL and get rid of the json
post-processing munging.
=> (PDB-1520) Use subselect with row-to-json aggregates

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/honeysql.clj, src/puppetlabs/puppetdb/mq.clj, src/puppetlabs/puppetdb/query/edges.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/scf/hash.clj, test/puppetlabs/puppetdb/scf/migration_legacy_test.clj
This commit makes some linting corrections found via the `eastwood` lein
plugin. This commit also makes some syntactic improvements to
services.clj, such as checking conditions before executing business
logic and not redefing varibales in let bindings.
=> (maint) Lint with `eastwood` and improve syntax in services.clj

project.clj
There are changes in ezbake 0.3.5 that are required to integrate
puppetdb into PE, which includes a bugfix related to systemd and the
defaults file. This commit copies the plugin definition from the ezbake
profile into the pe profile so that the ezbake version can be moved from
0.2.9 to 0.3.5.
=> (PE-9827) Override ezbake version in PE profile

resources/ext/ezbake.conf
In Puppet 4, the filesystem paths were updated and package names were
changed. This commit updates both the dependencies and postinst of
puppetdb to accomodate this change. On debian, versioned dependencies
cannot be satisfied with a package that uses Provides tags to enable
those capabilities (this is fixed in bleeding edge deb and ubuntu), so
the debian dependencies have an `| puppet-agent` added to cover this.
The puppetdb binaries will be laid down in /opt/puppetlabs/bin in the
new filesystem world, so to ensure that both new and old paths work, the
path is updated for the postinst so that both PDB 2.x and 3.x scripts
will be correctly found.
=> (PDB-1455) Update package dependencies and postinst for Puppet 4

project.clj
We're just following closely behind the release cycle of Clojure 1.7.0.
=> (maint) Bump to clojure 1.7.0-RC1

acceptance/helper.rb, acceptance/setup/pre_suite/70_install_released_puppetdb.rb
This commit adds a test_url and ssl_test_url param for checking whether
PuppetDB is up on Beaker upgrade testing. This allows us to check
different urls across PuppetDB versions.
=> (PDB-1485) Add a test_url param for upgrade testing

acceptance/tests/db_resilience/db_fallback.rb
This url_prefix changes mean that having a url_prefix in your
server_urls config on the master will produce a validation error,
therefore we mimic the downed-db behavior with a bad port instead in
this commit.
=> (PDB-1485) Test db_resilience with wrong port instead of wrong url

documentation/release_notes.markdown
Move 3.0.0 to the top of the release notes (above 2.3.4), and remove a
vestigial conflict marker.
=> (maint) release_notes: move 3.0.0 up; remove conflict marker

ext/redhat/puppetdb.spec.erb
We were pulling in the rubygem-json dependency, but this is unnecessary
since Puppet requires it. With the dependency there, the consumer needs
to include the puppetlabs-deps repo, but this doesn't match well with
Puppet 4 & AIO requirements.
So this removes it, Puppet 3.x will pull in the dependency automatically,
and Puppet 4 AIO will include it anyway.
=> (PDB-1469) Remove rubygem-json dependency

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
To allow sync convergence when there are conflicting writes to two 
nodes, the factset up-to-date check needs to allow records whose
producer_timestamp is equal to the existing producer_timestamp. This is
the same as the replace-catalog command's current behavior. 
Also include reports in the deactivate-node up-to-date check, using
their producer_timestamp field.
=> (maint) Fix factset up-to-date checks

src/puppetlabs/puppetdb/cli/benchmark.clj
This commit fixes a regression in the benchmarking tool that caused a
catalog to be reencoded to json every iteration of the benchmarking
tool.
=> (maint) Stop reencoding json catalog in benchmarking tool

src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/query/paging.clj, test/puppetlabs/puppetdb/jdbc_test.clj
This commit makes some syntatical changes to the query engine paging
functions as well as removing the `paged_results` wrapper and the sql we
generate for query-engine queries as it is no longer necessary.
=> (maint) Remove `paged_results.*` wrapper around generated sql

resources/ext/cli/ssl-setup
Previously we didn't include the AIO puppet in our PATH setup, we had this
fixed in stable but not in master, since the files changed so dramatically this
was lost in a rollup.
=> (PDB-1300) Include AIO paths to puppet in ssl-setup

resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/dashboard.clj, test/puppetlabs/puppetdb/dashboard_test.clj
This changes our default bootstrap.cfg to include a new service that redirects
/ to the dashboard at /pdb. The service is injected into the webrouting config
depending on the presence or absence of the service in the bootstrap.cfg,
so to disable the redirect users will need to remove the line from bootstrap.cfg.
=> (PDB-1537) dashboard redirect at root

src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query/edges.clj, src/puppetlabs/puppetdb/query/environments.clj, src/puppetlabs/puppetdb/query/event_counts.clj, src/puppetlabs/puppetdb/query/nodes.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query/resources.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/scf/migrate.clj, test/puppetlabs/puppetdb/testutils/events.clj
This commit removes the `with-query-results-cursor` macro, as it was
functionally unused. The macro wrapped `with-query-results-cursor*` with a
different interface, but the only thing that used the macro was
`streamed-query-results` which wrapped the macro in the original
interface of `with-query-results-cursor*`. This commit collapses these
functions/macros.
This commit also cleans up some syntax in jdbc, removing unnecessary
parens.
=> (maint) Remove unneccesary querying macro to improve streaming syntax

documentation/trouble_kahadb_corruption.markdown, src/com/puppetlabs/mq.clj
In the KahaDB corruption documentation, mention the possibility that MQ
related errors might be caused by downgrading PuppetDB (and by
extension, the ActiveMQ version), and if we hit an IOException while
starting the MQ broker (one of the known symptoms), suggest looking at
that documentation.
This PR pairs with master PR: #1417
=> (PDB-1454) Handle IOException while starting MQ

src/com/puppetlabs/puppetdb/scf/storage.clj, test/com/puppetlabs/puppetdb/test/command.clj, test/com/puppetlabs/puppetdb/test/scf/storage.clj
Before this commit we were updating the deactivated column of certnames to null
even if it was already null. This caused unnecessary contention on the certnames
table with each command submission, causing more frequent retries than needed.
Also corrects the corresponding test logic: if nothing happens, then no records
are updated, and the result of maybe-activate-node should *not* be positive.
=> (maint) don't activate the node when it's already active

acceptance/tests/db_garbage_collection/node_ttl.rb, src/puppetlabs/puppetdb/http.clj, src/puppetlabs/puppetdb/http/catalogs.clj, src/puppetlabs/puppetdb/http/environments.clj, src/puppetlabs/puppetdb/http/nodes.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query/edges.clj, src/puppetlabs/puppetdb/query/environments.clj, src/puppetlabs/puppetdb/query/event_counts.clj, src/puppetlabs/puppetdb/query/nodes.clj, src/puppetlabs/puppetdb/query/reports.clj, src/puppetlabs/puppetdb/query/resources.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/scf/hash_debug.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/http/explore_test.clj, test/puppetlabs/puppetdb/query/catalogs_test.clj, test/puppetlabs/puppetdb/query/environments_test.clj, test/puppetlabs/puppetdb/query/event_counts_test.clj, test/puppetlabs/puppetdb/query/events_test.clj, test/puppetlabs/puppetdb/query/nodes_test.clj, test/puppetlabs/puppetdb/query/reports_test.clj, test/puppetlabs/puppetdb/query/resources_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/testutils/events.clj, test/puppetlabs/puppetdb/testutils/reports.clj
This commit removes dead code from each of the query/* namespaces whic
was only used in testing code. Previously we were duplicating the
efforts of the produce-streaming-body/streamed-query-results on each of
our endpoints, this commit changes the utility functions in our tests to
use the updated pattern. This commit also removes corresponding unnecessary tests that were testing code we weren't using in production.
This commit also changes a number of update-in calls to update that we're within eyesight while making these changes.
=> (maint) Remove dead code and replace testing utility functions

documentation/api/query/v4/upgrading-from-v3.markdown, src/puppetlabs/puppetdb/http/catalogs.clj, src/puppetlabs/puppetdb/http/environments.clj, src/puppetlabs/puppetdb/http/factsets.clj, src/puppetlabs/puppetdb/http/nodes.clj, src/puppetlabs/puppetdb/http/reports.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/query/catalogs.clj, src/puppetlabs/puppetdb/query_eng.clj, test/puppetlabs/puppetdb/http/catalogs_test.clj, test/puppetlabs/puppetdb/http/environments_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/query/environments_test.clj, test/puppetlabs/puppetdb/query/nodes_test.clj, test/puppetlabs/puppetdb/query/reports_test.clj
Before this patch, for paths that contain child data:
* nodes
* environments
* factsets
* catalogs
* reports
Child data for missing parent data (for example factets/<node>/facts, where
<node> is unknown) used to return an empty array.
This patch does a small existance check for its parent, and instead returns
a 404 for missing child data. This means consumers can request child
information directly without having to first check if the parent exists.
=> (PDB-1473) Present 404 errors on missing parent data

acceptance/helper.rb
now that test_url can be overridden, we should be able to use strict_validation again.
=> (PDB-1134) turn on strict_validation

src/puppetlabs/puppetdb/query_eng.clj
The object exists query must return data even for nodes which are
expired or deactivated, since the subresources it filters on are
directly addressable from a search which includes deactivated 
and expired nodes.
=> (maint) Fix object exists query

src/puppetlabs/puppetdb/cheshire.clj, src/puppetlabs/puppetdb/http/nodes.clj, src/puppetlabs/puppetdb/http/query.clj, src/puppetlabs/puppetdb/query/paging.clj, src/puppetlabs/puppetdb/query_eng.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/server_test.clj, test/puppetlabs/puppetdb/testutils.clj
Webservers have limits on the length of GET request. This commit adds to
the nodes endpoint (root of the endpoint only) the ability to instead
issue the query as a POST, with a JSON document representation of the
query as the body. This new feature needs to be added to all endpoints
eventually, but the one where we see this problem the most is the root
of the nodes endpoint, so this commit starts there. This patch puts new
code in place to centralize handling of the PuppetDB query and related
parameters so that all endpoints can share the same code for handling
GETs and POSTs of queries. Currently only the nodes endpoint calls this
new centralized code. A bigger refactor will need to be made in the
future to switch other endpoints over to the new code.
=> (PDB-1536) Support POST queries for nodes

puppet/lib/puppet/indirector/facts/puppetdb.rb, puppet/lib/puppet/util/puppetdb/http.rb, puppet/spec/unit/indirector/facts/puppetdb_spec.rb
Once we switched to returning a 404 not found for child endpoints, the no-data
or not-found case wasn't working any more for puppet facts find. This patch just
handles the http 404 case properly.
=> (PDB-1125) Detect not found issues with facts find

src/puppetlabs/puppetdb/cli/benchmark.clj
Without this change, resubmission of a catalog using the benchmark tool will
not reactivate a deactivated node.
=> (maint) update catalog timestamp in untimed benchmark run

puppet/lib/puppet/indirector/facts/puppetdb.rb, puppet/lib/puppet/util/puppetdb/http.rb
There are many cases when a 404 from puppetdb is a perfectly
legitimate response, and a scary error message should not be logged.
- In the failover http layer, only treat 'real-looking' 404s as
not-found responses. Others are treated as errors. 
- In the facts terminus, no longer log a warning on not-found responses.
=> (PDB-1605) Don't log 404s in the terminus

acceptance/helper.rb
Packaging was failing due to a typo, fixed.
=> (PDB-1455) Fix typo for confdir in tests

acceptance/helper.rb, acceptance/setup/pre_suite/70_install_released_puppetdb.rb
After adapting the start_puppetdb/install_puppetdb functions to specify the
newer packages options for the module, we still need a way to flip back to
legacy support for the purposes of upgrades, at least until we ship 3.0.0.
This patch turns all the legacy support flags into 1 flag for those
functions and now also ensures that things like confdir and embedded_path
are set correctly when legacy is true.
=> (PDB-1455) Make start_puppetdb/install_puppetdb support legacy installation

acceptance/setup/pre_suite/40_install_deps.rb
This fixes a problem with puppetlabs-concat requiring a proper ruby vm when we
use puppetlabs-postgresql. Since AIO doesn't install one by default, we install
it especially for this node combination to work around the problem.
This issue should be solved in the 2.x branch of puppetlabs-concat once
released, since puppetlabs-concat 2.x uses proper types and providers, so the
ruby code is now internally called instead of Exec'd from the agent.
=> (PDB-1455) Install a proper ruby when using AIO on Debian

acceptance/helper.rb
The packaging tools require facter, but system ruby would not contain this
by default, especially in an AIO world.
So we just use the AIO PATH so that Puppet's rake is used instead, that
already contains facter.
=> (PDB-1455) Use AIO/Puppet rake for building packages from source

documentation/configure.markdown, documentation/connect_puppet_apply.markdown, documentation/puppetdb-faq.markdown
We recently improved our docs site toolchain to handle syntax highlighting with
fenced code blocks (via prism.js). Yay! But we're still using Kramdown, which
only supports one of the two fenced code block syntaxes specified in CommonMark.
Meh. Anyway, triple tildes good, triple backticks less-good, still best to
use "~~~ ruby" to highlight Puppet snippets for the time being.
=> (docs) Lose the liquid tags, and use triple tildes for best compatibility

documentation/api/query/v4/factsets.markdown, src/puppetlabs/puppetdb/http/factsets.clj, test/puppetlabs/puppetdb/http/facts_test.clj
We had missed this as a singleton query endpoint, this patch adds it.
=> (maint) Provide /factsets/<node> endpoint

acceptance/helper.rb, acceptance/setup/post_suite/01_validate_database.rb, project.clj, resources/ext/cli/anonymize, resources/ext/cli/export, resources/ext/cli/foreground, resources/ext/cli/import
This changes the uberjar name to 'puppetdb.jar' to match the 2.x release,
which simplifies some upgrade and init script logic.
This is related to https://github.com/puppetlabs/ezbake/pull/256
=> (re-4845)(packaging) Change jar name from puppetdb-release.jar to puppetdb.jar

test/puppetlabs/puppetdb/command_test.clj
After the last rollup from stable we ended up with an incorrect rollback error
message on postgres in the commands test. The new error still indicates a rollback.
=> (maint) update postgres error message on concurrent fact update

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
This fixes an issue from the rollup yesterday. It's effectively a port of
706df77 from stable.
=> (maint) fix rollup issue to reduce certnames contention

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
We didn't previously have a producer_timestamp field on reports, so they were
not considered in the decision to deactivate a stale node. This corrects that
behavior.
=> (PDB-1638) consider reports in stale-nodes analysis

documentation/api/query/v4/aggregate-event-counts.markdown, documentation/api/query/v4/upgrading-from-v3.markdown, src/puppetlabs/puppetdb/http/aggregate_event_counts.clj, src/puppetlabs/puppetdb/query/aggregate_event_counts.clj, src/puppetlabs/puppetdb/query/event_counts.clj, src/puppetlabs/puppetdb/query/events.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/http/aggregate_event_counts_test.clj, test/puppetlabs/puppetdb/query/aggregate_event_counts_test.clj
Author: Wyatt Alt <wyaltster@gmail.com>
Date:   Tue Jun 9 08:33:49 2015 -0700
(PDB-1587) Optimize aggregate event counts
This commit improves performance on aggregate-event-counts queries.
Included are the following changes:
* new (large) index on resource_events(resource_type, resource_title, timestamp)
* aggregate-event-counts now supports multiple comma-separated summarize_by params
* union all is used to combine results from multiple AEC summaries
* AEC output is now a map array, with a new key containing the summary param
* CTE used to improve performance when multiple summarize_by values are provided
* fairly expensive migration merged with mega-migration #29
* AEC no longer compatible with HSQLDB
=> (PDB-1587) Optimize aggregate event counts

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/mq.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/mq_test.clj, test/puppetlabs/puppetdb/testutils.clj, test/puppetlabs/puppetdb/testutils/services.clj
At startup, transfer any messages found in the old
com.puppetlabs.puppetdb.commands queue to puppetlabs.puppetdb.commands
so that pending commands won't be ignored after an upgrade.
=> (PDB-1632) Transfer old AMQP messages at startup

project.clj
Now we have a branch for 3.0.0, this branch can now designate a 3.1.0 build
formally.
=> (PDB-1647) Bump snapshot version to 3.1.0-SNAPSHOT

acceptance/helper.rb, acceptance/tests/catalog/replace_catalog_debugging.rb, puppet/lib/puppet/indirector/catalog/puppetdb.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
This corrects a bug where the terminus would scan for resource alias names
using the wrong key, which would cause the list of aliases to fall through to
an empty list.
Correcting this made it clear that we were also incorrectly assuming that
aliases within resources presented as arrays.
=> (PDB-1629) fix relationships on resource aliases

test/puppetlabs/puppetdb/mq_test.clj
This commit fixes a broken mq test where there was an `(= ...)`
expression that wasn't wrapped around its second argument. This failed
silently with a normal `lein test` but caused failures with the
humane-test-output plugin for `lein`. This commit also removes some
unnecessary commas and makes sure to cleanup the `somedir` created
during the mq-tests.
=> (maint) Repair broken mq test

acceptance/tests/catalog/replace_catalog_debugging.rb
This test was using /v3/events which is now retired, modified to use v4 instead.
=> (PDB-1629) Modify test to use the v4 api

acceptance/tests/catalog/replace_catalog_debugging.rb
Its /pdb/query/v4/ not /pdb/v4/query
=> (PDB-1629) Fix events call

src/puppetlabs/puppetdb/query/events.clj, test/puppetlabs/puppetdb/http/events_test.clj
This fixes a regression from the aggregate-event-counts optimization patch.
The issue was that the CTE added there for queries with distinct_resources=true
was not being applied to the SQL on which the include_total query was based,
in the case when the include_total param was passed.
include_total has never been supported for event-counts or aggregate-event-counts,
so events is the only thing this will affect and there's no concern about missing
the other endpoints.
=> (PDB-1652) support include_total with distinct events

project.clj, src/puppetlabs/puppetdb/catalog/utils.clj, src/puppetlabs/puppetdb/catalogs.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/facts.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/reports.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/catalogs_test.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/examples.clj, test/puppetlabs/puppetdb/reports_test.clj, test/puppetlabs/puppetdb/utils_test.clj
Note these previous versions are not supported at the API level. The
intent here is if the user has upgraded from PuppetDB 2.0.0 to 3.0.0 and
there are still persisted messages in the queue (POSTed, but not
processed) those messages should be consumable by PuppetDB 3.0.0.
This commit takes a previous version of the command and upgrades it,
filling in anything missing, changing the names of keys as necessary to
conform it to the current (supported) command version.
=> (PDB-1590) Support two previous versions of all commands (for upgrades)

src/puppetlabs/puppetdb/honeysql.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/http/event_counts_test.clj, test/puppetlabs/puppetdb/testutils.clj
This fixes a couple issues with the legacy query engine, which is used when
the distinct_resources parameter is passed as true:
* regex queries were broken due to use of honeysql instead of strings
* subqueries were broken because of an ambiguous column alias
I've expanded the distinct_resources testing in http/event-counts-test to cover
the fixed behavior.
=> (PDB-1646) tighten up regex and subqueries in the legacy query engine

acceptance/tests/import_export/legacy_storeconfigs_import_export.rb
This corrects an issue that cropped up due to a facter version change. There's
no longer a puppetversion fact -- dispatch on AIO status instead.
=> (maint) skip legacy storeconfigs import export on AIO

acceptance/config/ec2-west-el6-64mda-el5-64a-ubuntu1204-64a.cfg
Puppet didn't like the dot in our ubuntu 1204 hostname for the 3 box test,
this removes the dot.
=> Rename ubuntu 12.04 image name to remove dot

acceptance/setup/pre_suite/80_add_dev_repo.rb
The most recent facter no longer puts operatingsystemmajrelease in the default
output. This changes it to use the new os fact.
=> (maint) change operatingsystemmajrelease to os.release.major

src/com/puppetlabs/puppetdb/cli/services.clj, src/com/puppetlabs/puppetdb/scf/storage.clj, test/com/puppetlabs/puppetdb/test/scf/storage.clj
This patch implements the following policy around deprecation messages
FOSS: messages thrown < 9.4
PE: messages thrown < 9.4 *except* 9.2
=> (PDB-1610) deprecate postgres < 9.4

documentation/api/query/v3/aggregate-event-counts.markdown, src/com/puppetlabs/puppetdb/http/aggregate_event_counts.clj, src/com/puppetlabs/puppetdb/http/event_counts.clj
Don't warn about event-counts or aggregate-event-counts endpoints if the
product name isn't puppetdb.
=> (PDB-1665) Guard experimental endpoint warnings

ext/templates/puppetdb-ssl-setup.erb
The ssl setup tool uses the existence of the /etc/puppetlabs/puppetdb directory
to assess whether the install target is running PE. This was valid in the olden
days, but with AIO FOSS uses those paths as well. This meant that the ssl
setup tool would set the wrong user in the case of a downgrade from 3.0 to
2.3.x, since at this point the path would exist. This changes the tool to dispatch
on presence of the pe-puppetdb user.
=> (maint) remove ssl-setup references to AIO pathing

resources/ext/cli/ssl-setup.erb
This should fix our ssl setup stuff to get the right confdir in a 3.0 scenario
=> (maint) fix ssl setup rollup

test/puppetlabs/puppetdb/testutils/services.clj, test/puppetlabs/puppetdb/testutils/services_test.clj
Add with-log-level, allowing us to change the logback log level for a
given "logger-id" (normally a keyword, class, or namespace) during the
execution of a specified body.
Add with-logging-to-atom, which redirects all log events produced by a
specified body to an atom (i.e. redirects the result of all calls to
clojure.tools.logging's log/*), making it easier to test logging
behaviors.
cf. previous incarnation: #1489
=> (PDB-1613) Add with-logging-to-atom and with-log-level

project.clj
Clojure 1.7.0 was just released, this commit bumps this to this version.
=> (maint) Bump to Clojure 1.7.0

test/puppetlabs/puppetdb/command_test.clj
This commit removes an `=` called on an `every?` in our tests, which
cause human-test-output to fail with a one-handed equals failure.
=> (maint) Remove one-handed `=` in unit test

test/puppetlabs/puppetdb/command_test.clj
Reverts puppetlabs/puppetdb#1502
=> Revert "(maint) Remove one-handed `=` in unit test"

project.clj, src/puppetlabs/puppetdb/reports.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/reports_test.clj
This commit updates `specter` to the laster version to remove the
conflict with the name `update` in `clojure.core`.
=> (maint) Update specter dependency to remove `update` conflict

documentation/configure.markdown, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/jdbc.clj
This adds connection timeouts to the command processing and query
connection pools. This fixes the problem where the ActiveMQ session
can't be properly shutdown because the command connection pool can't get
a connection to the database (i.e. the database is down). Previously
this would hang, even with a Control-C. This hang was due to the
connection pool software getting caught in a loop trying to get a
connection to the database.
This connection timeout was also applied to the query side of the
application as user provided queries are expected to respond quickly and
a hanging behavior would be bad there as well.
This blocking/retrying behavior is what we want when PuppetDB first
starts up as we need to initialize the schema etc. This commit also
creates a special connection pool (just …
=> (PDB-1674) PuppetDB hangs on shutdown when the database is down 

src/puppetlabs/puppetdb/cli/benchmark.clj
-D was removed however this argument help still contained a reference to it.
=> (maint) Remove reference to -D switch for benchmark

project.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/meta.clj, src/puppetlabs/puppetdb/meta/version.clj, test/puppetlabs/puppetdb/cli/services_test.clj
This commit changes PuppetDB to use the Puppet Labs version-checking
library for it's version info functionality.
This commit also updates the startup of the updater to not run in a
future and to not shutdown puppetdb if there is an error in the worker
thread.
=> (PDB-1409) Use our puppetlabs version-checking library

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/http.clj, src/puppetlabs/puppetdb/http/command.clj, test/puppetlabs/puppetdb/http/command_test.clj
This adds some validation on our command handler to reject retired versions of
commands and commands that we don't recognize before enqueuing when submitted
over http.
=> (PDB-1701) reject old commands over http

project.clj
Fixes for service restart on upgrade.
=> (packaging) Bump ezbake to 0.3.13

src/puppetlabs/puppetdb/cli/services.clj
We had been initializing dashboard metrics on an ephemeral database connection,
which meant that the connection would be closed when the metrics were accessed.
=> (PDB-1731) broken dashboard

project.clj
This profile was used to build pe-puppetdb using lein-ezbake. Instead, we will
be building pe-puppetdb from the pe-puppetdb-extensions repo.
=> (QENG-2545) Remove pe profile.

resources/ext/cli/config-migration
Without this we were parsing the subname to get the location of the hsqldb data
directory so it can be migrated. In the default case though, this resides in the vardir, which is
migrated a moment before.
This patch changes things so that we only attempt to migrate that directory if
the original vardir still exists, which is a signal that the vardir is
nonstandard, but the subname still points to the old one (since it's still the
default value.)
=> (maint) fix config migration

project.clj
This reverts our project version so we can smoke test without polluting nexus.
=> (maint) revert project version

acceptance/setup/pre_suite/50_install_modules.rb
This commit pins the module version we use in acceptance tests as v5 of
the module was released today and contained breaking changes. This
commit is a temporary fix for the issue until we can upgrade to v5 of
the puppetdb module.
=> (maint) Pin the module version we use in acceptance tests

acceptance/setup/pre_suite/70_install_released_puppetdb.rb
This will cause installs to fall through to the expectedrpm and expecteddeb
version.
=> (maint) make install_puppetdb and install_puppetdb_terminus versions nil

project.clj
Due to an odd issue with PuppetDB, when PuppetDB 2.3.z and PuppetDB
3.0.0 are in the same repository (e.g. PC1) you can not install
PuppetDB 2.3.z because the terminus package is oboleted and therefore
brings in the 3.0.0 version of temini. That means you can't really run
2.3.5. This is bad since the tests for PuppetDB 2.3.z test against the
AIO and Puppet 3.8 and so they need access to PC1.
As a fix, we're creating a new metapackage 'puppetdb-terminus' at
version 3 that wil require puppetdb-termini to allow for easier
transistion and upgrades. That, combined with the removal of
Obsoletes/Provides in the PuppetDB package will allow a user to use a
2.3.z or 3.0.0 release of PuppetDB.
=> (RE-5033) Update Ezbake to new 0.3.14

resources/ext/ezbake.conf
This should fix the issue where we attempted to tar a nonexistent directory in
preinst when upgrading from 3.0.0 -> 3.0.x
=> (maint) update preinst for redhat to check for 2.x if upgrading

documentation/_puppetdb_nav.html, documentation/api/admin/v1/archive.markdown, resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/admin.clj, src/puppetlabs/puppetdb/cli/export.clj, src/puppetlabs/puppetdb/cli/import.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/client.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/http.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/admin_test.clj, test/puppetlabs/puppetdb/cli/export_test.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
This PR adds a `puppetlabs.puppetdb.admin` namespace.
The `admin` namespace contains a trapperkeeper service which serves a handler of the new import/export endpoints.
The new endpoints are served under the `/pdb/admin/v1` api root prefix.
The `archive` endpoint will stream you the tarball via a `GET`.
The `archive` endpoint will stream the tarball to PuppetDB for import via a `POST` of the archive in a multipart request with the archive as the `archive=` param. (`curl ... -F "archive=@foo_backup"`)
The CLI tools (import/export) functionality has been moved to these endpoints and the tools themselves essentially just make calls to these endpoints.
TODO and followups for this PR:
Anonymization could also be an endpoint, to anonymize a tarball in the backups directory.
There could be an …
=> (PDB-1631) Create the `/pdb/admin` API with import/export endpoints

acceptance/helper.rb, acceptance/setup/pre_suite/70_install_released_puppetdb.rb
Use 'git describe' to find the most recent released version and use that
to find the base version to install for upgrade tests.
=> (maint) Fix upgrade tests

acceptance/helper.rb
This is meant to fix https://jenkins.puppetlabs.com/job/platform_puppetdb_int-sys-legacystable/708/BEAKER_CONFIG=ec2-west-debian6-64mda-64a,BEAKER_OPTIONS=postgres,BEAKER_TYPE=foss,PUPPETDB_INSTALL_MODE=upgrade,label=beaker-ec2/testReport/junit/(root)/_var_lib_jenkins_workspace_platform_puppetdb_int-sys-legacystable_BEAKER_CONFIG_ec2-west-debian6-64mda-64a_BEAKER_OPTIONS_postgres_BEAKER_TYPE_foss_PUPPETDB_INSTALL_MODE_upgrade_label_beaker-ec2_acceptance_setup_pre_suite/90_install_devel_puppetdb_rb/
=> Coerce version symbols to strings

documentation/index.markdown, documentation/puppetdb-faq.markdown
On debian we will install 1.7 or 1.8 depending on what is available, but on
RHEL platforms 1.8 is required.
=> (maint) update docs to reflect java 1.8 dependency on rhel

acceptance/helper.rb, acceptance/setup/pre_suite/50_install_modules.rb, acceptance/tests/reports/event_query_with_read_db.rb
This commit upgrades PuppetDB to use v5 of the PuppetDB module (latest
at the time of this commit). This consists of using the new `globals`
class to specify the PuppetDB version.
=> (PDB-1791) Upgrade to version 5 of the PuppetDB module

acceptance/helper.rb
Var confdir was removed from the code scope, but not from the optional argument
to print_ini_files.
=> (PDB-1791) Remove option confdir to fix tests

src/com/puppetlabs/puppetdb/cli/services.clj
The command consumer worker threads don't currently apply the
max-frame-size parameter, so the AMQ default of 100MB is used.
=> (PDB-700) Apply max-frame-size to consumer

acceptance/setup/pre_suite/15_setup_repos.rb
This commit fixes an issue on el6 foss acceptance tests (non-aio) where
`yum install puppet -y` was getting:
```sh
el6-64-1 06:18:18$ yum install -y puppet
Loaded plugins: fastestmirror, presto
Determining fastest mirrors
Error: Cannot retrieve metalink for repository: epel. Please verify its
path and try again
```
This commit returns the `yum clean all -y` step before installing the
Puppet Labs repos so that we won't see these issues.
=> (PDB-1731) Add `clean all` step for FOSS el6 repos setup

acceptance/setup/pre_suite/15_setup_repos.rb
This commit reverts e4fe882b79a9dad2fa76e581385f62e4354c192d for el6 on
non-aio acceptance testing until we can find exactly what kind of
side-effects `yum upgrade -y` is having on installing our repositories
causing the error mentioned in 109c1a66d26cfceb78234452f94c41479bea4ec0.
=> (PDB-1731) Upgrade distros only on el6 non-aio acceptance tests

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/scf/migrate.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
Investigation of a performance problem revealed that analyzing the
value_types table improved a PostgreSQL backed http:/.../fact-values
query by a factor of about 4x when run against a ~10m fact benchmark DB
on a tmpfs on Linux.
It appeared that some tables had never been analyzed, and further
testing revealed that the autovacuum process ignored them.  In some
cases, it looks like this is because it ignores small tables that don't
change much, like value_types, which has 6 rows and effectively never
changes.
So make sure that all tables are analyzed at least once (after any
structure changes) by running a "vacuum (analyze, verbose)" whenever we
have to run any migration, and add a dummy migration so that all
existing databases will run the analysis too.
=> (PDB-1812) Analyze all pg tables at least once

project.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/meta/version.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/migration_legacy.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/jdbc_test.clj, test/puppetlabs/puppetdb/query/nodes_test.clj, test/puppetlabs/puppetdb/query/population_test.clj, test/puppetlabs/puppetdb/query/resources_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/scf/storage_utils_test.clj, test/puppetlabs/puppetdb/testutils.clj, test/puppetlabs/puppetdb/testutils/db.clj, test/puppetlabs/puppetdb/testutils/resources.clj
This commit upgrades PuppetDB to use the latest clojure.java.jdbc which
consists of using the deprecated namespace in the new version as well as
removing some test fixtures that reached into the old internals
namespace of jdbc to bind the *db* dynamic var.
=> (PDB-1739) Upgrade to the latest clojure.java.jdbc `0.3.7`

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
If the incoming "deactivate node" timestamp is newer than the one in the
database, replace the database value.  While perhaps reasonable in
general, this is particularly important for pdb sync, i.e. state
convergence.
=> (PDB-1313) Update deactivated timestamp if newer

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/scf/storage.clj
Pull the "should we actually allow this deactivation" guard out of the
:deactivate-node process-command! and make it a new public function,
allowing other code to determine whether a timely deactivate node
command is likely to do anything.
=> (PDB-1313) Add some-newer-record-for-certname

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/http/command.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/fixtures.clj
Arrange for all command submission and execution to go through the
command-service, so that it can track received and executed command
counts.  This makes it possible to know that all outstanding commands
have been executed by waiting until:
```clojure
(let [{:keys [received-commands executed-commands]} (stats cmd-service)]
(= executed-commands received-commands))
```
To make that possible, add a PuppetDBCommandDispatcher protocol for
command-service that provides enqueue-command, enqueue-raw-command, and
stats, and make the previous enqueue-command! and enqueue-raw-command!
functions private.  Ensure that all command submissions and executions
update the new stats.
=> (PDB-1313) Add statistics to puppetdb.commands

documentation/api/query/v4/aggregate-event-counts.markdown, documentation/api/query/v4/event-counts.markdown, src/puppetlabs/puppetdb/http/aggregate_event_counts.clj, src/puppetlabs/puppetdb/http/event_counts.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query/aggregate_event_counts.clj, src/puppetlabs/puppetdb/query/event_counts.clj, src/puppetlabs/puppetdb/query/events.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/http/aggregate_event_counts_test.clj, test/puppetlabs/puppetdb/http/event_counts_test.clj, test/puppetlabs/puppetdb/query/events_test.clj
(PDB-1809) improve aggregate event counts performance
This series of commits attempts to improve the performance of aggregate event
counts with the following actions:
* explicit C collation in group by used for with-latest-events
* query parameter for aggregate event counts endpoint is now optional
* moved some things from distinct-select into with-latest-events so they can be
reused across multiple summarize_by's
=> (PDB-1809) improve aggregate event counts performance

.gitignore, Rakefile, ext/build_defaults.yaml
This commit allows access to the packaging repo automation. Although
this is no longer needed or used to build packages (in favor of ezbake),
we still have some automation in that packaging repo that we should have
access to. For example, the automation to create release tickets lives
there.
=> (maint) Add access to packaging repo

ext/jenkins/beaker-tests-source.sh, ext/jenkins/beaker-tests.sh
net-ssh 2.10.0 was released with only Ruby 2 support, this patch bumps our
testing/ci scripts to use Ruby 2 instead.
=> (maint) Use latest ruby for beaker & net-ssh 2.10.0

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/scf/storage.clj
Move all the deactivation logic to the same place (i.e. to
deactivate-node! in storage).  Previously, part of the logic was in
process-command!.
=> (PDB-1823) Move deactivation logic to storage

src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj
Our fact storage mechanism previously created some very large prepared
statements when very large structured facts were updated. This changes things
so that our fact-storage related prepared statements use a single array-valued
parameter, so that a single statement should be applicable to all scenarios.
This change appears to have eased the original problem and also improves fact
command processing speed significantly.
=> (PDB-1721) memory starvation with large structured facts

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj
I haven't been able to see a benefit of a non-zero cache size at any scale I've
seen, either for all three commands or just catalogs (measured in terms of
one-minute command processing rate). Setting it to 0 is the easy fix for the
memory leak issues we've been seeing. Seems like defaulting it to that and
leaving it configurable is the way to go.
=> (maint) default statement cache size to 0

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj
Reverts puppetlabs/puppetdb#1571
=> Revert "(maint) default statement cache size to 0"

project.clj
This commit saves release from having to type an extra flag when pushing
the PuppetDB packages up for a release.
=> (PDB-1784) Target PC1 repos in ezbake config

test/puppetlabs/puppetdb/dashboard_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
Added a test that just issues a GET request on the two dashboard
URLs, / and /pdb, and verifies that the dashboard page is
returned. Issues the request from outside of PuppetDB to ensure proper
web routing config.
=> (PDB-1653) Add basic test for rendering of the dashboard page

documentation/maintain_and_tune.markdown
Since you can actually purge those now.
When this is merged, please resolve [DOC-1186](https://tickets.puppetlabs.com/browse/DOC-1186).
=> (docs) Remove note about ssh_authorized_key resources not being purgable

test/puppetlabs/puppetdb/admin_test.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/testutils.clj, test/puppetlabs/puppetdb/testutils/catalogs.clj, test/puppetlabs/puppetdb/testutils/reports.clj, test/puppetlabs/puppetdb/testutils/tar.clj
Before this patch, we had some functions in our import-export-roundtrip test
that were used in other test namespaces.  This prevented us from using our
fixtures namespace in any of the http tests due to a cyclic dependency, which
I need for PDB-1737. This will break sync testing, but the fix will be
straightforward.
=> (maint) stop reusing import-export-test functions

project.clj
This commit removes an unnecessary tools.nrepl dependency from the
PuppetDB project.clj which was causing conflicts when using ezbake
commands. The ezbake commands in question were in our Jenkins job
configs and although they were improper commands, they would not have
caused an issue if we didn't explicitly list `tools.nrepl` as a
dependency.
=> (maint) Remove unnecessary tools.nrepl dependency

src/puppetlabs/puppetdb/cheshire.clj, test/puppetlabs/puppetdb/cheshire_test.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
Previously puppetdb's generate-string just redirected to
cheshire/generate-string, whereas generate-pretty-string would add
puppetdb-specific date formatting (that rendered seconds at "full"
precision) in addition to setting :pretty to true.
Change generate-string to include the puppetdb-specific date formatting,
since not pretty shouldn't also mean not accurate.
This was causing trouble because information (accuracy) was being lost
in transit (say across http).
One of the tests may fail right now, due to an undesirable interaction between pdb-instance and the log tests, but that appears to be a preexisting issue that can be reproduced via `lein test :only puppetlabs.puppetdb.command-test puppetlabs.puppetdb.testutils.services-test`.  One possible fix: …
=> (PDB-1313) Uniformly format json dates

test/puppetlabs/puppetdb/admin_test.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/dashboard_test.clj, test/puppetlabs/puppetdb/testutils/log.clj, test/puppetlabs/puppetdb/testutils/log_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
(PDB-1845) Treat the log config as global resource
Previously pdb-instance invocations would pass a custom config to
trapperkeeper.  Although it probably intended for the changes to be
per-instance, the logging configuration is global, and so whatever
changes were made would apply to everyone, and the original
configuration would never be restored.
As an alternative, add a new with-log-suppressed-unless-notable macro
that can wrap the dynamic lifetime of any number of pdb-instances.  It
will suppress all logging unless an event matches its notable-event?
predicate, and if a notable event is encountered, it will dump the log
to *err* and provide a path to the temporary log file.
Include notable-pdb-event?, which ignores the same spurious errors
previously ignored by modifications …
=> (PDB-1845) Treat the log config as a global resource 

puppet/lib/puppet/reports/puppetdb.rb, puppet/lib/puppet/util/puppetdb/config.rb, puppet/spec/unit/reports/puppetdb_spec.rb
Previously we had now way of sending unchanged resources in the
terminus. This commit adds a boolean flag to the terminus config file,
`include_unchanged_resources=<boolean>`, which will _not_ filter
unchanged resources from a report when set to `true`.
As a side note PuppetDB cannot actually handle storing these unchanged resources if you turn them on, that will be handled by a subsequent storage related change.
=> (PDB-1855) Add flag for filtering unchanged resources in the terminus

puppet/spec/unit/reports/puppetdb_spec.rb
This commit ensures that non-unchanged resources are removed from the
unchanged resources terminus test to ensure that there is only one
unchanged resource in our resources list such that we don't get bogged
down by ordering issues which can be different on different versions of
ruby.
=> (PDB-1855) Remove non-unchanged resources in terminus spec test

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/meta/version.clj, src/puppetlabs/puppetdb/scf/hash_debug.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
Previously we required a database connection to determine the database and
version we were connected to. This patch stashes that data in a dynamic var
on startup.
=> (PDB-1737) use memoized function get-db-metadata for db metadata functions

acceptance/config/ec2-west-debian8-64mda-64a.cfg, config/image_templates/ec2.yaml
This adds config for the new Debian 8 AMI. After this is merged we can hook it
up.
=> (PDB-1797) enable test cells for debian jessie

documentation/api/command/v1/commands.markdown, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/http/command.clj
When submitting a command in blocking mode, relay any errors that occur
before the timeout in the http response.
=> (maint) Relay errors for blocking commands

src/puppetlabs/puppetdb/meta/version.clj, test/puppetlabs/puppetdb/meta/version_test.clj
This commit fixes a regression with our check-for-update! function in
which the new shared library we upgraded to does not swallow exceptions
like our previous code. Since the library will log exceptions and
rethrow them, we just need to be sure to swallow the exception in our
wrappers for the library. This commit swallows exceptions for the
version-check library on startup.
=> (PDB-1921) Swallow exceptions during the `check-for-update!` on startup

resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/admin.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/dashboard.clj, src/puppetlabs/puppetdb/http/command.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/meta.clj, src/puppetlabs/puppetdb/metrics.clj, src/puppetlabs/puppetdb/metrics/server.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/pdb_routing.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/dashboard_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/meta_test.clj, test/puppetlabs/puppetdb/metrics/core_test.clj, test/puppetlabs/puppetdb/middleware_test.clj, test/puppetlabs/puppetdb/pdb_routing_test.clj, test/puppetlabs/puppetdb/testutils.clj, test/puppetlabs/puppetdb/testutils/dashboard.clj, test/puppetlabs/puppetdb/testutils/http.clj, test/puppetlabs/puppetdb/testutils/services.clj
This commit moves the configuration of the ring routes to a single namespace (pdb-routing). Previously several components (dashboard, meta, admin) existed solely to attach a new top level pdb
route (i.e. /pdb/meta). This refactor sets us up to better accommodate global (from a PuppetDB perspective) functionality like setting PuppetDB in "maintenance mode" while starting.
=> (PDB-1653) Refactor to a one top level web route for /pdb

src/puppetlabs/puppetdb/admin.clj, src/puppetlabs/puppetdb/http/command.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/meta.clj, src/puppetlabs/puppetdb/pdb_routing.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/meta_test.clj
Prior to this change, each route (i.e. meta, admin, query etc) included
an explicit wrap of puppetdb-middleware. This pulls that wrapping up to
the top level (where the /pdb route is being defined). This reduces
duplication and centralizes that code to pdb-routing.
=> (MAINT) Refactor puppetdb-middleware to central location

documentation/api/wire_format/report_format_v6.markdown, src/puppetlabs/puppetdb/anonymizer.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/reports.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/examples/reports.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/query/events_test.clj, test/puppetlabs/puppetdb/reports_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/testutils/events.clj, test/puppetlabs/puppetdb/testutils/nodes.clj, test/puppetlabs/puppetdb/testutils/reports.clj
This commit moves to using JSONB columns for metrics, logs, and the new
column resources in the reports table. The resources column will be used
by unchanged resources for storing "resource" jsonb blobs. The old
metrics and logs json columns have been moved to deprecated_metrics and
deprecated_logs (coalesced with the jsonb columns in the query-eng to
preserve querying for the old data).
This commit also changes PuppetDB's report storage to expect the v6
wire-format with the resources (instead of resource_events) field and
stores the resources document as a JSONB column in reports that was
created in a previous commit's migration addition. This commit updates
the tests to be more compatible with the new version, removing
unnecessary fields in the example reports' `resource_events` fields.
=> (PDB-1852) Add migration and storage for JSONB columns for Unchanged Resources

acceptance/setup/pre_suite/15_setup_repos.rb
This should correct test failures on debian 7 due to missing keys.
=> (maint) install debian-archive-keyring in repo setup

src/puppetlabs/puppetdb/reports.clj
This commit removes the resources blob when formatting a reports-query
report format to a wire v5 format. This is used only in PE.
=> (PDB-1854) Strip resources blob when converting reports-query->wire-v5

puppet/spec/unit/indirector/facts/puppetdb_spec.rb
The list of trusted facts has been increased, with the addition of 'hostname'
and 'domainname' to the list. This patch simply fixes the termini rspec tests
to include those new keys for comparison if they exist.
=> (maint) Test for new trusted facts in rspec

src/puppetlabs/puppetdb/query_eng.clj
previously this transposed "query" and "entity"
=> (maint) correct misordered error message

resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/http/aggregate_event_counts.clj, src/puppetlabs/puppetdb/http/event_counts.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/http/v4.clj, src/puppetlabs/puppetdb/meta.clj, src/puppetlabs/puppetdb/metrics.clj, src/puppetlabs/puppetdb/metrics/server.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/mq_listener.clj, src/puppetlabs/puppetdb/pdb_routing.clj, src/puppetlabs/puppetdb/scf/migrate.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/meta_test.clj, test/puppetlabs/puppetdb/middleware_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
Currently configuration is retrieved from the TK config service,
defaulted and consumed by other componentes via shared-globals. This
commit creates a new DefaultedConfig service that has a similar API as
the config service, but applies our validation and defaulting logic
first. This will allow a large amount of shared-globals to be removed
and instead just use the defaulted values from this new service.
This also starts the process of removing things from shared-globals (specifically removing the authorizer). MQ related config probably makes the most sense to work on next (this will be handled in a separate ticket).
=> (PDB-1902) Create a defaulted config service

project.clj
PDB has been approaching, and recently exceeded the 128M MaxPermSize
setting in project.clj, which results in an out-of-memory exception
during lein test.
The default OpenJDK setting (at least on Linux), appears to be higher
than that (166M), and lein test currently tops out at about 140M.  So
raise the limit to 200M, and don't specify it for anything other than
JDK 7 (since JDK 8 doesn't support it, and issues a warning).
=> (PDB-1959) Increase JVM permgen space

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj
This documents the deprecation of catalog-hash-debugging.
=> (PDB-1932) deprecate catalog-hash-debug

puppet/lib/puppet/util/puppetdb/char_encoding.rb, puppet/lib/puppet/util/puppetdb/command.rb, puppet/spec/unit/util/puppetdb/char_encoding_spec.rb, puppet/spec/unit/util/puppetdb/command_spec.rb
Prior to this commit, any non-ASCII character found in a catalog would
be replaced by /ufffd and a warning would be issued saying it found an
invalid character. The code now takes into account the force_encoding
done by to_pson and attempts to force_encode it back to UTF-8. For most
cases this should be sufficient.
There are times when binary data can appear in a catalog. In this case,
we have characters that we can't represent in UTF-8. For this we
continue to give users a warning. This warning now includes the command
being submitted and the node the command is for. If users have debug
logging enabled, context is given around where this bad character data
occurred. Up to 100 characters before/after this bad data is included in
the Puppet debug log.
=> (PDB-135) Improve and reduce the number of UTF-8 warnings

Gemfile
Packaging currently requires at least Puppet 3.8.1, but the Gemfile is
out of date and lists the olds supported Puppet as 3.5.1. Bumping the
Gemfile to match packaging.
=> (maint) Bump oldes support puppet version in Gemfile

puppet/spec/unit/util/puppetdb/char_encoding_spec.rb, puppet/spec/unit/util/puppetdb/command_spec.rb
The code doesn't work on 1.8.7. The main code paths guard against that,
but the tests did not. This puts that guard around the tests
=> (maint) Change char encoding context test to > 1.8.7

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/meta/version.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/migration_legacy.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/jdbc_test.clj, test/puppetlabs/puppetdb/query/population_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/scf/storage_utils_test.clj, test/puppetlabs/puppetdb/testutils.clj, test/puppetlabs/puppetdb/testutils/db.clj, test/puppetlabs/puppetdb/testutils/resources.clj
```
(PDB-1738) (PDB-1739) Drop jdbc.deprecated
Migrate all code to the newer clojure.jdbc API.
Note that the newer jdbc API handles some database operations like
transactions by storing bookkeeping information in nested database
references.  For example, (with-db-transaction ...) creates a new
database connection map with an incremented level, and the library uses
that level to determine where the "top" is, i.e. to decide when to
commit.
To accommodate that approach (without threading a db argument through
all of the existing code), add a jdbc/*db* variable to refer to the
"current" database, and make sure to bind appropriately it in
puppetdb.jdbc wrappers for the relevant clojure.jdbc calls.
Use (jdbc/db) to refer to *db* when invoking the new jdbc API's
functions.
Use jdbc/ consistently …
```
=> (PDB-1738) (PDB-1739) Drop jdbc.deprecated

resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/dashboard.clj, src/puppetlabs/puppetdb/http/command.clj, src/puppetlabs/puppetdb/metrics.clj, src/puppetlabs/puppetdb/mq_listener.clj, src/puppetlabs/puppetdb/pdb_routing.clj, test/puppetlabs/puppetdb/admin_test.clj, test/puppetlabs/puppetdb/cli/services_test.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/http/command_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
Migrate the MQ endpoint, connection, threads, and discard-dir values from shared-globals to the DefaultedConfigService.
Move all command submission to PuppetDBCommandDispatcher and remove the PuppetDBCommand service.
Have PuppetDBCommandDispatcher manage its own AMQP connection.
=> (PDB-1951) remove static items from shared globals

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
This commit fixes a bug with the jdbc upgrade where reports without
resources/resource-events would throw and exception while trying to call
`jdbc/insert!`.
=> (maint) Store reports without resources again

src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj
previously we had a schema that was attempting to validate this as a string,
when it should have been an int.
=> (PDB-1848) make max-frame-size tunable

src/puppetlabs/puppetdb/scf/migrate.clj
Previously this gave the impression that 9.3 was allowed.
=> (maint) change migrate trgm message to refer to 9.4

.travis.yml, ext/travisci/test.sh
Let Travis handle the jdk selection.  Right now jdk_switcher doesn't
actually exist.  This means Travis generates the test matrix more
implicitly, so use exclusions to make sure we only test ruby on one
db/jdk combination.
Add "set -ueo pipefail" to catch errors.
=> (PDB-2004) Alter tests to fix Travis jdk_switcher

resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-304bebf8e5fc109ced84e8b086f9bcf8324f3d78.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-327147ee71a6e67db76112add34d49c674f97b4f.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-339914cdb0a7a9a7ca4c9c310ab96ba20649376f.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-9956b77aba1f29fe276978cd68d4c169f2e34d69.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-a454ec51cbadba8c31beb9c1d66e90e9482ff4a6.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-193c2a3ae8b277158dbb1073a35290b406c3c073.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-19fce4fd5281b1df9b42d58c808fecb2a783da3b.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-34ecfe5dcfebc9510d159d2ec010d6e1f9094fb1.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-b73c37f620703406b5666e7c919afff00c511f1e.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-bb3cea0e4f72a38fde935e93a9efca44e540ec3c.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-cfdc33f7bb68d2c25d3b3758f3dca50b851b96ea.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-02f72d7b1e2ded2074c4c3d6e2f415f6978d5932.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-05ce58a44a6441dc967559bf89fd82619068f72c.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-5ba2c61aeb5f3ed8722e45f9c2c7b53d606e402e.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-6eade546c696f0c045ec29f955bdb4d6a39a8291.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-9eeca12cedb235b2e8f616967bf1f46d3e1de812.json, src/puppetlabs/puppetdb/anonymizer.clj, src/puppetlabs/puppetdb/cli/benchmark.clj, src/puppetlabs/puppetdb/client.clj, src/puppetlabs/puppetdb/export.clj, src/puppetlabs/puppetdb/import.clj, src/puppetlabs/puppetdb/reports.clj, test/puppetlabs/puppetdb/anonymizer_test.clj, test/puppetlabs/puppetdb/cli/benchmark_test.clj, test/puppetlabs/puppetdb/reports_test.clj
This PR cleans up some of the anonymizer code syntax to make it more readable and a little faster.
This PR removes some redundant validation and sanitization we were using in a bunch of different places regarding reports wireformats.
This PR removes some JSON roundtripping we we're doing in the benchmarking tool which was preventing us from freely moving around some of the sanitization code used by the benchmarking tool on reports. Essentially our benchmarking tool obeyed the `pdb-client` API for submitting data but that API made no sense,  submit a jsonified report to the client, unjson it, sanitize, rejson, submit it to PDB. Therefore this API for the pdb-client was changed (only used by benchmarking anyways) to not need a jsonified report. To make the api consistent, the other entities …
=> (PDB-1984) Migrate CLI tools to wireformat v6 of reports

src/puppetlabs/puppetdb/anonymizer.clj, test/puppetlabs/puppetdb/anonymizer_test.clj
This changes our anonymization code so that structured facts like
{:foo {:bar "baz"}} and {:foo {:bar "biz"}} will be identical when anonymized
except for the element that differs. This also changes our handling of arrays so
[1 2 3] and [1 2 4] will only differ in the last element when anonymized.
Finally, this bumps our use of (rand-int 300) to (rand-int (min value 20)),
which should ensure that the integers we get are sufficiently diverse.
=> (PDB-1614) anonymize path and value independently

src/com/puppetlabs/puppetdb/cli/services.clj, src/com/puppetlabs/puppetdb/scf/storage.clj, test/com/puppetlabs/puppetdb/test/scf/storage.clj
This changes our facts GC to do pinpoint deletion in chunks of 3000 elements.
The chunking shouldn't come into play except for in pretty unusual
circumstances, but without it jdbc can truncate the message to the database.
=> (PDB-2003) facts GC overwhelmed with very large updates

documentation/api/query/v4/operators.markdown, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/catalogs_test.clj, test/puppetlabs/puppetdb/http/environments_test.clj, test/puppetlabs/puppetdb/http/fact_names_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj
This patch fleshes out the rest of the selects for subqueries, to allow
subqueries across all the remaining (meaningful) endpoints.
=> (PDB-1924) Add missing subquery selects

ext/jenkins/lein-test.sh
This commit aligns our lein-test.sh from FOSS with the script by the
same name in PE now that we use 2 postgresql's instance in clojure
testing in FOSS.
=> (PDB-2006) Update jenkins lein-test config to setup second testing db

src/puppetlabs/puppetdb/facts.clj, test/puppetlabs/puppetdb/facts_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
Without this commit we're broken on escape-quoted fact names and fact names
containing #~. Some escape-quoting we do before storage was causing different
names to come out of realize-paths! than went in, which caused an empty key
lookup that led to the error.
=> (pdb-2034) schema error on replace-facts with escape-quoted strings

documentation/api/query/v4/operators.markdown, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj
This commit fixes a bug in `engine.clj` where the clauses for dealing
with `extract` were misordered so we had incorrect behavior when
handeling aggregates with a group-by clause without a subexpression.
This commit also removes some documentation claiming that a user must
supply a subexpression.
=> (PDB-2049) Allow aggregates to omit subexpression

src/puppetlabs/puppetdb/export.clj, test/puppetlabs/puppetdb/testutils/cli.clj
This commit removes some of our child data expansion helpers that were
used for hsqldb, which is now retired.
=> (maint) Remove child expansion helpers from export and testutils

acceptance/setup/pre_suite/40_install_deps.rb
I needed these on debian jessie to get the sqlite3 gem installed. No clue why
it's not needed on wheezy.  We can remove them and the rest of this code block
once we convince ourselves storeconfigs are dead.
=> (maint) add make and gcc to debian deps

acceptance/tests/storeconfigs/basic_collection.rb, puppet/lib/puppet/indirector/catalog/puppetdb.rb
This fixes a discrepancy between JVM puppetserver and Puppet with respect to our
terminus, where manifests like
@@notify { "test":
tag => [undef, "a", "b"],
}
would fail due to inability to compare symbols and strings. With this patch, we
sort by string representation rather than sorting the array directly.
=> (PDB-2007) array params with undef don't sort

src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/query_eng_test.clj
This commit makes our query-recs defs rather than defns, now that hsqldb
has been removed.
=> (PDB-1996) Make query-recs defs rather than defns

test/puppetlabs/puppetdb/cli/benchmark_test.clj
This is locally replicable and debuggable. No reason for it to continue
holding up CI.
=> (maint) remove failing benchmark test

Gemfile, puppet/spec/spec_helper.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb, puppet/spec/unit/reports/puppetdb_spec.rb, puppet/spec/unit/util/puppetdb/command_spec.rb, puppet/spec/unit/util/puppetdb/config_spec.rb
This commit updates our rspec dependency to `~> 3.1` now that we no
longer support Puppet 3.
=> (PDB-1412) Update rspec dependency to `~> 3.1`

src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/facts_test.clj
This changes our fact queries to use the proper string or boolean column
instead of converting equality queries to a comparison on value_hash.
=> (PDB-2064) stop converting value equality queries to hash comparisons

ext/jenkins/packaging.sh
This adds jessie to our build targets. We probably shouldn't merge it until we
get a nightly run with a green cell on jessie.
=> (PDB-1798) add jessie to build targets

src/puppetlabs/puppetdb/admin.clj, src/puppetlabs/puppetdb/pdb_routing.clj
This commit adds the `compojure.route/not-found` route at the top-level
of the PuppetDB routes so that new PuppetDB routes won't need to add the
not-found route. This also fixes an error where if a user hit any
non-existent route under `/pdb`, PDB would throw an exception related to
our middleware not playing nicely with not-founds which produced a
confusing `nil...status` error.
=> (PDB-2096) Add not-found route to top-level `/pdb` route

src/puppetlabs/puppetdb/scf/migrate.clj
We need to swallow the error that occurs when the schema_migrations table
doesn't exist. Everything else should be thrown.
=> (PDB-1964) don't swallow errors in applied-migrations

src/puppetlabs/puppetdb/anonymizer.clj, test/puppetlabs/puppetdb/anonymizer_test.clj
* when randomizing strings, use a length equal to the length of the target
* when randomizing floats, cap the value with the target
* remove some unused leaf types
=> (maint) tweaks to anonymization

src/puppetlabs/puppetdb/anonymizer.clj, test/puppetlabs/puppetdb/anonymizer_test.clj
Previously we were prone to collisions on single-character fact names.
=> (maint) cap minimum anonymized string length at 10

documentation/puppetdb_connection.markdown, puppet/lib/puppet/util/puppetdb/config.rb, puppet/lib/puppet/util/puppetdb/http.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb, puppet/spec/unit/indirector/resource/puppetdb_spec.rb, puppet/spec/unit/util/puppetdb/config_spec.rb
This commit retires the deprecated server and port terminus settings
which were replaced by the server_urls setting.
=> (maint) Retire the old server and port terminus settings

documentation/release_notes.markdown
This adds the release notes for version 3.2.0, and fixes a version bug in
the older 3.1.0 release (it was accidentally changed to 3.2 instead).
=> (PDB-2086) Release notes for 3.2.0

project.clj
This is the natural bump after 3.2.0 has been released.
=> (PDB-2080) Bump project.clj to 3.2.1-SNAPSHOT ready for more work

project.clj
This has a bugfix we need in s/constrained.
=> (maint) Update prismatic schema to 1.0.3

documentation/install_from_source.markdown
The existing documentation was based on a world without ezbake. This patch
updates the documentation to provide ezbake-based source installation
instructions.
=> (PDB-2058) Fix build from source documentation

project.clj
Puppet QA would like to measure what percent of lines and forms are covered by PuppetDB's unit tests. We will generate code coverage numbers using the third-party package "cloverage", which lives at https://github.com/lshift/cloverage. Cloverage is run via a leinegen plugin called "lein-cloverage".
This PR does two things:
* add lein-cloverage plugin to `project.clj`
* add 2 dependencies to dev profile in `project.clj` to avoid dependency clashes with cloverage
=> add code coverage tool

puppet/spec/unit/indirector/facts/puppetdb_spec.rb
Puppet just changed the 'domainname' trusted fact to 'domain'; this
fixes our tests to work with it.
=> (maint) Fix trusted facts tests

ext/jenkins/beaker-tests.sh
We are currently not testing upgrades. The JJB jobs use an INSTALL_TYPE
environment variable to indicate whether we are testing an install or an
upgrade. PuppetDB does not recognize that variable and always assumes
were testing an install. This commit just sets the value of INSTALL_MODE
to what JJB has set for INSTALL_TYPE. This should fix things so our
upgrade tests go through the upgrade process.
=> (MAINT) Add an INSTALL_MODE var to beaker-tests.sh

acceptance/tests/security/puppetdb-ssl-setup/nonprod-environment.rb, resources/ext/cli/ssl-setup.erb
This changes our ssl-setup script to use "puppet agent" rather than "puppet
master" when gathering its hostname and config file locations.
=> (PDB-2100) ssl setup fails on nonproduction environments

test/puppetlabs/puppetdb/meta_test.clj
This commit merges two tests called test-latest-version. One of the
tests was shadowing the other and upon merge it became clear that one of
the tests that was being shadowed was broken. This commit also fixes the
misnamed config key that was causing issues and test failures.
=> (PDB-2099) Fix test-latest-version shadowing

ext/jenkins/lein-test.sh
For now, use the existing puppetdb postgres user as both the unit test
admin and test runner.
=> (PDB-2075) Conflate unit test admin/user on jenkins

ext/jenkins/lein-test.sh
Which should be something like this:
jenkins-enterprise_puppetdb_unit-clj-puppetdb_master-145
=> (PDB-2075) Use the BUILD_TAG for PDB_TEST_ID

ext/jenkins/lein-test.sh
Since BUILD_TAG is pushing up against the postgres name length limit.
=> (PDB-2075) Use a UUID for PDB_TEST_ID

project.clj
Ezbake 0.3.21 was just released, so this updates to use that version.
=> (maint) Update to latest ezbake

Rakefile, ext/jenkins/beaker-tests.sh
Without this patch the acceptance tests just always use `postgres` even if PUPPETDB_DBTYPE is set to something else.
Previously the name `embedded_db` was the alternative to `postgres` despite the fact that the unit test jobs actually used `hsqldb` vs `postgres` as the distinction. In https://github.com/puppetlabs/ci-job-configs/pull/715 I removed the use of `embedded_db` entirely to be replaced with `hsqldb` where appropriate.
=> (QENG-3111) Make use of the PUPPETDB_DBTYPE CI variable.

acceptance/tests/reports/report_storage.rb
The new puppet agent (4.3.0) drops 5 info level events, instead of just 4.
=> (maint) Tests: fix info level count due to new agent

documentation/api/status/v1/status.markdown, project.clj, src/puppetlabs/puppetdb/pdb_routing.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/status_test.clj
This changes our status implementation to return :starting while in maint mode,
and bumps to the status-service version that enables the change.
=> (maint) change maint-mode state of status implementation to :starting

src/puppetlabs/puppetdb/scf/migrate.clj
Without this patch, equality queries on our bytea fields trigger full table
scans because we're doing type coercion on the left hand side of the
comparison. This adds expression indexes for those coercions to enable fast
queries.
=> (PDB-2206) indexes not getting used for hash/uuid queries

src/puppetlabs/puppetdb/cli/benchmark.clj, test/puppetlabs/puppetdb/cli/benchmark_test.clj
This removes some unwarranted slashes from our benchmark code, and implements a
test for the -A flag.
=> (PDB-2112) fix benchmark -A flag

acceptance/config/ec2-west-ubuntu1404-64mda.cfg, config/image_templates/ec2.yaml
The packer builds for Centos 7 and Debian 7 have been updated, this PR
switches to the new AMI's.
=> (maint) Update Debian 7 & 8, Centos 7 and Ubuntu 14.04 ami's from latest packer builds

ext/jenkins/lein-test.sh
...in case it's handy when diagnosing failures.
=> (PDB-2246) Add trivial system info to Jenkins log

documentation/api/metrics/v1/mbeans.markdown, documentation/configure.markdown, project.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/jdbc/internal.clj
This commit moves our connection pooling to use HikariCP instead of
BoneCP. This means we lose our pool metrics for now, until we update our
codehale metrics dependency.
=> (PDB-992) Move to HikariCP instead of BoneCP

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj
This reverts commit 8a70a5d3416a89c45cf70c1b1c9e58f7e82ce19b.
=> Revert "Revert "(maint) default statement cache size to 0""

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/http/command.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/meta.clj, src/puppetlabs/puppetdb/metrics.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/pdb_routing.clj, src/puppetlabs/puppetdb/schema.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/config_test.clj, test/puppetlabs/puppetdb/fixtures.clj, test/puppetlabs/puppetdb/middleware_test.clj, test/puppetlabs/puppetdb/schema_test.clj
This commit uses the content-length header to determine the size of the
incoming request. If that POST request is too large for the system to
process (currently set at 1/205th of the max heap size) it will return
close the input stream and return a 412 status code.
=> (PDB-156) Fail gracefully when commands are too large

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/config_test.clj
This commit enables `reject-large-commands` by default. It can still be
disabled and the size of commands to reject can still be set via
`max-command-size`.
=> (PDB-156) reject-large-commands should be enabled by default

src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj
This commit changes our handling of bytea from using `trim` (which
relies implicitly on `bytea_output` being set to `'hex'` in PostgreSQL)
to instead use `encode(...,'hex')`. This allows our `bytea` usage to be
database setting independent.
This commit also cleans up some of the `fact_values` code in storage.clj
which was using `parse-db-hash` which is also not `bytea_output`
independent.
=> (PDB-2239) Use encode for handling bytea data

test/puppetlabs/puppetdb/testutils/services.clj
Originally notable-pdb-event? wasn't set up to be customized, but now we
want that (i.e. PDB-2215), so make it configurable by
adding *notable-pdb-event?* to testutils.services.
=> (PDB-2255) Make notable-pdb-event? configurable

documentation/api/query/v4/operators.markdown, project.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/http/catalogs_test.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj
This commit adds the `in`-`array` operator to the query language.
For example:
```json
["from", "nodes",
["subquery", "resources",
["in", "type",
["array",
["File",
"Apache::Mode",
"Apt::Pin"]]]]]
```
=> (PDB-163) Add the `in`-`array` operator to the query language

src/puppetlabs/puppetdb/middleware.clj
This changes our logging of command sizes from info to debug level.
=> (maint) log command sizes at debug level

puppet/lib/puppet/util/puppetdb/char_encoding.rb, puppet/spec/unit/util/puppetdb/char_encoding_spec.rb
The terminus includes code to help users diagnose the source of data
that cannot be converted to UTF-8. There are several sources of this,
but one is having an incorrect (or known) character set for portions of
the catalog. When this invalid character data is large, it would cause
the terminus to hang trying to include debugging information.
This patch changes the terminus to only look for the first instance of
bad data. It will also avoid doing the extra calculations needed for the
error context unless debug mode is enabled. When not in debug mode there
should be no impact on performance.
=> (PDB-2256) Fix terminus bug with large binary catalog data

documentation/configure.markdown, documentation/puppetdb_connection.markdown, src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/config_test.clj
This commit adds a setting for toggling the storage of
historical-catalogs (to be used in PE) to the `puppetdb` section of the
PuppetDB config.
=> (PDB-2264) Add setting for toggling historical-catalogs storage

.travis.yml, src/puppetlabs/puppetdb/scf/migrate.clj
Instead of parsing the error message to determine if the schema_migrations
table already exists, use the error code embedded in the exception.
=> (PDB-2259) Fix initial migration for non-english postgresql

src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/reports_test.clj
This commit fixes an issue in the query language where the group-by
operator assumed a function operator in the columns of the extract.
This was causing `NullPointerException`s for valid queries. This commit
also adds some more tests around this behavior.
=> (PDB-2262) Don't assume group-by needs function calls

.travis.yml
The bug described here: https://github.com/travis-ci/travis-ci/issues/5227
... and its work-around requires sudo, so we need to remove the sudo:false setting
for this to work. This is temporary until the bug is fixed upstream.
=> (maint) Enable sudo again to allow workaround for java bug

project.clj, src/puppetlabs/puppetdb/cli/benchmark.clj
Use ActiveMQ for on-disk intermediate storage when doing a
simulation-style (--runinterval) benchmark.
=> (maint) Improve memory usage in benchmark tool

documentation/_puppetdb_nav.html, documentation/trouble_session_logging.markdown
Preserve the documented session logging requirements from Jira into a more likely place for people to find it.
=> (PDB-2267) Document session logging

src/puppetlabs/puppetdb/jdbc.clj, test/puppetlabs/puppetdb/testutils.clj
This commit adds a similar mechanism to HikariCP that we have for
ActiveMQ to disable JMX reporting. This is because JMX is per JVM which
means our sync tests' metrics will collide by trying to start 2 PDB's in
the same JVM.
=> (PDB-2234) Add ability for sync tests to disable metrics

src/puppetlabs/puppetdb/catalogs.clj, src/puppetlabs/puppetdb/export.clj, src/puppetlabs/puppetdb/reports.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/acceptance/cli.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
This PR fixes a bug with historical catalogs where a user could turn
off historical catalogs and break some of the PE views because the JSONB
column storage was also turned off. This new atom will always be set to
true in PE (as opposed to the historical-catalogs' atom which is config
dependent).
This PR aligns the edges and resources jsonb format with the return
format from querying the catalogs endpoint, this means we do not have to
parse and munge jsonb in export, the new endpoints and sync.
=> (PDB-2286) Add ability to always store catalog jsonb fields, (PDB-2290) Munge edges and resources jsonb for storage

documentation/api/command/v1/commands.markdown, puppet/lib/puppet/util/puppetdb/char_encoding.rb, puppet/lib/puppet/util/puppetdb/command.rb, puppet/spec/unit/indirector/catalog/puppetdb_spec.rb, puppet/spec/unit/indirector/facts/puppetdb_spec.rb, puppet/spec/unit/indirector/node/puppetdb_spec.rb, puppet/spec/unit/reports/puppetdb_spec.rb, puppet/spec/unit/util/puppetdb/command_spec.rb, src/puppetlabs/puppetdb/cheshire.clj, src/puppetlabs/puppetdb/http/command.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/middleware_test.clj
This allows us to do more granular logging at the wire without parsing the
command payload itself.
=> (PDB-2230) support submission of certname/command/version via post params

documentation/api/ext/v1/resource-graphs.markdown, src/puppetlabs/puppetdb/query_eng/engine.clj
This commit fixes the nodes query to left join on only the latest
catalog and not all (historical catalogs) and fixes the documentation
for resource-graphs.
=> (maint) Fix nodes query for historical catalogs

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
This removes a gc operation that can become expensive on large environments.
Since report_statuses has 3 rows max, there's no reason to clean the table.
=> (maint) stop deleting unassociated report statuses

src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/config_test.clj
This commit modifies the configuration validation to support
specifying a relative path, which is necessary in order to
support a portable development environment where users
can run the system "out-of-the-box" (e.g., by including
a developer config file that has a hard-coded vardir path
of "./target/puppetdb-vardir".)
This is a requirement for the PE-AIO dev environment and tests
to work properly, at least based on their current implementation.
=> (PDB-2271) support relative path to vardir

src/puppetlabs/puppetdb/query_eng/engine.clj
This commit changes the nodes query to use a "regular" left join from
certnames to reports using the `latest_report_id` instead of using an
`in` expression.
=> (maint) Use join on `id` for nodes-query with reports

puppet/lib/puppet/util/puppetdb.rb, puppet/lib/puppet/util/puppetdb/http.rb, puppet/spec/unit/util/puppetdb_spec.rb
This commit adds a PuppetDB terminus utility function to query PuppetDB at the `root`
endpoint.
=> (PDB-2186) Add PuppetDB utility function for querying PuppetDB

src/puppetlabs/puppetdb/cheshire.clj, test/puppetlabs/puppetdb/http/reports_test.clj
This commit fixes an issue with the PGObject JSON encoder (when
pretty-printing) which assumed the object was a map.
=> (maint) Fix pretty-printing for PGObjects which are lists

src/puppetlabs/puppetdb/cheshire.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/http/command.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/mq.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/http/command_test.clj, test/puppetlabs/puppetdb/middleware_test.clj
Don't parse the incoming command body when it has command and version
parameters (which should now be the common case).  Instead, validate the
parameters, and pass the body directly to the queue, uninterpreted.
Otherwise, warn if body has to be parsed into RAM.
Attach the command, version, and if available, certname, to the queue
message as JMS properties, extracting them from the body (after
parsing), if they weren't available in the incoming request.
As before, reject incoming commands that don't have both command and
version when they have either.
=> (PDB-2252) Try to avoid parsing a POSTed cmd

src/puppetlabs/puppetdb/cli/benchmark.clj, src/puppetlabs/puppetdb/client.clj, test/puppetlabs/puppetdb/acceptance/cli.clj, test/puppetlabs/puppetdb/acceptance/node_ttl.clj, test/puppetlabs/puppetdb/admin_test.clj, test/puppetlabs/puppetdb/cli/benchmark_test.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/pdb_routing_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
This changes our tests and benchmark tool to use form params in accordance with
the new command submission style.
=> (PDB-2332) use params for submit-command-via-http

acceptance/tests/storeconfigs/puppetdb_query.rb, puppet/lib/puppet/functions/puppetdb_query.rb, puppet/lib/puppet/util/puppetdb.rb, puppet/spec/unit/util/puppetdb_spec.rb
This commit adds a puppetdb_query function for querying PuppetDB with
either AST of PQL syntax in a Puppet manifest.
=> (PDB-2186) Add puppetdb_query function for querying PuppetDB via Puppet

project.clj, src/puppetlabs/puppetdb/anonymizer.clj, test/puppetlabs/puppetdb/anonymizer_test.clj
This fixes an anonymization bug where we would anonymize text blobs as
completely different, sometimes long random strings even if they only differed
by a word. This prevented any reasonable compression of report logs/messages,
which meant that the tool produced unmanagebly large tarballs on big installs.
With this patch a text blob is replaced by a string of question marks of the
same length.
=> (PDB-2214) anonymize words as ?????

src/puppetlabs/puppetdb/mq_listener.clj
This commit renames the processed metric from discarded to processed.
=> (maint) Fix misnamed mq metric

acceptance/setup/pre_suite/70_install_released_puppetdb.rb, src/puppetlabs/puppetdb/scf/migrate.clj
This changes our oldest supported upgrade branch to 2.3.8, from 2.3.2
=> (maint) test upgrades from 2.3.8

src/puppetlabs/puppetdb/http/query.clj, test/puppetlabs/puppetdb/http/query_test.clj
This is needed so the sync code can use the newer query syntax.
=> (PDB-2289) Teach add-criteria about ["from" ...]

resources/ext/config/request-logging.xml
Prior to this commit puppetdb used a different request
logging format than console-services and puppetserver.
After this commit the request logging will be of the suggested
formatting for all trapper-keeper projects.
=> (PE-13485) Implement a consistent request logging format

project.clj
This updates the pinned lein-ezbake version
to 0.3.22.
=> (RE-6278) Update lein-ezbake pin to 0.3.22

resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/pdb_routing.clj, test/puppetlabs/puppetdb/testutils/services.clj
This splits the status functionality out into its own TK service so it can be
shared with PE routing.
=> (PDB-2434) PDB status missing in PE

documentation/configure.markdown, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/config_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
This commit limits the storage of historical catalogs to only the latest
three catalogs for a node. This commit limits the storage because for
our benchmarking data with 5000 nodes (~3 million catalogs) we were
seeing the catalogs table take up around 140GB of space.
=> (PDB-2380) Limit the storage of historical-catalogs

src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
Prior to this commit when historical catalogs was turned on, storing a
catalog for a given certname would delete all the other catalogs for the
other certnames in the database. This commit fixes the issue.
=> (PDB-2380) Only delete historical-catalogs for the given node

src/puppetlabs/puppetdb/cli/services.clj
This commit changes our population metrics to use the read-db and not
the write-db so that we leverage read replica's when they are available.
=> (PDB-2435) Use read-db for population metrics

project.clj
This bumps the EZBake version due
to a new release of EZBake
=> (maint) Bump EZbake version

src/puppetlabs/puppetdb/http/query.clj, src/puppetlabs/puppetdb/pql.clj, src/puppetlabs/puppetdb/query/paging.clj, test/puppetlabs/puppetdb/http/command_test.clj, test/puppetlabs/puppetdb/http/index_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/testutils.clj
This commit fixes an issue where PuppetDB was return HTTP 500 responses
for requests with malformed JSON in an AST query because our middleware
only catches IllegalArguementExceptions.
=> (maint) Don't 500 on malformed AST queries

project.clj, src/puppetlabs/puppetdb/query/population.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/query/population_test.clj
This is a stable backport of
1b79d8158698a01cefe791f8f8cc0031e62950e3. This switches the metrics
calls that query for number of nodes and resources per node to use table
stats rather than a full table scan for each call. This isn't an exact
backport as some things are different in master right now (java.jdbc
usage, metrics, fixtures are different etc). This does preserve the
behavior of caching the resources per node calls though. Number of
inactive nodes was not backported as it's a new metric and will need a
non-bugfix release.
=> (PDB-2425) use table stats to compute the number of resources

src/puppetlabs/puppetdb/query/population.clj, test/puppetlabs/puppetdb/query/population_test.clj
Table stats (and vacuum) should only be used when running on
Postgres. This was changed (on Postgres) for performance reasons. These
same performance tweaks aren't available on HyperSQL, so we should just
default back to the original query behavior in those cases.
=> (MAINT) Don't use table stats for HyperSQL dashboard queries

project.clj, src/puppetlabs/puppetdb/cli/benchmark.clj
Wrap the temp AMQ instance in a custom core.async Buffer,
allowing us to use a single channel with the custom buffer instead
of two separate channels.
=> (maint) Simplify core.async/AMQ use in benchmark

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/config_test.clj
Attempting to set a command size that is "too large" is difficult as
it's very dependent on environment. Having this enabled by default was
causing commands that were able to be processed before to be rejected as
they were considered too large by this setting. With the potential
impact of these false positives, the setting should be false by default.
Users wanting to set a max-command-size still can. We also output debug
logging to help users get a feel for their current command sizes, using
that users should better be able to determine their typical command
sizes and find a better default than our current (overly conservative)
estimate.
=> (PDB-2454) reject-large-commands false by default

documentation/api/query/v4/pql.markdown, resources/puppetlabs/puppetdb/pql/pql-grammar-experimental.ebnf, src/puppetlabs/puppetdb/pql/transform.clj, test/puppetlabs/puppetdb/http/index_test.clj, test/puppetlabs/puppetdb/pql/parser_test.clj, test/puppetlabs/puppetdb/pql/transform_test.clj
* Convert examples to double quotes, so they can be cut & paste using the curl example
* Show better path and array regexp examples that actually work
* Use a better explicit subquery example for multiple fields
* Allow question marks in a field
* Add more tests for the above bugs/problems
=> (maint) PQL fixes & corrections from Scott Walker

resources/puppetlabs/puppetdb/pql/pql-grammar-experimental.ebnf, test/puppetlabs/puppetdb/pql/parser_test.clj, test/puppetlabs/puppetdb/pql_test.clj
This patch allows inequality operators (>,>=,<,<=) to be used on date
fields similar to how they are allowed in the AST language. There is
currently no validation to ensure correct format of the date
strings (similar to AST).
=> (PDB-2407) PQL- Allow inequalities on date fields

src/puppetlabs/puppetdb/http/handlers.clj, src/puppetlabs/puppetdb/http/query.clj, src/puppetlabs/puppetdb/middleware.clj, src/puppetlabs/puppetdb/query_eng.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/testutils.clj
This commit fixes our `pretty` parameter for query POSTs, before this
commit we weren't properly passing the param from the POST body to the
produce-streaming-body function and weren't allowing the parameter
through validation.
=> (PDB-2438) Fix pretty-printing parameter for POST

src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
Currently delete-edges coerces the column and compares it with the data
passed in. This cause ALL source/target column values to be
decoded. This is slow and doesn't hit the unique index that is in
place. Instead this patch converts the source/target being deleted to
bytea and compares it with what is stored. This hits the index and will
be much faster as only 1 conversion is done, not one for each row + column.
=> (PDB-2424) Fix delete-edges! to hit unique index

src/puppetlabs/puppetdb/scf/migrate.clj
This commit moves the post migration vacuum analyze to a future so that
we don't block startup on the analyze which can take a while on large
databases.
=> (PDB-1960) Don't block startup on the post migration vacuum

test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/testutils.clj
Now that we do the post-migration vacuum in the background, it can
race with test execution (especially in the 3.x series, where we are
still running db migration once per test case). In this case, we are
testing pagination. If we do the first paginated query, then vacuum
executes, and then we do the second paginated query, the underlying
table can be rewritten to have a different natural order.
Fix this by supplying an order_by to the paginated query, ensuring
its stability across storage change.
=> (maint) Fix flaky reports test

src/puppetlabs/puppetdb/http/query.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/query_eng_test.clj
This commit fixes a bug with aggregates and group-by where the fields
used as arguments to those operators (`function` and `group_by`) weren't
being converted to our `fields` (honeysql) constructs which have the
table disambiguation and correct names for certain query API fields
(e.g. queries to `/nodes` grouping by certname now work instead of
erroring with an ambiguous column message, and queries to `/reports`
with `["function","min","report_timestamp"]` will now properly rename
`report_timestamp` to `reports.end_time` in the SQL).
=> (PDB-2360) Fix aliasing in aggregates and group-by

puppet/lib/puppet/util/puppetdb/http.rb
Remove an obsolete implementation of shared terminus state and eliminate
the associated warning message printed on startup.
=> (maint) Remove unused terminus code and warning

src/puppetlabs/puppetdb/http/query.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/testutils/http.clj
Don't clobber the [developer] pretty-print (config) value that's in
shared-globals with nil when there's no pretty parameter in the query
map, and add a trivial test for the effect of :pretty-print in
shared-globals.
=> (PDB-2596) Respect [developer] pretty-print

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj
This commit move the asynchronous vacuum analyze to use the write-db
connection pool instead of the temporary one we use for migrations so
that we know the connection will still be around while we attempt to
execute the vacuum.
=> (PDB-1960) Remove race condition with initial vacuum analyze

project.clj
This fixes an issue with ever-growing scheduler logs for failed
commands.
Changelog for 5.13.1: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311210&version=12334251
Changelog for 5.13.2: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311210&version=12334774
I've been through these and nothing aside from the relevant fix looks to impact features we use.
=> (PDB-2390) Upgrade to ActiveMQ 5.13.2

test/puppetlabs/puppetdb/http/event_counts_test.clj, test/puppetlabs/puppetdb/http/fact_names_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/http/resources_test.clj, test/puppetlabs/puppetdb/testutils/cli.clj
With the inclusion of the recent backgrounded 'analyze' it introduced some
flakiness to our tests due to ordering issues. This patch fixes two cases
where we are doing a limit without an order-by, and converts resource_events
for reports tests to a set so comparison always works.
=> (maint) Remove some potential ordering issues from tests

documentation/api/admin/v1/summary-stats.markdown
This file had an unclosed quote. But since the "canonical:" key is now optional
and automatically detected, I just deleted it entirely instead of closing the quote.
This only affects master, afaict. 
For folk with confluence accounts, here's a link about "canonical" being optional now: https://confluence.puppetlabs.com/display/DOCS/YAML+Frontmatter#YAMLFrontmatter-canonical:
=> (docs) Fix typo in yaml frontmatter (summary-stats)

documentation/pdb_support_guide.markdown
This file had an unclosed quote.
This affects master as well, but I think we're still merging stable to master occasionally, right?
=> (docs) Fix typo in yaml frontmatter (pdb_support_guide)

ext/jenkins/lein-test.sh, ext/travisci/test.sh, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj
This fixes an issue where our index-exists? function assumed the public schema.
=> (PDB-2486) allow upgrades in different schemas with pg_trgm

ext/jenkins/lein-test.sh
This corrects a misnamed environment variable for db admin credentials in our
jenkins test.
=> (maint) use correct db test admin credentials in jenkins

documentation/_puppetdb_nav.html
This commit makes it so we don't have to manually update the version number in
documentation/_puppetdb_nav.html every time we merge master to stable.
Instead of using a hardcoded version, we use existing metadata in the docs site
(configured in puppet-docs/source/_config.yml under the "documents:" key, which
we already update every time we post a new version of the docs). This lets us
look up both the correct version number -- {{ page.doc.version }} -- and the
base URL that the `documentation` folder gets mounted at -- {{puppetdb}}.
=> (docs) Make the sidebar nav version-agnostic

test/puppetlabs/puppetdb/testutils.clj
This wraps the entire macro in an `is` assertion. Since all cases where this was
used did this anyway, it provides more convenience. However, the main reason was
to ensure that the differential between the old and new values actually gets
printed during testing instead of simply returning the expectation of being true.
=> (PDB-2565) Change =-after? to is-equal-after

src/com/puppetlabs/puppetdb/scf/storage.clj, src/com/puppetlabs/puppetdb/scf/storage_utils.clj, test/com/puppetlabs/puppetdb/test/scf/storage.clj
This changes the resource-exists? function to use an array-valued prepared
statement parameter, rather than a list of parameters that could potentially
exceed max_short.
=> (PDB-2548) prepared statement array in resource-exists?

documentation/api/query/tutorial-pql.markdown, documentation/api/query/v4/index.markdown, documentation/api/query/v4/nodes.markdown, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/nodes_test.clj
This adds a latest_report_noop flag to the nodes response to indicate whether
the latest puppet run for a node was a noop.
=> (PDB-2490) add latest_report_noop field to nodes

puppet/spec/unit/indirector/resource/puppetdb_spec.rb
Puppet master branch (4.5.0 in the future) has added extra expectation on the scope object
now, in that it expects to be able to call environment. This patch fixes our tests so the
stub included environment also.
=> (PDB-2577) Fix environment method stubbing for indirector tests

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/jdbc.clj, test/puppetlabs/puppetdb/jdbc_test.clj
This patch raises the default number of pool connections fro 10 to 20 (same as
in all previous PDB releases) and fixes a bug where the configuration option
was not actually being applied.
=> (PDB-2581) set max connection size

test/puppetlabs/puppetdb/middleware_test.clj
This commit removes i18n middleware tests as they fail on travis because
the locales aren't installed. They also fail locally if the spanish
locale isn't installed. This is a temporary hack until we figure out a
more permnanent solution.
=> (maint) Remove i18n tests for travis

documentation/api/query/v4/ast.markdown, documentation/api/query/v4/pql.markdown, documentation/api/query/v4/reports.markdown, resources/puppetlabs/puppetdb/pql/pql-grammar-experimental.ebnf, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/pql/parser_test.clj, test/puppetlabs/puppetdb/query_eng_test.clj
This adds a to_string function that wraps PG's to_char function, and also
allows consumers to group by the results of a function, allowing users to get
counts of events by hour and similar.
=> (PDB-2494) add to_string function and ability to group by function results

ext/jenkins/packaging.sh
Debian 6 has reached EOL and should be removed from all build/test
pipelines
=> (maint) Remove Debian 6 from pipelines

src/puppetlabs/puppetdb/http/handlers.clj, test/puppetlabs/puppetdb/http/explore_test.clj
Fixes a regex bug introduced in the switch to comidi, which disallowed colons
in routes (e.g resource types/titles, etc). Strips a bit of incidental trailing whitespace too.
=> (PDB-2624) allow colons in routes

project.clj, src/puppetlabs/puppetdb/scf/storage.clj
We currently validate reports in puppetdb/command.clj and then
re-validate those reports twice in puppetdb/scf/storage.clj. This second
and third validation is very CPU intensive. Some load testing has
revealed as much as 30% of the CPU usage was dedicated to this purpose.
This inefficientcy is mainly spent on unchanged resources and would
likely only be observed on catalogs that have a large number of
unchanged resources.
=> (PDB-2620) Remove runtime validation of reports in storage

puppet/lib/puppet/functions/puppetdb_query.rb
To be compatible with Puppet 4.0.0 where recursive types
are not possible, the type checked here is not accurate.
Ideally, the type should be:
Variant[String[1], StringTree]
where StringTree is defined (recursively) by:
StringTree = Array[Variant[String, StringTree]]
=> Add a basic checking of the "query" parameter in the function puppetdb_query()

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
Instead of expiring one node at at time with a round-trip through PDB
for each, combine stale-nodes and expire-node! into expire-stale-nodes
which handles the entire process in a single SQL command, and returns
all of the expired certnames.
In addition to changing the expiration semantics a bit, this also alters
the reporting, logging "Auto-expired node foo" for each expired node
only after all of the nodes have been expired.  Previously an
"Auto-expiring node foo" was displayed for each node, just before that
node was expired.
=> (PDB-2576) Expire nodes in single SQL command

src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query/aggregate_event_counts.clj, src/puppetlabs/puppetdb/query/events.clj, src/puppetlabs/puppetdb/scf/migrate.clj, test/puppetlabs/puppetdb/http/aggregate_event_counts_test.clj, test/puppetlabs/puppetdb/http/event_counts_test.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/query/events_test.clj
* adds an index on certnames(latest_report_id)
* fixes a bug preventing latest_report? usage with the distinct_resources parameter
* moves query logic for unioned aggregate-event-counts queries from the
aggregations to the CTE
=> (PDB-2527) allow latest-report? to be used in legacy events queries

project.clj
This bumpes ezbake so we can fix PuppetDB on xenial pulling in java 9.
=> (PDB-2663) Bump ezbake version to include xenial fixes

src/puppetlabs/puppetdb/http.clj, src/puppetlabs/puppetdb/middleware.clj, test/puppetlabs/puppetdb/http/aggregate_event_counts_test.clj, test/puppetlabs/puppetdb/http/command_test.clj, test/puppetlabs/puppetdb/http/event_counts_test.clj, test/puppetlabs/puppetdb/http/events_test.clj, test/puppetlabs/puppetdb/http/fact_names_test.clj, test/puppetlabs/puppetdb/http/facts_test.clj, test/puppetlabs/puppetdb/http/index_test.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/paging_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/http/resources_test.clj, test/puppetlabs/puppetdb/middleware_test.clj
This patch fixes the cases where text errors were not returning the correct
text/plain Content-Type header by fixing error-response to do this, and forcing
all relevant code to use this function instead of trying to create errors
themeselves.
This also adds tests to ensure errors return the correct content-type.
=> (PDB-2621) Force all textual errors to be text/plain

documentation/configure.markdown, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/mq.clj, test/puppetlabs/puppetdb/config_test.clj, test/puppetlabs/puppetdb/mq_test.clj
This commit adds the ability to configure the ActiveMQ Broker's
MemoryLimit in PuppetDB. Before this commit the MemoryLimit was always
the default 1GB.
=> (PE-15026) Allow configuration of the ActiveMQ Broker's MemoryLimit

src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/scf/storage_test.clj
Drop contraints while sweeping reports (and reestablish them afterward)
to avoid triggering per-report checks during delete.
This appears to substantially decrease the sweep time, and we believe it
should be safe because all of the operations involved should be covered
by PostgreSQL MVCC (i.e. guarded by the transaction).
=> (PDB-2477) Drop constraints while sweeping reports/nodes

puppet/lib/puppet/reports/puppetdb.rb
This commit improves the algorithm which tries to recognize that puppet run was started with --noop param. Originally, any noop resource event caused that the whole report was marked as noop. However, a noop puppet run would have all resource events in noop state. With this commit, all resource events need to be noop to mark the whole report as noop.
The current implementation is not able to recognize an unchanged noop puppet run since it doesn't contain any events. So, this improvement is just a workaround. To be able to recognize noop puppet runs properly, puppet needs to report in which mode was the run started. This problem is logged as PUP-6294.
=> (PE-15587) Set noop flag on a report to true only if all its resource events are noop

src/puppetlabs/puppetdb/middleware.clj
This commit only logs a warning when rejecting a request for a
ssl-client-cn when the ssl-client-cn is present. Prior to this patch
when using token auth in PE PuppetDB, this warning would be printed for
perfectly valid requests.
=> (maint) Only log warning for ssl-client-cn rejection when not nil

resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/pdb_routing.clj, src/puppetlabs/puppetdb/status.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/testutils/services.clj
These changes will allow our extensions in PE to have a separate status that includes information from PE core but can also include additional dependencies when determining whether or not PuppetDB is 'up'.
=> (PDB-2680) Refactor PuppetDBStatus service to a plain function

test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
When the CI infrastructure is running slow, these some tests can exceed
their timeouts. Bumping those to allow them more time to finish.
=> (MAINT) Bump testing timeouts to deal with slow infra

documentation/connect_puppet_apply.markdown, documentation/connect_puppet_master.markdown, documentation/install_from_packages.markdown, documentation/install_via_module.markdown, documentation/pdb_client_tools.markdown
We're retiring the doc at https://docs.puppet.com/guides/puppetlabs_package_repositories.html. Change these links to point to the versioned docs at https://docs.puppet.com/puppet/latest/reference/puppet_collections.html, and note that we're referring to Puppet Collections.
=> (doc) Update references to package repos.

documentation/api/query/curl.markdown
This commit adds some documentation for how to use RBAC tokens (PE only)
with PuppetDB.
=> (PDB-2762) Add documentation for token authentication

documentation/api/query/v4/fact-paths.markdown, src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/http/fact_names_test.clj
Expose depth as a queryable field for the /fact-paths endpoint. This will allow
the middleware to query fact-paths more efficiently by excluding structured
facts.
=> (PDB-2771) expose depth for fact-path querying

src/puppetlabs/puppetdb/scf/migrate.clj
This reverts us back to the exact table schema used in burnside by removing an
index on certnames that made certain console queries against /nodes slow.
=> (PDB-2789) drop index on certnames(latest_report_id)

src/puppetlabs/puppetdb/mq_listener.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/mq_listener_test.clj
This commit separates the thread listening to ActiveMQ and the threads
that are processing the message (and persisting the changes to
disk). The intent of this change is to factor the code in a way that
allows a new queuing system to be dropped in place of ActiveMQ. The code
as it is has a subtle bug relating to how JMS expects messages to be
acknowledged. When acknowledging a message, it acknowledges all
previously unacknowledged messages for that thread. This code consumes all
messages (from ActiveMQ's perspective) via a single thread. This means it's
possible for a slow message to be in-flight, and a faster/smaller
message that is processed after, to acknolwedge that slower message. If
that slower message were then to fail, we'd have problems as ActiveMQ
would already have marked the …
=> (PDB-2737) Split message consumers from processing

puppet/spec/unit/reports/puppetdb_spec.rb
Originally, the tests were trying to set noop flag directly on Puppet::Transaction::Report but that failed because the noop flag has only attr_reader.
Now, the puppet run mode (noop/enforcement) is simulated by setting Puppet[:noop].
=> (maint) Fix rspec tests for noop flag in puppetdb terminus

resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-304bebf8e5fc109ced84e8b086f9bcf8324f3d78.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-327147ee71a6e67db76112add34d49c674f97b4f.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-339914cdb0a7a9a7ca4c9c310ab96ba20649376f.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-9956b77aba1f29fe276978cd68d4c169f2e34d69.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-a454ec51cbadba8c31beb9c1d66e90e9482ff4a6.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-193c2a3ae8b277158dbb1073a35290b406c3c073.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-19fce4fd5281b1df9b42d58c808fecb2a783da3b.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-34ecfe5dcfebc9510d159d2ec010d6e1f9094fb1.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-b73c37f620703406b5666e7c919afff00c511f1e.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-bb3cea0e4f72a38fde935e93a9efca44e540ec3c.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-cfdc33f7bb68d2c25d3b3758f3dca50b851b96ea.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-02f72d7b1e2ded2074c4c3d6e2f415f6978d5932.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-05ce58a44a6441dc967559bf89fd82619068f72c.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-5ba2c61aeb5f3ed8722e45f9c2c7b53d606e402e.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-6eade546c696f0c045ec29f955bdb4d6a39a8291.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-9eeca12cedb235b2e8f616967bf1f46d3e1de812.json
- While developing, we often need to pull in various data into PuppetDB. So we use `puppetlabs.puppetdb.cli.benchmark` tool pretty extensively to achieve that.
- This PR allows us in basic setup fill in needed data to populate fields.
- I think that there should also be a case for `noop=>false, status=>failed`, but that kind of report is not included in this data set. I wanted to make this simple so not included in this PR. If this PR is ok, I would like to also include this case.
=> (maint) Intended catalog failed

documentation/_puppetdb_nav.html, documentation/api/query/v4/ast.markdown, documentation/api/query/v4/catalogs.markdown, documentation/api/query/v4/entities.markdown, documentation/api/query/v4/factsets.markdown, documentation/api/query/v4/producers.markdown, documentation/api/query/v4/reports.markdown, src/puppetlabs/puppetdb/http/handlers.clj, src/puppetlabs/puppetdb/http/query.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/query_eng.clj, test/puppetlabs/puppetdb/http/producers_test.clj
This commit adds a "producers" query endpoint and includes reports, catalogs,
and factsets as subquery endpoints.
=> (PDB-2782) Add "producers" as a queryable entity

src/puppetlabs/puppetdb/mq_listener.clj, test/puppetlabs/puppetdb/command_test.clj
Message retries will work differently once Stockpile is introduced to the codebase. Currently retried messages are enqueued with a delay. In the future, we'll schedule a delayed task to reprocess the message. This PR refactors what before was called our message handling middleware to a single function, parameterized three functions. A function to delay a message (for retry), one function to discard a message and a function to process the message. With Stockpile, we switch the delay function and maybe the discard function.
This PR should only introduce one behavior change from the existing code. It removes the exponential backoff that was in place. Now it sleeps 1 second for each retry. This change is temporary as setting a higher value (i.e. 60 seconds) causes our tests to fail without a …
=> (PDB-2732) Refactor message retry logic for Stockpile

documentation/api/command/v1/commands.markdown, documentation/api/query/v4/nodes.markdown, documentation/api/query/v4/reports.markdown, documentation/api/wire_format/report_format_v8.markdown, puppet/lib/puppet/reports/puppetdb.rb, puppet/spec/unit/reports/puppetdb_spec.rb, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/reports.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/examples/reports.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/http/reports_test.clj, test/puppetlabs/puppetdb/reports_test.clj
Thread the new "noop_pending" Puppet report property through PDB and expose
via /reports and /nodes (for the latest report).
=> (PDB-2753) add noop pending to reports and nodes

src/puppetlabs/puppetdb/cli/export.clj
Files/copy has been observed to be notably more efficient than io/copy.
=> (PDB-2852) export: write data via Files/copy

documentation/versioning_policy.markdown, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/export.clj, test/puppetlabs/puppetdb/acceptance/cli.clj, test/puppetlabs/puppetdb/admin_test.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/command_test.clj
*Replace hard-coded command versions with calls to the maximum supported command versions defined in command.clj.
*Edit command versioning policy to more closely match the query versioning policy.
=> (PDB-2783) Revisit command versioning

src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/config_test.clj
We only ever "need" the latest two catalogs in the console for the
resource-graph feature. This commit doesn't store extra data for users
who don't need it.
=> (PDB-2888) Set hisotrical-catalogs-limit default to 2

src/puppetlabs/puppetdb/threadpool.clj, test/puppetlabs/puppetdb/threadpool_test.clj
This commit adds code that allows data from an core.async input channel
to be processed on a bounded threadpool. When the threadpool reaches
it's max size, it blocks the calling thread on put. The threadpool is
shutdown once the input channel has been closed and in-flight work as
finished.
=> (PDB-2847) Add a gated threadpool, fed by channel

src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/config_test.clj
This commit changes PuppetDB to turn off historical catalogs by default.
=> (PDB-2888) Turn off historical-catalogs by default in Couch

src/puppetlabs/puppetdb/cli/services.clj, test/puppetlabs/puppetdb/cli/services_test.clj
Prior to this commit, the checkin for puppetdb would only be run on
start up. This commit updates that to use overtone/at-at's `every`
function to run that checkin on a defined interval. In this case, once
at start up, and then again every 24 hours after.
=> (PE-16739) Update FOSS PuppetDB check in to be on interval

acceptance/helper.rb
This should fix our s3 transfer so repos are available in acceptance tests.
=> (maint) fix package build host to unbreak our sed in s3 transfer

test/puppetlabs/puppetdb/cli/services_test.clj
so that expected proceeds actual.
=> (maint) Fix typo in update-checking test and reorder assertions

project.clj, src/puppetlabs/puppetdb/config.clj
A new tk-status is needed, but this brought along with it:
- prismatic schema
- trapperkeeper
- tk-jetty9
- apache httpcomponents
Also update our usage of an internal trapperkeeper API that changed
between 1.5.8 and 1.5.9.
=> (PE-14579) Update tk-status dependency, etc.

Gemfile
This commit locks the json_pure and activesupport gem versions in the
PuppetDB Gemfile to maintain Ruby 1.9.3 - 2.2.0 support
=> (maint) Fix support for Ruby 1.9.3 - 2.2.0

src/puppetlabs/puppetdb/query/edges.clj, src/puppetlabs/puppetdb/query/fact_contents.clj, test/puppetlabs/puppetdb/http/facts_test.clj
This corrects a bug where the fact-contents and edges endpoints would not allow
usage of functions.
=> (PDB-2843) add function support to fact-contents

acceptance/setup/pre_suite/40_install_deps.rb
An out of date nss can cause issues with openjdk. Ensure it's up to date on both the database and the master.
=> (maint) ensure nss is up to date

src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/query_eng_test.clj
This commit checks for subqueries under 'extract' nodes and throws an exception
with an informative error message if the subquery operator is not among the
acceptable 'select_<entity>' operators.
=> (PDB-2310) Add helpful error message for invalid subquery operators

ext/jenkins/lein-test.sh, ext/travisci/test.sh, test/puppetlabs/puppetdb/testutils/log.clj
If PDB_TEST_DUMP_LOG_ON_FAILURE is set to true, and the
clojure.test *report-counters* register any change in the error or
failure count while inside call-with-log-suppressed-unless-notable, dump
the log to *err*.
Set PDB_TEST_DUMP_LOG_ON_FAILURE=true for the Travis and Jenkins tests.
=> (PDB-2890) Allow dumping pdb log on test failures

project.clj
This commit updates to lein-ezbake 0.4.3, which contains a fix for
a bug where EL sysv init script could create an empty pidfile before the
service was started.
=> (PDB-2910) Ezbake 0.4.3, empty pidfile fix

documentation/_puppetdb_nav.html, documentation/api/query/v4/ast.markdown, documentation/api/query/v4/inventory.markdown, documentation/api/query/v4/resources.markdown, locales/messages.pot, resources/puppetlabs/puppetdb/pql/pql-grammar-experimental.ebnf, src/puppetlabs/puppetdb/facts.clj, src/puppetlabs/puppetdb/honeysql.clj, src/puppetlabs/puppetdb/http/handlers.clj, src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/pql/transform.clj, src/puppetlabs/puppetdb/query/fact_contents.clj, src/puppetlabs/puppetdb/query/facts.clj, src/puppetlabs/puppetdb/query_eng.clj, src/puppetlabs/puppetdb/query_eng/engine.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/http/inventory_test.clj, test/puppetlabs/puppetdb/http/resources_test.clj, test/puppetlabs/puppetdb/pql/parser_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/scf/storage_utils_test.clj, test/puppetlabs/puppetdb/testutils/resources.clj
Add an inventory endpoint of fact name=>value pairs, along with capability to
query it and the resources parameters column with "dotted syntax" like
[= parameters.foo bar]. Also add support in PQL. This does not include
projection, regex matching of path elements, or array indexing of path
elements.
=> (PDB-2632) add inventory endpoint and support for dotted fields

puppet/spec/unit/reports/puppetdb_spec.rb
The test was presuming that a report could be modified like an array, but it
really needed the property method. This property is an attr_reader, stubbing
gets around this access problem though.
=> (maint) Switch to stubbing correct object method for corrective_change test

test/puppetlabs/puppetdb/testutils/db.clj
Running individual tests at the REPL will result in a
NullPointerException due to an issue in our with-test-db test
function. This commit fixes that so the tests can be ran from the
command line or from the REPL.
=> (PDB-2934) Fix issue with running tests at the REPL

src/puppetlabs/puppetdb/http/server.clj, src/puppetlabs/puppetdb/middleware.clj, test/puppetlabs/puppetdb/http/nodes_test.clj, test/puppetlabs/puppetdb/middleware_test.clj, test/puppetlabs/puppetdb/testutils/http.clj
This commit adds a check for content type in POST requests and throws
an exception if the content type is "application/x-www-form-urlencoded",
which is the default if no content type is specified, instead of returning
all results from the endpoint.
=> (PDB-2851) Reject POST query requests that are missing content-type

puppet/spec/unit/util/puppetdb/config_spec.rb
Ruby 2.2 as changed URI validation to allow underscores, which we were using in
tests as example invalid URLs. This just changes those tests to use # instead.
=> (PDB-2952) fix failing spec tests for ruby 2.2

src/puppetlabs/puppetdb/query_eng/engine.clj, test/puppetlabs/puppetdb/query_eng_test.clj
This commit adds 'or' and 'and' to the list of operators to ignore when checking
for invalid subqueries in nodes of the form ["extract" column [subquery-name _]].
=> (PDB-2946) single-arity usage of or/and broken in subqueries

ext/travisci/test.sh
Dumping the log on failure will produce a log file that is too big for travis
to handle, causing the job to get aborted.
=> (maint) don't dump test log on failure

ext/jenkins/packaging.sh
This commit updates the s3 command used to sync out apt repos to s3.
This change is meant to help enable the switchover from reprepro to
aptly for apt repo creation. In order to maintain the current expected
repo format with aptly, we are forced to create symlinks. However, since
s3 does not support symlinks, we need to ensure they are resolved before
we attempt to send those files to s3. The addition of this flag handles
that.
=> (maint) Have s3 resolve symlinks for apt repo sync

documentation/api/query/v4/environments.markdown, documentation/api/query/v4/nodes.markdown, src/puppetlabs/puppetdb/query_eng/engine.clj
This adds relationships from environment and node entities to inventory to
behave in a similar way to factsets. This allows implicit subqueries to work.
Without this patch you cannot do queries of this nature:
nodes { inventory { facts.operatingsystem = "CentOS" } }
Instead you are forced to use explicit querying:
nodes { certname in inventory[certname] { facts.operatingsystem = "CentOS" } }
Which is a lot more verbose and should be unnecessary.
=> (PDB-2962) Missing implicit inventory relationships

documentation/_puppetdb_nav.html, documentation/api/query/examples-pql.markdown, documentation/api/query/tutorial-pql.markdown, documentation/api/query/v4/pql.markdown
This patch adds a new PQL examples page with a list examples containing:
* a title
* description
* pql
* output
It also makes the PQL documentation a top-level element in navigation so it
and other related articles can be found easier.
The tutorial and references pages also have links to each other now so they
are easier to find.
=> (ORCH-1491) Better PQL examples and docs structure

src/puppetlabs/puppetdb/scf/storage.clj
There's no reason to, and the attempt causes PDB to wander off into the
long (eventually fruitless) retry process.
We believe that's also what was causing one of the convergence-test
failures.  i.e. if the database connection was slow enough, two syncs
that were scheduled one right after the other could enqueue the same
command twice (in that case the addition of a report), and then the test
would fail (time out) because the second addition never showed up as a
completed command since it was repeatedly rejected as a duplicate.
=> (PDB-2939) Don't try to store same report twice

.travis.yml, ext/travisci/test.sh, test/puppetlabs/puppetdb/command_test.clj
Fix the concurrent-fact-updates test to work with newer versions of
postgres (9.4.9 at least).
It appears that postgres has changed the way it handles the relevant
transaction, rejecting it for its environments constraint violation
instead of the serialization error.
Establish the relevant "DEV" environment at the start of the test so
that it's no longer part of the transaction, and then change the code to
examine the entire exception chain instead of just the first item
because the serialization exception is no longer at the front.
=> (PDB-2988) Fix pg 9.4.9 concurrent-fact-updates

src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/scf/migrate.clj
By default, the jdbc driver will set a fetchsize of 0 for prepared statements,
which causes all results to be held in memory. Changing the with-resultset-seq
call to with-query-results-cursor causes us to use a fetchsize of 500,
eliminating the memory problem.
=> (PDB-2997) Fix upgrade OOM related to migrate-through-application

dev-resources/Makefile.i18n, project.clj
This version fixes a performance issue with calls to the translate
function (via trs/tru). The Makefile has also been updated to reflect
the changes for the release.
=> (PDB-2985) Bump to 0.4.2 of clj-i18n

documentation/pdb_client_tools.markdown
This commit adds documentation for the CLI's configuration options
rather than just linking to the man pages.
=> (maint) Add documentation for the PuppetDB CLI configuration options

documentation/api/query/curl.markdown
This commit adds a note about configuring token auth for Couch users,
because we forgot to manage the client-auth setting for Jetty in the
Couch PE module.
=> (maint) Add note about configuring token auth for Couch users

project.clj, src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/command/dlo.clj, src/puppetlabs/puppetdb/mq_listener.clj, src/puppetlabs/puppetdb/queue.clj, test/puppetlabs/puppetdb/command/dlo_test.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/http/command_test.clj, test/puppetlabs/puppetdb/queue_test.clj, test/puppetlabs/puppetdb/testutils/queue.clj
This commit opens the stockpile queue, then loads the command channel
with existing entries in a background thread. This allows the startup
process to continue while the commands are being re-enqueued in memory.
=> (PDB-3031) Separate stockpile open and load

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/cli/shovel.clj, src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/mq_listener.clj, test/puppetlabs/puppetdb/cli/shovel_test.clj, test/puppetlabs/puppetdb/http/command_test.clj, test/puppetlabs/puppetdb/testutils.clj, test/puppetlabs/puppetdb/testutils/log.clj, test/puppetlabs/puppetdb/threadpool_test.clj
This commit adds the ability to upgrade from an existing ActiveMQ queue to Stockpile. This happens automatically on startup. If an ActiveMQ queue is present, it moves all of the messages out of the queue and into Stockpile. It leaves a "lock" file in place so that there's no need to initialize the ActiveMQ broker and connections upon restart.
@ajroetker did most of this work, I took what he had and adapted it to how stockpile was integrated into PDB
=> (PDB-2734) Add stockpile upgrade code

ext/build_defaults.yaml, test-resources/com/puppetlabs/puppetdb/test/cli/export/big-catalog.json
We are in the process of introducing a new signing key. This commit
updates PDB to switch from the old key to the new one
=> (maint) Update PDB to use new signing key

documentation/api/query/v4/aggregate-event-counts.markdown, documentation/api/query/v4/event-counts.markdown, src/puppetlabs/puppetdb/query.clj, src/puppetlabs/puppetdb/query/aggregate_event_counts.clj, src/puppetlabs/puppetdb/query/event_counts.clj, test/puppetlabs/puppetdb/http/aggregate_event_counts_test.clj, test/puppetlabs/puppetdb/http/event_counts_test.clj, test/puppetlabs/puppetdb/testutils/reports.clj
This PR subdivides `successes` and `noops` counts into intentional and corrective parts in `event-counts` and `aggregate-event-counts` endpoints for PE. Events are mapped to the corresponding counts based on value of `corrective_change` flag.
The response formats for FOSS are not changed.
=> (PDB-3047) Corrective change counts

acceptance/config/ec2-west-debian7-64mda-64a.cfg, acceptance/config/ec2-west-debian7-64mda-fallback.cfg, acceptance/config/ec2-west-debian8-64mda-64a.cfg, acceptance/config/ec2-west-el5-64mda-el5-64a.cfg, acceptance/config/ec2-west-el6-64mda-el5-64a-ubuntu1204-64a.cfg, acceptance/config/ec2-west-el6-64mda-el6-64a.cfg, acceptance/config/ec2-west-el6-64mda-perf.cfg, acceptance/config/ec2-west-el6-64mda.cfg, acceptance/config/ec2-west-el7-64mda-el7-64a.cfg, acceptance/config/ec2-west-f20-64mda-f20-64a.cfg, acceptance/config/ec2-west-ubuntu1204-64mda-64a.cfg, acceptance/config/ec2-west-ubuntu1404-64mda-64a.cfg, acceptance/config/ec2-west-ubuntu1510-64mda-64a.cfg, acceptance/config/ec2-west-ubuntu1604-64mda-64a.cfg
This switches us to use operations special subnet/vpc setup, so we
can access various mirrors from our tests out in EC2.
=> (OPS-10270) Switch PuppetDB vpc/subnet ids to use new tunnel

acceptance/setup/pre_suite/15_setup_repos.rb
This seems likely to be the right thing to do in general, and may
address recent keyring install failures (missing package).
=> (maint) pre_suite: update before keyring install

acceptance/setup/pre_suite/40_install_deps.rb
On the Debian 8 hosts, "gem install i18n" is failing like this:
ERROR:  Loading command: install (LoadError)
/usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference - /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so
ERROR:  While executing gem ... (NoMethodError)
undefined method `invoke_with_build_args' for nil:NilClass
Fix it by upgrading to the latest available openssl.
=> (PDB-3056) pre_suite: fix gem install i18n

src/puppetlabs/puppetdb/amq_migration.clj, src/puppetlabs/puppetdb/cheshire.clj, src/puppetlabs/puppetdb/command.clj
This function is useful in extensions, so this commit moves it from
amq-migration to cheshire. This commit also fixes up an issue with the
maps being enqueued in the response-mult, causing the extensions tests
to break.
=> (PDB-3026) Move the clj -> json byte stream function

.travis.yml
We already require it, but haven't had to specify it because it's the
default for puppetlabs/puppetdb on travis ("default for repositories
enabled before 2015").
Without this explicit setting, anyone who tries to set up their own
travis build will end up defaulting to "sudo: false", which won't work.
=> (maint) .travis.yml: require sudo explicitly

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/command/constants.clj, src/puppetlabs/puppetdb/command/dlo.clj, src/puppetlabs/puppetdb/constants.clj, src/puppetlabs/puppetdb/export.clj, src/puppetlabs/puppetdb/queue.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/acceptance/cli.clj, test/puppetlabs/puppetdb/admin_test.clj, test/puppetlabs/puppetdb/cli/import_export_roundtrip_test.clj, test/puppetlabs/puppetdb/command/dlo_test.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/queue_test.clj, test/puppetlabs/puppetdb/utils_test.clj
Change `puppetdb.queue/metadata-str` to replace illegal filename
characters and underscores in the certname it's given, truncate the
certname if its length would cause the metadata string to exceed 255
characters, and add the SHA1 hash of the original certname if the
certname in the metadata string differs in any way (via character
replacement or truncation) from the original certname.
Change the *-filename functions in `puppetlabs.command.dlo` to truncate
just the metadata portions of the filenames if they would cause the
filenames to exceed 255 bytes in length. Truncating the metadata portion
is acceptable since all these filenames contain stockpile IDs, which
ensures they'll be unique.
See the individual commits & messages for more details.
=> (PDB-3039) Safely embed certnames in queue & DLO filenames

src/puppetlabs/puppetdb/query.clj, test/puppetlabs/puppetdb/query/events_test.clj, test/puppetlabs/puppetdb/testutils/events.clj
There is a need to query `events` by `corrective_change` flag in PE. This PR enables that.
Currently, there is no INDEX in `resource_events` for the `corrective_change` flag.  Since we always query `events` by `status` and `corrective_change` fields at the same time `resource_events_status_idx` seems to be sufficient. However, a combined index `CREATE INDEX xyz_idx ON resource_events (status, corrective_change)` would be ideal. @senior , @wkalt What is your policy concerning new INDEXes?
=> (PDB-3073) Add support for querying resource events by corrective_change flag

src/puppetlabs/puppetdb/command/dlo.clj, src/puppetlabs/puppetdb/queue.clj, test/puppetlabs/puppetdb/command/dlo_test.clj, test/puppetlabs/puppetdb/queue_test.clj
(**NB**: this commit depends on #2065)
Replace `puppetdb.queue/metadata-command-names` with a map called
`metadata-command->puppetdb-comand` that defines the mapping between
the command names that can appear in the queue metadata that forms the
message filenames and the command names used by the rest of PuppetDB.
The inverse mapping is dynamically constructed under the var
`puppetdb-command->metadata-command`.
Replace `puppetdb.queue/metadata-str` with `metadata-serializer`, which
takes a map from PuppetDB command names to the metadata command names
and returns a function with the same signature as `metadata-str`; viz.
taking all the queue metadata components and returning a metadata
string. The only differences are that the returned function looks up the
command name it's given in the …
=> (PDB-2982) Shorter Command Names in Queue Metadata

Gemfile
docker-api 1.32.0 has introduced a dependency on ruby 2.0. This pins us to
1.31.0.
=> (maint) pin docker-api for ruby breakage

config.sample.ini, documentation/configure.markdown, resources/ext/config/conf.d/config.ini, src/puppetlabs/puppetdb/config.clj, test/puppetlabs/puppetdb/config_test.clj
This commit includes warnings and deprecation notes for the now obsolete
ActiveMQ config items. The config params no longer apply to PuppetDB
when running with Stockpile.
=> (PDB-2948) Deprecate ActiveMQ Config

project.clj, resources/ext/config/logback.xml, resources/ext/config/request-logging.xml
This PR bumps the Trapperkeeper and lein-ezbake dependencies up to 1.5.1 and 1.0.0, respectively, in order for PuppetDB packages to be built with support for service reload functionality (built on top of SIGHUP).  This PR also includes some logback configuration changes to support moving to logback file-size based log rotation and disabling the logic in ezbake that previously enabled log rotation via logrotate.
=> (PDB-3077) Add service reload and logback size-based rotation

documentation/configure.markdown, resources/ext/config/conf.d/config.ini, src/puppetlabs/puppetdb/config.clj
Change the default value for the concurrent writes configuration setting
from 100 to the minimum of half the CPU coresb (rounded up) and 4.
Add documentation for the command processing `concurrent-writes`
configuration setting to the configuration documentation file, and add
some commented-out lines to the default `config.ini` file that set its
value and explain what it's for.
=> (PDB-3060) `concurrent-writes` setting

documentation/maintain_and_tune.markdown
This commit changes a paragraph in the documentation which had referred
to the configuration of logrotate for logging to instead reference the
use of Logback's own file rotation.
=> (PDB-3077) Update doc reference from logrotate to Logback for rotation

src/puppetlabs/puppetdb/reports.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/examples/reports.clj, test/puppetlabs/puppetdb/reports_test.clj
This was a schema error introduced with the corrective_change feature.
The main operational impact was that users upgrading from 3.2.x to 4.2
with enqueued data would have their commands fail on restart.
This commit corrects the schema to accept v6 reports, and also does a
bit of test cleanup so we won't have this problem again. Specifically it
consolidates synthesis of old command versions under the example reports
namespace and causes test compilation to fail if the synthetic reports
are invalid.
=> (PDB-3058) version 6 reports incorrectly rejected

puppet/lib/puppet/util/puppetdb/config.rb
It's relatively common for users to miss the retirement of server/port
when upgrading from versions of PDB that supported it. This has the
effect of defaulting their server/port to puppetdb:8081, producing agent
run failures that log a puppetdb hostname different from what they
believe they've configured.
This patch logs warnings when server and port are detected in the config
file. I think it would be preferable to remove the defaulting behavior
and throw an error when server_urls is not present, but I don't have a
sense of whether anyone relies on the defaulting today.
=> (PDB-3071) Log a warning if retired server/port config items are in use.

project.clj, resources/ext/cli/config-migration, resources/ext/cli/ssl-setup.erb
This commit upgrades the lein-ezbake dependency from 1.0.0 to 1.1.2.
This is needed to fix problems with the PuppetDB service not starting
properly on Debian-based platforms due to a permissions issue around the
use of the service rundir.  The rundir problem was previously introduced
by the bump to lein-ezbake 1.0.0.
In the newer ezbake release, subcommands run with a umask of 027.  This
commit includes a couple of explicit chmod calls in the migration and
ssl-setup subcommands which ensure that any modified config files are
still world-readable.  World-readability is required for these files in
order for the puppetdb service, running as user puppetdb, to be able to
still read the config files, which are owned by root:root.
=> (PDB-3077) Upgrade to lein-ezbake 1.1.2, fix Debian startup problems

src/puppetlabs/puppetdb/scf/migrate.clj
The main purpose of this index is to help `resource_events` queries with `corrective_change = true` - that is the case of `PE Events` queries.
It's expected that minority of events are corrective, so the partial index wouldn't consume a lot of disk space and improve performance.
=> (PDB-3092) Create a partial index in resource_events for querying by corrective events

Gemfile
Previously, PuppetDB's Gemfile was picking up beaker version 2.43.0.
This was transitively picking up hocon version 0.9.5.  puppetserver
recently added some variable interpolation to the puppetserver.conf
file.  Some fixes in hocon 1.0 and later are needed in order for the
interpolation to be handled correctly.
This commit bumps the beaker dependency in the Gemfile to ~> 2.50.0,
which transitively will cause test jobs to pick up a newer hocon gem
dependency, >= 1.0.
=> (MAINT) Bump beaker to 2.50.0

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj
(**NB:** these commits depend on #2077 and should be merged after it.)
Change the message identifier in the command namespace's log/info
invocations to be a concatenation of the stockpile ID and the timestamp
the message was received at, in order to guarantee uniqueness across
restarts (as the stockpile ID may reset).
Change the overall structure of the logged message in the same form so
it's clear *what* is being logged.
When a command is placed on the queue, log its ID, command name, and
certname at the debug level, similarly to the logging after the command is
processed.
=> (PDB-3067) Improve command logging

src/puppetlabs/puppetdb/amq_migration.clj, src/puppetlabs/puppetdb/command.clj
Before beginning to transfer messages from activemq to stockpile, send
an "end-of-line" tracer command that when received later should indicate
the end of the queue.
In the unlikely (and unsupported) downgrade case, older versions of
puppetdb should just reject the sentinel as garbage.
=> (PDB-3066) Detect queue upgrade end via sentinel

project.clj
This commit bumps the lein-ezbake plugin dependency from 1.1.2
to 1.1.3.  This change re-adds the XXOutOfMemoryError java
command line arg which had unintentionally been dropped as part
of the ezbake bump for service reload functionality done for
PDB-3077.
=> (PDB-3077) Bump lein-ezbake dep to 1.1.3

src/puppetlabs/puppetdb/scf/hash.clj
Because the memoization is based on count, not overall pool size, it
could consume arbitrary RAM, and was responsible for overruning a 32GB
JVM in the field.
cf. (PDB-3059)
=> (PDB-3065) Stop memoizing resource identity hashes

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/command.clj
This feature has issues in an HA setting. To fix it, we need to use the
producer timestamp to determine which catalog/factset is "newer" before
deciding that we want to discard one of the catalogs/factsets. Disabling
the feature with this commit to be revisited after an initial release.
=> (PDB-3101) Disable certname "bash in place"

src/puppetlabs/puppetdb/command.clj, src/puppetlabs/puppetdb/middleware.clj
Add three new metrics to the mq metrics registry:
* `size`: a histogram of the size of received commands as reported by
the HTTP request's Content-Length header.
* `awaiting-retry`: a count of the number of commands that are
currently waiting to be re-inserted into the queue.
* `queue-time`: a histogram of the time in seconds that messages
waited in the queue before being processed.
=> (PDB-3082) Add new queue metrics

resources/puppetlabs/puppetdb/benchmark/samples/catalogs/host-0.json, resources/puppetlabs/puppetdb/benchmark/samples/catalogs/host-1.json, resources/puppetlabs/puppetdb/benchmark/samples/catalogs/host-2.json, resources/puppetlabs/puppetdb/benchmark/samples/facts/pg1.vm.json, resources/puppetlabs/puppetdb/benchmark/samples/facts/pg2.vm.json, resources/puppetlabs/puppetdb/benchmark/samples/facts/puppetdb1.vm.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-304bebf8e5fc109ced84e8b086f9bcf8324f3d78.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-327147ee71a6e67db76112add34d49c674f97b4f.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-339914cdb0a7a9a7ca4c9c310ab96ba20649376f.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-9956b77aba1f29fe276978cd68d4c169f2e34d69.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg1.vm-a454ec51cbadba8c31beb9c1d66e90e9482ff4a6.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-193c2a3ae8b277158dbb1073a35290b406c3c073.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-19fce4fd5281b1df9b42d58c808fecb2a783da3b.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-34ecfe5dcfebc9510d159d2ec010d6e1f9094fb1.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-b73c37f620703406b5666e7c919afff00c511f1e.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-bb3cea0e4f72a38fde935e93a9efca44e540ec3c.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/pg2.vm-cfdc33f7bb68d2c25d3b3758f3dca50b851b96ea.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-02f72d7b1e2ded2074c4c3d6e2f415f6978d5932.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-05ce58a44a6441dc967559bf89fd82619068f72c.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-5ba2c61aeb5f3ed8722e45f9c2c7b53d606e402e.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-6eade546c696f0c045ec29f955bdb4d6a39a8291.json, resources/puppetlabs/puppetdb/benchmark/samples/reports/puppetdb1.vm-9eeca12cedb235b2e8f616967bf1f46d3e1de812.json, src/puppetlabs/puppetdb/cli/benchmark.clj
The sample data included with PuppetDB that is used whenever you invoke
the benchmark tool without a dataset had become stale. Unchanged
resources for reports, producer, catalog_uuid and code_id are recent
additions that were missing from the sample data (and from the
randomization that benchmark does). This commit adds this new data.
=> (PDB-2810) Update benchmark sample data

test/puppetlabs/puppetdb/admin_clean_test.clj
Wait for 120s instead of 10s to hopefully accommodate surprising CI
behavior.
=> (PDB-3151) admin-clean-competition: inc deref wait

test/puppetlabs/puppetdb/testutils/services.clj
This specifically removes the fields from our "call-with-pdb-instance"
tests which leads test output like:
The [database] classname setting has been retired and will be ignored.
The [database] subprotocol setting has been retired and will be ignored.
=> (MAINT) Remove classname/subprotocol from tests

project.clj
This release includes externalized i18n strings for error messages
=> (MAINT) Bump to stockpile 0.0.4

test/puppetlabs/puppetdb/amq_migration_test.clj, test/puppetlabs/puppetdb/command_test.clj, test/puppetlabs/puppetdb/testutils.clj
The issue is startup will proceed if all messages from AMQ have been
enqueued, but doesn't ensure that the messages have finished processing
before startup can proceed. CI server slowness exposed issues in our
tests that assumed if the service has started, the messages have been
processed.
=> (PDB-3175) Fix transient AMQ upgrade failures

documentation/api/query/curl.markdown
This commit clarifies the permissions required for accessing PuppetDB
data with a token.
=> (PDB-3188) Clarify the RBAC permissions required for PuppetDB data

documentation/pdb_support_guide.markdown, documentation/puppetdb-faq.markdown
Update the FAQ to remove dead links to the old catalog duplication page.
Fold some of the information from that duplication page into the support
guide, and link to that instead.
=> (maint) update support guide and faq

project.clj, src/puppetlabs/puppetdb/jdbc.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/scf/storage.clj, src/puppetlabs/puppetdb/scf/storage_utils.clj, test/puppetlabs/puppetdb/jdbc_test.clj, test/puppetlabs/puppetdb/query/population_test.clj, test/puppetlabs/puppetdb/scf/migrate_test.clj, test/puppetlabs/puppetdb/scf/storage_test.clj, test/puppetlabs/puppetdb/testutils/db.clj, test/puppetlabs/puppetdb/testutils/resources.clj
Update PuppetDB's usage of clojure.java.jdbc to the most recent non-alpha release, changing the shadow JDBC API implementation in `puppetdb.jdbc` accordingly. The `puppetdb.jdbc` API didn't change in any significant way, though some unused functionality (namely transaction booleans) was removed. See the individual commit messages for more details.
=> (PDB-2909) Update clojure.java.jdbc usage

documentation/_puppetdb_nav.html
We just did this for the newest versions of our other docs, because nested list elements in HTML are the illegible worst. This way you can easily see the tree structure without having to go crosseyed looking for that last missing `</ul>`.
=> (docs) Convert nav sidebar to Markdown

locales/messages.pot
The i18n version was updated in PuppetDB which had some useful changes
to the makefile such as removing line numbers from the messages.pot.
This commit checks in the changes to the messages.pot file.
=> (maint) Checkin changes to the messages.pot file

src/puppetlabs/puppetdb/cli/services.clj, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/core.clj, src/puppetlabs/puppetdb/main.clj, src/puppetlabs/puppetdb/scf/migrate.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/testutils/db.clj
While we may still want to pursue a more coherent exit strategy
eventually (PDB-2053), this hopes to make it less likely that we'll lose
output (diagnostic or otherwise) when we quit via System/exit.
The underlying issue is that the JVM does not necessarily flush stdout
or stderr during a System/exit.
=> (PDB-3191) Attempt to flush output before exit

documentation/maintain_and_tune.markdown, project.clj, resources/ext/cli/config-migration, resources/ext/cli/ssl-setup.erb, resources/ext/config/logback.xml, resources/ext/config/request-logging.xml
This PR backports changes done originally for the PuppetDB 4.2.4 release for:
1) Adding a 'reload' action (via ezbake) that the service framework can use to
HUP the puppetdb service.
2) Add file-size based log rotation to the logback configuration.
This PR includes cherry-picks of commits from the following PRs that were
previously merged for the 4.2.4 release: #2087, #2091, #2097, #2098, and
#2102.
=> (PDB-3207) Backport ezbake reload and logback file-sized based rotation

src/puppetlabs/puppetdb/query_eng/engine.clj
Prior to this commit, the where clause operated on the fact_values
table which is a giant table compared to the value_types table.
After this comit, the where clause operates on the value_types
table.  The <> 5 filter forces a seq_scan of the table so doing
that on a table with 6 rows is better than doing it on a table with
100K rows.  Also, filtering on the smaller table first improves the
row estimates in the rest of the query as well.
=> Change where clause on fact nodes to operate on smaller table

.travis.yml, acceptance/helper.rb, locales/messages.pot, project.clj, resources/puppetlabs/puppetdb/bootstrap.cfg, src/puppetlabs/puppetdb/config.clj, src/puppetlabs/puppetdb/meta/version.clj, src/puppetlabs/puppetdb/utils.clj, test/puppetlabs/puppetdb/cli/benchmark_test.clj, test/puppetlabs/puppetdb/config_test.clj, test/puppetlabs/puppetdb/testutils/services.clj
This switches us over to use clj-parent for managed dependencies.
Edit (AJ): And updates all the dependencies we're using in the process.
=> (maint) Start using clj-parent

acceptance/setup/pre_suite/40_install_deps.rb
It looks like Ubuntu 16.10 may no longer have "python" available by
default, so make sure it's explicitly installed on Debian derivatives in
the pre-suite.
=> (PDB-3234) Explicitly install python 2 on debs

project.clj
This includes a new version of trapperkeeper-metrics that fixes a bug
affecting PuppetDB. Specifically when requesting many metrics via
POST, a stream closed exception would occur. Bumping to 0.3.0 of
clj-parent will fix that.
=> (PDB-3209) Bump clj-parent to 0.3.0

src/puppetlabs/puppetdb/scf/migrate.clj
This commit drops the resource_events_resource_type_idx index
because the primary column duplicates the
resource_events_resource_timestamp index and as such we see that
the resource_type_idx is never used in practice.
=> (PDB-3220) Drop resource_events_resource_type_idx

test/puppetlabs/puppetdb/testutils/services.clj
This commit bumps the testutils sync-command-post to 20sec aligning it
with the 4.x branches of PuppetDB, which should avoid some errors caused
by Jenkins testing performance.
This commit also changes the sync-command-post to not use ex-info and
throw a formated string error instead so that lein test will format the
actual error response instead of hiding it.
=> (PDB-3247) Bump timeout in testutils sync-command-post to 20sec

test/puppetlabs/puppetdb/testutils/log.clj
The 'with-log-suppressed-unless-notable' macro passes it's predicates
log event objects, NOT the Clojure map versions created by the
event->map function. The predicates were written to expect the map
version. This resulted in ALL log messages being filtered out. This
commit makes that conversion in the predicates to ensure we don't
lose related log messages in tests.
=> (PDB-3240) Convert log event to map for logging predicates

test/puppetlabs/puppetdb/amq_migration_test.clj, test/puppetlabs/puppetdb/command_test.clj
This sometimes times out when running on shared test infrastructure; attempt to
work around this by increasing the timeout.
=> (PDB-3169) Increase timeout in command test
