project.clj

This commit upgrades the clj-parent dependency from 0.3.0 to 0.3.2 in
order to pick up a fix from trapperkeeper-status 0.7.1 where gc/cpu
metric collection could corrupt the status endpoint.

(MAINT) Upgrade to clj-parent 0.3.2

---

documentation/index.markdown

Add a note to the docs marking 2.3.x end of life and encouraging users
to upgrade.

(PDB-3271) Mark 2.3.x end of life

---

test/puppetlabs/puppetdb/jdbc_test.clj

Previously, the max connections jdbc pool-construction tests did not
close the connection pool data source before falling out of scope.
Depending upon timing, this could cause the tests to fail on
attempting to drop temp databases which are still busy being used
by the connection pool.
This commit wraps usage of the data source in each of the max
connections tests with `with-open` calls, allowing the connection pool
to be closed off before any calls to drop the temporary databases occur
(and, therefore, for the tests to complete successfully).

(MAINT) Close datasource in max connection jdbc pool tests

---

project.clj

This bump is needed to use the new CI based i18n message generation infrastructure.

(PDB-3255) Bump to clj-i18n 0.6.0

---

src/puppetlabs/puppetdb/scf/migrate.clj

Prior to this commit, there was no index on latest_report_id.
In PDB-2789, it was thought that this index caused performance
issues but this was potentially a red-herring.
After this commit, we create a unique index on latest_report_id. 
The index is absolutely necessary for deleting reports as the
reports table has a constraint on latest_report_id and without this
index it scans the whole certnames table once for every row it
deletes from reports.  For a 100,000 rows this index causes
deleting from reports to go from 3-4 mins to 3-4 seconds.

(PDB-3053) Create unique index on certnames.latest_report_id

---

resources/public/dashboard/charts.js
resources/public/dashboard/index.html
src/puppetlabs/puppetdb/dashboard.clj
src/puppetlabs/puppetdb/pdb_routing.clj
test/puppetlabs/puppetdb/dashboard_test.clj

Rework the dashboard to get the list of meters to display in a request to the
server, rather than hardcoding them in javascript. This has several benefits:
- All metrics can be returned in a single response, instead of having to poll
each metric individually
- The meter descriptions can be localized
- The data can be overriden in PE, to allow new meters to be added there for
PE-only functionality.

(PDB-2524) Data-driven dashboard

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/lib/puppet/indirector/facts/puppetdb.rb
puppet/lib/puppet/indirector/node/puppetdb.rb
puppet/lib/puppet/reports/puppetdb.rb
puppet/lib/puppet/util/puppetdb.rb
puppet/lib/puppet/util/puppetdb/command.rb
puppet/spec/spec_helper.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
puppet/spec/unit/indirector/facts/puppetdb_spec.rb
puppet/spec/unit/indirector/node/puppetdb_spec.rb
puppet/spec/unit/reports/puppetdb_spec.rb
puppet/spec/unit/util/puppetdb/command_spec.rb
puppet/spec/unit/util/puppetdb_spec.rb
src/puppetlabs/puppetdb/amq_migration.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/client.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/command/dlo.clj
src/puppetlabs/puppetdb/http/command.clj
src/puppetlabs/puppetdb/import.clj
src/puppetlabs/puppetdb/queue.clj
src/puppetlabs/puppetdb/time.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/command/dlo_test.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/http/command_test.clj
test/puppetlabs/puppetdb/queue_test.clj
test/puppetlabs/puppetdb/testutils.clj
test/puppetlabs/puppetdb/testutils/queue.clj

This PR adds producer-timestamp to the command POST headers and threads it through the stack. The parameter is used in the "bash in place" code to determine which command is older. This also required modifying the terminus to include that parameter in the POST.
While working on this patch, I found it difficult to thread the new producer-timestamp value through the stack for enqueuing. There's also a commit in this set that refactors the enqueuing functions to pass a "command request" through the stack. That map gets created (and validated) by the service, which is then passed through the stack.
Note to reviewers, it will probably be easier to look at the commits individually.
~~This PR depends on https://github.com/puppetlabs/puppetdb/pull/2152, which needs to go in first.~~

(PDB-3108) Add producer-timestamp to the command header, enable "bash in place"

---

.gitignore
dev-resources/Makefile.i18n

Commit the changes introduced by 'lein i18n init', given the update to
puppetlabs/i18n 0.6.0.  This should stop automatically generating the
messages.pot locally.  Now changes to that file are managed/committed by
the CI infrastructure.

(PDB-3294) Makefile.i18n update to 0.6.0

---

puppet/lib/puppet/util/puppetdb/command.rb
puppet/spec/unit/util/puppetdb/command_spec.rb
src/puppetlabs/puppetdb/amq_migration.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/command/dlo.clj
src/puppetlabs/puppetdb/http/command.clj
src/puppetlabs/puppetdb/import.clj
src/puppetlabs/puppetdb/middleware.clj
src/puppetlabs/puppetdb/queue.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/command/dlo_test.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/http/command_test.clj
test/puppetlabs/puppetdb/middleware_test.clj
test/puppetlabs/puppetdb/queue_test.clj
test/puppetlabs/puppetdb/testutils.clj
test/puppetlabs/puppetdb/testutils/queue.clj

This commit adds support for gzip-compressing commands which the
PuppetDB terminus sends out.  When stockpile persists the commands to
disk, it stores the gzipped json bytes with a .json.gz file extension.
Command payloads are decompressed and parsed from JSON when processed
back out of the queue.
The terminus does not gzip-compress the command content itself.
Instead, to minimize memory usage somewhat and realize a bit better
performance, it passes through its intent for the implementation
upstream from the Puppet::Network::HttpPool.http_instance to perform
the gzip compression.  Corresponding work in Puppet Server and its
upstream clj-http-client library enables the payload to be compressed.

(PDB-2640) Add support for gzip-compressing commands via terminus

---

test/puppetlabs/puppetdb/testutils/services.clj

In extensions tests we often need to have multiple PuppetDBs and can't
rely on *base-url* to be correct. This commit parameterizes the URL
functions for the HTTP test client code to allow either the *base-url*
var or the base-url

(PDB-3304) Paramterize test URL functions with base-url

---

src/puppetlabs/puppetdb/scf/storage.clj

While this query was correct, it didn't use the index we have in place on this
column, making it very slow.

(PDB-3323) Make report exists query use index

---

src/puppetlabs/puppetdb/command.clj
test/puppetlabs/puppetdb/command_test.clj

New Relic's java agent likes to inject extra JMS headers; update our message
schema to allow for unexpected keys so this doesn't bring the world down.

(PDB-3107) Allow extra headers in commands

---

documentation/maintain_and_tune.markdown

The docs previously gave the impression that changing the cleartext
hosts setting was the preferred mechanism of access. This updates them
to recommend an ssh tunnel instead.

(maint) update the docs on dashboard access

---

documentation/api/query/v4/ast.markdown

* Without the extra newline the JSON isn't 
highlighted

(maint) Fix doc issue with `JSON` example

---

project.clj

Somehow we have two things that transitively pull in cljs-time; exclude it from
one.

(maint) Update excludes for newer puppetserver

---

.travis.yml

We can't due to clj-parent versionitis breaking dependency resolution in the dev
profile.

(maint) Don't test against puppetserver master for now

---

documentation/api/wire_format/facts_format_v5.markdown
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/facts.clj
src/puppetlabs/puppetdb/scf/hash.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/facts_test.clj
test/puppetlabs/puppetdb/scf/hash_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

This commit adds package inventory to facts storage. Package data is
hashed and will only create/update/delete when the agent submits
changes. Facts containing the same packages should be a noop after
computing the hash.

(PDB-3330) Add storage of package data

---

src/puppetlabs/puppetdb/scf/hash.clj
test/puppetlabs/puppetdb/scf/hash_test.clj

Before this commit, string values were converted ot JSON and the
results of that were hashed. We can just hash the string directly and
avoid the JSON roundtrip.

(PDB-3354) Hash strings directly

---

test/puppetlabs/puppetdb/scf/migrate_test.clj

This had previously made an assertion that was only applicable when trgm
was not installed. Correct it to expect the trgm index on fact_paths.

(maint) fix facts migration test

---

src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

In fact, there only a small number of array items in the current
database, yet we check nearly every value that comes back to see if it
might be an array that needs conversion.  Start stopping that.
Accordingly, don't attempt array conversion in call-with-query-rows, and
add a new call-with-array-converted-query-rows that preserves the old
behavior.  Continue to call the former in the fact related storage code,
but adjust everything else to use the latter to preserve existing
behavior.
As the original motivation, Wyatt noticed non-trivial cost for the
"isa?" test via coerce-to-array when processing facts.

(PDB-3297) Don't act as if facts might be arrays

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/query_eng_test.clj

Switch from using a select_nodes subquery for restrictions to active
nodes, to a dedicated CTE containing only inactive nodes. This approach
is faster and less sensitive to memory settings than the previous
approach, particularly on the prospective query for package inventory.

(PDB-3356) Use a CTE for inactive nodes

---

src/puppetlabs/puppetdb/queue.clj

The previous :stock/ reference wasn't the keyword we were looking for.

(PDB-3355) Refer to unable-to-commit via ::stock/

---

puppet/lib/puppet/indirector/facts/puppetdb.rb
puppet/spec/unit/indirector/facts/puppetdb_spec.rb
test/puppetlabs/puppetdb/integration/fixtures.clj
test/puppetlabs/puppetdb/integration/inventory/package_inventory.clj
test/puppetlabs/puppetdb/integration/reports.clj

This adds terminus support for that package inventory feature. When the
_puppet_inventory_1 fact is seen it is removed, reformatted to be in the tabular
format expected by puppetdb, and placed in a top-level 'package_inventory' key
in the facts command payload.

(PDB-3328) Munge package inventory facts in terminus

---

documentation/api/query/v4/ast.markdown
documentation/api/query/v4/catalogs.markdown
documentation/api/query/v4/edges.markdown
documentation/api/query/v4/events.markdown
documentation/api/query/v4/fact-contents.markdown
documentation/api/query/v4/facts.markdown
documentation/api/query/v4/factsets.markdown
documentation/api/query/v4/inventory.markdown
documentation/api/query/v4/nodes.markdown
documentation/api/query/v4/packages.markdown
documentation/api/query/v4/reports.markdown
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/query_eng_test.clj

Centralize definition of certname-based implicit relationships. This
will make us less likely to leave them out or create inconsistencies in
the future.

(maint) use a common set of certname-based implicit relations

---

src/puppetlabs/puppetdb/cli/export.clj

Since users don't necessarily have the client tool installed, link to
docs instead of pointing them to the man page.

(PDB-2849) correct deprecation warning for export tool

---

src/puppetlabs/puppetdb/query_eng/engine.clj

Only apply the CTE to non-subqueries.

(maint) don't duplicate CTE for inactive nodes

---

src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/http/index_test.clj

Previously paging options supplied in a query would cause paging options
supplied outside the query to be ignored.

(maint) allow paging options to be specified in two places

---

puppet/spec/unit/indirector/catalog/puppetdb_spec.rb

A recent patch to Puppet broke several of our spec tests. This corrects
the ones that are due to a changed error message. There are some other
failures that are due to what seems like a Puppet bug to me. I'll wait
to get confirmation before changing those ones.

(maint) fix spec test failures against puppet master

---

src/puppetlabs/puppetdb/command.clj

Change command processing logging to include elapsed ms. This will be
useful to support for correlating slow processing to specific nodes.

(PDB-3096) log elapsed time with command processing

---

locales/eo.po
project.clj

This commit updates the i18n scaffolding arounding PuppetDB to be in
line with the latest.

(PE-19944) Update clj-i18n to 0.8.0

---

src/puppetlabs/puppetdb/query/population.clj

When doing db queries for the population metrics, don't wait for the connection
to time out every time. Instead, fail fast if the connection failed less than 5
seconds ago. This improves the performance of the dashboard data endpoint when
the database is down, as it reduces the number of times it has to wait for
timeouts to occur.

(PDB-3312) Back off population metric db connection on failure

---

documentation/api/admin/v1/cmd.markdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/admin_clean_test.clj

Package GC was included in the 'other' cleanup step. As it could be somewhat
heavy, this moves it out to a separate "gc_packages" step that can be
explicitly triggered and monitored.

(PDB-3384) Move package gc to a top-level cleanup step

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

I tried the purge-nodes query on our big dataset: it took ~2.5s to purge 800 nodes (1%) and ~22 s to purge 8k (10%). Subquery vs. CTE form makes no difference in this case. 
I also tried a relational-ier "delete using" version of the query, but I got the same query plan (and perf) as the subquery.

(PDB-3385) Clean up certname_packages when deleting nodes

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
test/puppetlabs/puppetdb/integration/sensitive_params.clj

A resource parameter marked Sensitive()
notify {'hi':  message => Sensitive('there')}
will show up in the terminus
like this:
input = {...
'environment'=>'production',
'resources'=>
[...
{'type'=>'Notify',
'title'=>'hi',
'tags'=>Puppet::Util::TagSet.new(['notify', 'hi', 'class']),
'file'=> 'site.pp',
'line'=>1,
'exported'=>false,
'parameters'=>{:message=>'there'},
'sensitive_parameters'=>[:message]}],
'edges'=>
[{'source'=>'Stage[main]', 'target'=>'Class[Settings]'},
{'source'=>'Stage[main]', 'target'=>'Class[main]'},
{'source'=>'Class[main]', 'target'=>'Notify[hi]'}],
'classes'=>['settings']}
Remove any sensitive values from 'parameters', and remove
'sensitive_parameters' before sending data to PuppetDB.
Aside from the fact that we don't want senstitive parameters to be
stored in (or …

(PDB-3322) Redact sensitive parameters in terminus

---

src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage_utils.clj
test/puppetlabs/puppetdb/http/resources_test.clj
test/puppetlabs/puppetdb/testutils/resources.clj

Corrects an issue where resource parameters specified via dot notation
could not be queried via regex.

(PDB-3285) fix regex queries on nested resource params

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

This commit adds the ability to purge all packages for a given
node. If a node previously had packages stored and either the packages
list is gone (i.e. package support is disabled) or null/empty, all
packages associated to that node with be disassociated from the node.

(PDB-3394) Add support for package purge

---

project.clj
test/puppetlabs/puppetdb/integration/puppetserver_metrics.clj

Add integration test that the http client metrics specified in the PuppetDB
termini show up in the Puppet Server master status endpoint.
This commit also bumps the Puppet Server version to a `voom` release based off
current master of Puppet Server, which will be what eventually goes into
Puppet Server 5.

(SERVER-1745) Add integration test for Puppet Server metrics

---

documentation/configure.markdown
documentation/install_from_packages.markdown

This commit adds some references to PG docs on setup. It also
encourages users to install via the module on the package install page
along with letting them know about the module in the database
configuration section.

(PDB-3426) Add PG references and encourage module install

---

documentation/CONTRIBUTING.md

Switch from:
https://github.com/puppetlabs/puppetdb/blob/master/documentation/configure.html#using-postgresql
to:
https://github.com/puppetlabs/puppetdb/blob/master/documentation/configure.markdown#using-postgresql

fix configure_postgres link

---

test/puppetlabs/puppetdb/generative/submit_command.clj

The database can return these in arbitrary orders, at times.

(PDB-3427) Ignore order of resource_events in generative tests

---

src/puppetlabs/puppetdb/scf/storage.clj

This backports both the check and the fix to make it hit the index on the hash column to the LTS branch.

(PE-20115) backport report exists check

---

test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/jdbc_test.clj
test/puppetlabs/puppetdb/testutils/db.clj

This lowers the connection pool to a size of 5. We will use as many as
4 connection pools concurrently depending on the test, so this should
reduce the "high water mark" from ~100 to ~20.

(PDB-2583) Reduce the number of DB connections used in tests

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

There's a broader issue with null bytes from the input leaking through the
database at times, but this is the specific instance we've seen in the field. A
broader fix will be forthcoming.

(PDB-3058) Disallow null bytes from resource event fields

---

test/puppetlabs/puppetdb/integration/sensitive_params.clj

This test is currently failing due to an incorrect version of the
PostgreSQL client installed on the Jenkins test machines. Once that
issue has been fixed (tracked as PDB-3461) this commit can be reverted
and the test re-enabled.

(PDB-3461) Disable the sensitive parameters test

---

test/puppetlabs/puppetdb/integration/fixtures.clj
test/puppetlabs/puppetdb/integration/soft_fail/soft_write_fail.clj

Instead of trying to track the number of expected commands, just use the
existing 'wait-for-server-processing' helper. This should eliminate some
intermittent race conditions caused by the previous approach.

(maint) Simplify synchronized-command-processing integration helper

---

src/puppetlabs/puppetdb/jdbc.clj

db-do-commands doesn't appear to care right now, but but let's follow
the documented API anyway.

(PDB-3421) do-commands: pass vector to db-do-commands, not list

---

project.clj

The current version, 5.0.0-master-20170329_182047-ga16e296, prevents
use of lein installed versions, and it sounds like we don't need a
specific jar, just some 5.0.0 snapshot.

(PDB-3458) Change the puppetserver-version to SNAPSHOT

---

project.clj

The key fix for this bump is the bump in cheshire to 5.7.1 that fixes
a memory issue (holding onto the head of a lazy-seq).

(PDB-3467) Bump to clj-parent 0.7.1

---

documentation/configure.markdown
documentation/maintain_and_tune.markdown
src/puppetlabs/puppetdb/config.clj
test/puppetlabs/puppetdb/config_test.clj

Default node-ttl to 7 days and node-purge-ttl to 14 days. This helps keep cruft
from piling up in the database in the default configuration, without user
intervention.

(PDB-3318) Better defaults for node-ttl, node-purge-ttl

---

project.clj

Fixes an issue where cheshire hold onto the head of a seq while write it to a
stream.

(PDB-3467) Bump cheshire version to 5.7.1

---

src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/hash.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/http/events_test.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/http/resources_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

These messages are surfaced in the console when invalid PQL is supplied.
This change fixes a comma splice and changes the vector in the error
message to a comma separated string.

(maint) clean up the error messages around unknown fields

---

test-resources/integration-puppetdb.conf

This commit drops the number of acceptors and selectors used for Puppet
Server testing.  The bump to the new Jetty version results in an
implicit bump in the number of selectors used internally by Jetty.  This
commit drops that number down in order to avoid having the combination
of selector and acceptor threads exceed the max-threads that are
configured.

(MAINT) Drop the number of selectors/acceptors for puppetserver testing

---

project.clj

This reverts commit 054eb944a5add455b2526c03e1cfd9c457aa3900.  The
commit should no longer be required now that the latest puppetserver
repo jars include their own jruby dependencies again.

Revert "(PDB-3503) Add the jruby dev dep puppetserver now expects"

---

puppet/spec/unit/indirector/resource/puppetdb_spec.rb

Changes coming in Puppet 5.0.0 change how Puppet::Parser::Resource
instances set default values; in specific they do so upon object
construction which requires a functioning(ish) scope object. The
Puppetdb terminus specs were relying on the scope object being
relatively simple and easily stubbed but this change in defaults makes
it much harder to treat the scope object as an easily stubbed object.
To simplify stubbing and potentially reduce future breakage this commit
changes the scope stubbing to partially stub a full scope object instead
of creating a pure stub object and adding methods as necessary. By using
a full scope object we can let the internal APIs of Puppet handle
implementation changes.

(maint) Use a real scope object for terminus testing

---

acceptance/setup/pre_suite/15_setup_repos.rb
acceptance/setup/pre_suite/40_install_deps.rb

Install openjdk-8-jre-headless on jessie from backports, since we've
dropped support for openjdk 7, and now require openjdk 8.

(PDB-3506) acceptance: install openjdk 8 on jessie

---

resources/puppetlabs/puppetdb/pql/pql-grammar.ebnf
src/puppetlabs/puppetdb/query/event_counts.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/pql_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

This patch accomplishes a few things
* allows usage of limit/offset in PQL in combination with a group by
* detects paged aggregate queries against package_inventory like those
used in the console and reformulates them to be fast, i.e transforms
```
package_inventory[package_name, version, provider, count()]
{version ~ "foo" group by package_name, version, provider limit 10
offset 10}
```
into
```
package_inventory[package_name, version, provider, count()]
{[package_name, version, provider] in packages[package_name, version,
provider]{version ~ "foo" limit 10 offset 10} group by package_name,
version, provider}
```
* relatedly, changes the query engine to process top-level AST from
clauses, rather than stripping them out in query-eng.clj and only
passing the remaining query. This …

(PDB-3395) bypass costly join on paged packages aggregate queries

---

src/puppetlabs/puppetdb/scf/migrate.clj

These indexes help support some queries made by the reports summary page
in the PE console.  They take a couple minutes to run on a dataset with
11M reports. It'll probably worthwhile to test on a larger set somehow.
Space on disk is minimal (couple mb) due to how targeted these are.

(maint) add partial indexes on reports

---

resources/puppetlabs/puppetdb/pql/pql-grammar.ebnf
src/puppetlabs/puppetdb/query/event_counts.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/pql_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

@wkalt This is causing very strange failures in pe-ext tests, indicating that this had unintended consequences. I'm going to revert it for now; can you take a look at the failures and re-open when you get a handle on them?

Revert "(PDB-3395) bypass costly join on paged packages aggregate queries"

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb

The `Puppet::Util::TagSet` class has a method named `#to_data_hash`. It
returns an `Array` instead of a `Hash`. PuppetDB assumes that the hash
returned from a call to `Puppet::Resource::Catalog#to_data_hash` contains
tag sets and calls the `#to_data_hash` to convert them into an `Array`.
This now breaks because the bug that caused the hash to contain tag sets
was fixed in PUP-7381.
This commit changes the call to `#to_data_hash` to instead be a call to
`#to_a`. Both the `Puppet::Util::TagSet` and the `Array` class implements
this method which means that PuppetDB will be capable of munging catalogs
produced both before and after PUP-7381.

(PDB-3527) Use #to_a method, not #to_data_hash when converting TagSets

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb

Puppet has changed its to_data_hash code to emit json-compatible data. This
means that all map keys are now strings, where some used to be symbols.

(maint) Use string keys in terminus data munging code

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb

Puppet is stringifying all resource titles in catalog.to_data_hash now, but
catalog.resource(type, title) can't accept string titles in all case. It special
cases :main, so apply the inverse special case here.

(maint) Workaround PUP-7605

---

documentation/CONTRIBUTING.md

This commit replaces the stale link to the old puppet wiki with a link to the
contributor guidelines.

(maint) Update contributing resource links

---

acceptance/helper.rb
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

- Update the minimum version vector to [9 6].
- Refactor version check functions to allow the minimum version to be overriden
if necessary (temporary internal hook, for use by PE)
- Fix a bug that was preventing version-check test assertions from running

(PDB-2950) Require PostgreSQL >= 9.6

---

documentation/api/query/curl.markdown
documentation/api/query/v4/ast.markdown
documentation/api/query/v4/events.markdown
documentation/api/query/v4/index.markdown
src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/index_test.clj
test/puppetlabs/puppetdb/testutils/http.clj
test/puppetlabs/puppetdb/testutils/nodes.clj

Previously, queries to the root endpoint (which includes all PQL queries)
included all expired and deactivated nodes. This is different from all the other
query endpoints, and practically never what you want to do.
With this change, the root query endpoint modifies queries in the same way as
the other query endpoints to exclude inactive and expired nodes.

(PDB-3420) Exclude inactive and expired nodes in root query endpoint

---

src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage_utils.clj

We had this before, but it was lost in a migration which rewrote the certnames
table but neglected to restore all of the foreign key constraints. This adds it
back in a special startup function; nominally this would be in a migration, but
we've already consumed the following migration numbers in newer versions. The
corresponding change in the new code will use a migration.

(PDB-3515) Add edges_certname_fkey constraint

---

src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj

First, this backports several indexes to LTS so we can get up to the official version of this index. Then we have a change to the query engine to make queries that don't break the planner's brain.

(PDB-3518) fix latest report id index problems

---

src/puppetlabs/puppetdb/query_eng/engine.clj

Previously, queries which cross certnames and reports via latest_report_id would
sometimes get a degenerate query plan due to the presence of
idx_certnames_latest_report_id. The planner was led to believe that this index
made starting with a filtered version of the reports table and then joining that
to certnames was a good plan; it is not.
By adding an additional condition to the join which touches the certname table,
we encourage the planner to deal directly with rows which include both report.id
and certname.certname. The most direct way to do this is to scan down certnames
and pull each latest_report using the main report id index. This is the plan it
makes now, and it's a lot faster.

(PDB-3518) More specific join for certname->reports

---

src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/scf/storage.clj
src/puppetlabs/puppetdb/scf/storage_utils.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

Instead of calling System/exit, use the trapperkeeper shutdown service
to shut down when an unsupported database is detected.  Previously pdb
would just hang.
One drawback to this approach is that it looks like the only way to
get trapperkeeper to shut down and exit with a non-zero status is to
throw an exception, and we'd prefer to avoid the backtrace since the
problem has already been described in the log and on stderr.
Hopefully trapperkeeper will add something more suitable, and then we
can use it.

(PDB-3541) Don't hang on unsupported database

---

documentation/configure.markdown
documentation/index.markdown
documentation/install_from_source.markdown

Update the documentation, and remove support for jvm versions older
than 8.  Have pdb exit with an error if an unsupported jvm is
detected, and unify the failure handling with the recent changes
related to unsupported postgres versions.
After this, "run services" will initiate a tk shutdown-on-error when
it detects an unsupported jvm, as it does for an unsupported
postgresql, instead of calling (System/exit 1).
cf. PDB-3541 a8559cfebeb35eb3e1fca6338b90e069b4b0ff1e

(PDB-3548) Document the removal of support for jvm < 8

---

acceptance/helper.rb
acceptance/setup/pre_suite/15_setup_repos.rb
acceptance/setup/pre_suite/80_add_dev_repo.rb

Replace previous usage of `PC1` nightlies with `puppet5`.
Add support for the use case where the puppetdb build version is not specified. In this case, the version of puppetdb published in the `puppet5-nightly` repo will be installed.

(PDB-3549) Update acceptance to use puppet5-nightly

---

src/puppetlabs/puppetdb/command.clj
test/puppetlabs/puppetdb/command_test.clj

The top-level exception handler used in command processing threads missed most
ExceptionInfo exceptions; this includes schema validation errors.

(PDB-3566) Fix the catch-all for command processing errors

---

src/puppetlabs/puppetdb/middleware.clj

We sometimes don't get the length header now, with gzip compression from
puppetserver.

(maint) Remove content-length warning

---

resources/ext/ezbake.conf

- Puppet Server, PDB, and Puppet will all be released at version '5' and
require version 5 of each other. Update the dependency expressed in PDB.
Support both 'puppet' and 'puppet-agent' in case distros ship a puppet 5 and
PDB can depend on that.
- for PDB specifically, requiring puppet 5 means that we can rely on puppet 5
semantics in the various puppetdb termini. This will allow us to remove some
processing done in the terminus that is no longer necessary, possibly
optimizing performance, but cetainly optimizing maintainability.
Signed-off-by: Moses Mendoza <moses@puppet.com>

(PDB-3558) depend on puppet 5

---

documentation/ha.markdown

this version also is mismatched on this page.

(docs) update mismatched version number in heading (in 4.4).

---

Gemfile
puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb

In Puppet 5, Catalog#to_data_hash will only emit data types that are
safe for JSON, YAML, etc, and in particular will never emit Symbols.
When synthesizing an edge from any resource to an aliased resource:
require => Package['my_alias']
puppetdb would fail to find the target resource in the catalog. And that
was because it was looking for the `:alias` parameter in the catalog
hash, which didn't exist.
This commit updates the add_namevar_alias and map_aliases_to_titles to
use the String form of 'alias'. It adds a unit test demonstrating the
problem, and updates other tests that relied on the previous symbol
behavior.
Note the terminus behaves different if the resource specifying the
`alias` metaparam has multiple namevars (eg Package) or not.

(PDB-3620) Use string 'alias' metaparameters

---

documentation/configure.markdown

This fix a rendering problem caused by the missing space:
https://docs.puppet.com/puppetdb/latest/configure.html#conn-keep-alive-1

(maint) Documentation markup fix

---

resources/ext/config/logback.xml

I noticed this problem in `puppetserver`, and I'm going around updating the other projects that use `tk-status`'s periodic status logging
---
This commit changes the status logger's logging level to debug. This logback logger picks up log messages from the `tk-status` periodic logging feature, if it is enabled.
The periodic status logging feature in `tk-status` logs at the `debug` level, so
unless the logback root logger is set to `debug`, for the status logger to inherit from,
no periodic status log messages will appear. 
This change has no affect on any of the the other logging that the app does

(MAINT) Change status logger to debug level

---

test-resources/puppetserver/bootstrap.cfg

It's been needed for a long time, but for some reason just started making builds
fail.

(maint) Add jruby to puppetserver bootstrap.cfg

---

acceptance/helper.rb
acceptance/setup/pre_suite/90_install_devel_puppetdb.rb

This seems to be required for jessie, when install postgres packages from pgdg.

(maint) Install apt-transport-https in acceptance test

---

acceptance/setup/pre_suite/15_setup_repos.rb
acceptance/setup/pre_suite/80_add_dev_repo.rb
resources/puppetlabs/puppetdb/benchmark/samples/facts/pg2.vm.json

In order to test against the right set of packages, we need to update
these tests to hit the new repos. Rather than pin to puppet 5, we're
just going to pin to the rolling puppet repos. This will change
automatically to puppet6 once we change these repos to point to puppet6.

(RE-8458) Update tests to use the puppet repos

---

documentation/api/admin/v1/summary-stats.markdown
src/puppetlabs/puppetdb/facts.clj
src/puppetlabs/puppetdb/package_util.clj
src/puppetlabs/puppetdb/query.clj
src/puppetlabs/puppetdb/query/summary_stats.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/hash.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/admin_test.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/scf/hash_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/scf/storage_utils_test.clj

Previously, we had changed fact storage to put the value in the facts table, in
order to simplify storage and sidestep the problematic garbage collection issues
when fact values had their own table. But this proved to make queries too slow,
especially when dealing with queries which have multiple conditions on facts.

(PDB-3611) Deduplicate fact values (again)

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/inventory_test.clj
test/puppetlabs/puppetdb/pql/parser_test.clj

For some ancient reason we were converting all dashes in field names to
underscores. Stop doing that so PQL queries with dashes in fact paths
work.

(PDB-3501) make dashed queries work

---

src/puppetlabs/puppetdb/scf/migrate.clj

Updates the varchar columns to test. I believe this should be fast
because varchar and text are binary coercible, but we'll need to verify
to be sure.

(maint) change varchar columns to text

---

project.clj

This version of EZBake stores the build metadata (including the deployed
snapshot version and fully-resolved versions of all snapshot
dependencies) in a persistent location, rather than one that gets
deleted after two weeks.

(maint) Update EZBake to 1.5.1

---

src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

In the flat fact storage code, null fact values were stored as sql null instead
of json null. Update the migration code to account for this.

(PDB-3643) Fix fact dedupe migration with null values

---

src/puppetlabs/puppetdb/cli/services.clj

I've added gc_packages to the scheduled garbage collection (not currently included):
```
2017-09-01 01:24:12,766 INFO [p.p.c.services] Starting database garbage collection
2017-09-01 01:24:12,772 INFO [p.p.c.services] Finished database garbage collection
2017-09-01 02:24:12,773 INFO [p.p.c.services] Starting sweep of stale nodes (threshold: 7 days)
2017-09-01 02:24:12,780 INFO [p.p.c.services] Finished sweep of stale nodes (threshold: 7 days)
2017-09-01 02:24:12,780 INFO [p.p.c.services] Starting purge deactivated and expired nodes (threshold: 5 minutes)
2017-09-01 02:24:12,781 INFO [p.p.c.services] Finished purge deactivated and expired nodes (threshold: 5 minutes)
2017-09-01 02:24:12,781 INFO [p.p.c.services] Starting sweep of stale reports (threshold: 14 days)
2017-09-01 02:24:12,783 …
```

(PE-21799) Ensuring gc_packages runs

---

src/puppetlabs/puppetdb/cli/benchmark.clj

The 'mq-ch' queue is populated by both 'start-populate-queue' and 'start-simulation-loop' concurrently. When the user specifies arguments like "--nummsgs 1 --numhosts 20", the expected 20 hosts are not loaded because the simulation loop requeues the early hosts before the later ones have been populated the first time. In total there are 20 commands processed but host-0, host-1, ... see 2 or more messages each while ..., host-18, host19 see zero. When trying to load a large number of nodes, facts or catalogs the user is forced to specify a larger value for 'numhosts' than really needed and incur the cost of repeated processing of the early hosts.
This commit makes sure that every host in enqueued once before the simulation loop starts.

(maint) Ensure the benchmark tool creates the requested number of hosts

---

acceptance/setup/pre_suite/70_install_released_puppetdb.rb

Per https://github.com/puppetlabs/ci-job-configs/blob/master/jenkii/cinext-jenkinsmaster-enterprise-prod-1/projects/puppetdb.yaml#L24,L27 , this is using the wrong keyword.

(maint) change install_mode to install_type

---

acceptance/helper.rb

With the move to the new ezbake packaging, we've fixed a long-standing
bug where we had packages with the same name but different content as we
didn't include the codename in the release field. This however breaks
the method of puppetdb installations, so update the version
determination.

(maint) Update version determination

---

puppet/lib/puppet/indirector/resource/puppetdb.rb

Before this commit, the resource type would be passed to `Resource#new`
in string form. This is problematic since it may result in the load of
a Ruby resource type which then is in conflict with genereated Pcore
resource type.
This commit ensures that the indirection uses the same logic as Puppet
when creating new resources.

(PDB-3734) Ensure that resource indirection uses existing resource type

---

documentation/api/query/v4/nodes.markdown
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/testutils/nodes.clj

In order to be able to display the job-id successfully on the PE Overview table, the job-id needs to be available in the pdb payload when a given report was the result of running from the orchestrator.

(PE-22668) Add job_id from the latest report to nodes endpoint.

---

project.clj

Previously would send releases and snapshots to nexus, we want to ship these to artifactory instead.
Tested [here](https://artifactory.delivery.puppetlabs.net/artifactory/webapp/#/search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5IjoicHVwcGV0ZGItNC4yLjMuOC0yMDE3MTExNi4xOTQiLCJzZWxlY3RlZFJlcG9zaXRvcmllcyI6WyJjbG9qdXJlLXNuYXBzaG90c19fbG9jYWwiXX0=)

(RE-9732) Use artifactory instead of nexus (4.2.3.x branch)

---

project.clj

Previously would send releases and snapshots to nexus, we want to ship these to artifactory instead.
Tested and [shipped to artifactory](https://artifactory.delivery.puppetlabs.net/artifactory/webapp/#/search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5IjoicHVwcGV0ZGItNC40LjMtMjAxNzExMTYuMTkzNjA1Iiwic2VsZWN0ZWRSZXBvc2l0b3JpZXMiOlsiY2xvanVyZS1zbmFwc2hvdHNfX2xvY2FsIl19)

(RE-9732) Use artifactory instead of nexus (4.4.x branch)

---

src/puppetlabs/puppetdb/cli/benchmark.clj
test/puppetlabs/puppetdb/cli/benchmark_test.clj

I've moved the `validate-cli` call to the `main` method of the benchmark namespace.
This allows me to call the benchmark function from elsewhere and pass in my options map.  With this change, I can pass an already loaded config without having to read anything from disk.

(MAINT) Enable benchmarking via clojure

---

src/puppetlabs/puppetdb/query_eng/engine.clj

The original SQL query to get event counts from the latest report was
````
SELECT * 
FROM (SELECT containing_class,
SUM(CASE WHEN status = 'failure' THEN 1 ELSE 0 END) AS failures,
SUM(CASE WHEN status = 'skipped' THEN 1 ELSE 0 END) AS skips,
SUM(CASE WHEN (status = 'success' and coalesce(corrective_change, false) = false) THEN 1 ELSE 0 END) AS intentional_successes,
SUM(CASE WHEN (status = 'success' and corrective_change = true) THEN 1 ELSE 0 END) AS corrective_successes,
SUM(CASE WHEN (status = 'noop' and coalesce(corrective_change, false) = false) THEN 1 ELSE 0 END) AS intentional_noops,
SUM(CASE WHEN (status = 'noop' and corrective_change = true) THEN 1 ELSE 0 END) AS corrective_noops 
FROM (SELECT DISTINCT certname, status, corrective_change, containing_class
FROM (WITH …
```

(PE-22860) Optimize event queries with the latest_report? parameter

---

src/puppetlabs/puppetdb/scf/storage.clj

"delete where not in" is a bad query in postgres. See discussion on SO for
alternatives:
https://stackoverflow.com/questions/15959061/delete-records-which-do-not-have-a-match-in-another-table

(PDB-3695) speed up package gc

---

src/puppetlabs/puppetdb/http/handlers.clj
test/puppetlabs/puppetdb/http/facts_test.clj

Stop restricting queries to active nodes when there is no node
associated with the relevant entity, e.g environments, fact_paths,
packages.
fact_names is special (unqueryable) and is already avoiding this issue
via other means.

(PDB-3779) Fix inappropriate restriction to active nodes

---

ext/build_defaults.yaml

Our automation is attempting to sign tarballs that aren't there. This will make sure we don't try to do that.

(maint) Add build_tar: FALSE to build_defaults

---

project.clj

This commit updates to the latest version of ezbake, which will set build_tar to false, preventing the nightlies job from attempting to sign tars that don't exist.

(maint) Bump to ezbake 1.7.3

---

project.clj

This commit updates to the latest version of ezbake, which will allow clojure projects' repo-target to be interpreted by the packaging repo, ensuring builds get shipped to the correct repos.

(maint) Bump to ezbake 1.7.4

---

project.clj

This PR updates the repo-target and nonfinal-repo-target and bumps to the newest version of ezbake so that puppet5 components ship to the correct repos.

(EZ-118) Clojure projects not shipping to puppet5-nightly

---

documentation/configure.markdown

Fixes incorrect syntax in the docs for facts blacklist in ini files.

(maint) update docs with correct syntax for facts blacklist

---

documentation/release_notes.markdown

Add release notes for PuppetDB 5.1.4.
All other changes are line endings modified by the text editor.
> PuppetDB 5.1.4 is a minor bug-fix release.

(docs) Add 5.1.4 release notes.

---

documentation/_puppetdb_nav.html
documentation/api/admin/v1/cmd.markdown
documentation/api/query/curl.markdown
documentation/api/query/tutorial-pql.markdown
documentation/api/query/v4/ast.markdown
documentation/api/query/v4/inventory.markdown
documentation/api/query/v4/packages.markdown
documentation/api/query/v4/pql.markdown
documentation/api/query/v4/query.markdown
documentation/api/wire_format/facts_format_v5.markdown
documentation/community_add_ons.markdown
documentation/configure.markdown
documentation/connect_puppet_apply.markdown
documentation/install_from_packages.markdown
documentation/known_issues.markdown
documentation/pdb_client_tools.markdown
documentation/pdb_support_guide.markdown
documentation/puppetdb_connection.markdown
documentation/release_notes.markdown

Several parts of the documentation have invalid or inconsistent Markdown
formatting, broken links, or errors in heading levels or heading contents.
This results in issues when rendering these docs on GitHub or
puppet.com/docs.
This PR resolves these issues. It does not attempt to validate, resolve
issues with, or update any of the surrounding content.

(docs) Fix Markdown, formatting, and ToC issues.

---

documentation/pdb_client_tools.markdown

Fix a typo causing errors in an example, and fix a spelling error in and clarify a related note.

(docs)(DOCUMENT-809) Fix typos in PDB client tools docs.

---

documentation/pdb_client_tools.markdown

Add examples showing Windows path escaping, and fix a Markdown formatting issue causing a Windows path to render inconsistently.

(docs)(DOCUMENT-812) Add and fix Windows examples in PDB client tools docs

---

documentation/api/query/tutorial-pql.markdown

(via PR #2431 by @Nekototori)
> .each doesn't change the result to store in the variable. It keeps
> any changes/output isolated. Need .map to use the result outside
> of the iterator per the example.
>
> Also, no capital on `notify`.
(retargeted at 5.1.x, and amended the commit message for CI)

(docs)(DOCUMENT-813) Fix errors in PQL example

---

ext/build_defaults.yaml

This commit adds 'puppetdb' as the project name. Previously, when attempting to ship tarballs, the packaging repo was unable to find any retrieved tarballs because it expected them in the form <project>-<version>.tar.gz, but there was no project set.

(maint) Add project name to build defaults

---

ext/build_defaults.yaml

This reverts commit f9733e1b0adcd2fd6b998f6aa817e7bb1cf88488.
We were fixing a symptom of a problem, rather than the problem itself (see
RE-10238).

Revert "(maint) Add build_tar: FALSE to build_defaults"

---

documentation/release_notes.markdown

As of 1 p.m. PT Feb. 13 this should contain all content for PDB 5.2.0 from JIRA release notes.

(docs) Add PuppetDB 5.2.0 release notes.

---

acceptance/setup/pre_suite/15_setup_repos.rb

This commit updates the nightlies paths used for acceptance tests to reflect the new nightlies path structure.

(RE-9880) Update acceptance tests that reference nightlies

---

src/puppetlabs/puppetdb/command.clj

Prior to this commit, when a message is discarded it had no effect
on the command queue depth metrics.
After this commit, when a message is discarded we decrement the
queue depth metric.

(PDB-3830) Decrement queue depth when discarding a message

---

puppet/spec/unit/reports/puppetdb_spec.rb

Accommodate the resource tag optimizations in
d2e6af6cf0d4745cd838184b50fde0f6e970cf7f by setting
:merge_into => nil in the stubs.
Thanks to Patrick Carlisle for suggesting the fix.

(PDB-3873) Accommodate puppet's recent resource tag optimizations

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

Previously, all queries to the facts endpoint generated brute-force fallback sql
which extracted all fact names and values using jsonb_each and filtered the
resulting tuple. This is very slow.
This change optimizes queries which constrain the fact name to a single value,
the most common way of using the facts endpoint. It does this by rewriting the
facts query-rec to explicitly extract the indicated value using the jsonb ->
operator.

(PDB-3838) Optimize fact queries which constrain to a single name

---

documentation/api/query/tutorial-pql.markdown

.each doesn't change the result to store in the variable. It keeps
any changes/output isolated. Need .map to use the result outside
of the iterator per the example.
Also, no capital on `notify`.

(docs)(DOCUMENT-816) Cherry-pick fix for 5.0.x example

---

src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/storage_utils.clj
test/puppetlabs/puppetdb/http/facts_test.clj

This commit fixes structured facts queries that descend into arrays and
those that contain regexes.
Regexes on structured facts queries have been fixed by querying the
database for all paths that match the given path regex and then adding
the results from that into the original user-query with an "or"
statement around the returned paths.
Queries that descend into arrays have been fixed by examining the query
and using the #> operator instead of the @> operator in the where
clause.

(PDB-3852) Fix broken structured facts queries

---

.travis.yml

For now test the corresponding platform versions, and the previous
platform versions.

(PDB-3920) 5.2.x: test appropriate server and puppet versions in CI

---

documentation/release_notes.markdown

No tickets in PDB 5.2.3 are marked as requiring release notes, so in lieu of notes I'm linking to the JIRA search for issues with that fixVersion.

(docs) Add 5.2.3 release notes

---

test/puppetlabs/puppetdb/integration/file_with_binary_template.clj

The puppet issue appears to have been resolved.

(PDB-3560) Restore file-with-binary-template-test

---

project.clj
src-gems/puppetlabs/puppetdb/integration/install_gems.clj

Prior to this commit (due to a file name change in puppetserver), the
integration tests were broken between master branches.
This commit makes it possible for the puppetdb master branch to run
against master as well as the tagged releases of puppetserver by
choosing the proper file name depending on puppetserver's version.

(PDB-3963) Use proper gem-list from puppetserver

---

project.clj

pdbext needs rbac 0.9.0 in order to be able to upgrade to clj-parent
2.0, clojure 1.9, etc.

(PDB-3938) Update to clj-parent 2.0.2 for pdbext rbac-client dep

---

test/puppetlabs/puppetdb/http/facts_test.clj

Previously, it was possible for garbage collection to run in the middle
of the developer-pretty-print test, which if it ran in between adding
the cert and facts and the test checks would clean them out of the database.
This commit changes the test to use the timestamp now so that even if
garbage collection runs, the facts will remain.

(PDB-3948) Fix transient failure of pretty print

---

ext/bin/clj-1.9
ext/bin/dep-diff

...since pdb no longer depends on or uses clojure 1.8, and since
clojure 1.9 is multi-jar.

(PDB-3953) Add ext/bin/clj-1.9 and use it in dep-diff

---

src/puppetlabs/puppetdb/config.clj
test/puppetlabs/puppetdb/config_test.clj

This is needed to match the format of exception data that trapperkeeper expects. Kitchensink cli-errors are explicitly caught and handled, as a result their format doesn't need to change.

(PDB-3652) Change format of non-kitchensink :cli-errors

---

resources/ext/config/logback.xml

This commit updates the logback configuration bundled with puppetdb
packages to implement the following improvements:
- Set `scanPeriod="60 seconds"` so that settings like log levels can be
toggled without requiring a service restart.
- Use RFC 3339 compliant timestamps that include the offset from UTC.

(PDB-3884) Update logback configuration

---

acceptance/tests/security/puppetdb-ssl-setup/no-puppet-certs.rb
acceptance/tests/security/puppetdb-ssl-setup/nonprod-environment.rb

This changes the way we retrieve config data in our acceptance tests to make it compatible with changes to the puppet cli that are being made in 6.0.0.

Change config data retrieval in acceptance tests

---

project.clj

This commit bumps to the latest ezbake version. This version adds a Gemfile to
the resulting package build and makes use of the packaging gem, rather than
cloning the packaging repo.

(maint) Bump to ezbake 1.8.7

---

Rakefile

Since we have lots of different parts of our infrastructure which still
use package:implode and package:bootstrap we cannot exactly remove them
entirely yet. This commit adds empty warnings back in order to make sure
that the tasks don't fail during any of our pipelines.

(maint) Add packaging bootstrap/implode warnings

---

puppet/lib/puppet/util/puppetdb/http.rb
puppet/spec/unit/util/puppetdb/http_spec.rb

Prior to this commit, the http submission with command_broadcast enabled
always returned the last response. As a result, a failure would be shown if
the last connection produced a 503 response even though there was
previously a successful PuppetDB response and the minimum successful
responses have been met. This issue does not occur with responses that
raised an exception. Since the puppet http_pool does not raise 503
as an exception, this issue can be seen when the PuppetDB is in
maintenance mode.
This commit changes the behavior to send the last successful response
when the minimum successful submissions have been met.

(PDB-4020) Return the last successful reponse with command_broadcast

---

acceptance/helper.rb

Before this commit acceptance tests on debian 9 would fail due to
there not being packages made for that platform before pdb version 5.1.1

(PDB-4104) Change oldest supported version to access to deb9 packages

---

.gitattributes
docker/puppetdb-postgres/Dockerfile
docker/puppetdb/Dockerfile

- Typically the contents of Linux files should have LF line endings,
as is the case with scripts being copied into Linux containers such
as the ENTRYPOINT script.
When cloning git source on Windows, files normally end with CRLF.
The correct way to guarantee line endings remain Linux compatible is
to add .gitattributes entries as these override any git client
specific settings that may otherwise break line endings
- Further, note that while git metadata understands the +x execute
bit on non-Windows platforms, when checking out code on Windows there
is no way to represent this information and it's lost.
When copying files into a Docker image, scripts lose their ability
to execute.
The only way to address this is to +x the scripts inside the
Dockerfile

(maint) Fix Linux Docker scripts on Windows builds

---

documentation/CONTRIBUTING.md
documentation/anonymization.markdown
documentation/community_add_ons.markdown
documentation/configure.markdown
documentation/connect_puppet_apply.markdown
documentation/connect_puppet_master.markdown
documentation/ha.markdown
documentation/index.markdown
documentation/install_from_packages.markdown
documentation/install_from_source.markdown
documentation/install_via_module.markdown
documentation/known_issues.markdown
documentation/load_testing_tool.markdown
documentation/logging.markdown
documentation/maintain_and_tune.markdown
documentation/pdb_client_tools.markdown
documentation/pdb_support_guide.markdown
documentation/postgres_ssl.markdown
documentation/puppetdb-faq.markdown
documentation/puppetdb_connection.markdown
documentation/repl.markdown
documentation/scaling_recommendations.markdown
documentation/trouble_session_logging.markdown
documentation/upgrade.markdown
documentation/using.markdown
documentation/versioning_policy.markdown

There are some version numbers in the following files that I left for you to update to 6.0 or not because I wasn't positive on the changes:
Index.markdown
Contributing.md
Connect_puppet_master.markdown

Updated version numbers in the 6.0 release.

---

documentation/api/query/v4/ast.markdown

A user in Slack had some issues because they started from an extract
statement that had been copy-pasted from these.

(docs) Add missing comma in extract queries

---

documentation/CONTRIBUTING.md
project.clj

Until we're able to remove the internal :repositories from the default
repository list, allow them to be removed by setting
PUPPET_SUPPRESS_INTERNAL_LEIN_REPOS to true, yes, or 1 in the
environment.

(PDB-4135) Support PUPPET_SUPPRESS_INTERNAL_LEIN_REPOS

---

src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/utils_test.clj

Both to account for the version change for newer jdks (e.g. 10 instead
of 1.10), and to fix bugs.

(PDB-4141) Fix jdk-support-status regexes

---

azure-pipelines.yml
docker/Gemfile

- This definition doesn't do anything other than query system information.
It must be first merged against the 5.1.x branch to enable Azure Pipelines authorization to run custom agent builds against this branch.

(maint) Add basic Azure Pipelines definition

---

documentation/configure.markdown
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/schema.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/config_test.clj

This commit adds support for regex in the facts-blacklist config 
option. Given a valid regex pattern it will not store facts where
a pattern matches a fact name. This is controlled by the use of a
:facts-blacklist-type flag which defaults to 'regular'. The default
preserves the existing facts-blacklist behavior. Setting this flag
to 'regex' allows a user to submit valid java regex patterns for use.

(PDB-3928) Add regex to facts-blacklist

---

ext/bin/pdbbox-init

Sets a few tuning parameters to make the default postgresql installation deal
with the write-heavy load that puppetdb has.
This is best combined with disabling fsync during startup, via:
pg_ctl -o "-F" start

(PDB-4081) adding perf tuning params to postgresql config

---

project.clj

It looks like the use of ^:replace :dependencies in the ezbake profile
causes all pins in the normal :dependencies section to be ignored.  So
for now, just repeat the pins for the recent CVEs in the :ezbake
profile, which does cause them to show up here:
lein with-profiles ezbake deps :tree
In addition, stop pinning hikaricp and clojure/jdbc so that we won't
fall afoul of :pedantic, *and* so that we'll actually be testing the
versions that we ship (verified by spot-checking the relevant
META-INF/maven/ pom.xml versions in the 5.1.5 debian/stretch jar).

(PDB-4165) Duplicate dependency pins in :ezbake profile

---

.travis.yml
ext/travisci/prep-os-essentials-for

AdoptOpenJDK 8 is deprecated and no longer has a proper cacert bundle

(PDB-4176) Travis: Fix openjdk8 testing on OSX

---

.travis.yml

Master should be running integration tests against puppet and
puppetserver's master branches as well as the latest release branches
(the 6.0.x branch for each).

(PDB-4179) Travis: fix master test suite

---

src/puppetlabs/puppetdb/query_eng/engine.clj

This was inadvertently introduced during a merge from 5.1.x to 5.2.x

(maint) remove unintended merge of fv-variant func

---

docker/puppetdb/docker-entrypoint.sh

Previously, docker-entrypoint.sh checked whether the puppetmaster is up and
running by using 'nc -z'. That only checks that something is listening on
the given port, but not whether that service is actually ready. This is a
problem when the puppetmaster is behind a load balancer since it only
checks that the loadbalancer is listening, even though the puppetmaster
might take quite a while longer to become ready; in such a scenario, the
PuppetDB startup fails.
This change replaces the 'nc -z' check with a check for the puppetmaster's
status, and only proceeds when the master is fully up and ready to handle
requests.

(maint) Make check in container whether puppetmaster is up more robust

---

project.clj

This commit bumps to the latest ezbake version. This version adds a Gemfile to
the resulting package build and makes use of the packaging gem, rather than
cloning the packaging repo.

(RE-11578) Bump to ezbake 1.8.10

---

docker/puppetdb/docker-entrypoint.sh

Hitting an endpoint instead of using netcat will work when Puppet Server
is behind a load balancer.
We tried this approach earlier but weren't specifying HTTPS and the
-k flag when curling.

(PDB-4192) Curl Puppet Server status endpoint

---

project.clj

lein-parent 0.3.1 doesn't work properly with -SNAPSHOT builds of
dependencies.

(PDB-4164) update lein-parent to support snapshots

---

project.clj

Update is in order to pull in a change to our Jetty configuration that 
prevents Jetty from sending the server version in the HTTP response and
error pages.

Update tk-webserver-jetty9 to 2.3.1

---

documentation/load_testing_tool.markdown

@samwoods1 this is a first pass at adding docs for running benchmark on an agent using what you described in [DOCUMENT-857](https://tickets.puppetlabs.com/browse/DOCUMENT-857).
I'm wondering if puppetdb and the necessary pieces to run the benchmark tool are installed on the agent by default, or do you think we need to list doing that as an additional step?

(DOCS-857) Update benchmark docs with information about running on agent

---

src/puppetlabs/puppetdb/cli/services.clj

Add the message we know we're going to want later so that it can be
translated in time for the rlease.  The remaining code will follow.

(PDB-2487) Add log gc-resource-events! message for translation

---

documentation/configure.markdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/integration/resource_events.clj

* Adds a config parameter: database.resource-events-ttl with a default of 14d
* Adds two admin metrics: resource-events-purges and resource-events-purge-time
* Adds documentation for this new feature
This will allow the resource_events table to be cleaned up at a different interval
than the reports table.

(PDB-2487) adding the ability to gc the resource-events table

---

docker/puppetdb/docker-entrypoint.sh

Previously, on anything but the initial run, if the puppetdb container
started up before puppetserver, the container would fail and exit since
the directory that is checked for existence never exists on startup. By
updating the checks in the entrypoint, there is now no hard dependency
between puppetserver and puppetdb.

(maint) Update puppetdb entrypoint for less dependence on puppetserver

---

puppet/lib/puppet/util/puppetdb/command.rb
puppet/spec/spec_helper.rb
puppet/spec/unit/util/puppetdb/command_spec.rb
src/puppetlabs/puppetdb/client.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/command/constants.clj
src/puppetlabs/puppetdb/http/command.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/http/command_test.clj

Prior to these commits the producer-timestamp wasn't sent in the correct format from the terminus or pulled out of the query parameters. This caused all cmdrefs to have nil values for producer-ts.

(PDB-4177) Fix bash in place

---

documentation/release_notes.markdown

Release notes for PuppetDB 6.1.0.

(docs) 6.1.0 Release notes

---

Gemfile
acceptance/helper.rb

Prior to this commit the puppet agent install would fail on some but not all
platforms due to a repo url mismatch. We need to specify the :puppet_collection
in order to get the correct behavior on all platforms.

(maint) change install method for puppet agent

---

acceptance/helper.rb

Prior to this commit we were using a more specific method to install the agent
which lacked beaker path munging on the host when doing a non aio install.

(maint) Change install puppet-agent call to use more general method

---

ext/bin/dep-diff

This makes ignore-exclusions work, so global exclusions won't cause a build to fail

(maint) dep-diff: actually respect --ignore-exclusions

---

ext/travisci/prep-os-essentials-for

Recently osx tests started failing like this during "brew install
bash":
/usr/local/Homebrew/Library/Homebrew/config.rb:39:in `initialize': no implicit conversion of nil into String (TypeError)
from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `new'
from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/local/Homebrew/Library/Homebrew/global.rb:25:in `<top (required)>'
from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `require_relative'
from …

(PDB-4244) travis: brew update ruby to fix brew failures

---

.gitattributes
docker/puppetdb/Dockerfile
docker/puppetdb/docker-entrypoint.d/10-configure-ssl.sh
docker/puppetdb/docker-entrypoint.sh

Decompose the single docker-entrypoint.sh script into a directory of
ordered scripts.
This follows the same pattern that was introduced recently in the
puppetserver container.

(MAINT) Introduce docker-entrypoint.d/

---

docker/ci/build.ps1

Tagging as latest was accidentally added during a recent refactor.
We don't need to deal with "latest" in Azure for PuppetDB because the
latest tagging will happen during "make publish" after the tests pass,
which is currently only called by the Distelli/Pipelines CI.
----
I accidentally added this line here: https://github.com/puppetlabs/puppetdb/commit/00a73a8426bb9da24c5d1841945ad28ec78493aa#diff-170dc9c792e45a1be2328aa2dbf41483L35

(MAINT) Don't tag as latest in Azure

---

acceptance/setup/pre_suite/50_install_modules.rb

This commit pins the version of puppetlabs-apt in our acceptances tests
in order to work around a dependency cycle issue which was introduced in
the 6.3.0 release. We plan to drop this pin when the issue is resolved.

(PDB-4256) Pin puppetlabs-apt to 6.2.1 in acceptance tests

---

docker/puppetdb/ssl-setup.sh

Previously the `ssl-setup.sh` script would use the `HOSTNAME` environment when dealing with `{certname}.*.pem` ssl cert paths. In the case where a hard coded cert name is copied in to place in a Dockerfile that derives from the puppetdb image allow the configuration of the certname with an environment variable called `CERTNAME`. The default of `HOSTNAME` will still be respected in the case that `CERTNAME` is unset.

(maint) Allow configuration of certname in ssl-setup.sh

---

documentation/api/query/v4/ast.markdown
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

Previously this array type check would fail for any array greater than
one element. This solves the type check bug by using a set to
de-depulicate the array of fact-value types.
This also updates a documentation example that is no longer valid due to
a stricter type-checking.

(PDB-4199) Allow multi-value array in 'in' queries

---

documentation/api/query/curl.markdown

The format for the `pretty` option is slightly different between GET and
POST. The example previously used POST with the GET `pretty` format so
the query would fail.

(PDB-4214) Switch pretty-print example to GET

---

acceptance/setup/pre_suite/50_install_modules.rb

With the fix to puppetlabs-postgresql for MODULES-8553 we no longer need
to pin to the last release of apt.

(PDB-4256) Remove pin to puppetlabs-apt 6.2.1

---

docker/puppetdb/Dockerfile

The ssl.sh script has been updated to use `command -v` instead of `type
-p` when checking for dependencies.

(MAINT) Use new SSL script in container

---

project.clj

This commit bumps the ezbake version to 1.9.6, which adds support for el 8.

(RE-12078) Bump to ezbake 1.9.6

---

project.clj

This reverts commit d0712d72d5760330059a075413072648769ed785.
Puppetserver tests started to fail after this bump, so reverting until we sort
it out.

Revert "(RE-12078) Bump to ezbake 1.9.6"

---

.travis.yml
ext/test/top-level-cli
project.clj

Update dynapath to 1.0.0 to fix an illegal reflective access error
Remove openjdk10 from build matrix as it EOL'ed in September 2018

(MAINT) Fixing errors that make CI fail

---

project.clj

This commit bumps the ezbake version to 1.9.7, which includes support for el 8.

(RE-12078) Bump to ezbake 1.9.7

---

ext/travisci/prep-os-essentials-for

Attempt to fix recently appearing failures like this by manipulating
the cert file as root:
+old_cacert_path=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/security/cacerts
+rm /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/security/cacerts
override rw-r--r--  root/wheel for /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/security/cacerts?
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

(maint) Adjust travis osx cacert paths as admin

---

project.clj

This commit adds a dependency on net.logstash.logback/logstash-logback-encoder
which is described in the PuppetDB documentation as a tool for transforming
log messages into JSON format:
https://puppet.com/docs/puppetdb/6.2/logging.html#json-text
Prior to this commit, the required library was missing from the uberjar. The
library is managed by clj-parent as Puppet Server includes it.

(PDB-4277) Add logback logstash encoder

---

ext/test/upgrade-and-exit
project.clj
src/puppetlabs/puppetdb/scf/hash.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

This will allow this table to be cleaned with pg_repack instead of relying
on a VACUUM FULL, which avoids locks on the table.

(PDB-3911) adding pk to resource_events table

---

documentation/api/command/v1/commands.markdown
documentation/api/wire_format/configure_expiration_format_v1.markdown
ext/test/upgrade-and-exit
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/command/constants.clj
src/puppetlabs/puppetdb/http/command.clj
src/puppetlabs/puppetdb/queue.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/acceptance/node_ttl.clj
test/puppetlabs/puppetdb/http/command_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

Add a new "configure expiration" command which can be used to disable
factset expiration for a given certname.  This is intended to support
nodes that are managed more directly, and/or are more ephemeral than
nodes that are managed by the agent.

(PDB-4270) Support "configure expiration" command

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb

Previously, the `save` method of the catalog terminus would only save
`job_id` if it came in as part of the catalog. This commit ensures that
we also extract `job_id` from the extra request data if it is present,
and use that if `job_id` is not present in the catalog.

(SERVER-2497) Extract `job_id` from request metadata

---

test/puppetlabs/puppetdb/command_test.clj

Unmake my mess.  Fix intermittent test failures in
handling-commands-producing-unusual-queue-names-across-restart which
I believe were caused by redef races across the server restart and/or
redefing at too low a level (move the redef to process-cmdref to
bypass all of the processsing, discards, etc.).
Rework the test to use two completely separate instances with a shared
vardir to make the phase separation simpler and hopefully clearer.

(PDB-4310) Fix intermittent unusual-queue-names test failures

---

puppet/lib/puppet/indirector/catalog/puppetdb.rb

PuppetDB has a schema in place for the wire format of the catalog that
requires `job_id` to be a string. Since it comes from Puppet as an
integer, this commit converts it to a string in the terminus before
passing it on to PDB proper.

(SERVER-2497) Convert job_id to string

---

acceptance/helper.rb
acceptance/setup/pre_suite/40_install_deps.rb

There are still issues with the acceptance tests skipping certain steps and with deb8 installing jessie-backports. Will address those in a different pr. This should get the pipelines green with rhel8 in the meantime.

(maint) Update acceptance tests for rhel8

---

documentation/api/query/v4/nodes.markdown
src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/time.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

Adds an "expires" field to the node response, that contains two embedded
fields: "facts" and "facts_updated"
If "facts" is true (the default), the node is subject to garbage
collection and expiration. If the value is set to false, the node is
excluded from the garbage collection procedure. If this value has been
explicitly set via a command, the facts_updated field will be a
timestamp representing when the field was set.

(PDB-4271) query for fact expiration

---

docker/puppetdb/Dockerfile
docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

- After some fumbling around with @underscorgan, we determined that the
wtfc code doesn't properly handle command strings that include pipes.
Even if situations where the command is successful, it will exit with
a non-0 failing exit status.
The fix for that is in https://github.com/puppetlabs/wtfc/pull/1
- With this script updated in the container, nested quotes have to be
handled differently as well (in the case where the Consul JSON is
being grepped for "state":"running"). " must first become \", which
is then escaped as \\"\"".
- Simplify how quoting is done around hostnames, replacing " with '
- This fixes code originally introduced in #2883 that was presumed
fixed in #2884 (but wasn't actually fixed)

(maint) Properly perform health checks

---

documentation/configure.markdown

This should escape the asterisks in the blacklist example regex so that they render properly on the docs site.

(PDB-4321) escape asterisks in example regex

---

documentation/api/wire_format/configure_expiration_format_v1.markdown
src/puppetlabs/puppetdb/anonymizer.clj
src/puppetlabs/puppetdb/command/constants.clj
src/puppetlabs/puppetdb/export.clj
src/puppetlabs/puppetdb/import.clj
src/puppetlabs/puppetdb/nodes.clj
test/puppetlabs/puppetdb/admin_test.clj
test/puppetlabs/puppetdb/testutils/cli.clj

Adds export and import of configure-expiration commands via the nodes
queries

(PDB-4275) import/export configure expiration

---

docker/puppetdb/docker-entrypoint.sh

In rare situations running chmod and the script directly afterwards causes a 'Text file busy' error. 
Looks like this:
```
Running /docker-entrypoint.d/10-analytics.sh
/docker-entrypoint.sh: line 8: /docker-entrypoint.d/10-analytics.sh: Text file busy
Running /docker-entrypoint.d/10-analytics.sh
(/docker-entrypoint.d/10-analytics.sh) Sending metrics http://www.google-analytics.com/collect?v=1&t=event&tid=UA-132486246-1&an=puppetdb&av=6.3.0&cid=a81b1abe-6e61-463e-980d-57cbddd8bcd3&ec=production&ea=start
Running /docker-entrypoint.d/20-wait-for-hosts.sh
wtfc.sh: waiting 30 seconds for ping -c1 -W1 postgres
wtfc.sh: ping -c1 -W1 postgres finished with expected status 0 after 0 seconds
Running /docker-entrypoint.d/30-configure-ssl.sh
Running /docker-entrypoint.d/40-consul.sh …
```

Add sync to prevent a 'Text file busy' error

---

.travis.yml

Ignore build failures on osx, treat them as advisory

(maint) allow osx build stages to fail

---

ext/test/upgrade-and-exit
src/puppetlabs/puppetdb/scf/hash.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/admin_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

Add a name column to the resource_events table that will be put to use
in a future PR. This column is needed to further guarantee uniqueness of
events.
Add more columns to the resource_events hash: timestamp, status,
old_value, new_value, message, file, line, name
Replace existing migration with a new migration that will rehash
the resource_events table again
Add an ON CONFLICT DO NOTHING to do the resource_events insert-multi to
ignore any duplicate hashes found. This can happen due to an agent bug
where the exec module can send duplicate events.

(PDB-4315) ignore duplicates in resource_events

---

src/puppetlabs/puppetdb/catalogs.clj
test/puppetlabs/puppetdb/catalogs_test.clj
test/puppetlabs/puppetdb/http/resources_test.clj
test/puppetlabs/puppetdb/testutils/resources.clj

In PUP-7579, Puppet added support for Unicode letters in resource tags,
but the supported tags regex was never changed in PuppetDB so any
catalogs using unicode resource tags would not be stored in PuppetDB.
This changes the tag regex in PuppetDB to allow all lower case unicode
letters as tags.

(PDB-4326) Allow unicode in resource tags

---

documentation/pdb_client_tools.markdown

Fixing a couple of incorrect paths. This fix should be merged forward as well. See DOC-4042 for details.

(DOCS) fixing an incorrect path

---

src/puppetlabs/puppetdb/scf/migrate.clj

Removing an existing migration causes puppetdb to throw a state
exception when it doesn't recognize the migration version number.

(PDB-4338) Re-add migration 67

---

src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/client.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/queue.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/http/command_test.clj
test/puppetlabs/puppetdb/queue_test.clj
test/puppetlabs/puppetdb/testutils.clj

This commit adds an atom which tracks commands that are enqueued but not
yet processed. The pdbext HA-sync code uses this atom to avoid enqueuing
duplicate commands when performing a sync.

(PDB-3742) Add atom to track enqueued commands

---

.gitattributes
.travis.yml
azure-pipelines.yml
docker/ci/build.ps1
docker/docker-compose.yml
docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh
docker/puppetdb/spec/puppetdb_spec.rb
docker/puppetdb/spec/spec_helper.rb

- Wait on Postgres port to be listening
- In Pupperware tests, waiting on the puppetserver to be listening
introduces additional wait time that appears to allow Postgres to
fully startup (preventing cluster start failures), which we don't
get the benefit of here
- This test suite isn't using puppetserver, so should instead rely on
waiting for Postgres
- Use docker-compose 1.24.0 in Travis
- Prune volumes / networks in Azure cleanup step
- Switch to using Linux Postgres container instead of unmaintained Windows Postgres container given our CI builders are now RS5
- Randomize the location on disk for Postgres data (to be outside of git checked out area)
- Refactor test failures modes in PuppetDB to catch all errors properly
- Remove usage of `Timeout` class for retrying operations and …

(maint) Rework tests for Linux Postgres container / Docker Compose

---

docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

- When firing up the PDB container, it was waiting 90 seconds by
default for Postgres to become available.
In CI environments like Azure, this appears to not be long
enough.
- Increase the timeout by a minute to 2:30

(maint) Increase default PDB Postgres wait time

---

.travis.yml

Our AdoptOpenJDK packages on MacOS are a nightmare to manage due to
their unmodified cacert. This problem is resolved in JDK 11 so we will
only be running OSX tests on JDK 11 for increase PuppetDB team sanity.

(maint) travis: osx: Remove jdk8 testing

---

ext/travisci/prep-os-essentials-for

Remove mongodb and CouchDB repositories from /etc/apt/sources.list.d/
Update git-lfs repo key
Add a retry to apt-get update when the mirror is out of sync.
When this happens, the failure similar to:
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release: The following signatures were invalid: KEYEXPIRED 1515625755
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: …

(maint) handle apt-get update failures

---

docker/puppetdb/Dockerfile

The CRL isn't necessary here in PuppetDB but update to the latest
version of this script anyway for consistency across the containers.

(MAINT) Use new ssl.sh that gets the CRL

---

test/puppetlabs/puppetdb/http/events_test.clj
test/puppetlabs/puppetdb/query/events_test.clj

Change is-query-result to a macro so it will report the expansion line
number for a failure rather than the function's line numbers.
Make sure the expected values are first in the test assertions.

(PDB-4345) Improve test failure output for events_tests

---

documentation/api/query/v4/events.markdown
documentation/api/query/v4/reports.markdown
documentation/api/wire_format/report_format_v8.markdown
puppet/lib/puppet/reports/puppetdb.rb
puppet/spec/unit/reports/puppetdb_spec.rb
src/puppetlabs/puppetdb/query.clj
src/puppetlabs/puppetdb/query/events.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/reports.clj
src/puppetlabs/puppetdb/scf/hash.clj
test/puppetlabs/puppetdb/examples/reports.clj
test/puppetlabs/puppetdb/http/events_test.clj
test/puppetlabs/puppetdb/testutils/reports.clj

Add the name column to the terminus so it's sent to puppetdb
Populate the name column that was previously added to the database in
PDB-4315

(PDB-4345) populate name column in resource_events

---

docker/puppetdb/Dockerfile

- This version adds 5 curl retries with a delay of 2 seconds to work
around transient issues
Even though the waiter scripts seem to be properly waiting for
containers to initially become available at their designated
names, there are still transient failures that occur when performing
various curl commands while handling certs

(maint) Upgrade to latest copy of ssl.sh

---

docker/puppetdb/Dockerfile
docker/puppetdb/healthcheck.sh

- The previous format can confuse LCOW and result in errors like:
CreateProcess: failure in a Windows system call: Unspecified error (0x80004005)
[Event Detail: failed to run runc create/exec call for container
- Puppetserver is using this style with success

(maint) Refactor PDB Docker HEALTHCHECK

---

docker/README.md
docker/puppetdb/Dockerfile
docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

-  New variable `PUPPETSERVER_PORT` is added that defaults to 8140
- Rename wait_for_host to wait_for_host_name_resolution to better
reflect its purpose.
Change it's behavior to use the host command (which returns proper
exit codes) instead of using ping. ping will not work in a k8s
environment where hosts are not reachable by ping
- After succeeding or failing DNS lookup with the host command,
emit the dig output for that lookup for the sake of logs
- There appear to be many reported issues against Alpine DNS. This
is an attempt to work around the ones we're experiencing.
- In local testing (specifically under LCOW), DNS resolution under
Alpine seems to be very problematic.
`nslookup` may repeatedly fail to perform a DNS resolution against
another container name like `puppet.local` …

(maint) Docker DNS reliability improvements

---

docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

- Running `dig` always yields a non-zero exit code. Capture the exit
status of the wtfc.sh helper script when querying the name with host
which yields a non-zero exit code on failure.
This ensures that initial lookups fail the entrypoint script as
desired, rather than continuing on

(maint) Exit Docker wait script properly

---

docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

- Unexpectedly, a Travis failure was also encountered where 30 seconds
of running `host postgres.internal` failed, but the immediately
subsequent call to `dig postgres.internal` succeeded.
Running dig seems to prime a local cache, so perform a dig prior
to host in an effort to help fix this problem, given the PDB
container is based on Alpine
https://github.com/Microsoft/opengcs/issues/303

(maint) Docker dig names prior to running host

---

.travis.yml
docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

- The host command may return non-zero exit codes when the given host
is missing certain record types. For instance:
/ # host www.google.com
www.google.com has address 172.217.3.196
www.google.com has IPv6 address 2607:f8b0:400a:803::2004
Host www.google.com not found: 3(NXDOMAIN)
/ # echo $?
1
- If the record type is limited to A records for IPv4, the same query
returns the expected 0 exit status
/ # host -t A www.google.com
www.google.com has address 172.217.3.196
/ # echo $?
0
- In TravisCI, failures are cropping up when puppetdb looks up the
postgres container via the network alias postgres.internal and
this should help to alleviate that problem

(maint) Only query host A records in Docker waiter

---

.travis.yml
docker/Makefile

Bundle installing / bundle execing with an RVM project in travis gets
complicated when there's a Gemfile at the root of your repo and you're
trying to use a gemfile from a different directory.
This makes sure we're setting the BUNDLE_PATH and BUNDLE_BIN environment
variables, and explicitly passes the path for the Gemfile for all bundle
commands.

(maint) Update Makefile / .travis.yml to use rvm

---

docker/puppetdb/docker-entrypoint.d/40-consul.sh

We should run this check every 10 seconds to decrease latency with consul knowing what services/hosts are available

(maint) If consul is enabled, run the http healthcheck every 10 seconds

---

acceptance/helper.rb

Revert this commit once we've resolved PDB-4373

(PDB-4374) Add workaround for centos6 :upgrade_oldest tests

---

src/puppetlabs/puppetdb/scf/migrate.clj

Prevent rededuplicate-facts migration failures caused by orphaned
facts that have no path in fact_paths.  For example:
ERROR [p.p.s.migrate] Caught SQLException during migration
java.sql.BatchUpdateException: Batch entry 3 ALTER TABLE facts ADD CONSTRAINT fact_path_id_fk
FOREIGN KEY (fact_path_id)
REFERENCES fact_paths(id) was aborted. Call getNextException to see the cause.
at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:133)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2004)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:360)
at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1019)
at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:125)
at …

(PDB-3840) Fix rededuplicate migration crash; rm values with no path

---

acceptance/helper.rb

Installation from git source in acceptance tests is broken so it doesn't
make sense as a default.
This also removes the package fall back when the repo configuration was
missing and forces you to use the install_type: :package setting
instead.

(maint) acceptance: Use package install by default

---

docker/puppetdb/Dockerfile

The new version fails immediately if the CA already has an unsigned CSR
for this host, instead of waiting for the signing timeout to occur.

(MAINT) Use latest ssl.sh in image

---

src/puppetlabs/puppetdb/scf/storage.clj

Temp tables *are* unlogged tables[1], not vice versa (as had been
assumed), so change the gc table to a temp table.
Since unlogged tables aren't temp tables, you could see a table name
conflict if, for example, multiple gc attempts ran simultaneously:
WITH recursive live_paths(path, value) AS
...
SELECT path
INTO   unlogged tmp_live_paths
FROM   live_paths
was aborted: ERROR: relation "tmp_live_paths" already exists
...
[1] https://rhaas.blogspot.com/2010/05/global-temporary-and-unlogged-tables.html

(PDB-4347) Make fact path gc table temp, not unlogged

---

src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

Replace use of MD5 in aggregate functions with SHA1. FIPS discourages
the use of MD5, and this aggregate is used in queries (not stored to the
database) in PE.

(PDB-4356) switch to sha1 from md5

---

ext/bin/test-config
ext/bin/wrtrepo

Given a ref, report if that ref isn't included in the most recent
version of any release branch (any *.x branch) that it's on.
If nothing else, this might make computing fixversions easier, e.g.:
$ ext/bin/wrtrepo ref-lands-where HASH
New in release after 5.2.8 of refs/remotes/origin
New in release after 6.0.3 of refs/remotes/origin
New in release after 6.3.2 of refs/remotes/origin
$ ext/bin/wrtrepo ref-lands-where HASH
Appears to have been released
Note that the tool doesn't try to guess about what the next release on
a branch will be, since it could be an X, Y, or Z.

(maint): add "wrtrepo ref-lands-where REF" utility

---

src/puppetlabs/puppetdb/command.clj
test/puppetlabs/puppetdb/command_test.clj

If a certname contain invalid characters for the queue metadata, such as
an underscore, or if it is too long it will be coerced and a hash of the
original will be appended to the end. For replace-catalogs, this
certname would end up getting stored in the database (only after PDB-4257).
Now the certname is correctly read out of the command payload (the
uncoerced value) and stored properly.

(PDB-4390) Store the uncoerced catalog certname

---

src/puppetlabs/puppetdb/scf/migrate.clj

PostgreSQL 9.6.14 introduced a bug:
BUG #15865: ALTER TABLE statements causing "relation already exists" errors when some indexes exist
See: https://www.postgresql.org/message-id/15865-17940eacc8f8b081%40postgresql.org
This will make any ALTER TABLE statement only affect a single column per
statement.

(maint) workaround postgresql bug #15865

---

ext/bin/pdbbox-env
ext/bin/pdbbox-init
ext/bin/require-pgbox
ext/bin/with-pdbbox

Add IPv6 support to pdbbox. Allows a pdbbox sandbox to initialize with
IPv6 support, IPv4 support, or both. IPv4 defaults to on, IPv6 defaults
to off.

(PDB-4360) add IPv6 support to pdbbox

---

src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query/facts.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/hash.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/testutils/facts.clj

This adds support for the include_package_inventory query option, which
when provided will re-create the original wire format of
package_inventory.
This is intended to support proper syncing of factsets in PE.

(PDB-4266) Add include_package_inventory flag to factsets query

---

azure-pipelines.yml

If a PR is opened on the main repo (and not a fork) we want to prevent
Azure from triggering 2 runs.

(MAINT) Prevent Azure double builds

---

ext/bin/require-leiningen

While pdb doesn't require it yet, let's make sure it works, since
we'll need it for trapperkeeper 3+.

(PDB-4449) travis: test against lein 2.9.1

---

src/puppetlabs/puppetdb/scf/migrate.clj

Prior to this commit, the factsets, catalogs, and certnames tables
were autovacuumed far too frequently.
This commit changes the percentage change before the table
is considered for autovacuuming.  The way these tables are
inserted and updated apparently moves the counter for changes
forward when the rows can't be reclaimed.

(PDB-3745) Increase autovacuum vacuum scale factor

---

puppet/lib/puppet/util/puppetdb/http.rb
puppet/spec/unit/face/node/status_spec.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
puppet/spec/unit/indirector/facts/puppetdb_spec.rb
puppet/spec/unit/indirector/node/puppetdb_spec.rb
puppet/spec/unit/indirector/resource/puppetdb_spec.rb
puppet/spec/unit/reports/puppetdb_spec.rb
puppet/spec/unit/util/puppetdb/command_spec.rb
puppet/spec/unit/util/puppetdb/http_spec.rb

As part of ongoing work to improve SSL initialization in Puppet,
PUP-9513 is deprecating Puppet::Network::HttpPool.http_instance() that
relied on the old Puppet::SSL::Host in favor of a newer HttpPool.connection()
method that uses the new Puppet::SSL::SSLContext.
This patch updates the Puppet::Util::Puppetdb::Http class to use
Puppet::Network::HttpPool.connection(). The SSLContext object is
obtained from Puppet's base_context via Puppet.lookup.
Specs are updated to match.
This paves the way for these methods to be removed in Puppet 7, and
clears up warnings that were being emitted with Puppet 6.7.1-42-gc60d6aaa88
(and PE 2019.2.x) when Puppet::Util::Puppetdb initializes a connection.

(PUP-9513) Change http_instance to connection

---

azure-pipelines.yml

- Don't rely on defaults for Lint-Dockerfile as they will be removed.
Instead, specify all explicitly.
This further standardizes the YAML

(maint) Specify all Docker lints as data for Azure

---

src/puppetlabs/puppetdb/command.clj

An incorrect keyword used to look up the command name
for 'replace catalog inputs' commands caused a log message like
`'null' command processed for new-host` to be printed.

(PDB-4372) Log command name for replace catalog inputs

---

docker/puppetdb/Dockerfile

- Alpine seems to still be having issues with DNS resolutions inside
an LCOW environment. In an effort to reduce these transient
problems, switch the base container to a non-Alpine platform.
A ticket has been filed with a repro for Alpine DNS issues under LCOW
https://github.com/docker/libnetwork/issues/2371
- While this may increase the image size by about 100MB, the goal here
is reliability and robustness
for the builder container:
clojure:lein-alpine was about 142MB
clojure:openjdk-8-lein is about 507MB
for the target container:
openjdk:8-jre-alpine was about 85MB
openjdk:8-buster-slim is about 184MB
- Ubuntu 18.04 shares a lineage with debian buster, which should
be a well supported platform for PDB
All OpenJDK container variants are listed at: …

(maint) Switch PDB container off of Alpine

---

docker/puppetdb/ssl-setup.sh

Contains a fix for #3040 
- When the base container image was changed from Alpine Linux to
Debian Slim Buster in #3040, the /bin/sh implementation changed.
3c876e5847915fd769976a382b1dc3f890809019 merged this code
On Alpine, /bin/sh is the standard bare-bones cross-platform
Bourne Shell.
On Debian, /bin/sh is a symlink to dash.
- Update shellscript syntax to be compatible with Dash.

(maint) Fix Docker ssl-setup.sh for Debian / Dash

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/command_test.clj

I imagine we'll eventually want an index anyway, that'd end up
requiring uniqueness, but for now suppress them so that they won't be
visible to queries, etc.

(PDB-4482) Suppress duplicate catalog inputs on ingestion

---

documentation/release_notes.markdown
documentation/release_notes/release_notes_6.5.markdown

Symlinked release_notes.markdown to the new file:  release_notes/release_notes_6.5.markdown

(docs) Adding release notes for 6.5.0

---

docker/.rspec
docker/docker-compose.yml
docker/spec/puppetdb_spec.rb

- pupperware stack is using this as a healthcheck, which allows
replacing any calls to PDB specific waiters with a generic
health waiter

(maint) Add Postgres pg_isready based healthcheck

---

docker/docker-compose.yml

- pg_isready is insufficient for determining that the Postgres database
is "healthy", since it seems to return a 0 exit code, even for
invalid user names or invalid databases
- Instead use a similar check to what spec helpers used to do (i.e.
establishing that the puppetdb database can be connected to from
the puppetdb user - this is equivalent to counting databases in the
postgres system table)
Adapted from https://stackoverflow.com/questions/14549270
- Examples of what the script reports to docker when the database is
not reachable (from `docker inspect`)
```json
"Health": {
"Status": "healthy",
"FailingStreak": 0,
"Log": [
{
"Start": "2019-08-20T22:49:19.4322016Z",
"End": "2019-08-20T22:49:19.7158295Z",
"ExitCode": 2,
"Output": "psql: could not connect to server: No such file or …
```

(maint) Update Docker Postgres healthcheck

---

.travis.yml

with clj-parent 4.0.4, you cannot run puppetserver 6.4 in the same JVM
as puppetdb. We will address this in a future change to run puppetserver
and puppetdb in separate JVMs.

(maint) disable tests that cannot pass

---

puppet/lib/puppet/util/puppetdb/config.rb
puppet/lib/puppet/util/puppetdb/http.rb
puppet/spec/unit/util/puppetdb/config_spec.rb
puppet/spec/unit/util/puppetdb/http_spec.rb

As part of work to migrate to `Puppet::SSL::SSLContext`, we have unintentionally broken
compatibility with standalone/masterless nodes, who don't have a local CA or cert chain
to validate.
This commit introduces a new configuration variable (name TBC), and uses it to either
inherit from Puppet's SSL context (if we are running with a master and certificates)
or allows simple CA/CRL validation in the event that the PuppetDB server is using
either self-signed or commodity certificates.
Handoff to Puppet for these settings is via the configuration options `localcacert`
and `certificate_revocation` - if using a commodity certificate, `localcacert` should
be pointed to your OS local trust-store, and `certificate_revocation` set to `false`. If
using a self-signed certificate, this needs to be …

(PDB-4487) Fixing Standalone Nodes using SSLContext

---

src/puppetlabs/puppetdb/jdbc.clj

The failfast property of HikariCP is deprecated and replaced with a
failtimeout.
Our previous setting of failfast=false would not error when the
minimum number of connections could not be obtained. The new fail
timeout setting of less than zero will mean the pool will start
immediately, and it will not timeout if it can't establish the minimum
number connections.

(maint) Change HikariCP FailFast to FailTimeout

---

src/puppetlabs/puppetdb/query_eng/engine.clj

Prior to this commit the catalog-inputs-query would return rows for
any entry in the certnames table even if that entry didn't have inputs.
This would cause a validaion error in the row munging function.

(maint) Change order of left-join for catalog-inputs query

---

acceptance/setup/pre_suite/75_clean_out_puppet5_repos.rb

During an upgrade_oldest test, the config file of puppetserver
had changed so the install of the new puppetserver was hanging
on confirming what to do with the changed conf file. Now it will
always take the new config file.

(maint) Fix install of puppetserver

---

project.clj

Longer term excluding the bouncycastle jar from the uberjar and loading
either the standard or the FIPs version at runtime is likely simpler,
but for now, the infrastructure for that does not exist so we'll revert
to building either a standard uberjar or a FIPs uberjar (with the fips
profile).

(maint) Re-add bouncycastle to uberjar

---

acceptance/setup/pre_suite/15_setup_repos.rb
project.clj

Ezbake does not use the :uberjar profile, so
it could not find any bouncycastle library.

(maint) Add bouncycastle to ezbake profile

---

docker/.rspec

We already fail fast when the :before block errors, and we'd prefer to
run all tests if we get out of that block.

(MAINT) Remove --fail-fast

---

docker/spec/puppetdb_spec.rb

- wait_on_service_health now sets the default timeout based on the
definition of the healthcheck for a container (whether in the
Dockerfile or docker-compose.yml)
- get_service_container also has a normal reasonable default which
should not be modified here

(maint) Remove explicit Docker spec timeouts

---

documentation/connect_puppet_apply.markdown
documentation/release_notes/release_notes_latest.markdown

This configuration option was added to allow SSL connections to be made
between Puppet and PuppetDB when they are not using the Puppet Server
CA.

(docs) Add documentation for 'verify_client_certificate'

---

project.clj
src/puppetlabs/puppetdb/scf/migrate.clj

Log "Migrated X of Y events" roughly once per minute during the
migration so that you can fairly quickly estimate about how long it
might take, and can see that it's making progress.

(PDB-4505) Log progress during resource-events-pk migration

---

documentation/api/metrics/v1/mbeans.markdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/queue.clj
test/puppetlabs/puppetdb/command_test.clj

This commit adds a metric that tracks the number of commands which are
"bashed" in the command queue.

(PDB-4278) Add metric that tracks "bashed" commands

---

docker/docker-compose.yml
docker/puppetdb/Dockerfile
docker/puppetdb/logging/logback.xml
docker/puppetdb/logging/request-logging.xml
docker/spec/puppetdb_spec.rb

- Dockerfile was copying 2 files that were unused. Restore the default
logging configuration files to write to files in addition to STDOUT
Since PDB was already configured to remove timestamps over STDOUT in the logback.xml, keep it configured as such (Docker also emits timestamps, so dupes are not needed)
- It turns out that LCOW has a bug with permissions on Docker VOLUMEs which is why Postgres Linux container won't start by default. This issue is filed as https://github.com/moby/moby#39922
For now, our hosts have granted permissions to the group that runs
all containers (NT VIRTUAL MACHINE\Virtual Machines) so that symlinks
can be created inside NTFS backed VOLUMEs for Linux containers, as
is required for Postgres container initialization
- Based on the container configuration, there …

(maint) Specify Docker volumes explicitly

---

docker/puppetdb/conf.d/jetty.ini
docker/puppetdb/docker-entrypoint.d/30-configure-ssl.sh

Should have been included in #3082 (specifically as part of https://github.com/puppetlabs/puppetdb/pull/3082/commits/713b736c9721d931774f6250ded57d73ccdcfdb0)
- Disable all ssl-* settings in jetty.ini initially, and only
enable them when USE_PUPPETSERVER is on (the default).
Otherwise, only listen on non-HTTP port 8080 and leave SSL
unconfigured

(maint) Fix Docker Jetty SSL configuration

---

docker/puppetdb/docker-entrypoint.d/30-configure-ssl.sh

- In some instances, users may be deriving from this container to
specify well-known cert files (as is the case with Bolt specs).
In this case, users are setting USE_PUPPETSERVER=false, but still
desire SSL to be configured in Jetty, based on well known certs
that have been supplied.
- Adjust the script for these cases:
* Only generate certs through puppetserver when no cert files are
on disk *and* USE_PUPPETSERVER=true
* When a private key exists at $SSLDIR/private_keys/$CERTNAME.pem:
* always generate a corresponding pk8
* always create / overwrite symlinks for Jetty
* always enable SSL in Jetty
* always correct ownership / perms
This will handle scenarios where SSL files have been generated,
or when they've been supplied by a user (as in the Bolt case)

(maint) Make Docker SSL configuration flexible

---

src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

This commit updates the add-resource-events-pk migration to perform
insertions in batches of 1000 when re-writing the resource_events
table to add a primary key.

(PDB-4504) Use batched inserts for add-resource-events-pk

---

documentation/README.md

Adding a README to explain to users why they might have been redirected here, and how they can find what they really need.

(docs) explain docs redirect

---

docker/puppetdb/Dockerfile

- There is a race in container startup where Java may not have a
proper log directory to write to, and will fail with:
OpenJDK 64-Bit Server VM warning: Cannot open file /opt/puppetlabs/server/data/puppetdb/logs/puppetdb_gc.log due to No such file or directory

(maint) Ensure Docker log directory exists

---

docker/puppetdb/docker-entrypoint.d/00-lcow-volume-fix.sh

Follow on to #3092 to handle a specific LCOW issue
- Due to the LCOW bug https://github.com/moby/moby#39892 make
certain that the logs path also exists in the LCOW volume before
starting any applications

(maint) Create LCOW logs path in VOLUME

---

Gemfile

This commit renames the environment variable used to override the version of
the packaging dependency. `PACKATING_LOCATION` is the name used everywhere else
(in other projects and in shipping automation), so things break without this.

(maint) Rename `PACKAGING_VERSION` to `PACKAGING_LOCATION`

---

documentation/api/command/v1/commands.markdown
puppet/lib/puppet/util/puppetdb/command.rb
src/puppetlabs/puppetdb/middleware.clj
test/puppetlabs/puppetdb/integration/puppetserver_metrics.clj
test/puppetlabs/puppetdb/middleware_test.clj

The 'Content-Length' header isn't sent when commands are compressed in the
terminus. As a result the PDB size metrics aren't updated and the
'max-command-size' configuration option which relies on 'Content-Length'
doesn't function as intended.
This commit adds a custom 'X-Uncompressed-Length' header to requests
sent from the terminus. The value of this header is the size in bytes of
the command before it is compressed. This value is used to update
the size metric and to decide when to discard commands based on
'max-command-size'.

(PDB-4502) Add a custom header for uncompressed command size

---

src/puppetlabs/puppetdb/cli/services.clj
test/puppetlabs/puppetdb/cli/services_test.clj

If a puppetdb was applying migrations on a database with `standard_conforming_strings = off` it would previously error with
```
2019-09-18T13:31:10.415-04:00 INFO  [p.p.s.migrate] Applying database migration version 43
2019-09-18T13:31:10.456-04:00 ERROR [p.p.s.migrate] Caught SQLException during migration
java.sql.BatchUpdateException: Batch entry 1 CREATE AGGREGATE sha1_agg (BYTEA)
(
sfunc = dual_sha1,
stype = bytea,
initcond = '\x00'
) was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00
```
Now it will recognize the invalid configuration and exit after printing
```
********************
*
* Invalid database configuration settings: 'standard_conforming_strings' (expected 'on', got 'off')
*
********************
```

(PDB-4509) Throw error for invalid database configuration

---

docker/puppetdb/docker-entrypoint.d/30-configure-ssl.sh

- Docker supplies the HOSTNAME value, which may be different from how
host recognizes its hostname setting (short and fully qualified).
While these values may be duplicated, that's OK b/c the ssl.sh
script doesn't care if names are duplicated.
- NOTE: hostname -s / hostname -f doesn't properly return under LCOW
like it does on Linux, and always returns the short name

(maint) Use all hostnames for Docker DNS_ALT_NAME

---

Gemfile
Rakefile
dev-docs/README.md
dev-docs/release/reconciliation.md

I've had this script locally for a while now, but wanted to add it
to the repo (with docs :) ) in the hope that it might be of use more broadly

(maint) Add ticket reconciliation task as a Rake task

---

project.clj

This stops us from building fips packages for FOSS

(maint) Bump ezbake to 2.1.5

---

docker/puppetdb/docker-entrypoint.d/30-configure-ssl.sh

@Iristyle I'm not sure if there was something that required having DNS_ALT_NAMES for the puppetdb container always, but that change could break setups where puppetserver doesn't have DNS alt names enabled in the CA.

(PDB-4540) Only set DNS_ALT_NAMES if an alt name is provided

---

src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/command/constants.clj
src/puppetlabs/puppetdb/nodes.clj
test/puppetlabs/puppetdb/command_test.clj

I can handle merge ups when this goes in. It's going to conflict with the other pr against 6.3.x

(PDB-4547) Add wireformat validation for deactivate node cmds

---

azure-pipelines.yml
docker/puppetdb/Dockerfile
docker/puppetdb/docker-entrypoint.d/20-wait-for-hosts.sh

- Set reasonable upper bounds for various stages in Azure to abort
jobs quickly when Docker misbehaves
- Reduce both the start period by 2m and increase the retries
by 1m to overall reduce wait time from 6m to 5m
- This time only needs to be longer than Postgres, which has a
healthcheck timeout defined in docker-compose (given its the
stock container), but which typically starts under LCOW in
about 2m
Additional time allotted is to cover migrations
- Restructure the scripted waiter to wait in the correct order for
services (matching pe-puppetdb), and also to ensure that it roughly
considers time already elapsed, rather than continually adding time.
Even though SSL is not enabled here, the order is kept the same as
pe-puppetdb for consistency:
puppetserver
postgres
Once Postgres is up, …

(maint) Update healthcheck timeouts

---

Rakefile

The Jira query would fail if the fixVersion does not exist. This will
allow that to fail and print an error message before checking for git
commits since the last tag

(maint) Allow Jira query failure for fixVersion

---

azure-pipelines.yml

- Undoes #2861 / 39f6bbbd467d0970140a7cddcdf9d42ebdb64d06 which disabled
builds on this branch.
Not sure why we did that at the time, but since we're still shiping
2019.1.2 off of 6.3 and other PRs have targeted the 6.3 branch,
let's turn Azure back on for pull requests

(maint) Re-enable Azure PRs on 6.3.x branch

---

docker/puppetdb/Dockerfile

- Based on the removal performed in pe-puppetdb-extensions,
make this consistent based on the conversation that IPv4 is no
loger necessary to prefer.
PR https://github.com/puppetlabs/pe-puppetdb-extensions/pull/498/
https://github.com/puppetlabs/pe-puppetdb-extensions/commit/db8c43847b25e434d21db45f3352ef7828a20a57

(maint) Remove IPv4 stack preference in Docker

---

project.clj

This addresses CVE-2019-14439, which affects logback

(PDB-4576) Update jackson-databind to 2.9.10

---

project.clj

clj-parent differences since 2.6.0
- updated jackson-databind for CVE-2019-14439
- updated jvm-ssl-utils for minor security fixes
- nrepl updates
- use clojure 1.10.1

(PDB-4576) Update clj-parent to 2.7.2

---

project.clj

Changes since 4.2.4
- updated jackson-databind for CVE-2019-14439
- updated trapperkeeper-webserver-jetty9 to fix excessive loggings and
FIPS cipher-suite
- updated dujour-version-check for FIPS and Java 11

(PDB-4576) Update clj-parent to 4.2.6

---

src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/middleware.clj
test/puppetlabs/puppetdb/middleware_test.clj

See the commit messages for additional context -- this is intended as underpinnings for the drop-joins parameter in master, but I thought we might want to consider laying the foundations in 5.2 to help minimize future merge conflicts (assuming we're comfortable with making the changes there otherwise).  I've added the don't merge tag for now, because we'll need some coordination, e.g., I'll need to rebase the corresponding master pr onto these change.

(PDB-4512) Centralize query params and provide global set

---

src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query_eng.clj

This will need to be rebased on top of #3143 once it's merged -- it contains all of those changes, plus the few drop-joins related changes that were relevant to 6.3 (e.g. include_facts_expiration).

(PDB-4512) Allow include_facts_expiration everywhere

---

documentation/api/admin/v1/cmd.markdown
src/puppetlabs/puppetdb/admin.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/pdb_routing.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/admin_clean_test.clj

This command allows for the immediate deletion of all data associated with the
certname in the command payload.

(PDB-3300) Add admin delete node command

---

src/puppetlabs/puppetdb/reports.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/testutils/nodes.clj

A report with no events does not get the latest_report pointer in its
certname entry set. This occurred because of a nesting error.
The schema for reports does not allow an empty set of events, but that
was only used at testing time. In production, this happens frequently
(due to truncation of the resource events table, and other conditions.)

(PDB-4590) store reports with no events properly

---

.travis.yml
ext/travisci/prep-os-essentials-for
test/puppetlabs/puppetdb/testutils/db.clj

Apply an ordering to the indexes-sql results, so that all versions of
postgresql return this the same.
pgsql 12 has a different default ordering than 9.x and 11.

(PDB-4577) fix tests for pgsql 12

---

project.clj

PostgreSQL JDBC driver has a bug where the isValid() call on a
connection does not respect timeouts. This causes our connection pool to
not detect a dead connection, which will eventually exhaust our
connection pool entirely. See pgjdbc/pgjdbc#1557
This fix is specific to PuppetDB 5.2.x and should not be applied to
newer branches.

(PDB-4579) fix connection tests

---

.github/workflows/docker.yml
docker/Makefile
docker/distelli-manifest.yml

Pipelines is EOL Jan 31, so we need to migrate to something else. This
adds a github action to lint, build, test, and publish containers on
pushes to the master branch.
Pipelines auto-builds have been disabled and necessary secrets have been
added to the puppetdb github repo.

(maint) Migrate container builds from pipelines to GitHub Actions

---

src/puppetlabs/puppetdb/query_eng/engine.clj

This proved useful when working on the query engine, making it
immediately obvious which query is involved when looking at the query
records during the compilation process (for example, inside
compile-user-query->sql).

(PDB-4512) engine: add ::which-query annotations

---

project.clj

This has changes to clj-http-client that are necessary for Java 11

(maint) Bump clj-parent to 4.2.11

---

src/puppetlabs/puppetdb/scf/migrate.clj

The query to determine which partitions to create in advance of the
migration uses the postgresql function date_trunc, which will work and
match the trigger and other code if you do not attempt to coerce to UTC
at the same time.
Tested by switching my local machine to CET (UTC+01:00) and running the
tests, to match the customer use-case.

(PDB-4626) date_trunc uses different semantics

---

ext/travisci/prep-os-essentials-for

A dependency now requires ruby 2.4 or greater

(maint) travis: bump ruby version

---

.travis.yml

The 5.3.x branch on puppetlabs/puppetdb was deleted

(maint) travis: Remove testing for EOL puppet

---

ext/travisci/prep-os-essentials-for

This avoid using the system ruby which is ruby2.3

(maint) travisci: pyenv hasn't been updated in travis

---

src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/generative/submit_command.clj
test/puppetlabs/puppetdb/http/facts_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj
test/puppetlabs/puppetdb/testutils/events.clj
test/puppetlabs/puppetdb/testutils/http.clj
test/puppetlabs/puppetdb/testutils/reports.clj
test/puppetlabs/puppetdb/testutils/services.clj

This modifies the definition of inactive_nodes in the query engine to
omit nodes that are eligible for garbage collection. These nodes are in
essence 'dead', in that the only reason we haven't deleted them is we
haven't hit the user's gc-interval.
We add an explicit definition of active_nodes because an "active node"
was previosuly defined as the complement of inactive_nodes and we
obviously don't want nodes that have been inactive for `node-purge-ttl`
and about to be garbage collected to temporarily enter "active" status.
The new definition for active_nodes is logically equivalent to the
complement of the _old_ definition of inactive_nodes because the
criteria for being an active node has not changed.
This solves a problem in pe-puppetdb where a node would be garbage
collected on one …

 (PDB-4479) Omit "gc-able" nodes from queries for inactive nodes

---

src/puppetlabs/puppetdb/command/constants.clj
src/puppetlabs/puppetdb/http/command.clj
src/puppetlabs/puppetdb/middleware.clj
test/puppetlabs/puppetdb/integration/puppetserver_metrics.clj

Prior to this commit duplicate metrics could be created for incoming commands.
When the create-metrics-for-command! func was called with the query param
command name directly it would create a metric entry for "store_report" when all
other metrics updates used the normalized name "store report". This commit fixes
this issue for all command types so the normalized name is now used everywhere.

(PDB-3417) Normalize all command metric names

---

src/puppetlabs/puppetdb/constants.clj
src/puppetlabs/puppetdb/http/server.clj
src/puppetlabs/puppetdb/middleware.clj
test/puppetlabs/puppetdb/http/sync_version_checking.clj

This commit adds checking for the x-pdb-sync-ver header which is sent from
all pe-puppetdb sync requests. If there is a mismatch detected the incoming
sync request will receive a 409 conflict response until it is upgraded and
starts emitting a matching sync version. This is needed during pe-puppetdb
ha-sync to detect and avoid syncing with a pdb that has been recently upgraded
in a way that's not backwards compatible.

(PDB-4552) Add support for checking x-pdb-sync-ver header

---

ext/test/upgrade-and-exit
src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

Without this, the index could introduce a breaking change for FOSS users
not following the recommendation of installing `pg_trgm` and
unwilling/unable to install it from the postgresql-contrib pacakge.
Instead we make this index optional for now, deprecate running without
`pg_trgm` and will require `pg_trgm` in a later release.

(PDB-4640) Make catalog resources file trgm index optional

---

src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/partitioning.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

Force the timezone to UTC for determining the unique dates of
resource_events.
PostgreSQL returns dates in the client's timezone. What we need to do
here is force the connection into UTC. We want the date of the event, in
UTC, so that we can create the partition for it. To do this, we have the
find_resource_events_unique_dates plpgsql function above. For the
duration of this migration transaction, dates will be displayed in UTC.
If the timezone is in the local timezone (say, EST, or CEST), you get
the date in that timezone with the time cut off. So,
2020-01-30T05:00:00Z, which truncates to 2020-01-30 using the pgsql date
functions. In reality, this is actually 2020-01-31 in UTC, which is the
date we need for creating the partition successfully.

(PDB-4641) get unique dates properly in UTC

---

documentation/configure.markdown

Add documentation for config options added by PDB-3747 and PDB-3751.

(docs) Add documentation for two [sync] options

---

documentation/configure.markdown

This parameter no longer has a default for 5.2.x, while unset it
does nothing

(docs) Update initial-report-threshold docs

---

.github/workflows/docker.yml
docker/Makefile

In our github actions configuration, we always want to try to make a release
build so that we don't have to kick that off manually. But we also only
want to build and publish a release build if it doesn't already exists.
This adds some safeguards so we don't try to build the release build yet
if it hasn't been published and updated in dujour, and also so that we
only build and publish the release build if we haven't already pushed
that tag.

(maint) Only build a release build if it makes sense

---

ext/bin/run-external-tests
ext/test/database-migration-config
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/core.clj
src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/admin_clean_test.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/testutils/db.clj

This won't have the custom exit status values until we have a tk that supports them (i.e. maybe not in 5.2.x.), and you should be able to run the new `ext/test/database-migration-config` test directly.
Suggest looking at the individual commits and commit messages, and in some cases ignoring whitespace may make it easier to follow along.
Oh, and we'll also have backtraces being dumped when migration is rejected until we have the newer tk, where we can make the handling friendlier.

(PDB-4636) Allow disabling migrations

---

ext/test/upgrade-and-exit
src/puppetlabs/puppetdb/scf/hash.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/partitioning.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/examples/reports.clj
test/puppetlabs/puppetdb/http/events_test.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/integration/reports.clj
test/puppetlabs/puppetdb/scf/hash_test.clj
test/puppetlabs/puppetdb/scf/migrate_partitioning_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

Partition the reports table on producer_timestamp. This creates
a partition per day, and allows garbage collection to occur by
dropping expired tables. This follows the same pattern as PDB-4420.
The report hash has been changed to remove resource_events from the
hash calculation. The resource_events table can be garbage collected
separately from the reports table, and if the hash is still including
the resource_events, we end up with duplicate reports during a pdb
sync. The hash is rewritten during the migration.
There is no trigger to direct inserts to the appropriate partition.
This is because the usage of the reports table relies on the behavior
of a RETURNING clause on the INSERT INTO statement. You cannot rewrite
the query and combine it with a RETURNING clause. All INSERTs occur …

(PDB-4606) partition the reports table

---

documentation/configure.markdown
ext/bin/run-external-tests
ext/test/schema-mismatch-causes-pdb-shutdown
src-gems/puppetlabs/puppetdb/integration/install_gems.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/jdbc.clj
test/puppetlabs/puppetdb/config_test.clj
test/puppetlabs/puppetdb/migration_coordination_test.clj

This commit uses the HikariCP connectionInitSql option to block the creation of
new connections when there is a migration mismatch detected between the database
and PDB. This guards against a situation that could arise with PDB on compilers
where the database is migrated to a newer version before the local PDB has been
upgraded.

(PDB-4639) Add connection init check to Hikari pools

---

project.clj

This version was released publicly to clojars.
4.3.3 was an internal-only release

(maint) Bump clj-parent to 4.4.1

---

project.clj

This version was released publicly to clojars.
1.2.1 was an internal-only release

(maint) Bump tk-metrics to 1.2.2

---

resources/ext/cli/delete-reports.erb

In the ezbake packaging process, the `:build-type` option is converted
to `:is-pe-build` boolean, it is true only if `:build-type` is `"pe"`.
The rename happens in clojure [here](https://github.com/puppetlabs/ezbake/blob/master/src/puppetlabs/ezbake/core.clj#L623-L624).
An example usage of `:is_pe_build` can be seen [here](https://github.com/puppetlabs/ezbake/blob/72c9a33a01f15cb4b24800979848d60dfac88c8c/resources/puppetlabs/lein-ezbake/template/global/controller.sh.erb#L160-L162).

(PDB-2398) Fix ezbake config `:build-type` is `:is_pe_build`

---

src/puppetlabs/puppetdb/scf/storage_utils.clj
test/puppetlabs/puppetdb/testutils/db.clj

If clear-db-for-testing! is called on a migrated db, it will attempt to
delete the sha1_agg aggregate function via the drop-function! testutils
method. Because aggregates and function are deleted differently (ie.
"DROP AGGREGATE" instead of "DROP FUNCTION") this would cause the test
to fail with
```
java.sql.BatchUpdateException: Batch entry 0 DROP FUNCTION IF EXISTS sha1_agg(bytea) CASCADE was aborted: ERROR: "sha1_agg" is an aggregate function
Hint: Use DROP AGGREGATE to drop aggregate functions.
```
This adds a DROP AGGREGATE section to the clear-db-for-testing!
function. It also changes the sql-current-connection-function-names to
exclude aggregates and adds a new version of that function to lookup
aggregate names.

(maint) Fix testutil that clears db

---

documentation/postgres_ssl.markdown

The main change is we will no longer document that FOSS users can use
their Puppet CA cert for postgres SSL via a Java keystore. They should
use libPQFactory because this is what is used in PE so it is more
tested. The documentation for creating a Java keystore remains, but is
downgraded to being recommended only if your cert comes from another CA
and is not able to be verified by the default Java keystore.

(PDB-4678) Update PostgreSQL SSL documentation

---

src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/scf/migrate.clj

See commit messages for an explanation of the changes that were made. I fixed up the indentation for the _reports-partitioning_ function in a separate commit from the one where I changed the functionality to make review easier. I can combine these changes into a single commit before we merge if y'all prefer.

(PDB-4676) Update migration 74 to guard against OOM errors

---

src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/scf/partitioning.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/testutils/nodes.clj
test/puppetlabs/puppetdb/testutils/reports.clj

In partitioned tables, we attempted every insertion to CREATE TABLE IF
NOT EXISTS and then INSERT the data. This caused a issue where when
processing multiple insertions concurrently, we could deadlock between
the table creation in one command processor and the insertion in
another.
This instead switched the CREATE TABLE step to be opportunistic, and
will only happen when an attempt to store the data failed with a "table
undefined" error. If multiple reports are being processed at once, we
can still see some errors in the postgresql logs about the table already
existing, but that is an example of rollbacks properly rectifying the
error.
By moving partition creation to another transaction, the insertion of
reports is returned to its previous complexity and the deadlocks no
longer occur.

(PDB-4675) Fix deadlock issue in partitioned tables

---

ext/test/schema-mismatch-causes-pdb-shutdown

Redirection does create the file while the command is running, and does
so even before any output is produced. But the `&` operator takes
precendence here and runs the entire command in the background,
including the redirections, so its possible for the files to not
exist when they are read below.

(maint) Create files before background redirection

---

documentation/maintain_and_tune.markdown
documentation/upgrade.markdown

This moves the documentation for how and why to delete reports to the
upgrade docs where they are most applicable. It also adds a section on
how to delete your reports manually if the `delete-reports` script is
not yet available on your system.

(maint) Add docs for how to delete reports manually

---

.travis.yml

Shortly after tagging puppetserver bumped clj-parent which broke
integrations tests. This is a temporary pin while we release 6.10.1

(maint) travis: pin to puppetserver tag

---

src/puppetlabs/puppetdb/query_eng/default_reports.clj
test/puppetlabs/puppetdb/query_eng/default_reports_test.clj

Adds `nil` as a basecase because `nil` is a valid expression.
Adds `"offset"` as one of the allowed paging operators.

(PDB-4741) Fix errors with agent report filter

---

src/puppetlabs/puppetdb/cli/services.clj

Comparison was backward, and also didn't consult "migrate=?" settings.
fixes: 7a52d73801a38be79b725a25aa74bcfe1d847bcb

(PDB-4743) Fix migration check when there's more than one db

---

project.clj

This reverts the clj-i18n bump that seems to be breaking reloads on
certain OS's

(maint) Bump clj-parent to 4.5.2

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/query_eng_test.clj

Prior to PDB-4479 (commit 262573c)
an "active node" was anything that was not an inactive node. The
definition of an inactive node was too broad so it was reduced in scope
and active_nodes was explicitly described. The result was the
active_nodes definition changed from
```
WITH inactive_nodes AS
(SELECT certname from certnames
WHERE (deactivated IS NOT NULL OR expired IS NOT NULL)
...
WHERE NOT (certname in (SELECT certname FROM inactive_nodes))
```
to
```
WITH active_nodes AS
(SELECT certname from certnames
WHERE (deactivated IS NULL AND expired IS NULL)
...
WHERE (certname in (SELECT certname FROM active_nodes))
```
While the two are logically equivalent, the Postgres query planner
treats them very differently. The planner began filtering via the
active_nodes CTE using a HashAggregate …

(PDB-4769) Revert definition of active_nodes

---

src/puppetlabs/puppetdb/pdb_routing.clj

In active installs, this makes the startup logs (especially migration
progress logs), nearly unreadable because the vast majority of the lines
are this message.
The 503 error code can also be found in the puppetdb_access.log to
monitor declined HTTP requests.

(PDB-4599) Don't spam log with HTTP request received

---

project.clj

This updates pgjdbc to 42.2.14, which includes the fix for
CVE-2020-13692. We were not vulnerable to this CVE because we don't use
the PgSQLXML code, but are updating for peace of mind and to ensure that
we pass security scans.

(maint) Bump clj-parent to 4.5.3

---

project.clj

This includes an update to trapperkeeper-metrics that adds trapperkeeper
authentication to its endpoints.

(maint) Bump clj-parent to 4.5.4

---

project.clj

This reverts commit 66855297fe6696d2d0e842e3b1631f482b436f2b.

Revert "(maint) Bump ezbake version to 2.1.7"

---

project.clj

Update version for databind for another CVE from jackson-databind that
we are likely not vulnerable to (CVE-2020-9548).
Pin jackson-core to 2.9.10 since that was being held back by our
version of clj-parent.

(maint) Update jackson-databind version

---

src/puppetlabs/puppetdb/scf/storage_utils.clj

This is intended to log an error in PE tests without having to configure
logback.xml. Before releasing, this should be removed or changed to log
at the debug level

(maint) Log a warning when the db-up? query fails

---

.travis.yml

Run all puppetdb tests in one stage to save time. After this commit,
there are only two stages, clojure/ruby tests and container tests.

(maint) travis: run drop-joins test in main stage

---

documentation/known_issues.markdown
src/puppetlabs/puppetdb/scf/storage_utils.clj

Expected `/status/v1/services/puppetdb-status` response
```
{
"service_version": "6.11.2",
"service_status_version": 1,
"detail_level": "info",
"state": "error",
"status": {
"maintenance_mode?": false,
"queue_depth": 0,
"read_db_up?": false,
"write_db_up?": false,
"write_dbs_up?": false,
"write_db": {
"default": {
"up?": false
}
}
},
"active_alerts": [],
"service_name": "puppetdb-status"
}
```
Actual response
```
{
"service_version": "6.11.2",
"service_status_version": 1,
"detail_level": "info",
"state": "unknown",
"status": "Status check for puppetdb-status threw an exception: clojure.lang.ExceptionInfo: Output of status-details does not match schema: \n\n\t \u001b[0;33m  {:write_db_up? (not (instance? java.lang.Boolean nil))} \u001b[0m \n\n {:type :schema.core/error, :schema …
```

(PDB-4836) Document status bug as a known issue

---

src/puppetlabs/puppetdb/client.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/command_broadcast_test.clj
test/puppetlabs/puppetdb/testutils/services.clj

Will need to rebase this once Rob's config work gets merged. Also needs a fix for a race in blocking cmd submission when in broadcast mode (see [PDB-4796](https://tickets.puppetlabs.com/browse/PDB-4796)).

(PDB-4659) Add  acceptance tests for cmd broadcast

---

src/puppetlabs/puppetdb/scf/partitioning.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/testutils.clj

This removes our usage of pg_tables and regex to identify table
partitions, and instead we ask postgres's own tables what the partitions
of a given parent table are.
The second commit ensures that we continue to support a non-public schema, as long as our tables show up on the search path before any other tables with the same name in a different schema.
We should not merge this until **_after_** we have released 6.11.3

(PDB-4839) Standardize getting names of table partitions 

---

documentation/ha.markdown

HA was renamed to DR in PE 2019 docs. We'll need the DR link in master and the HA link in 5.2.x.  
https://puppet.com/docs/pe/2019.8/dr_overview.html
https://puppet.com/docs/pe/2018.1/high_availability_overview.html

(PDB-4752) Update link for DR overview docs

---

.travis.yml

Also removes commented out integration tests. In the new release cadence
we don't have any STS releases with z's, which is what the commented out
tests were testing. We'll need to think of the proper way to ensure
backwards compatibility without testing every single platform Y release.

(maint) travis: test in a single stage

---

test/puppetlabs/puppetdb/acceptance/node_ttl.clj

Two things acquire the `clean-lock`, periodic garbage collection and the
admin clean endpoint. Garbage collection uses `(.lock clean-lock)`,
which means it will block until the lock is available. The admin
endpoint uses `(when (.tryLock clean-lock) <clean>)` which means if the
lock is not available it will return `false` and skip the attempt to
perform the admin clean action.  Sometimes, when this test runs, gc can
be running in the background and cause the initial call to
`(cli-svc/clean pdb ["expire_nodes"])` to be skipped, which puts the db
into an incorrect state for the following test checks.

(PDB-4745) disable gc in config-expiration test

---

ext/bin/pdbbox-init

Using install may have been fine, but the handling of permissions is
not documented, and install might not be as portable, so just rely on
mktemp, which we already require, and which at least Linux and OpenBSD
does explicitly document the handling of permissions.

(maint) pdbbox-init: use mktemp for all auth data

---

ext/bin/run-external-tests
ext/test/oom-causes-shutdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/utils.clj

As a practical matter, swallowing the exception prevented it from
being printed from with-monitored-execution, but of course it also
prevented anything higher up the call stack from having the option to
respond.
Add an oom-causes-shutdown external test to test this, and to make
sure we actually do log OutOfMemoryErrors.  To facilitate that,
allocate memory from the schema check task when
PDB_TEST_ALLOCATE_AT_LEAST_MB_AT_STARTUP is set, so that we can
trigger the failure.
Always log our fatal error related shutdown requests (at least the
summary information -- the full backtrace should be logged by the
wrappers after we rethrow).

(PDB-4853) with-shutdown-request-on-fatal-error: always rethrow

---

src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/dashboard_test.clj

This was breaking the dashboard data query, and resulted in a blank
dashboard page.
While adding support for multiple write dbs we used a metric prefix to
distinguish between the two dbs metrics. We omitted providing the prefix
to this function, so the "value" of the metric was this string instead
of a duplication percentage.
```
"javax.management.RuntimeMBeanException: clojure.lang.ArityException: Wrong number of args (1) passed to: puppetlabs.puppetdb.utils.metrics/maybe-prefix-key"
```
This caused an error when we later tried to multiply this metric value.
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
at clojure.lang.Numbers.multiply(Numbers.java:173)
at puppetlabs.puppetdb.dashboard$fn_42532$get_dashboard_data42537$fn42538$iter4253942543$fn42544$ …
```

(PDB-4855) Fix initialization of duplicate-pct metric

---

Gemfile
acceptance/helper.rb
acceptance/setup/pre_suite/75_clean_out_puppet5_repos.rb

Specify the oldest supported version for Ubuntu focal
Update beaker hostgenerator to a version new enough to know about Ubuntu
20 when using ABS (which is what we use in CI).

(PDB-4788) Enable ubuntu20 acceptance tests

---

src/puppetlabs/puppetdb/query_eng/engine.clj

Fix the :source-tables metadata for the catalog inputs queries They
were incorrectly using :source-table and providing a string, not a
set, but given the current uses of the data, that may not have
affected anything.

(PDB-4897) Correct :source-tables for catalog inputs queries

---

src/puppetlabs/puppetdb/scf/storage.clj

Accidentally introduced by the refactoring related to lock-statuses
cf. f240694492b0bf783190cfdb5630ad1218400afa
Causes the normal periodic garbage collections to fail like this:
ERROR puppetlabs.puppetdb.cli.services - Error while sweeping reports and resource events
java.sql.BatchUpdateException: Batch entry 0 0 was aborted: ERROR: syntax error at or near "0"
Position: 1  Call getNextException to see other errors in the batch.
The garbage collections at startup and those triggered by the admin
endpoint should be unaffected.

(PDB-4908) prune-daily-partitions: don't nest do-commands

---

src/puppetlabs/puppetdb/cli/services.clj

Before this used `name` which logged the clojure function instead of the
`db-name`
```
Ensuring clojure.core$name@5d616d65 database is up to date
```
Now it will log a more intelligible name like
```
Ensuring default database is up to date
```

(maint) Fix log message db-name

---

ext/build_defaults.yaml
project.clj

These project.clj variables control where ezbake builds get
published to when shipping to nightlies or release repos.
It's unclear what exactly `build_defaults.yaml` controls, but to be
safe, this commit also updates those values.

(maint) Ship to puppet7 streams

---

ext/bin/require-jdk

The v2 API is deprecated and doesn't seem to work anymore.

(maint) Update adoptopenjdk api version

---

acceptance/helper.rb
acceptance/setup/pre_suite/15_setup_repos.rb
acceptance/setup/pre_suite/40_install_deps.rb
acceptance/setup/pre_suite/75_clean_out_puppet5_repos.rb

Also includes some maintainence work on the test setup
>  (PDB-4939) Use PostgreSQL repo on el8
>
> When we first added testing for redhat8, postgres provided packages, but
not a repo for redhat8 because it was not yet released. Now, instead of
installing each package on its own, we can simply enable to repo and let
the module do the rest.

(PDB-4939) Fix postgres install in centos8 tests

---

puppet/spec/spec_helper.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
puppet/spec/unit/indirector/facts/puppetdb_spec.rb
puppet/spec/unit/indirector/node/puppetdb_spec.rb
puppet/spec/unit/indirector/resource/puppetdb_spec.rb
puppet/spec/unit/reports/puppetdb_spec.rb
puppet/spec/unit/util/puppetdb/command_spec.rb
puppet/spec/unit/util/puppetdb/http_spec.rb

The Puppet::HTTP::Response#nethttp method is going away, because puppetserver's http client implementation is not based on Net::HTTP.
This adds a create_http_response helper to create the correct HTTP response adapter based on the puppet version.

(maint) Puppet::HTTP::Response#nethttp is going away

---

puppet/lib/puppet/util/puppetdb/http.rb

previously `concat_url_snippets` was called only with `path`
part of `server_url`, without passing `host` and `port` settings

(maint) fix call to `concat_url_snippets`

---

src/puppetlabs/puppetdb/cli/services.clj

Since this is now a non-fatal error, we've gone further than deprecating
postgresql less than 11. In PuppetDB 7+ it will be officially
unsupported and may break in any release.

(PDB-4961) State that postgres <11 is unsupported

---

documentation/configure.markdown

Mention PDB_USE_DEPRECATED_QUERY_STREAMING_METHOD in the experimental
variables section in the configuration docs.

(PDB-4962) (PDB-4871) Mention experimental env var in docs

---

project.clj

With the release of java-1.8.0_272
[a bug in bouncycastle](https://github.com/bcgit/bc-java/issues/633)
started showing up in tests, specfically integration tests and PE
2016.4 to 2018.1 upgrade tests.
The bug was fixed in bc 1.65 so we are upgrading to that version in
order to test that PE upgrades are fixed. It appears that puppetserver
is not compatible with bc 1.65 (at least in our integration tests) so if
it fixes PE upgrade tests, we will either need to update puppetserver as
well or retire the integration tests before the `5.2.x` branch is
officially EOL.

(PDB-4947) Pin bounncycastle to 1.65

---

.travis.yml

See [RE-13716](https://tickets.puppetlabs.com/browse/RE-13716) for more
information on the issue that forced us to upgrade bouncycastle to 1.65.
Puppetserver is not compatible with bouncycastle 1.65, and the upgrade
path is not as simple as ours. As a result our integration tests will
not pass. Since this branch will EOL on Jan 31, they don't plan to
upgrade at all, so we should stop attempting to run integration tests.

(maint) travis: remove integration tests

---

docker/README.md
docker/puppetdb/Dockerfile
docker/puppetdb/conf.d/.dockerenv
docker/puppetdb/conf.d/jetty.ini
docker/puppetdb/docker-entrypoint.d/20-configure-ssl.sh
docker/puppetdb/docker-entrypoint.sh
docker/puppetdb/puppetdb

- Upgrades ssl.sh - uses static files produced from there in jetty.ini
- Enable token auth in jetty.ini
- Hide SSLDIR / LOGDIR from users (they're not settable ENV vars)
- Make sure that PUPPETDB_JAVA_ARGS works in containers!
Supersedes #3314

(maint) Upgrade ssl.sh script, hide SSLDIR / LOGDIR, honor PUPETDB_JAVA_ARGS

---

Gemfile
puppet/lib/puppet/indirector/facts/puppetdb.rb
puppet/lib/puppet/indirector/resource/puppetdb.rb
puppet/spec/unit/indirector/node/puppetdb_spec.rb

* Remove dependency on json_pure
* This is an old an unused dependency that was causing deprecation warnings on Ruby 2.7
* Replace URI with CGI
* The URI functions we were using were obsoleted by CGI replacements
* rspec: fix a deprecation warning
* The name shadowing was producing a warning

(PDB-4971) Remove Ruby 2.7 deprecation warnings

---

puppet/lib/puppet/face/node/status.rb
puppet/lib/puppet/indirector/facts/puppetdb.rb
puppet/lib/puppet/indirector/resource/puppetdb.rb
puppet/lib/puppet/util/puppetdb.rb
puppet/lib/puppet/util/puppetdb/command.rb

In Ruby 3.0 they are aiming to separate positional and keyword
arguements, so in 2.7 they deprecated the implicit use of keyword
arguments as the last parameter. Adding the "hash splat" operator to the
function call makes it explicit that the hash is to be parsed as keyword
arguments.

(PDB-4971) Explicitly splat the http options

---

src/puppetlabs/puppetdb/cli/services.clj
test/puppetlabs/puppetdb/cli/services_test.clj

When gc is disabled, PuppetDB would never deliver on the
initial-gc-finished promise. This would cause sync to never run, and
puppetdb to never exit maintenance mode on startup. Now we'll deliver on
the promise if gc is disabled or once all initial garbage collections
have finished. Before this, gc would deliver at the end of its first
initial gc, even if there were multiple databases.

(PDB-4975) Deliver on promise even if gc disabled

---

src/puppetlabs/puppetdb/cli/services.clj

Initialize the count to the number of databases and only count down to
prevent a race where one gc starts and finishes, delivers the promise,
and then another gc starts on a second database, but the initial gc
promise was already delivered on.

(PDB-4975) Prevent delivering initial gc promise early

---

.github/workflows/docker.yml
docker/puppetdb/Dockerfile

- Improves script robustness under a number of specific scenarios:
- keypair generated on disk, CSR never submitted
- keypair generated on disk, CSR submitted, cert never downloaded
(i.e. cert matches keypair on disk)
- keypair generated on disk, cert exists but doesn't match
- keypair generated, CA down, CSR requires multiple resubmits until
CA ready
- no keypair generated, certname exists for another host
- Additionally make improvements:
- Verify that there is a 200 response from the masters CA as well to
determine CA readiness to prevent:
- Error: cannot reach CA host 'pe-puppet'
- Error: cannot reach CRL host 'pe-puppet'
- Under rare circumstances *any* HTTP response may not be blank, but
may be malformed with a unparseable status code.
In such instances, fail fast -- otherwise, the …

(maint) Update ssl.sh agent script

---

src/puppetlabs/puppetdb/cli/services.clj

In the success case this will create two log messages
```
INFO Starting delete of all data for host foo.example.com
INFO Finished delete of all data for host foo.example.com
```
If it errors it will throw and not log the finished messages so the logs
will look like.
```
INFO  Starting delete of all data for host foo.example.com
ERROR Failed to delete all data for host foo.example.com
<with an exception here>
```

(maint) Log when deleting nodes

---

project.clj

- Bumps clj-parent to 4.6.11 to pick up an updated typesafe/config
version via typesafe 1.4.1 (from 1.2.0)
Includes feature to load environment variables into lists
like:
FOO.1
FOO.2
More info is available at
https://github.com/lightbend/config/blob/master/NEWS.md
https://github.com/puppetlabs/clj-parent/pull/27

(maint) Bump hocon version support via clj-parent

---

docker/puppetdb/conf.d/auth.conf
documentation/CONTRIBUTING.md
ext/bin/pdbbox-init
ext/bin/render-pdb-schema
ext/test/database-migration-config
ext/test/oom-causes-shutdown
ext/test/schema-mismatch-causes-pdb-shutdown
ext/test/upgrade-and-exit
project.clj
resources/ext/config/conf.d/auth.conf
resources/puppetlabs/puppetdb/bootstrap.cfg

Assuming puppetdb's jetty is configured to use the same certs, metrics
can be access via authenticated GET requests like the curl command
below.
```
curl -G https://localhost:8081/metrics/v2/list \
--cacert test-resources/ca.pem \
--cert test-resources/localhost.pem \
--key test-resources/localhost.key
```

 (PDB-4811) Add tk-auth to tk-metrics endpoint

---

docker/puppetdb/docker-entrypoint.sh

- Both docker (per https://github.com/moby/moby/issues/16585) and
Kubernetes (per https://github.com/kubernetes/kubernetes/issues/2707)
support passing environment variables with dots as config, despite
dot not technically being supported in POSIX.
This is necessary to be able to specify hocon array values like
FOO.0, FOO.1, etc now that the Hocon library is updated to
typesafe/config 1.4.1 via puppetlabs/typesafe-config 0.2.0 /
clj-parent 4.6.11
/bin/sh will not add such variables to the environment, but /bin/bash
will properly expose them, so that they may be consumed by
puppetserver and hocon.
NOTE: ElasticSearch is notorious for passing such values, and it also
uses the tini init system, so it served as a good design to follow: …

(maint) Support dotted env vars in containers

---

pdb
project.clj
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/utils.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/command_test.clj

Although we'd expected to be waiting for our schedulers (at-at pools)
to stop before returning from our start/stop methods, we weren't
because at-at runs the relevant ScheduledThreadPoolExecutor shutdown
function in a future and returns immediately.
Since our needs are fairly straightforward, and since the relevant
blocking function in at-at is private, just manage the
ScheduledThreadPoolExecutors ourselves.
cf. PDB-4932

(PDB-4974) Wait for schedulers to shut down (and replace at-at)

---

src/puppetlabs/puppetdb/query_eng.clj

Query Logging is enabled by a config variable, and disabled by default,
so we can log them at info level without causing unecessary log growth.

(maint) Log queries at INFO level

---

project.clj
src/puppetlabs/puppetdb/middleware.clj
test/puppetlabs/puppetdb/middleware_test.clj

There was a vulnerability in tika-core, but upgrading pantomime was
going to pull in a bunch of new dependencies. We only used it for
parsing the Content-Type header for its basetype, so this replaces that
call with a custom regex matching the RFC definition of base type.
Also bumps clj-parent for vulnerabilities

(PDB-5000) Remove dependency on pantomime

---

ext/test/upgrade-and-exit
resources/ext/cli/delete-reports.erb
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/partitioning.clj
test/puppetlabs/puppetdb/scf/migrate_partitioning_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj

Also structures migration 74 in a way that future changes to `partitioning/create-report-partition` won't cause changes to the migration and its schema diff test. This allowed the simplification of the testing for migration 76 because it no longer has two cases to test.

(PDB-5003) Add (certname,end_time) index to reports

---

docker/puppetdb/docker-entrypoint.d/20-configure-ssl.sh

- This simply makes it consistent with the filename used in
orchestration services and console services. Changes will be made to
ssl.sh to produce this file, and it makes sense to have all
containers have the same naming convention

(maint) Update container pk8 filename

---

test/puppetlabs/puppetdb/pdb_routing_test.clj

An unit test, that checks that metrics can be retrieved in maintenance mode, was added.

(PDB-4172) Allow metrics during startup

---

src/puppetlabs/puppetdb/cli/services.clj
test/puppetlabs/puppetdb/admin_clean_test.clj

Prior to this commit there was an arg missing from the
scf-store/delete-resource-events-older-than! function which is
used when the admin endpoint gets a purge_resource_events clean
command.

(PDB-5017) Add missing arg to admin purge_resource_events path

---

documentation/configure.markdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/config_test.clj

For some databases the user we use for connecting to the databse can be different from the one reported by the database. For example the Azure managed PostgreSQL uses `username@hostname` to connect to a database, but the user that is reported by the database is `username`.  
PuppetDB does not make a distinction between the two users and will fail when it compares the connection user to the user reported by the database.
Added two new users `connection-migrator-username` and `connection-username`. The new users are used to establish connections to the database when the connection username is different form the database username (this is the case for managed PostgreSQL in Azure)
`database.ini` example
```
[database]
subname = //<databse_url>:5432/puppetdb
connection-migrator-username = …
```

(PDB-4934-2) PuppetDB does not support username@hostname auth for Azure PostgreSQL

---

project.clj

will sign packages with the new gpg key

(maint) Update ezbake to 2.2.2

---

src/puppetlabs/puppetdb/catalogs.clj
src/puppetlabs/puppetdb/cheshire.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/pql.clj
src/puppetlabs/puppetdb/query.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/queue.clj
src/puppetlabs/puppetdb/reports.clj
src/puppetlabs/puppetdb/utils.clj
src/puppetlabs/puppetdb/utils/string_formatter.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/examples.clj
test/puppetlabs/puppetdb/examples/reports.clj
test/puppetlabs/puppetdb/http/index_test.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/reports_test.clj
test/puppetlabs/puppetdb/utils/string_formatter_test.clj
test/puppetlabs/puppetdb/utils_test.clj

**Problem description**:
When submitting multiple queries in one request, the first one is resolved and the rest are ignored.
Example: `["from","facts"] ["not" ["=", "certname", "security-sensitive-host"]]`. This returns all the facts. 
Also if we add random strings after the query, they get ignored as well.
Example: `["from","facts"] this-is-trailing-garbage-and-not-part-of-the-query-that-gets-evaluated`. This returns all the facts.
With this PR, when multiple queries are submitted, an error message is returned, saying that no more than one 
query may be submitted in one request. 
When the query ends with a string, a `Malformed JSON` error is returned.

(PDB-2488) Invalid AST query is ignored

---

project.clj
src/puppetlabs/puppetdb/middleware.clj
test/puppetlabs/puppetdb/middleware_test.clj

the base-type function and tests are now in kitchensink

(PE-31121) Update clj-parent to 4.6.18

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/cli/services_test.clj

For PuppetDBServer TK query method a new option `(:explain true)` can be used to enable explain output for queries.

(PDB-5042) Enable TK query to receive explain

---

src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/schema.clj

The options config passed to `prep-replace-facts` has more keys in it
than just blocklist options now. Update the function to only attempt to
filter blocked facts when the config option `facts-blocklist` is
present. We don't need to also check `facts-blocklist-type` because it
is defaulted in the config so it will always be present (except in some
tests). Also if a bug exists where a user sets a blocklist but we fail
to default the blocklist type, it would be better to error than store
potentially sensitive or gargantuan information in the database.

(PDB-5059) Fix facts blocklist logic in command submission

---

src/puppetlabs/puppetdb/command.clj
src/puppetlabs/puppetdb/threadpool.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/threadpool_test.clj

Added `pause-execution` and `resume-execution` service functions to allow pausing of command execution.

(PDB-4524) PuppetDBCommandDispatcher: support pause and resume 

---

acceptance/helper.rb
acceptance/setup/pre_suite/15_setup_repos.rb
project.clj

See [PDB-4643](https://tickets.puppetlabs.com/browse/PDB-4643) for background info. With both java 8 & java 11 I needed to add **-Djdk.tls.ephemeralDHKeySize=2048** to the JAVA_ARGS to get around the **routines:tls_process_ske_dhe:dh key too small** described in that ticket.

(SERVER-2500) Increase ephemeralDHKeySize to 2048

---

docker/puppetdb/Dockerfile
docker/puppetdb/docker-entrypoint.d/20-configure-ssl.sh

- Includes a number of new features in ssl.sh, including:
* Much better logging during failed HTTP requests
* Produce pk8 private key files for apps like orch, console services,
pdb (so that their entrypoints can remove code to generate them)
* Set permissions on cert files - 700 for dirs, 600 for files
(so that entrypoint scripts are not responsible)
* Always generate canonical symlinks to certs up front (rather than
as files are generated), which repairs bad links on disk
* Add ability to retry HTTP requests and do this when:
- Grabbing CA
- Grabbing CRL
- Retrieving signed certs
* Warning when new a different certname is used when a cert already
exists on disk
- Additionally simplifes the entrypoint script to always run ssl.sh
when USE_PUPPETSERVER is true, given ssl.sh is idempotent. …

(maint) Update ssl.sh script / entrypoint

---

resources/ext/cli/ssl-setup.erb

Previously "puppet ssl-setup -f" would append a line like this to
jetty.ini
client-auth = want = client-auth = want
rather than
client-auth = want

ssl-setup: don't double "client-auth = want" in config file for -f

---

src/puppetlabs/puppetdb/http/server.clj
src/puppetlabs/puppetdb/middleware.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/middleware_test.clj

When an exception is thrown on the server,
only return the error message to the API.
The stack trace is no longer returned,
it is logged as an error.

(PDB-5063) Return only error message on API

---

acceptance/setup/pre_suite/15_setup_repos.rb

This commit should be reverted once PDB 6.15.1 and PDB 7.2.1 are released.

(maint) Set crypto-policies to LEGACY in el8 acceptance tests

---

src/puppetlabs/puppetdb/pql.clj
test/puppetlabs/puppetdb/http/catalog_inputs_test.clj
test/puppetlabs/puppetdb/http/index_test.clj

On endpoints underneath `/pdb/query/v4` having an empty query string was
valid. This would get parsed as "PQL" because it does not contain a `"["`
(even though PQL is not valid at sub-endpoints). There are 0 pql queries
in the string, so the previous check `(= 1 ...)` would fail.
This fixes the following query (which is used by puppetserver acceptance
tests) that previously worked.
```
curl -X POST http://localhost:8080/pdb/query/v4/catalog-input-contents \
-H 'Content-Type:application/json' \
-d '{"query": "" }'
```

(PDB-2488) Allow empty query string

---

src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query/paging.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/http/nodes_test.clj
test/puppetlabs/puppetdb/http/paging_test.clj
test/puppetlabs/puppetdb/http/resources_test.clj

This PR exposes a new query parameter (:explain) introduced in : https://github.com/puppetlabs/puppetdb/pull/3433

(PDB-5055) Add :explain query parameter

---

.travis.yml
docker/Makefile
docker/puppetdb/Dockerfile

- Symlinks in the same directory for canonical filenames server.pub,
server.key and server.crt - works better when initContainer mounts
to a different path structure than a destination container in k8s.

(maint) Update container with latest ssl.sh

---

project.clj

Includes a bump to jetty that will keep us in line with puppetserver

(maint) Update clj-parent to 4.6.20

---

src/puppetlabs/puppetdb/scf/hash.clj
test/puppetlabs/puppetdb/scf/hash_test.clj

Prior to this commit changes in the ordering of package_inventory
could produce differing hashes for a factset when all else was equal.
This could create a situation with pe-puppetdb sync that could cause a
factset to be pulled repeatedly even though both sides had stored the
same factset already. This could happen if the ordering of the
package_inventory for a factset pulled via sync didn't match the
order when the factset was first inserted. This mismatch could create
differing hashes and then sync would repeatedly decide it needed to
pull that factset from the remote and continue to calculate a
different hash due to the change in package_inventory ordering. This
problem could only happen when sync did the initial transfer of a
factset. If a factset was broadcast to both puppetdbs in a …

(PDB-5021) Sort package_inventory when calculating hash

---

.travis.yml

- Instead of incurring the upgrade cost to Travis 20.10, use the
existing 19.03 version.
In practice, upgrading Docker in Travis turned out to be unreliable.
To enable buildx requires installing the plugin from the github
releases page. Using the experimental cli flag was supposed to enable
the plugin for 19.03, but didn't seem to work in the Travis env.

(maint) Use Docker 19.03 in Travis again

---

docker/puppetdb/Dockerfile

- Since K8s always creates volumes empty, there's no need to defer
these stages until later. It also doesn't look like the note was
correct anymore when building with Docker 20.10 on OSX

(maint) Move Docker VOLUME declarations up

---

src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj

Rename "paging-options" parameter to "options" along the following calls:  [query](https://github.com/puppetlabs/puppetdb/blob/main/src/puppetlabs/puppetdb/cli/services.clj#L1126-L1137) -> [stream-query-result](https://github.com/puppetlabs/puppetdb/blob/main/src/puppetlabs/puppetdb/query_eng.clj#L197-L227) -> [query->sql](https://github.com/puppetlabs/puppetdb/blob/main/src/puppetlabs/puppetdb/query_eng.clj#L111-L173) -> [compile-user-query->sql](https://github.com/puppetlabs/puppetdb/blob/main/src/puppetlabs/puppetdb/query_eng/engine.clj#L3010-L3017) -> [compile-query](https://github.com/puppetlabs/puppetdb/blob/main/src/puppetlabs/puppetdb/query_eng/engine.clj#L2973-L3008)

(PDB-1936) Rename parameters for more consistency

---

ext/bin/jdk-info

The `echo` command needs to print multiple lines, but the `head -1`
command only reads the first line before completing. Sometimes this
means that the head command will finish and close its pipe before the
echo prints all its lines to the pipe. Due to the `-o pipefail` setting
in this file, this transient issue will cause the script to fail with
the error
```
+ ext/bin/check-spec-env lint/openjdk11
ext/bin/jdk-info: line 38: echo: write error: Broken pipe
Error: Process completed with exit code 1.
```
This allows the pipefail for this command to fix the transient error.

(maint) test: fix pipefail error in jdk-info

---

resources/ext/cli/ssl-setup.erb

Previously the user/group/mode would just be lost in some cases, or
the user and group would be lost, and the mode would be
unconditionally set to 644.

(PDB-2590) ssl-setup: preserve file permissions when making changes

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/reports_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj

A new way of querying for all reports was introduced. All reports are queried by including `type = "any"` in the query body.

(PDB-4766) Query reports with type=any

---

src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
test/puppetlabs/puppetdb/http/index_test.clj

The PE console was relying on this functionality.
This reverts commit c614d16b2fe26219ac6743f33c79ee6594a2b94f.

Revert "(PDB-2898) Disallow paging opts outside pql query"

---

documentation/configure.markdown
documentation/release_notes/release_notes_latest.markdown

These are only applicable for people _not_ using the puppetdb module to
install and configure their setup.

(docs) Add read-only user setup docs

---

dev-resources/jdk11-fips-security
dev-resources/jdk8-fips-security

There is an issue with bc-fips 1.0.2.1 involving circular provider
loading, that can be fixed by using the full class name for the
BCJSSE FIPS provider, rather than relying on an alias. This commit
updates our java-security files to use the full name. Note this only
caused issues on Java 11, but it is valid for both versions, so we are
updating it in both files for consistency.

(PE-32070) Update Java security files for new BCFIPS

---

test/puppetlabs/puppetdb/http/reports_test.clj

The tests also verifies that the response is blank-padded to 9 characters. 
This is how PostgreSQL renders the response when the month formatting mask is used.

(PDB-5103) Enabled skipped month-from-producer-timestamp test

---

documentation/release_notes/release_notes_latest.markdown

Since our release notes were moved to a release notes folder, the old
links that start with `./` are no longer correct. This changes those
links to `../`.
Also removes unused links so that they are not incorrectly used in
future release notes.

(docs) Fix release notes links

---

src/puppetlabs/puppetdb/query.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/facts_test.clj

**Description of the problem (short):** Query with to_string function doesn't return anything on the facts endpoint and fails with the following error in fact-contents endpoint: 
```
Input to munge-result-row does not match schema:
[(named {:to_string disallowed-key} row)]
```
**Description of the problem (long):** An optimisation was introduced, for queries that constrain the fact name to a
single value if they are made on the facts endpoint, in [this commit](https://github.com/puppetlabs/puppetdb/commit/8d5b509c9b6e5aa529bd0667694a8bd036100d42 ). Because the json -> operator for [the selection field](https://github.com/puppetlabs/puppetdb/blob/2126eb44069fb281330593b655fe95ffe97b72a2/src/puppetlabs/puppetdb/query_eng/engine.clj#L2740) was introduced, the parameters for the fact-name …

(PDB-5104) Fix to_string function on facts and fact-contents endpoint

---

docker/puppetdb/Dockerfile
docker/ruby-docker-copy-patch.rb

FOSS port of pe-puppetdb's 0886afb401129df40da1d0965b91ee2c08c76e7a
There's a particularly gnarly bug in Linux kernels 5.6 to 5.10 that
can result in 0 byte files being written when copying files inside
containers in a specific workflow as described in:
docker/for-linux#1015
This impacts the packaging gem used by ezbake when it renders ERB
templates, resulting in 0 byte files critical to the execution of
the build process.
Using a different filesystem (like tmpfs) for /tmp as a workaround
didn't seem to work.
Since there is no way to explicitly control the kernel version in
environments like Travis, the best approach is to monkey-patch the
_Entry class in Ruby that supports FileUtils.cp, such that a no-op
mode change is performed on the source and destination files before
and after being …

(RE-14082) Monkey-patch docker ezbake build Ruby

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/nodes_test.clj

**Description of the problem:** If the options (limit, offset, order_by) are provided to a subquery that uses "from", the context isn't switched to the entity from the "from" syntax. This behaviour results in an error when the subquery is made on the reports table. Eg. 
```
["from" "nodes"
["and"
["in"
"certname"
["from"
"reports"
["extract" "certname" ["=" "type" "agent"]]
["limit" 1]
["order_by" [["certname" "desc"]]]]]
["=" "node_state" "active"]]]
```
Results in the following error: 
```'type' is not a queryable object for nodes. Known queryable objects are 'cached_catalog_status', 'catalog_environment', 'catalog_timestamp', 'certname', 'deactivated', 'expired', 'facts_environment', 'facts_timestamp', 'latest_report_corrective_change', 'latest_report_hash', 'latest_report_job_id', …
```

(PDB-5026) Switch context in query when using from

---

acceptance/tests/commands/delete_reports.rb
resources/ext/cli/delete-reports.erb

PuppetDB needs to be running to begin a PE upgrade, so leaving it
stopped caused issues for users. Stopping PuppetDB is also a partial
solution for PE users who have PuppetDB on compilers as commands
submitted from those machines could still conflict with the reports
deletion.

(PDB-5142) delete-reports: don't stop puppetdb

---

locust/load-test/cd4pe.yaml
locust/load-test/console.yaml
locust/load-test/example.yaml
locust/load-test/load-test.py
locust/run-load-test

Add different .yaml files for the console, cp4pe and example queries.
Introduced an optional alias field in the .yaml files for easy identification of the request.
Requests query field is now optional.

(PDB-5105) Add console and cd4pe queries

---

src/puppetlabs/puppetdb/query_eng/engine.clj

When a field is misspelled in a group by it gets treated like a function,
causing a less than intelligble error. This replaces that with a
straightforward and usable error message.

(maint) Fix group_by error message

---

documentation/release_notes.markdown

Fix contributors typo.  Use link refs (and relative links) in 6.18.0
notes.  Change underscores to dashes in link refs (underscores were
treated as emphasis in some cases, at least in emacs markdown mode).

(PDB-5178) Fix release notes for 6.18.0

---

Gemfile
documentation/api/query/examples-pql.markdown

Removes some old Ruby test dependencies, which should remove some spurious warning in Github.
Removes some _very old_ query documentation on querying for active nodes.

(maint) Remove old ruby deps, update pql examples

---

test/puppetlabs/puppetdb/integration/puppetserver_metrics.clj
test/puppetlabs/puppetdb/integration/reports.clj

[This puppet PR](https://github.com/puppetlabs/puppet/pull/8691) removed the node definition request that previously made a "facts find" call to PDB to gather the facts. Also an info message is no longer printed by puppet.

(maint) Fix integration tests

---

src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/admin_test.clj
test/puppetlabs/puppetdb/http/inventory_test.clj

dotted fact paths should be grouped by their SQL identier "facts.foo"
instead of the actual SQL field `(fs.volatile||fs.stable)` like a
traditiional column. Fixes an error in a group by inventory-test.
Also fixes a transient in the admin-test where the query result order
could fail the test.

(PDB-5226) group by dotted SQL identifier

---

test/puppetlabs/puppetdb/integration/reports.clj

Due to this [PR](https://github.com/puppetlabs/puppet/pull/8733/files#diff-51e52bffe1de00c153bde14dea475f15abdcb6a1fdaf2691633dad8238e654cfR310) there is an extra log added that prints the environment when puppet starts. This causes the reports integration test to fail. 
@rbrw @austb @joshcooper Can you please have a look?

(maint) Fix report integration test

---

documentation/api/query/examples-pql.markdown
src/puppetlabs/puppetdb/query_eng.clj
test/puppetlabs/puppetdb/http/reports_test.clj

Example: 
`AST validation failed, but was successfully converted to SQL. Please file a PuppetDB ticket at https://tickets.puppetlabs.com
Unrecognized ast clause ["order_by" "certname"] in ast query ["extract" "certname" ["subquery" "reports" ["order_by" "certname"]]]`
Also updated docs that had invalid query as example.

(PDB-5256) Add details to message when AST validation fails

---

documentation/_puppetdb_nav.html
documentation/api/metrics/v1/mbeans.markdown
documentation/api/overview.markdown
documentation/api/query/v4/overview.markdown

This fixes the spots in the documentation markdown where `index.html` was not changed to `overview.html` in the previous docs bugfix commit

(maint) Fix outdated index.html docs references

---

acceptance/setup/pre_suite/40_install_deps.rb

Recently a major root certificate expired and had to be replaced. This
caused postgres to fail to install, on platforms where we install PDB.
This commit adds a step to our presuite that fetches new CA certificates,
to ensure that next time a cert is rotated, we will fetch it automatically.

(maint) Fix certificates main

---

acceptance/setup/pre_suite/40_install_deps.rb

Recently a major root certificate expired and had to be replaced. This
caused postgres to fail to install, on platforms where we install PDB.
This commit adds a step to our presuite that fetches new CA certificates,
to ensure that next time a cert is rotated, we will fetch it automatically.

(maint) Update CA certificates.

---

ext/test/upgrade-and-exit
resources/ext/cli/delete-reports.erb
src/puppetlabs/puppetdb/scf/migrate.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/testutils/db.clj

From first commit message:
This commit creates a new migration which prepares for the upcoming
workspaces feature by adding two new tables: workspaces and
workspace_membership. These tables track workspaces and which certnames
belong in which workspaces. Design specific notes:
- In the workspace_membership table, the certname column purposefully
does not have a foreign key constraint because we want to potentially
include deleted certnames in workspace_membership query results

(PDB-5326) Add db storage for workspaces

---

src/puppetlabs/puppetdb/cli/services.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/integration/reports.clj

This commit fixes a bug that causes reports to get garbage collected
even though they were created within the 'reports-ttl' timeframe. This
was due to a comparision of these two datetime values:
- the 'reports-ttl' derived "cut-off" datetime: exactly 'reports-ttl'
ago.
- the table partition's datetime: the very beginning of the day in which
the reports witin were created.
In puppetlabs.puppetdb.scf.storage/prune-daily-partitions, a table
partition is deemed expired if the latter datetime is *before* the
former. When GC'ing at 00:05 with a 'reports-ttl' of '1d', the partition
with all of yesterday's reports is deemed expired. The user is left with
reports from only the last 5 minutes.
This fix does a "floor" operation on the cutoff datetime generated from
the 'reports-ttl' value before …

(PDB-5351) Fix reports table partition gc bug

---

test/puppetlabs/puppetdb/integration/puppetserver_metrics.clj

Failing test case
```
lein test :only puppetlabs.puppetdb.integration.puppetserver-metrics/puppetserver-http-client-metrics
FAIL in (puppetserver-http-client-metrics) (puppetserver_metrics.clj:44)
Puppet Server status endpoint contains expected puppetdb metrics
expected: (= #{["puppetdb" "command" "replace_catalog"] ["puppetdb" "command" "store_report"] ["puppetdb" "command" "replace_facts"] ["puppetdb" "resource" "search"] ["puppetdb" "query"]} (set (map :metric-id metrics)))
actual: (not (= #{["puppetdb" "command" "replace_catalog"] ["puppetdb" "command" "store_report"] ["puppetdb" "command" "replace_facts"] ["puppetdb" "resource" "search"] ["puppetdb" "query"]} #{["puppetdb" "facts" "find"] ["puppetdb" "command" "replace_catalog"] ["puppetdb" "command" "store_report"] ["puppetdb" …
```

(maint) Fix failing integration metrics test

---

ext/jenkins/beaker-tests.sh

The sysstat package is failing on redhat6, so disable this on `6.x`.
Since we are removing el6 builds/testing on `main`, this should be
switched back to on in the merge-up

(maint) Disable jenkins perf data

---

Gemfile
acceptance/helper.rb
acceptance/setup/pre_suite/05_clear_firewalls.rb

With a small additional change locally (not commited) to pull and
install puppetserver from our internal staging build servers, this
passes the install tests. Once puppetserver publishes a nightly build,
these acceptance tests will pass in CI.

(PDB-5391) Fix tests on Debian 11

---

ext/bin/check-command-perf
ext/bin/run-locust-load-tests
ext/test/schema-mismatch-causes-pdb-shutdown
src/puppetlabs/puppetdb/cli/services.clj
test/puppetlabs/puppetdb/acceptance/node_ttl.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/integration/resource_events.clj

Upon every startup, PuppetDB previously garbage collected every DB for
which GC was enabled. We no longer want to do this because GC can take a
very long time, upwards of 20 minutes on large installations. This patch
stops GC at startup from occuring by issuing an initial delay to the GC
job scheduler. This initial delay is simply the :gc-interval from the
provided DB config.
Previously, the inital GC job would prune an unlimited number of
partitions, and all subsequent GC would prune partitions incrementally.
Now GC will always prune partitions incrementally.
Some tests expected GC to run upon PDB starting up, so those tests were
changed to have a :gc-interval of "0.01" minutes in order to trigger GC
very quickly. This way, the tests still confirm GC works and they can be
mostly kept in …

(PDB-5422) Stop garbage collecting at startup

---

documentation/known_issues.markdown
documentation/release_notes_6.markdown

PDB-5259 has an issue with PostgreSQL JIT compilation, which was
reported in PDB-5450. The workaround is to disable JIT compilation
(which is the default in PG 11, and can be set in PG 12+).

(docs) Add known issue for 6.20.0 and 7.9.0

---

src/puppetlabs/puppetdb/middleware.clj

In order to safely `assert` things in the query code, we need to ensure
that we do not leak AssertionErrors, which are not caught by `catch
Exception`. Add catch Throwable as a catch-all backstop to
any other thing that could be thrown.

(maint) Catch everything in query middleware

---

ext/bin/tag-release

The tag-release script is intended to automate tagging both a puppetdb
and pe-puppetdb release (as we currently tag both repos for all
releases).

(maint) Add tag-release script to ext/bin/

---

src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/command.clj

Some of the invocations of request-shutdown pass an exit map with no
:messges, which is disallowed by tk's schema check.  The resulting
exception can cause pdb to crash with a stackoverflow, so pass []
instead, when there are no messages.

(PDB-5467) Always pass :messages to request-shutdown

---

acceptance/setup/pre_suite/75_clean_out_puppet5_repos.rb

deb11 starts on the puppet7 platform, so forcing puppet6 here creates a
repo conflict

(maint) fix deb11 upgrade_oldest tests

---

resources/puppetlabs/puppetdb/pql/pql-grammar.ebnf

Avoid recursion in some of our rules to avoid *very* bad performance
for, as an example, a large number of 'or' filter clauses.
Before the change, this PQL query would saturate the CPU for many
minutes before running out of memory and crashing the test program:
(str "nodes[] { certname in [\""
(str/join "\", \""
(repeat 5000 "heavy-empire.delivery.puppetlabs.net"))
"\"] }"))
After the change, that same query finishes in a couple of seconds on a
fairly slow laptop.  While that still seems slow, it's a huge
improvement.
For what it's worth, for that particular query, the important change
is the one to <literallist>.
From https://github.com/Engelberg/instaparse/blob/4d1903b059e77dc0049dfbc75af9dce995756148/docs/Performance.md:
Prefer using * and + over recursion to describe simple …

(PDB-5260) Avoid recursive rules to mitigate slow PQL parsing

---

project.clj
src/puppetlabs/puppetdb/utils.clj

...and switch to upstream tools.namespace.  If upstream still can't
handle spaces in the classpath, then let's pursue it there.
The only change in the puppetlabs fork was this in loader-classpath:
-     #(java.io.File. (.getPath ^java.net.URL %))
+     #(java.io.File. (.toURI ^java.net.URL %))
https://github.com/puppetlabs/tools.namespace/commit/6ab30bc2be773bb64850ce9460cec22f9d3fdf9e

(PE-33853) Update clj parent to 5.0.0

---

CODEOWNERS
project.clj

This updates clj-parent to 4.11.0, to incorporate the most recent updates, and updates the CODEOWNERS file to be correct.

(maint) update clj-parent to 4.11.0, update code owners

---

project.clj

This updates clj-parent to 5.1.0, which contains a newer version
of jetty.(maint) update clj-parent to 5.1.0

(maint) update clj-parent to 5.1.0

---

project.clj

This brings in jetty, version 9.4.48 which contains a few security fixes as well as dependency updates.

(PE-34097) update clj-parent to 4.11.1

---

project.clj

This change in clj-parent brings in a new version of tk-jetty9 that uses a newer
version of Jetty (9.4.48).  This change includes several security fixes,
bug fixes as well as dependency updates.

(PE-34097) update clj-parent to 5.1.1

---

.travis.yml

The container tests started mysteriously failing around April 4th 2022.
This is causing all CI runs to be failures. Since efforts to fix the
failing test have been unsuccessful and the PDB container is not a
priority, this commit disables the container tests.

(maint) Disable travis container tests

---

src/puppetlabs/puppetdb/http/handlers.clj
src/puppetlabs/puppetdb/http/query.clj
src/puppetlabs/puppetdb/query_eng.clj
test/puppetlabs/puppetdb/http/inventory_test.clj
test/puppetlabs/puppetdb/http/query_logging_test.clj

Adds query logging before parsing so parsing failures are easier to debug. Please see commit messages for more info.

(PDB-5482) Log queries before parsing

---

project.clj

This updates the clj-parent reference to 4.11.2 to bring in a newer
version of the postgres driver to address CVE-2022-31197.

(PE-34257) update clj-parent to 4.11.2

---

project.clj

This updates clj-parent to 5.2.1 to include a new version of the postgres driver
to address CVE-2022-31197

(PE-34257) update clj-parent to 5.2.1

---

ext/bin/tag-release

Push the release commit and the tag before pushing the final commit
introducing the new snapshot version so that anything watching the
branch will see the events in branch order.
Previously, for example, jenkins (triggered via the webhook) never ran
the jobs for the release.

(PE-34279) tag-release: push tag before snapshot for release

---

src/puppetlabs/puppetdb/command.clj

Previously, the received-time would be formatted by the translation
library, which adds commas to the integer
```
2022-08-24 10:38:48,975 DEBUG [qtp1365504513-29] [p.p.command] [0-1,661,362,728,961] 'configure expiration' command enqueued for new-host
```
The purpose of this received-time is to correlate it with a later log
message (in which we do not include the commas)
```
2022-08-24 10:38:48,991 INFO  [cmd-proc-thread-1] [p.p.command] [0-1661362728961-1560874645000] [7 ms] 'configure expiration' command processed for new-host
```
So we now format this integer as a string to avoid additional formatting
by the translation library
```
2022-08-24 10:39:51,447 DEBUG [qtp1480434848-35] [p.p.command] [1-1661362791430] 'configure expiration' command enqueued for new-host
```

(maint) Format recieved-time before translation

---

ci/bin/prep-and-run-in
ci/bin/run
ext/bin/dep-diff
pdb
project.clj

This updates clj-parent to 5.2.5 which includes an updated set of bouncycastle dependencies off the renamed `18on` series of libraries.  All references to `15on` were changed to `18on` appropriately.

(PE-34636) update clj-parent to 5.2.5, bc references

---

project.clj

This brings in new versions of `trapperkeeper-webserver-jetty9` `trapperkeeper-metrics` and `dujour-version-check` which have recently been updated to migrate to the bouncycastle `18on` versions from the `15on` versions.

(maint) bump clj-parent to 5.2.8

---

.travis.yml

These were never shipped in a PE release, and coverage of PG 14 should be sufficient to cover the changes in those version as well.

(maint) Remove Postgres tests against 12 and 13

---

documentation/configure.markdown
src/puppetlabs/puppetdb/cli/services.clj
src/puppetlabs/puppetdb/config.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/admin_clean_test.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/command_broadcast_test.clj
test/puppetlabs/puppetdb/config_test.clj

Split the gc into multiple jobs to allow them to be scheduled at different intervals.
Run the gc routines on Postgres on a threadpool with a single worker thread to ensure gc jobs don't compete for PG's resources.

(PDB-5547) Schedule gc jobs separately

---

src/puppetlabs/puppetdb/query/paging.clj
test/puppetlabs/puppetdb/http/inventory_test.clj

Prior to the upgrade to honeysql v2 (PDB-5519), we handled constructing the order by clauses separately from the rest of the query. This meant we needed to extract the sql from raw requests to create an SQL string ahead of time. Now we are letting the paging components stay in the main query until honeysql constructs the whole query at once at the end. This means that during dealiasing we can simply select the honeysql field from the query map with no futher alterations.

(PDB-5568) Fix order by clause compilation

---

src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj

We have not released this migration, otherwise a separate migration would be needed.
Postgres foreign keys are implemented with bidirectional triggers this means that even after we have detached the partition from the parent table, dropping it will still require access exclusive locks on all the tables that we reference with foreign keys.

(PDB-5553) Remove foreign keys from report partitions

---

project.clj
src/puppetlabs/puppetdb/cli/benchmark.clj
src/puppetlabs/puppetdb/cli/generate.clj
src/puppetlabs/puppetdb/core.clj
src/puppetlabs/puppetdb/random.clj
test/puppetlabs/puppetdb/cli/generate_test.clj
test/puppetlabs/puppetdb/random_test.clj

Adds a generate command to generate sample data files to be used to seed a benchmark.
First pass at catalog generation to accompany it.

(PDB-5592) Generate catalogs

---

src/puppetlabs/puppetdb/http/query.clj

Users should not need to opt-in to this warning

(PDB-5642) Un-conditionalize log slow PQL warning

---

ext/bin/analyze-index-usage

The script is designed to easily get the index usage from a PE support script.
It is difficult to know which file a particular piece of data is in in the support script, so the file path is support script specific.
That being said, the data it needs is all standard postgres statistics, so it is trivial to reproduce the format well-enough that it will work on an open-source installation of PuppetDB
```
mkdir enterprise
echo puppetdb > enterprise/postgres_db_stats.txt
echo pg_stat_user_tables >> enterprise/postgres_db_stats.txt
psql puppetdb -c "select * from pg_stat_user_tables" >> enterprise/postgres_db_stats.txt
echo pg_stat_user_indexes >> enterprise/postgres_db_stats.txt
psql puppetdb -c "select * from pg_stat_user_indexes" >> enterprise/postgres_db_stats.txt
vim …
```

(PE-35599) Add script to analyze index usage

---

project.clj

This updates lein-ezbake to 2.4.2 to add build target support for ubuntu 2204

(PDB-5636) update ezbake to 2.4.2

---

acceptance/helper.rb

This adds ubuntu 2204/jammy to the set of supported puppetdb versions starting now.

(PDB-5636) add ubuntu 2204 as supported platform

---

ext/jenkins/beaker-tests.sh

This adds an option so that netssh will look in the local ssh config for settings, which will allow authentication to external test hosts correctly

(PDB-5636) enable ssh-config option

---

.github/workflows/daily.yml

Move testing of jdk8 to only on the 7.x branch. After upgrading hikari in the main branch, it is no longer compatible with jdk8.

(maint) testing: move jdk8 testing to 7.x only

---

ext/jenkins/beaker-tests.sh

7.x acceptance job is passing while main is not, and this is one visible
difference, though it's not clear why it would matter.

(maint) Remove beaker-hostgenerator --global-config ssh for smallstep

---

project.clj

This updates ezbake to 2.5.2, which does two things:
* it enables builds of the el9 platform
* it adds in tzdata-java as a dependency on the el platforms
tzdata-java was strangely removed as a dependency from openjdk, so this adds it in as a dependendency to ensure we don't release a broken package.

(maint) update ezbake to 2.5.2

---

documentation/install_from_packages.markdown
documentation/known_issues.markdown

Document RedHat 8 issue that OpenJDK 11.0.20.0.8-1 does not include tzdata-java.
Bug 2224427 - https://bugzilla.redhat.com/show_bug.cgi?id=2224427)

(docs) Document known issue with RedHat 8's openjdk 11

---

src/puppetlabs/puppetdb/client.clj

in the pe-puppetdb tests, this `str` call was leaving in a space between the date and time that wasn't working as a URL parameter. Switch to using the to-string function which formats the timestamp with ISO 8601 formatting, which uses a T to separate the date and time.

(maint) format timestamp with ISO formatter

---

src/puppetlabs/puppetdb/cli/benchmark.clj

The progressing-timestamp was being called with each update-host, regenerating the function each time with a base value. This ensures that we generate the function once so it can progress.
Also changed the default end-command-in days to 0 so that for cases where adding historical reports should take only minutes or hours don't end up shifted forward 7 days by default.

(maint) Fix progressing-timestamp to progress

---

puppet/lib/puppet/util/puppetdb.rb

This provides a hook for flushing the Puppetdb classes @config variable. This in turn means the next time Puppetdb.config is callled it will reload the configuration file.
This becomes important if in some command using this utility, we have accessed the Puppetdb.config, then go on to update puppet's puppetdb.conf with new information, and need to then take additional operations with Puppetdb.config that should be based on the new configuration state.

(PE-36947) Allow for Puppet::Util::Puppetdb to flush config

---

documentation/puppetdb_connection.markdown
documentation/release_notes_8.markdown
eastwood.clj
puppet/lib/puppet/indirector/catalog/puppetdb.rb
puppet/lib/puppet/util/puppetdb/config.rb
puppet/spec/unit/indirector/catalog/puppetdb_spec.rb
test/puppetlabs/puppetdb/integration/reports.clj
test/puppetlabs/puppetdb/integration/smoke.clj

Add configuration option to the terminus, `include_catalog_edges` that, when set to `false`, will disable sending any catalog edges to PuppetDB. Profiling of PuppetDB command processing has shown catalog edges can take as much as one third of the total time to process a catalog. Users with many nodes that don't use edges in their queries could benefit quite substantially from using this option. It is not enabled by default to maintain backwards compatibility during PuppetDB 8.
Resolves #3912.

(GH-3912) add include_catalog_edges config to terminus

---

acceptance/helper.rb

postgres 11 is deprecated, use postgres 14 for acceptance testing.

(maint) use postgres 14 for acceptance testing

---

acceptance/helper.rb

Install the puppetdb module from a branch to allow taking up a suitable puppetlabs-postgresql module.

(PE-37477) Install puppetlabs-puppetdb from branch

---

acceptance/helper.rb

The dependency resolution in the installation of the puppetdb module in our upgrade scenario does not catch that puppetlabs-apt >= 9.1 is no longer puppet 6 compatible. This commit pins back apt when installing the puppetdb module for the upgrade scenario.

(PE-37477) Pin back puppetlabs-apt when installing form puppet 6

---

acceptance/helper.rb

Use a branch of puppetlabs-postgresql with gpg backports to the last module version that supported puppet 6 for upgrade tests.

(PE-37482) Use a branch for puppetlabs-postgresql for upgrade tests

---

project.clj

With the recent update of clj-parent 7.3.7, the version of metrics is now managed along with the version of jetty. This removes the metrics pin as it is no longer appropriate.

(PE-37632) unpin metrics

---

ext/test/upgrade-and-exit
resources/ext/cli/delete-reports.erb
src/puppetlabs/puppetdb/query/population.clj
src/puppetlabs/puppetdb/query/summary_stats.clj
src/puppetlabs/puppetdb/query_eng.clj
src/puppetlabs/puppetdb/query_eng/engine.clj
src/puppetlabs/puppetdb/scf/migrate.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/admin_clean_test.clj
test/puppetlabs/puppetdb/cli/services_test.clj
test/puppetlabs/puppetdb/command_test.clj
test/puppetlabs/puppetdb/query/population_test.clj
test/puppetlabs/puppetdb/query_eng_test.clj
test/puppetlabs/puppetdb/scf/migrate_partitioning_test.clj
test/puppetlabs/puppetdb/scf/migrate_test.clj
test/puppetlabs/puppetdb/scf/storage_test.clj
test/puppetlabs/puppetdb/testutils/db.clj
test/puppetlabs/puppetdb/testutils/resources.clj

For most queries, the query engine will add an active nodes filter to
exclude deactivated and expired nodes from the results. Without this
index, that filter will generate a Seq Scan of the certnames table. If
that table is relatively small, and the write-rate of the database is
slow enough, the certnames table is almost entirely in the buffer cache
and the filter is quite quick. But when testing with a large number of
nodes, which creates a high write rate, the updating of the
latest_report_id dirties the certnames buffer cache pages quickly. If
queries are issued infrequently, the filter clause can create a lot of
reads and writes, which slow it down dramatically. This creates highly
variable query performance, in testing on 100,000 nodes it was as fast
as 80ms on repeated queries, and …

Improve query performance on the certnames table

---

documentation/puppetdb-faq.markdown

This was missed when releasing 7.0.0, but has been the implemented reality (see 6a96dd05366229e9704de175a3b884404f025462) and documented requirement (see d778b926eae65c54aa37e761c4367b2df10afb08) since the first release in the 7 series.

(docs) Update Java version FAQ

---

documentation/release_notes_8.markdown
src/puppetlabs/puppetdb/query_eng/engine.clj
test/puppetlabs/puppetdb/http/nodes_test.clj

Without another reference to a field that depends on the certnames table, a query for latest_report_status will fail with the error.
ERROR: missing FROM-clause entry for table "certnames"
latest_report_status needs the certnames table in order to know the latest_report_id that it needs to join against the reports table.
Fixes #3966

(PDB-5743) Fix join-deps for latest_report_status

---

project.clj

These upgrades conflicted with pins elsewhere, e.g. digest in kitchensink, so revert them until we can revisit a broader upgrade (and related migrations to clj-parent).

(PDB-5768) Revert conflicting pins for now

---

Gemfile
project.clj

Updated ezbake build version to support debian-12-x86_64 build for puppetdb in 7.x

(PDB-5794): Updated ezbake build version to support debian-12-x86_64 build for puppetdb in 7.x

---

documentation/release_notes_7.markdown
src/puppetlabs/puppetdb/jdbc.clj
src/puppetlabs/puppetdb/scf/partitioning.clj
src/puppetlabs/puppetdb/scf/storage.clj
test/puppetlabs/puppetdb/cli/services_test.clj

Handle failure cases of report gc
